export const voiceOptions = [
  {
    id: "en-US-AnaNeural",
    name: "Ana",
    gender: "female",
    language: "English",
    country: "US",
    description: "Giọng nữ Mỹ ấm áp, rõ ràng và truyền cảm hứng",
    premium: false,
    popular: false,
    avatar: "AN",
    sample: "Hello! I'm Ana, ready to help you with clear English pronunciation.",
  },
  {
    id: "en-US-ChristopherNeural",
    name: "Christopher",
    gender: "male",
    language: "English",
    country: "US",
    description: "Giọng nam Mỹ chuyên nghiệp, tự tin và rõ ràng",
    premium: true,
    popular: false,
    avatar: "CH",
    sample: "Hello, I'm Christopher. Let me assist you with your English learning journey.",
  },
  {
    id: "en-US-EricNeural",
    name: "Eric",
    gender: "male",
    language: "English",
    country: "US",
    description: "Giọng nam Mỹ chín chắn, đáng tin cậy và rõ ràng",
    premium: false,
    popular: false,
    avatar: "ER",
    sample: "Hi there, I'm Eric. I'm here to help you perfect your English pronunciation.",
  },
  {
    id: "en-US-GuyNeural",
    name: "Guy",
    gender: "male",
    language: "English",
    country: "US",
    description: "Giọng nam Mỹ thân thiện, tự nhiên và hấp dẫn",
    premium: true,
    popular: false,
    avatar: "GU",
    sample: "Hey! I'm Guy, and I'm excited to help you with your English skills.",
  },
  {
    id: "en-US-MichelleNeural",
    name: "Michelle",
    gender: "female",
    language: "English",
    country: "US",
    description: "Giọng nữ Mỹ thanh lịch, mượt mà và chuyên nghiệp",
    premium: true,
    popular: false,
    avatar: "MI",
    sample: "Hello, I'm Michelle. I'll guide you through perfect English pronunciation.",
  },
  {
    id: "en-US-RogerNeural",
    name: "Roger",
    gender: "male",
    language: "English",
    country: "US",
    description: "Giọng nam Mỹ lịch lãm, rõ ràng và đáng tin cậy",
    premium: false,
    popular: false,
    avatar: "RO",
    sample: "Good day, I'm Roger. Let me help you master American English pronunciation.",
  },
  {
    id: "en-US-SteffanNeural",
    name: "Steffan",
    gender: "male",
    language: "English",
    country: "US",
    description: "Giọng nam Mỹ năng động, tràn đầy năng lượng và rõ ràng",
    premium: true,
    popular: false,
    avatar: "ST",
    sample: "Hi! I'm Steffan, ready to make your English learning experience great.",
  }, //english voices
  {
    id: "en-US-JennyNeural",
    name: "Jenny",
    gender: "female",
    language: "English",
    country: "US",
    description: "Giọng nữ Mỹ rõ ràng, tự nhiên và thân thiện",
    premium: false,
    popular: true,
    avatar: "JN",
    sample: "Hello, I'm Jenny. I'll help you with English pronunciation.",
  },
  {
    id: "en-US-AriaNeural",
    name: "Aria",
    gender: "female",
    language: "English",
    country: "US",
    description: "Giọng nữ Mỹ biểu cảm với ngữ điệu tự nhiên",
    premium: false,
    popular: true,
    avatar: "AR",
    sample: "Hi there! I'm Aria, and I'm here to make your English sound great.",
  },
  {
    id: "en-GB-SoniaNeural",
    name: "Sonia",
    gender: "female",
    language: "English",
    country: "UK",
    description: "Giọng nữ Anh quốc thanh lịch với giọng điệu sang trọng",
    premium: true,
    popular: false,
    avatar: "SO",
    sample: "Good day! I'm Sonia from Britain, ready to assist with your English.",
  },
  {
    id: "en-AU-NatashaNeural",
    name: "Natasha",
    gender: "female",
    language: "English",
    country: "AU",
    description: "Giọng nữ Úc ấm áp và thân thiện",
    premium: false,
    popular: false,
    avatar: "NT",
    sample: "G'day! I'm Natasha from Australia, here to help with your English.",
  },
];
