export const tierSilverI = [
  {
    id: "topic_clothing_b1",
    title: "Trang phục",
    category: "topic",
    description: "Các loại trang phục, phụ kiện thông dụng và các hành động liên quan.",
    color: "bg-purple-500",
    words: [
      {
        id: "clo1",
        term: "Shirt",
        phonetic: "/ʃɜːt/",
        translation: "Áo sơ mi",
        examples: [
          { en: "He wears a white shirt to work.", vi: "Anh ấy mặc một chiếc áo sơ mi trắng đi làm." },
          { en: "This shirt is too small for me.", vi: "Chiếc áo sơ mi này quá nhỏ đối với tôi." },
          { en: "She bought a blue shirt for her father.", vi: "Cô ấy đã mua một chiếc áo sơ mi màu xanh dương cho bố cô ấy." },
        ],
        notes: "Thường dùng để chỉ áo sơ mi có cổ.",
      },
      {
        id: "clo2",
        term: "T-shirt",
        phonetic: "/ˈtiː ʃɜːt/",
        translation: "Áo thun, áo phông",
        examples: [
          { en: "I like wearing a T-shirt and jeans in summer.", vi: "Tôi thích mặc áo thun và quần jeans vào mùa hè." },
          { en: "He bought a new cotton T-shirt.", vi: "Cậu ấy đã mua một chiếc áo thun cotton mới." },
          { en: "The yellow T-shirt has a funny picture.", vi: "Chiếc áo phông màu vàng có một hình vẽ rất ngộ nghĩnh." },
        ],
        notes: "Áo cổ tròn, ngắn tay dáng chữ T.",
      },
      {
        id: "clo3",
        term: "Pants",
        phonetic: "/pænts/",
        translation: "Quần dài",
        examples: [
          { en: "His black pants are dirty.", vi: "Chiếc quần dài màu đen của anh ấy bị bẩn." },
          { en: "She needs to buy new pants for school.", vi: "Cô ấy cần mua chiếc quần dài mới để đi học." },
          { en: "These pants are very comfortable.", vi: "Chiếc quần dài này rất thoải mái." },
        ],
        notes: "Từ này được dùng phổ biến trong tiếng Anh-Mỹ. Tiếng Anh-Anh thường dùng 'trousers'.",
      },
      {
        id: "clo4",
        term: "Skirt",
        phonetic: "/skɜːt/",
        translation: "Chân váy",
        examples: [
          { en: "She is wearing a long pink skirt.", vi: "Cô ấy đang mặc một chiếc chân váy màu hồng dài." },
          { en: "The school uniform includes a gray skirt.", vi: "Đồng phục trường học bao gồm một chiếc chân váy màu xám." },
          { en: "I bought a new skirt yesterday.", vi: "Hôm qua tôi đã mua một chiếc chân váy mới." },
        ],
        notes: "Chân váy rời, phân biệt với 'dress' (váy liền).",
      },
      {
        id: "clo5",
        term: "Dress",
        phonetic: "/dres/",
        translation: "Váy liền, đầm",
        examples: [
          { en: "She looks beautiful in her wedding dress.", vi: "Cô ấy trông thật xinh đẹp trong chiếc váy cưới của mình." },
          { en: "She decided to wear a red dress to the party.", vi: "Cô ấy quyết định mặc một chiếc đầm đỏ đến bữa tiệc." },
          { en: "The dress is made of soft silk.", vi: "Chiếc đầm được làm từ lụa mềm." },
        ],
        notes: "Trang phục liền thân từ vai đến quá hông.",
      },
      {
        id: "clo6",
        term: "Jacket",
        phonetic: "/ˈdʒækɪt/",
        translation: "Áo khoác ngắn, áo nhẹ",
        examples: [
          { en: "Put on your jacket; it is cold outside.", vi: "Mặc áo khoác vào đi; ngoài trời lạnh lắm." },
          { en: "He bought a black leather jacket.", vi: "Anh ấy đã mua một chiếc áo khoác da màu đen." },
          { en: "This blue jacket has many pockets.", vi: "Chiếc áo khoác màu xanh dương này có rất nhiều túi." },
        ],
        notes: "Áo khoác mỏng hoặc ngắn ngang hông.",
      },
      {
        id: "clo7",
        term: "Coat",
        phonetic: "/kəʊt/",
        translation: "Áo khoác dài, áo măng tô",
        examples: [
          { en: "She wore a heavy coat in the snow.", vi: "Cô ấy đã mặc một chiếc áo khoác dày dưới trời tuyết." },
          { en: "Hang your coat in the closet, please.", vi: "Vui lòng treo áo khoác của bạn vào tủ." },
          { en: "His winter coat is very warm.", vi: "Chiếc áo khoác mùa đông của anh ấy rất ấm áp." },
        ],
        notes: "Áo khoác dày, thường dài qua hông hoặc đầu gối.",
      },
      {
        id: "clo8",
        term: "Shoes",
        phonetic: "/ʃuːz/",
        translation: "Giày",
        examples: [
          { en: "Take off your shoes before entering the house.", vi: "Hãy cởi giày trước khi vào nhà." },
          { en: "She bought a pair of running shoes.", vi: "Cô ấy đã mua một đôi giày chạy bộ." },
          { en: "These leather shoes fit me perfectly.", vi: "Đôi giày da này vừa vặn với tôi." },
        ],
        notes: "Thường dùng dạng số nhiều 'shoes' trừ khi chỉ đề cập đến 1 chiếc.",
      },
      {
        id: "clo9",
        term: "Socks",
        phonetic: "/sɒks/",
        translation: "Tất, vớ",
        examples: [
          { en: "I need to buy some warm socks for winter.", vi: "Tôi cần mua một vài đôi tất ấm cho mùa đông." },
          { en: "He is wearing white socks with black shoes.", vi: "Anh ấy đang đi tất trắng với giày đen." },
          { en: "Where is my other sock?", vi: "Chiếc tất còn lại của tôi ở đâu rồi?" },
        ],
        notes: "Thường dùng dạng số nhiều 'socks'.",
      },
      {
        id: "clo10",
        term: "Hat",
        phonetic: "/hæt/",
        translation: "Mũ, nón",
        examples: [
          { en: "She wore a large hat to protect her face from the sun.", vi: "Cô ấy đội một chiếc mũ rộng vành để bảo vệ da mặt khỏi ánh nắng mặt trời." },
          { en: "The boy put his hat on the table.", vi: "Cậu bé đặt chiếc mũ của mình lên bàn." },
          { en: "He took off his hat to greet her.", vi: "Anh ấy đã cất mũ để chào cô ấy." },
        ],
        notes: "Chỉ các loại mũ có vành tròn quanh đầu.",
      },
      {
        id: "clo11",
        term: "Gloves",
        phonetic: "/ɡlʌvz/",
        translation: "Găng tay",
        examples: [
          { en: "I wear gloves to keep my hands warm.", vi: "Tôi đeo găng tay để giữ ấm bàn tay." },
          { en: "She bought woolen gloves for her daughter.", vi: "Bà ấy đã mua găng tay len cho con gái mình." },
          { en: "He lost one of his leather gloves.", vi: "Anh ấy đã làm mất một bên găng tay da." },
        ],
        notes: "Thường dùng dạng số nhiều 'gloves'. Loại có xỏ từng ngón.",
      },
      {
        id: "clo12",
        term: "Scarf",
        phonetic: "/skɑːf/",
        translation: "Khăn quàng cổ",
        examples: [
          { en: "She wrapped a red scarf around her neck.", vi: "Cô ấy quàng một chiếc khăn đỏ quanh cổ." },
          { en: "My grandmother knitted this warm scarf for me.", vi: "Bà tôi đã đan chiếc khăn ấm này cho tôi." },
          { en: "He wore a woolen scarf on a cold day.", vi: "Anh ấy đã quàng một chiếc khăn len vào ngày lạnh giá." },
        ],
        notes: "Số nhiều của 'scarf' có thể viết là 'scarves' hoặc 'scarfs'.",
      },
      {
        id: "clo13",
        term: "Belt",
        phonetic: "/belt/",
        translation: "Thắt lưng, dây nịt",
        examples: [
          { en: "He wore a black leather belt.", vi: "Anh ấy đã đeo một chiếc thắt lưng da màu đen." },
          { en: "The pants are loose; I need a belt.", vi: "Chiếc quần bị rộng; tôi cần một cái thắt lưng." },
          { en: "She bought a belt to match her dress.", vi: "Cô ấy đã mua một chiếc thắt lưng để hợp với chiếc váy." },
        ],
        notes: "Phụ kiện dùng quanh hông để giữ quần hoặc trang trí.",
      },
      {
        id: "clo14",
        term: "Boot",
        phonetic: "/buːt/",
        translation: "Giày bốt, ủng",
        examples: [
          { en: "She bought a pair of tall leather boots.", vi: "Cô ấy đã mua một đôi bốt da cổ cao." },
          { en: "I need rain boots for this wet weather.", vi: "Tôi cần ủng đi mưa cho thời tiết ẩm ướt này." },
          { en: "He cleaned the mud off his boots.", vi: "Cậu ấy đã làm sạch bùn bám trên đôi ủng." },
        ],
        notes: "Loại giày cao cổ bao bọc bàn chân và cổ chân.",
      },
      {
        id: "clo15",
        term: "Suit",
        phonetic: "/suːt/",
        translation: "Bộ com lê, bộ âu phục",
        examples: [
          { en: "He wore a gray suit to the job interview.", vi: "Anh ấy đã mặc một bộ âu phục màu xám đến buổi phỏng vấn xin việc." },
          { en: "The suit fits him very well.", vi: "Bộ com lê rất vừa vặn với anh ấy." },
          { en: "She bought a formal suit for her husband.", vi: "Cô ấy đã mua một bộ âu phục trang trọng cho chồng mình." },
        ],
        notes: "Trang phục gồm áo vest và quần tây (hoặc chân váy) cùng chất liệu.",
      },
      {
        id: "clo16",
        term: "Jeans",
        phonetic: "/dʒiːnz/",
        translation: "Quần jeans, quần bò",
        examples: [
          { en: "I prefer blue jeans to black ones.", vi: "Tôi thích quần jeans màu xanh dương hơn quần màu đen." },
          { en: "These jeans are durable and comfortable.", vi: "Chiếc quần bò này rất bền và thoải mái." },
          { en: "She bought a cheap pair of jeans.", vi: "Cô ấy đã mua một chiếc quần bò giá rẻ." },
        ],
        notes: "Luôn dùng ở dạng số nhiều 'jeans'.",
      },
      {
        id: "clo17",
        term: "Wear",
        phonetic: "/weə/",
        translation: "Mặc, mang, đội, đeo",
        examples: [
          { en: "She likes to wear jewelry.", vi: "Cô ấy thích đeo trang sức." },
          { en: "What did you wear to the party?", vi: "Bạn đã mặc gì tới bữa tiệc?" },
          { en: "I always wear glasses when reading.", vi: "Tôi luôn đeo kính khi đọc sách." },
        ],
        notes: "Động từ bất quy tắc (quá khứ là 'wore', phân từ hai là 'worn').",
      },
      {
        id: "clo18",
        term: "Put on",
        phonetic: "/pʊt ɒn/",
        translation: "Mặc vào, đội vào, xỏ vào",
        examples: [
          { en: "Put on your coat; it's cold.", vi: "Mặc áo khoác vào đi; trời lạnh đấy." },
          { en: "He put on his shoes and walked out.", vi: "Anh ấy xỏ giày vào rồi bước ra ngoài." },
          { en: "Please put on your helmet before riding.", vi: "Vui lòng đội mũ bảo hiểm trước khi đi xe." },
        ],
        notes: "Cụm động từ chỉ hành động đang mặc đồ vào cơ thể.",
      },
      {
        id: "clo19",
        term: "Take off",
        phonetic: "/teɪk ɒf/",
        translation: "Cởi ra, tháo ra",
        examples: [
          { en: "Take off your wet socks, please.", vi: "Vui lòng cởi đôi tất ướt của bạn ra." },
          { en: "He took off his glasses before sleeping.", vi: "Anh ấy đã tháo kính ra trước khi ngủ." },
          { en: "The boy took off his hat inside.", vi: "Cậu bé đã cởi mũ khi ở trong nhà." },
        ],
        notes: "Trái nghĩa với 'put on'.",
      },
      {
        id: "clo20",
        term: "Pocket",
        phonetic: "/ˈpɒkɪt/",
        translation: "Túi quần, túi áo",
        examples: [
          { en: "He put his keys in his pocket.", vi: "Anh ấy đã cất chìa khóa vào túi quần." },
          { en: "The jacket has a secret inside pocket.", vi: "Chiếc áo khoác có một cái túi ẩn bên trong." },
          { en: "She felt something cold in her pocket.", vi: "Cô ấy cảm thấy có gì đó lạnh lạnh ở trong túi áo." },
        ],
        notes: "Phần túi vải may liền trên trang phục.",
      },
    ],
  },
  {
    id: "topic_home_rooms_b1",
    title: "Nhà cửa & Phòng ốc",
    category: "topic",
    description: "Các phòng trong ngôi nhà, cấu trúc xây dựng cơ bản và đồ nội thất.",
    color: "bg-blue-500",
    words: [
      {
        id: "hom1",
        term: "House",
        phonetic: "/haʊs/",
        translation: "Ngôi nhà",
        examples: [
          { en: "We bought a small house in the village.", vi: "Chúng tôi đã mua một ngôi nhà nhỏ ở trong làng." },
          { en: "The house has a red roof.", vi: "Ngôi nhà có một mái nhà màu đỏ." },
          { en: "Our house is near the lake.", vi: "Nhà của chúng tôi ở gần hồ." },
        ],
        notes: "Chỉ chung tòa nhà dùng để ở.",
      },
      {
        id: "hom2",
        term: "Room",
        phonetic: "/ruːm/",
        translation: "Căn phòng, phòng",
        examples: [
          { en: "This hotel room has a great view.", vi: "Phòng khách sạn này có tầm nhìn rất đẹp." },
          { en: "He is cleaning his room now.", vi: "Cậu ấy đang dọn dẹp căn phòng của mình." },
          { en: "There are five rooms in our house.", vi: "Có năm căn phòng trong ngôi nhà của chúng tôi." },
        ],
        notes: "Từ chỉ một khoảng không gian khép kín trong nhà.",
      },
      {
        id: "hom3",
        term: "Bedroom",
        phonetic: "/ˈbedruːm/",
        translation: "Phòng ngủ",
        examples: [
          { en: "My bedroom has a large window.", vi: "Phòng ngủ của tôi có một ô cửa sổ lớn." },
          { en: "She painted her bedroom pink.", vi: "Cô ấy đã sơn phòng ngủ của mình màu hồng." },
          { en: "He went to his bedroom to rest.", vi: "Anh ấy đi vào phòng ngủ để nghỉ ngơi." },
        ],
        notes: "Phòng dùng để ngủ, thường có giường.",
      },
      {
        id: "hom4",
        term: "Living room",
        phonetic: "/ˈlɪvɪŋ ruːm/",
        translation: "Phòng khách",
        examples: [
          { en: "We watch TV together in the living room.", vi: "Chúng tôi cùng nhau xem ti vi ở phòng khách." },
          { en: "The living room has a large sofa.", vi: "Phòng khách có một chiếc ghế sofa lớn." },
          { en: "She welcomed her guests in the living room.", vi: "Cô ấy đã đón tiếp những vị khách trong phòng khách." },
        ],
        notes: "Phòng chung sinh hoạt của cả gia đình hoặc tiếp khách.",
      },
      {
        id: "hom5",
        term: "Kitchen",
        phonetic: "/ˈkɪtʃɪn/",
        translation: "Nhà bếp, bếp",
        examples: [
          { en: "My mother is cooking in the kitchen.", vi: "Mẹ tôi đang nấu ăn trong bếp." },
          { en: "The kitchen smells of fresh cookies.", vi: "Nhà bếp tỏa ra mùi bánh quy tươi thơm phức." },
          { en: "We eat our meals in the kitchen.", vi: "Chúng tôi ăn các bữa ăn ngay tại nhà bếp." },
        ],
        notes: "Nơi chuẩn bị và nấu nướng đồ ăn.",
      },
      {
        id: "hom6",
        term: "Bathroom",
        phonetic: "/ˈbɑːθruːm/",
        translation: "Phòng tắm, nhà vệ sinh",
        examples: [
          { en: "The bathroom is next to the kitchen.", vi: "Phòng tắm ở ngay cạnh nhà bếp." },
          { en: "He is brushing his teeth in the bathroom.", vi: "Cậu ấy đang đánh răng trong phòng tắm." },
          { en: "She needs to clean the bathroom.", vi: "Cô ấy cần phải dọn dẹp phòng tắm." },
        ],
        notes: "Phòng có bồn tắm/vòi sen, gương và thường có bồn vệ sinh.",
      },
      {
        id: "hom7",
        term: "Door",
        phonetic: "/dɔː/",
        translation: "Cửa ra vào, cánh cửa",
        examples: [
          { en: "Please close the door when you leave.", vi: "Vui lòng đóng cửa khi bạn rời đi." },
          { en: "The door is painted white.", vi: "Cánh cửa được sơn màu trắng." },
          { en: "Someone is knocking at the door.", vi: "Có ai đó đang gõ cửa." },
        ],
        notes: "Khác với 'gate' (cổng ngoài sân).",
      },
      {
        id: "hom8",
        term: "Window",
        phonetic: "/ˈwɪndəʊ/",
        translation: "Cửa sổ",
        examples: [
          { en: "Open the window to let fresh air in.", vi: "Hãy mở cửa sổ để đón không khí trong lành vào." },
          { en: "He looked out of the window.", vi: "Anh ấy đã nhìn ra ngoài cửa sổ." },
          { en: "She broke the bedroom window with a ball.", vi: "Cô ấy đã làm vỡ cửa sổ phòng ngủ bằng một quả bóng." },
        ],
        notes: "Cửa kính thu ánh sáng và thông gió.",
      },
      {
        id: "hom9",
        term: "Wall",
        phonetic: "/wɔːl/",
        translation: "Bức tường, tường",
        examples: [
          { en: "There is a beautiful picture on the wall.", vi: "Có một bức tranh đẹp treo trên tường." },
          { en: "The walls of the room are white.", vi: "Các bức tường của căn phòng có màu trắng." },
          { en: "They painted the wall yesterday.", vi: "Hôm qua họ đã sơn bức tường." },
        ],
        notes: "Cấu trúc thẳng đứng để ngăn cách hoặc bao quanh các không gian.",
      },
      {
        id: "hom10",
        term: "Floor",
        phonetic: "/flɔː/",
        translation: "Sàn nhà / Tầng nhà",
        examples: [
          { en: "He dropped his keys on the floor.", vi: "Anh ấy đã làm rơi chìa khóa xuống sàn nhà." },
          { en: "My apartment is on the third floor.", vi: "Căn hộ của tôi nằm ở tầng ba." },
          { en: "The wooden floor is very clean.", vi: "Sàn gỗ rất sạch sẽ." },
        ],
        notes: "Vừa chỉ sàn nhà vừa chỉ các tầng trong một tòa nhà.",
      },
      {
        id: "hom11",
        term: "Roof",
        phonetic: "/ruːf/",
        translation: "Mái nhà",
        examples: [
          { en: "The roof of the house was damaged in the storm.", vi: "Mái nhà đã bị hư hại trong trận bão." },
          { en: "The cat is sitting on the roof.", vi: "Con mèo đang ngồi trên mái nhà." },
          { en: "They need to repair the leaking roof.", vi: "Họ cần sửa chữa phần mái nhà bị dột." },
        ],
        notes: "Phần che phủ trên cùng của ngôi nhà.",
      },
      {
        id: "hom12",
        term: "Garden",
        phonetic: "/ˈɡɑːdn/",
        translation: "Khu vườn, vườn",
        examples: [
          { en: "My grandfather works in the garden every day.", vi: "Ông tôi làm việc ngoài vườn mỗi ngày." },
          { en: "There are many red roses in the garden.", vi: "Có rất nhiều hoa hồng đỏ trong vườn." },
          { en: "They have a small vegetable garden.", vi: "Họ có một khu vườn trồng rau nhỏ." },
        ],
        notes: "Khoảng đất trồng cây hoa hoặc rau quanh nhà.",
      },
      {
        id: "hom13",
        term: "Bed",
        phonetic: "/bed/",
        translation: "Giường",
        examples: [
          { en: "The bed is soft and comfortable.", vi: "Chiếc giường thật mềm mại và thoải mái." },
          { en: "He lies on the bed to read a book.", vi: "Cậu ấy nằm trên giường để đọc sách." },
          { en: "It is time to make your bed.", vi: "Đã đến lúc dọn dẹp giường của bạn rồi." },
        ],
        notes: "Đồ đạc để nằm ngủ.",
      },
      {
        id: "hom14",
        term: "Table",
        phonetic: "/ˈteɪbl/",
        translation: "Bàn, cái bàn",
        examples: [
          { en: "Please put the glass on the table.", vi: "Làm ơn hãy đặt chiếc cốc lên bàn." },
          { en: "We sat around the kitchen table.", vi: "Chúng tôi ngồi xung quanh chiếc bàn ăn ở bếp." },
          { en: "He bought a wooden coffee table.", vi: "Anh ấy đã mua một chiếc bàn cà phê bằng gỗ." },
        ],
        notes: "Bàn để làm việc, ăn uống.",
      },
      {
        id: "hom15",
        term: "Chair",
        phonetic: "/tʃeə/",
        translation: "Ghế, cái ghế",
        examples: [
          { en: "Sit on this chair, please.", vi: "Vui lòng ngồi vào chiếc ghế này." },
          { en: "There are four chairs around the table.", vi: "Có bốn chiếc ghế xung quanh bàn." },
          { en: "The wooden chair is broken.", vi: "Chiếc ghế gỗ đã bị gãy." },
        ],
        notes: "Ghế đơn có chỗ tựa lưng.",
      },
      {
        id: "hom16",
        term: "Mirror",
        phonetic: "/ˈmɪrə/",
        translation: "Cái gương, gương soi",
        examples: [
          { en: "She looked at herself in the mirror.", vi: "Cô ấy tự nhìn mình trong gương." },
          { en: "There is a large mirror in the bathroom.", vi: "Có một cái gương lớn trong phòng tắm." },
          { en: "He wiped the mirror clean.", vi: "Anh ấy đã lau sạch tấm gương." },
        ],
        notes: "Mặt kính phản chiếu để soi.",
      },
      {
        id: "hom17",
        term: "Sofa",
        phonetic: "/ˈsəʊfə/",
        translation: "Ghế sofa, ghế bành dài",
        examples: [
          { en: "We sat on the sofa to watch a movie.", vi: "Chúng tôi ngồi trên ghế sofa để xem phim." },
          { en: "The cat is sleeping on the comfortable sofa.", vi: "Con mèo đang ngủ trên chiếc ghế sofa êm ái." },
          { en: "She bought a gray fabric sofa.", vi: "Cô ấy đã mua một chiếc ghế sofa vải màu xám." },
        ],
        notes: "Ghế dài bọc đệm êm thường đặt ở phòng khách.",
      },
      {
        id: "hom18",
        term: "Lamp",
        phonetic: "/læmp/",
        translation: "Đèn, cây đèn",
        examples: [
          { en: "Turn on the lamp, please; it is dark.", vi: "Vui lòng bật đèn lên; trời tối rồi." },
          { en: "I have a reading lamp on my desk.", vi: "Tôi có một chiếc đèn đọc sách trên bàn làm việc." },
          { en: "The table lamp has a white shade.", vi: "Chiếc đèn bàn có cái chao đèn màu trắng." },
        ],
        notes: "Đèn thắp sáng có thể di chuyển, đặt trên bàn hoặc sàn.",
      },
      {
        id: "hom19",
        term: "Stairs",
        phonetic: "/steəz/",
        translation: "Cầu thang",
        examples: [
          { en: "He walked slowly down the stairs.", vi: "Anh ấy đi chậm rãi xuống cầu thang." },
          { en: "The stairs are made of dark wood.", vi: "Cầu thang được làm bằng gỗ tối màu." },
          { en: "She fell down the stairs and hurt her leg.", vi: "Cô ấy bị ngã cầu thang và đau chân." },
        ],
        notes: "Luôn dùng dạng số nhiều 'stairs' để chỉ dãy bậc thang.",
      },
      {
        id: "hom20",
        term: "Gate",
        phonetic: "/ɡeɪt/",
        translation: "Cổng, cửa cổng",
        examples: [
          { en: "Please lock the front gate before bed.", vi: "Vui lòng khóa cổng trước khi đi ngủ." },
          { en: "A tall iron gate surrounds the garden.", vi: "Một chiếc cổng sắt cao bao quanh khu vườn." },
          { en: "He stood at the gate waiting for his friend.", vi: "Cậu ấy đứng ở ngoài cổng chờ bạn." },
        ],
        notes: "Cửa lớn ở ngoài sân hoặc hàng rào bao quanh.",
      },
    ],
  },
  {
    id: "topic_daily_activities_b1",
    title: "Hoạt động hàng ngày",
    category: "topic",
    description: "Các thói quen sinh hoạt và hoạt động thường nhật từ sáng đến tối.",
    color: "bg-green-500",
    words: [
      {
        id: "act1",
        term: "Wake up",
        phonetic: "/weɪk ʌp/",
        translation: "Thức giấc, mở mắt dậy",
        examples: [
          { en: "I usually wake up at six o'clock.", vi: "Tôi thường thức giấc lúc sáu giờ." },
          { en: "The loud alarm made him wake up.", vi: "Tiếng chuông báo thức lớn đã làm anh ấy tỉnh giấc." },
          { en: "She woke up early today.", vi: "Hôm nay cô ấy đã tỉnh dậy sớm." },
        ],
        notes: "Chỉ hành động tỉnh giấc sau khi ngủ, chưa nhất thiết phải bước ra khỏi giường.",
      },
      {
        id: "act2",
        term: "Get up",
        phonetic: "/ɡet ʌp/",
        translation: "Thức dậy, rời giường",
        examples: [
          { en: "I get up ten minutes after I wake up.", vi: "Tôi thức dậy rời giường mười phút sau khi tôi tỉnh giấc." },
          { en: "He has to get up early for work.", vi: "Anh ấy phải dậy sớm để đi làm." },
          { en: "She got up and made some coffee.", vi: "Cô ấy đã rời giường và pha một chút cà phê." },
        ],
        notes: "Chỉ hành động thức dậy và thực sự bước ra khỏi giường.",
      },
      {
        id: "act3",
        term: "Wash face",
        phonetic: "/wɒʃ feɪs/",
        translation: "Rửa mặt",
        examples: [
          { en: "I always wash my face after getting up.", vi: "Tôi luôn rửa mặt sau khi thức dậy." },
          { en: "He washed his face with cold water to wake up.", vi: "Anh ấy rửa mặt bằng nước lạnh để cho tỉnh táo." },
          { en: "Wash your face before applying cream.", vi: "Hãy rửa mặt thật sạch trước khi thoa kem." },
        ],
        notes: "Kết hợp động từ 'wash' và bộ phận cơ thể.",
      },
      {
        id: "act4",
        term: "Brush teeth",
        phonetic: "/brʌʃ tiːθ/",
        translation: "Đánh răng",
        examples: [
          { en: "You should brush your teeth twice a day.", vi: "Bạn nên đánh răng hai lần một ngày." },
          { en: "She is brushing her teeth in the bathroom.", vi: "Cô ấy đang đánh răng trong phòng tắm." },
          { en: "He brushes his teeth after breakfast.", vi: "Anh ấy đánh răng sau bữa ăn sáng." },
        ],
        notes: "Danh từ 'teeth' là dạng số nhiều của 'tooth'.",
      },
      {
        id: "act5",
        term: "Shower",
        phonetic: "/ˈʃaʊə/",
        translation: "Tắm (bằng vòi hoa sen)",
        examples: [
          { en: "I take a quick shower every morning.", vi: "Tôi tắm nhanh bằng vòi hoa sen mỗi sáng." },
          { en: "She is taking a shower now.", vi: "Lúc này cô ấy đang tắm." },
          { en: "A hot shower helps me relax.", vi: "Tắm nước nóng giúp tôi thư giãn hơn." },
        ],
        notes: "Thường đi với cụm từ 'take a shower' hoặc 'have a shower'.",
      },
      {
        id: "act6",
        term: "Get dressed",
        phonetic: "/ɡet drest/",
        translation: "Mặc quần áo",
        examples: [
          { en: "I get dressed after taking a shower.", vi: "Tôi mặc quần áo sau khi tắm xong." },
          { en: "Hurry up and get dressed!", vi: "Nhanh lên và mặc quần áo vào đi!" },
          { en: "She got dressed in her school uniform.", vi: "Cô ấy mặc bộ đồng phục trường học." },
        ],
        notes: "Chỉ toàn bộ quá trình sửa soạn mặc đồ chỉnh tề.",
      },
      {
        id: "act7",
        term: "Eat breakfast",
        phonetic: "/iːt ˈbrekfəst/",
        translation: "Ăn sáng",
        examples: [
          { en: "Do you eat breakfast every day?", vi: "Bạn có ăn sáng mỗi ngày không?" },
          { en: "I usually eat breakfast at seven.", vi: "Tôi thường ăn sáng lúc bảy giờ." },
          { en: "We had bread and milk for breakfast.", vi: "Chúng tôi đã ăn bánh mì và uống sữa cho bữa sáng." },
        ],
        notes: "Có thể dùng động từ 'have breakfast' thay thế.",
      },
      {
        id: "act8",
        term: "Go to school",
        phonetic: "/ɡəʊ tə skuːl/",
        translation: "Đi học, đến trường",
        examples: [
          { en: "My children go to school by bus.", vi: "Con cái tôi đi học bằng xe buýt." },
          { en: "I go to school from Monday to Friday.", vi: "Tôi đi học từ thứ Hai đến thứ Sáu." },
          { en: "She is ready to go to school.", vi: "Cô ấy đã sẵn sàng để đến trường." },
        ],
        notes: "Không có mạo từ 'the' khi đi học với tư cách là học sinh.",
      },
      {
        id: "act9",
        term: "Go to work",
        phonetic: "/ɡəʊ tə wɜːk/",
        translation: "Đi làm, đến nơi làm việc",
        examples: [
          { en: "He has to go to work early today.", vi: "Hôm nay anh ấy phải đi làm sớm." },
          { en: "I go to work by motorcycle.", vi: "Tôi đi làm bằng xe máy." },
          { en: "She went to work despite the rain.", vi: "Cô ấy đã đi làm mặc dù trời mưa." },
        ],
        notes: "Không sử dụng mạo từ 'the' trước 'work'.",
      },
      {
        id: "act10",
        term: "Study",
        phonetic: "/ˈstʌdi/",
        translation: "Học tập, nghiên cứu",
        examples: [
          { en: "I need to study for the test.", vi: "Tôi cần phải học để chuẩn bị cho bài kiểm tra." },
          { en: "She studies English every night.", vi: "Cô ấy học tiếng Anh mỗi tối." },
          { en: "They study in the library.", vi: "Họ học tập ở trong thư viện." },
        ],
        notes: "Động từ chia số ít ở hiện tại đơn là 'studies'.",
      },
      {
        id: "act11",
        term: "Eat lunch",
        phonetic: "/iːt lʌntʃ/",
        translation: "Ăn trưa",
        examples: [
          { en: "What time do you eat lunch?", vi: "Bạn ăn trưa lúc mấy giờ?" },
          { en: "I eat lunch with my coworkers.", vi: "Tôi ăn trưa với các đồng nghiệp của mình." },
          { en: "We had rice and fish for lunch.", vi: "Chúng tôi đã ăn cơm và cá cho bữa trưa." },
        ],
        notes: "Có thể dùng cụm từ 'have lunch'.",
      },
      {
        id: "act12",
        term: "Go home",
        phonetic: "/ɡəʊ həʊm/",
        translation: "Về nhà",
        examples: [
          { en: "I go home at five in the afternoon.", vi: "Tôi về nhà lúc năm giờ chiều." },
          { en: "He wants to go home because he is tired.", vi: "Anh ấy muốn về nhà vì mệt." },
          { en: "They went home together after school.", vi: "Họ đã cùng nhau đi về nhà sau buổi học." },
        ],
        notes: "Không sử dụng giới từ 'to' giữa 'go' và 'home'.",
      },
      {
        id: "act13",
        term: "Cook",
        phonetic: "/kʊk/",
        translation: "Nấu ăn, nấu nướng",
        examples: [
          { en: "I love to cook for my family.", vi: "Tôi rất thích nấu ăn cho gia đình mình." },
          { en: "Who is going to cook dinner tonight?", vi: "Ai sẽ là người nấu bữa tối tối nay?" },
          { en: "She is learning how to cook.", vi: "Cô ấy đang học cách nấu ăn." },
        ],
        notes: "Danh từ 'cook' chỉ đầu bếp (không phải cooker - nồi cơm điện).",
      },
      {
        id: "act14",
        term: "Eat dinner",
        phonetic: "/iːt ˈdɪnə/",
        translation: "Ăn tối",
        examples: [
          { en: "We eat dinner together at eight o'clock.", vi: "Chúng tôi ăn tối cùng nhau vào lúc tám giờ." },
          { en: "He cooked a nice dinner for his wife.", vi: "Anh ấy đã nấu một bữa tối rất ngon cho vợ mình." },
          { en: "I usually have a light dinner.", vi: "Tôi thường ăn một bữa tối nhẹ nhàng." },
        ],
        notes: "Cụm từ tương đương: 'have dinner'.",
      },
      {
        id: "act15",
        term: "Do homework",
        phonetic: "/duː ˈhəʊmwɜːk/",
        translation: "Làm bài tập về nhà",
        examples: [
          { en: "You must do your homework before dinner.", vi: "Con phải làm bài tập về nhà trước bữa tối." },
          { en: "She is doing her math homework.", vi: "Cô ấy đang làm bài tập toán về nhà." },
          { en: "He forgot to do his homework.", vi: "Cậu ấy đã quên làm bài tập về nhà." },
        ],
        notes: "'Homework' là danh từ không đếm được, dùng động từ 'do' chứ không dùng 'make'.",
      },
      {
        id: "act16",
        term: "Watch TV",
        phonetic: "/wɒtʃ ˌtiːˈviː/",
        translation: "Xem ti vi, xem vô tuyến",
        examples: [
          { en: "We watch TV in the living room.", vi: "Chúng tôi xem ti vi ở phòng khách." },
          { en: "He watches TV for one hour every evening.", vi: "Cậu ấy xem ti vi một tiếng mỗi tối." },
          { en: "She does not let her children watch too much TV.", vi: "Cô ấy không cho con mình xem ti vi quá nhiều." },
        ],
        notes: "Không sử dụng mạo từ 'the' trước 'TV' khi ám chỉ chương trình truyền hình.",
      },
      {
        id: "act17",
        term: "Listen to music",
        phonetic: "/ˈlɪsn tə ˈmjuːzɪk/",
        translation: "Nghe nhạc",
        examples: [
          { en: "I like to listen to music when I clean.", vi: "Tôi thích nghe nhạc khi dọn dẹp." },
          { en: "She is listening to pop music.", vi: "Cô ấy đang nghe nhạc pop." },
          { en: "He listens to music through his headphones.", vi: "Anh ấy nghe nhạc qua tai nghe." },
        ],
        notes: "Luôn có giới từ 'to' sau động từ 'listen'.",
      },
      {
        id: "act18",
        term: "Read a book",
        phonetic: "/riːd ə bʊk/",
        translation: "Đọc sách",
        examples: [
          { en: "I read a book before sleeping.", vi: "Tôi đọc sách trước khi đi ngủ." },
          { en: "The teacher asked us to read a book.", vi: "Giáo viên yêu cầu chúng tôi đọc một cuốn sách." },
          { en: "She is reading an interesting book about history.", vi: "Cô ấy đang đọc một cuốn sách thú vị về lịch sử." },
        ],
        notes: "Động từ 'read' ở quá khứ viết giống hệt nhưng phát âm là /red/.",
      },
      {
        id: "act19",
        term: "Clean",
        phonetic: "/kliːn/",
        translation: "Lau dọn, dọn dẹp",
        examples: [
          { en: "We clean the house every Sunday.", vi: "Chúng tôi dọn dẹp nhà cửa vào mỗi Chủ Nhật." },
          { en: "She is cleaning the kitchen.", vi: "Cô ấy đang lau dọn nhà bếp." },
          { en: "I need to clean my room today.", vi: "Hôm nay tôi cần dọn dẹp phòng của mình." },
        ],
        notes: "Vừa là động từ vừa là tính từ (sạch sẽ).",
      },
      {
        id: "act20",
        term: "Go to bed",
        phonetic: "/ɡəʊ tə bed/",
        translation: "Đi ngủ, đi nằm",
        examples: [
          { en: "I go to bed at ten o'clock.", vi: "Tôi đi ngủ vào lúc mười giờ." },
          { en: "The children should go to bed early.", vi: "Trẻ em nên đi ngủ sớm." },
          { en: "She went to bed late last night.", vi: "Tối qua cô ấy đã đi ngủ muộn." },
        ],
        notes: "Chỉ hành động chuẩn bị đi ngủ, khác với 'sleep' (trạng thái ngủ).",
      },
    ],
  },
  {
    id: "topic_wild_animals_b1",
    title: "Động vật hoang dã",
    category: "topic",
    description: "Các loài động vật hoang dã sống ngoài tự nhiên và môi trường sống của chúng.",
    color: "bg-yellow-500",
    words: [
      {
        id: "wil1",
        term: "Lion",
        phonetic: "/ˈlaɪən/",
        translation: "Sư tử",
        examples: [
          { en: "The lion is the king of the jungle.", vi: "Sư tử là chúa tể rừng xanh." },
          { en: "We saw a family of lions at the zoo.", vi: "Chúng tôi đã nhìn thấy một gia đình sư tử ở sở thú." },
          { en: "Lions hunt in groups.", vi: "Sư tử săn mồi theo bầy đàn." },
        ],
        notes: "Con đực có chiếc bờm (mane) đặc trưng.",
      },
      {
        id: "wil2",
        term: "Tiger",
        phonetic: "/ˈtaɪɡə/",
        translation: "Con hổ, cọp",
        examples: [
          { en: "The tiger has beautiful stripes.", vi: "Con hổ có những chiếc vằn rất đẹp." },
          { en: "A tiger is a very fast hunter.", vi: "Hổ là loài đi săn rất nhanh." },
          { en: "Wild tigers are now endangered.", vi: "Hổ hoang dã hiện đang đứng trước nguy cơ tuyệt chủng." },
        ],
        notes: "Thú săn mồi họ mèo lớn.",
      },
      {
        id: "wil3",
        term: "Elephant",
        phonetic: "/ˈelɪfənt/",
        translation: "Con voi",
        examples: [
          { en: "An elephant is the largest land animal.", vi: "Voi là loài động vật trên cạn lớn nhất." },
          { en: "The elephant has a very long trunk.", vi: "Con voi có một chiếc vòi rất dài." },
          { en: "We fed the elephants some bananas.", vi: "Chúng tôi đã cho những chú voi ăn vài quả chuối." },
        ],
        notes: "Đi với mạo từ 'an'.",
      },
      {
        id: "wil4",
        term: "Monkey",
        phonetic: "/ˈmʌŋki/",
        translation: "Con khỉ",
        examples: [
          { en: "The monkey is swinging from the tree.", vi: "Con khỉ đang chuyền cành từ trên cây." },
          { en: "Monkeys love eating bananas.", vi: "Khỉ rất thích ăn chuối." },
          { en: "We heard monkeys chattering in the forest.", vi: "Chúng tôi nghe thấy tiếng khỉ kêu chí chóe trong rừng." },
        ],
        notes: "Loài linh trưởng nghịch ngợm, nhanh nhẹn.",
      },
      {
        id: "wil5",
        term: "Giraffe",
        phonetic: "/dʒɪˈrɑːf/",
        translation: "Hươu cao cổ",
        examples: [
          { en: "The giraffe eat leaves from tall trees.", vi: "Hươu cao cổ ăn lá trên những cây cao." },
          { en: "A giraffe has a long neck and blue tongue.", vi: "Hươu cao cổ có một cái cổ dài và chiếc lưỡi màu xanh dương." },
          { en: "We took photos of a tall giraffe.", vi: "Chúng tôi đã chụp ảnh một chú hươu cao cổ rất cao." },
        ],
        notes: "Động vật cao nhất thế giới.",
      },
      {
        id: "wil6",
        term: "Bear",
        phonetic: "/beə/",
        translation: "Con gấu",
        examples: [
          { en: "The brown bear catches fish in the river.", vi: "Chú gấu nâu bắt cá ở dưới sông." },
          { en: "Bears sleep through the cold winter.", vi: "Gấu ngủ suốt mùa đông lạnh giá." },
          { en: "A polar bear has thick white fur.", vi: "Một chú gấu bắc cực có bộ lông trắng dày." },
        ],
        notes: "Gấu bắc cực được gọi là 'polar bear'.",
      },
      {
        id: "wil7",
        term: "Snake",
        phonetic: "/sneɪk/",
        translation: "Con rắn",
        examples: [
          { en: "Some snakes are very poisonous.", vi: "Một số loài rắn rất độc." },
          { en: "The snake is crawling quietly in the grass.", vi: "Con rắn đang bò lặng lẽ trong cỏ." },
          { en: "She is afraid of snakes.", vi: "Cô ấy rất sợ rắn." },
        ],
        notes: "Động vật bò sát không chân.",
      },
      {
        id: "wil8",
        term: "Crocodile",
        phonetic: "/ˈkrɒkədaɪl/",
        translation: "Con cá sấu",
        examples: [
          { en: "The crocodile has sharp teeth and strong skin.", vi: "Con cá sấu có hàm răng sắc nhọn và bộ da rất khỏe." },
          { en: "Crocodiles live in rivers and lakes.", vi: "Cá sấu sống ở các dòng sông và hồ nước." },
          { en: "Don't go near the water; there are crocodiles.", vi: "Đừng đến gần mép nước; có cá sấu đấy." },
        ],
        notes: "Bò sát ăn thịt lớn sống dưới nước.",
      },
      {
        id: "wil9",
        term: "Fox",
        phonetic: "/fɒks/",
        translation: "Con cáo",
        examples: [
          { en: "The clever fox hid behind the bush.", vi: "Con cáo khôn ngoan đã trốn sau bụi cây." },
          { en: "A fox has a beautiful bushy tail.", vi: "Một con cáo có chiếc đuôi xù rất đẹp." },
          { en: "The red fox is a very fast animal.", vi: "Cáo đỏ là một loài động vật rất nhanh." },
        ],
        notes: "Tượng trưng cho sự khôn ngoan và tinh ranh.",
      },
      {
        id: "wil10",
        term: "Deer",
        phonetic: "/dɪə/",
        translation: "Con hươu, con nai",
        examples: [
          { en: "A wild deer ran across the road.", vi: "Một con nai hoang dã chạy vụt qua đường." },
          { en: "Male deer have large antlers.", vi: "Hươu đực có những chiếc gạc rất to." },
          { en: "We saw a group of deer in the forest.", vi: "Chúng tôi thấy một đàn hươu ở trong rừng." },
        ],
        notes: "Số nhiều vẫn giữ nguyên là 'deer'.",
      },
      {
        id: "wil11",
        term: "Wolf",
        phonetic: "/wʊlf/",
        translation: "Chó sói",
        examples: [
          { en: "The wolf is howling at the moon.", vi: "Con sói đang hú dưới trăng." },
          { en: "Wolves live and hunt in packs.", vi: "Sói sống và đi săn theo bầy đàn." },
          { en: "He is afraid of the big bad wolf.", vi: "Cậu ấy sợ con sói xám hung dữ." },
        ],
        notes: "Số nhiều biến đổi thành 'wolves' (bất quy tắc).",
      },
      {
        id: "wil12",
        term: "Hippo",
        phonetic: "/ˈhɪpəʊ/",
        translation: "Con hà mã",
        examples: [
          { en: "The hippo spent all day in the water.", vi: "Chú hà mã dành cả ngày ở dưới nước." },
          { en: "A hippo looks heavy but runs very fast.", vi: "Hà mã trông nặng nề nhưng chạy rất nhanh." },
          { en: "We saw a massive hippo at the national park.", vi: "Chúng tôi đã nhìn thấy một chú hà mã khổng lồ tại công viên quốc gia." },
        ],
        notes: "Tên đầy đủ là 'hippopotamus'.",
      },
      {
        id: "wil13",
        term: "Kangaroo",
        phonetic: "/ˌkæŋɡəˈruː/",
        translation: "Chuột túi, kangaroo",
        examples: [
          { en: "The kangaroo hops very high.", vi: "Con chuột túi nhảy rất cao." },
          { en: "A baby kangaroo lives inside its mother's pouch.", vi: "Chuột túi con sống bên trong chiếc túi của mẹ nó." },
          { en: "Karoos are native to Australia.", vi: "Chuột túi có nguồn gốc từ nước Úc." },
        ],
        notes: "Biểu tượng nổi tiếng của nước Úc.",
      },
      {
        id: "wil14",
        term: "Eagle",
        phonetic: "/ˈiːɡl/",
        translation: "Chim đại bàng",
        examples: [
          { en: "The eagle has sharp eyes and strong wings.", vi: "Đại bàng có đôi mắt sắc bén và đôi cánh khỏe." },
          { en: "An eagle is flying high in the sky.", vi: "Một con đại bàng đang bay lượn trên bầu trời cao." },
          { en: "Eagles build their nests on tall mountains.", vi: "Đại bàng làm tổ trên những ngọn núi cao." },
        ],
        notes: "Đi với mạo từ 'an'.",
      },
      {
        id: "wil15",
        term: "Zebra",
        phonetic: "/ˈziːbrə/",
        translation: "Ngựa vằn",
        examples: [
          { en: "A zebra has black and white stripes.", vi: "Ngựa vằn có các sọc đen và trắng." },
          { en: "Zebras eat grass on the savanna.", vi: "Ngựa vằn ăn cỏ trên thảo nguyên." },
          { en: "Each zebra has a unique pattern of stripes.", vi: "Mỗi con ngựa vằn đều có một kiểu sọc độc nhất." },
        ],
        notes: "Thường sống theo đàn để tránh thú dữ.",
      },
      {
        id: "wil16",
        term: "Gorilla",
        phonetic: "/ɡəˈrɪlə/",
        translation: "Khỉ đột",
        examples: [
          { en: "The gorilla is a very strong animal.", vi: "Khỉ đột là một loài động vật rất khỏe." },
          { en: "Gorillas live in family groups.", vi: "Khỉ đột sống theo nhóm gia đình." },
          { en: "The male gorilla is beating his chest.", vi: "Chú khỉ đột đực đang đấm vào ngực mình." },
        ],
        notes: "Loài khỉ lớn nhất và có họ hàng gần với con người.",
      },
      {
        id: "wil17",
        term: "Dolphin",
        phonetic: "/ˈdɒlfɪn/",
        translation: "Cá heo",
        examples: [
          { en: "The dolphin is very friendly and intelligent.", vi: "Cá heo rất thân thiện và thông minh." },
          { en: "We saw a group of dolphins jumping out of the sea.", vi: "Chúng tôi thấy một đàn cá heo nhảy lên khỏi mặt biển." },
          { en: "Dolphins communicate with each other using sounds.", vi: "Cá heo giao tiếp với nhau bằng cách sử dụng các âm thanh." },
        ],
        notes: "Dù sống dưới nước nhưng cá heo là động vật có vú (mammals), không phải loài cá thực sự.",
      },
      {
        id: "wil18",
        term: "Shark",
        phonetic: "/ʃɑːk/",
        translation: "Cá mập",
        examples: [
          { en: "The great white shark is a dangerous hunter.", vi: "Cá mập trắng lớn là một loài săn mồi nguy hiểm." },
          { en: "Sharks have multiple rows of sharp teeth.", vi: "Cá mập có nhiều hàng răng sắc nhọn." },
          { en: "Many people are afraid of sharks when swimming.", vi: "Nhiều người sợ cá mập khi đi bơi." },
        ],
        notes: "Loài cá săn mồi đỉnh cao ở đại dương.",
      },
      {
        id: "wil19",
        term: "Jungle",
        phonetic: "/ˈdʒʌŋɡl/",
        translation: "Rừng rậm nhiệt đới",
        examples: [
          { en: "Many wild animals live in the deep jungle.", vi: "Nhiều động vật hoang dã sống ở trong rừng rậm sâu thẳm." },
          { en: "They went on a trip through the jungle.", vi: "Họ đã có một chuyến đi băng qua rừng rậm." },
          { en: "The jungle is warm and wet.", vi: "Rừng rậm nhiệt đới rất ấm và ẩm ướt." },
        ],
        notes: "Thường chỉ rừng rậm rạp có nhiều dây leo và mưa nhiều.",
      },
      {
        id: "wil20",
        term: "Wild",
        phonetic: "/waɪld/",
        translation: "Hoang dã, tự nhiên",
        examples: [
          { en: "I love seeing animals in the wild.", vi: "Tôi thích ngắm nhìn các động vật trong tự nhiên." },
          { en: "These flowers are wild and grow everywhere.", vi: "Những bông hoa này là hoa dại và mọc ở khắp mọi nơi." },
          { en: "It is dangerous to touch a wild animal.", vi: "Rất nguy hiểm khi chạm vào một con động vật hoang dã." },
        ],
        notes: "Tính từ chỉ mọi thứ tự nhiên, chưa được thuần hóa.",
      },
    ],
  },
];
