export const tierEliteII = [
  {
    id: "topic_basic_law_ta2",
    title: "Chủ đề: Luật pháp cơ bản",
    category: "topic",
    description: "Các quy tắc hiến pháp, hành vi vi phạm pháp luật, quy trình tố tụng hình sự và phán quyết tại tòa án.",
    color: "bg-indigo-900",
    words: [
      {
        id: "law1",
        term: "Regulation",
        phonetic: "/ˌreɡjuˈleɪʃn/",
        translation: "Quy định, quy tắc chính thức",
        examples: [
          { en: "The government introduced new regulations on cybersecurity.", vi: "Chính phủ đã ban hành các quy định mới về an ninh mạng." },
          { en: "All employees must comply with the safety regulations of the factory.", vi: "Tất cả nhân viên phải tuân thủ các quy định an toàn của nhà máy." },
          { en: "The regulation of traffic is necessary for road safety.", vi: "Việc điều chỉnh kiểm soát giao thông là rất cần thiết cho an toàn đường bộ." },
        ],
        notes: "Quy tắc chính thức do một cơ quan có thẩm quyền ban hành.",
      },
      {
        id: "law2",
        term: "Court",
        phonetic: "/kɔːt/",
        translation: "Tòa án, phiên tòa / Sân đấu (bóng rổ/tennis)",
        examples: [
          { en: "The suspect is scheduled to appear in court on Friday morning.", vi: "Nghi phạm dự kiến sẽ phải hầu tòa vào sáng thứ Sáu." },
          { en: "The judge asked for order in the crowded court.", vi: "Thẩm phán đã yêu cầu trật tự trong phiên tòa đông đúc." },
          { en: "The hotel has a private basketball court for guests.", vi: "Khách sạn có một sân bóng rổ riêng tư dành cho khách lưu trú." },
        ],
        notes: "Nơi diễn ra các hoạt động xét xử pháp lý hợp pháp.",
      },
      {
        id: "law3",
        term: "Judge",
        phonetic: "/dʒʌdʒ/",
        translation: "Thẩm phán, quan tòa / Đánh giá, phán xét",
        examples: [
          { en: "The judge listened to the arguments from both lawyers.", vi: "Thẩm phán đã lắng nghe các lập luận lý lẽ từ cả hai luật sư." },
          { en: "It is difficult to judge a person based on their appearance.", vi: "Thật khó để phán xét một con người dựa trên ngoại hình của họ." },
          { en: "He works as a senior judge in the supreme court.", vi: "Ông ấy làm việc với tư cách là một thẩm phán cao cấp tại tòa án tối cao." },
        ],
        notes: "Vừa là danh từ (thẩm phán) vừa là động từ (đánh giá, phán xét).",
      },
      {
        id: "law4",
        term: "Lawyer",
        phonetic: "/ˈlɔɪə/",
        translation: "Luật sư, trạng sư",
        examples: [
          { en: "You should consult a lawyer before signing this contract.", vi: "Bạn nên tham khảo ý kiến của luật sư trước khi ký kết hợp đồng này." },
          { en: "The lawyer successfully defended his client in the trial.", vi: "Luật sư đã bào chữa thành công cho thân chủ của mình trong phiên tòa." },
          { en: "My cousin is studying hard to become a corporate lawyer.", vi: "Anh họ tôi đang học tập chăm chỉ để trở thành một luật sư doanh nghiệp." },
        ],
        notes: "Chuyên gia pháp lý được cấp phép đại diện cho khách hàng.",
      },
      {
        id: "law5",
        term: "Crime",
        phonetic: "/kraɪm/",
        translation: "Tội phạm, hành vi phạm tội",
        examples: [
          { en: "The police are determined to fight violent crime in the city.", vi: "Cảnh sát quyết tâm chống lại tội phạm bạo lực trong thành phố." },
          { en: "Stealing digital data is a serious cyber crime.", vi: "Ăn cắp dữ liệu số là một tội phạm công nghệ mạng nghiêm trọng." },
          { en: "He was arrested for committing a serious financial crime.", vi: "Anh ấy đã bị bắt vì thực hiện một tội phạm tài chính nghiêm trọng." },
        ],
        notes: "Hành động phạm pháp bị nhà nước nghiêm cấm và trừng phạt.",
      },
      {
        id: "law6",
        term: "Sentence",
        phonetic: "/ˈsentəns/",
        translation: "Bản án, hình phạt tù / Câu văn",
        examples: [
          { en: "The judge gave him a five-year prison sentence.", vi: "Thẩm phán đã đưa ra cho anh ấy một bản án năm năm tù giam." },
          { en: "Please write a complete sentence using this new word.", vi: "Vui lòng viết một câu hoàn chỉnh sử dụng từ mới này." },
          { en: "The murderer was sentenced to life imprisonment.", vi: "Kẻ giết người đã bị kết án tù chung thân." },
        ],
        notes: "Vừa là danh từ (bản án / câu văn) vừa là động từ (kết án).",
      },
      {
        id: "law7",
        term: "Witness",
        phonetic: "/ˈwɪtnəs/",
        translation: "Nhân chứng, người chứng kiến / Làm chứng, chứng kiến",
        examples: [
          { en: "The police called a witness to describe the car accident.", vi: "Cảnh sát đã gọi một nhân chứng để mô tả lại vụ tai nạn xe hơi." },
          { en: "She signed the document as a witness to the agreement.", vi: "Cô ấy đã ký vào văn bản với tư cách là nhân chứng cho thỏa thuận." },
          { en: "Thousands of excited fans witnessed the historic match.", vi: "Hàng ngàn người hâm mộ hào hứng đã chứng kiến trận đấu lịch sử." },
        ],
        notes: "Người chứng kiến sự việc trực tiếp và có thể khai báo trước tòa.",
      },
      {
        id: "law8",
        term: "Rights",
        phonetic: "/raɪts/",
        translation: "Quyền lợi, quyền lực hợp pháp",
        examples: [
          { en: "Every citizen has the right to free education.", vi: "Mỗi công dân đều có quyền được giáo dục miễn phí." },
          { en: "They fought for years to protect their basic human rights.", vi: "Họ đã chiến đấu nhiều năm để bảo vệ quyền con người cơ bản của mình." },
          { en: "The police informed the suspect of his legal rights.", vi: "Cảnh sát đã thông báo cho nghi phạm về các quyền hợp pháp của mình." },
        ],
        notes: "Danh từ số nhiều chỉ quyền lợi đạo đức hoặc pháp lý của cá nhân.",
      },
      {
        id: "law9",
        term: "Legal",
        phonetic: "/ˈliːɡl/",
        translation: "Hợp pháp, thuộc về luật pháp",
        examples: [
          { en: "You need to seek professional legal advice on this matter.", vi: "Bạn cần tìm kiếm lời khuyên pháp lý chuyên nghiệp về vấn đề này." },
          { en: "Is it legal to park your car on this sidewalk?", vi: "Đỗ xe hơi của bạn trên vỉa hè này có hợp pháp không?" },
          { en: "They are engaged in a long legal dispute over land.", vi: "Họ đang tham gia vào một tranh chấp pháp lý kéo dài về đất đai." },
        ],
        notes: "Liên quan đến luật pháp hoặc được luật pháp cho phép. Trái nghĩa là 'illegal'.",
      },
      {
        id: "law10",
        term: "Illegal",
        phonetic: "/ɪˈliːɡl/",
        translation: "Bất hợp pháp, phạm pháp",
        examples: [
          { en: "It is illegal to drive a motorcycle without a helmet.", vi: "Lái xe máy mà không đội mũ bảo hiểm là bất hợp pháp." },
          { en: "The factory was shut down for dumping illegal toxic waste.", vi: "Nhà máy đã bị đóng cửa vì đổ chất thải độc hại bất hợp pháp." },
          { en: "She was charged with illegal entry into the foreign country.", vi: "Cô ấy đã bị buộc tội nhập cảnh bất hợp pháp vào quốc gia nước ngoài." },
        ],
        notes: "Trái nghĩa hoàn toàn với 'legal'. Có mạo từ phủ định 'il-' ở trước.",
      },
      {
        id: "law11",
        term: "Violation",
        phonetic: "/ˌvaɪəˈleɪʃn/",
        translation: "Sự vi phạm pháp luật, xâm phạm",
        examples: [
          { en: "Dumping trash in the river is a direct violation of environmental law.", vi: "Đổ rác xuống sông là một sự vi phạm trực tiếp luật môi trường." },
          { en: "The military action was a violation of international treaties.", vi: "Hành động quân sự đã là một sự vi phạm các hiệp ước quốc tế." },
          { en: "He was fined for a minor traffic violation last night.", vi: "Anh ấy đã bị phạt tiền vì một vi phạm giao thông nhỏ tối qua." },
        ],
        notes: "Hành động phá vỡ một quy tắc, hiệp ước hoặc quyền lợi.",
      },
      {
        id: "law12",
        term: "Fine",
        phonetic: "/faɪn/",
        translation: "Tiền phạt, phạt tiền / Tốt, ổn khỏe",
        examples: [
          { en: "He had to pay a heavy fine for speeding.", vi: "Anh ấy đã phải trả một khoản tiền phạt nặng vì chạy quá tốc độ." },
          { en: "The court fined the company for misleading advertisements.", vi: "Tòa án đã phạt tiền công ty vì những quảng cáo gây hiểu lầm." },
          { en: "I am fine, thank you for asking.", vi: "Tôi khỏe, cảm ơn bạn đã hỏi." },
        ],
        notes: "Trong ngữ cảnh pháp luật, chỉ hình phạt tài chính buộc phải trả.",
      },
      {
        id: "law13",
        term: "Citizen",
        phonetic: "/ˈsɪtɪzn/",
        translation: "Công dân",
        examples: [
          { en: "Every citizen has a duty to respect the local laws.", vi: "Mỗi công dân đều có nghĩa vụ phải tôn trọng luật pháp địa phương." },
          { en: "She became a British citizen after living in London for ten years.", vi: "Cô ấy đã trở thành một công dân Anh sau khi sống ở Luân Đôn mười năm." },
          { en: "Active citizens take part in community improvement programs.", vi: "Những công dân năng động tham gia vào các chương trình cải thiện cộng đồng." },
        ],
        notes: "Thành viên chính thức của một quốc gia có quyền lợi và nghĩa vụ pháp lý.",
      },
      {
        id: "law14",
        term: "Justice",
        phonetic: "/ˈdʒʌstɪs/",
        translation: "Sự công lý, sự công bằng, tư pháp",
        examples: [
          { en: "The victims of the financial crime are demanding justice.", vi: "Các nạn nhân của tội phạm tài chính đang đòi hỏi công lý." },
          { en: "We must protect the independence of the justice system.", vi: "Chúng ta phải bảo vệ sự độc lập của hệ thống tư pháp." },
          { en: "The trial was a triumph for justice and human rights.", vi: "Phiên tòa đã là một thắng lợi cho công lý và quyền con người." },
        ],
        notes: "Sự đối xử công bằng trước pháp luật.",
      },
      {
        id: "law15",
        term: "Prosecute",
        phonetic: "/ˈprɒsɪkjuːt/",
        translation: "Khởi tố, truy tố trước tòa",
        examples: [
          { en: "The state decided to prosecute the manager for fraud.", vi: "Nhà nước đã quyết định truy tố người quản lý vì hành vi lừa đảo." },
          { en: "Shoplifters will be prosecuted to the full extent of the law.", vi: "Những kẻ trộm cắp ở cửa hàng sẽ bị khởi tố theo đúng mức độ hình phạt của pháp luật." },
          { en: "It is difficult to prosecute cyber criminals across different borders.", vi: "Thật khó để truy tố tội phạm mạng xuyên qua các biên giới quốc gia khác nhau." },
        ],
        notes: "Hành động buộc tội chính thức một người tại tòa án.",
      },
      {
        id: "law16",
        term: "Defense",
        phonetic: "/dɪˈfens/",
        translation: "Sự biện hộ, sự bào chữa / Sự phòng thủ",
        examples: [
          { en: "The lawyer prepared a strong defense for the accused suspect.", vi: "Luật sư đã chuẩn bị một sự bào chữa thuyết phục cho nghi phạm bị buộc tội." },
          { en: "He argued in defense of his client's innocence.", vi: "Ông ấy đã tranh luận để biện hộ cho sự vô tội của thân chủ." },
          { en: "The country invested heavily in military national defense.", vi: "Quốc gia đã đầu tư rất lớn vào phòng thủ quốc phòng quân sự." },
        ],
        notes: "Tiếng Anh-Anh thường viết là 'defence'. Hành động bác bỏ lời cáo buộc trước tòa.",
      },
      {
        id: "law17",
        term: "Verdict",
        phonetic: "/ˈvɜːdɪkt/",
        translation: "Phán quyết của bồi thẩm đoàn hoặc thẩm phán",
        examples: [
          { en: "After hours of discussion, the jury reached a guilty verdict.", vi: "Sau nhiều giờ đồng hồ thảo luận, bồi thẩm đoàn đã đưa ra một phán quyết có tội." },
          { en: "We are still waiting for the judge's final verdict on the trial.", vi: "Chúng tôi vẫn đang chờ đợi phán quyết cuối cùng của thẩm phán về phiên tòa." },
          { en: "The verdict was welcomed by the victim's family.", vi: "Phán quyết đã được gia đình nạn nhân hoan nghênh chào đón." },
        ],
        notes: "Quyết định chính thức cuối cùng của phiên tòa tuyên bố bị cáo có tội hay vô tội.",
      },
      {
        id: "law18",
        term: "Accuse",
        phonetic: "/əˈkjuːz/",
        translation: "Buộc tội, cáo buộc",
        examples: [
          { en: "She was accused of stealing money from the cash register.", vi: "Cô ấy đã bị buộc tội ăn cắp tiền từ ngăn kéo đựng tiền lẻ." },
          { en: "Do not accuse him without having strong evidence.", vi: "Đừng cáo buộc anh ấy khi không có bằng chứng thuyết phục." },
          { en: "He was falsely accused of committing the financial fraud.", vi: "Anh ấy đã bị buộc tội oan vì thực hiện vụ lừa đảo tài chính." },
        ],
        notes: "Thường đi kèm giới từ 'of' ('accuse someone of doing something').",
      },
      {
        id: "law19",
        term: "Agreement",
        phonetic: "/əˈɡriːmənt/",
        translation: "Hiệp định, hợp đồng, sự thỏa thuận",
        examples: [
          { en: "They signed a formal trade agreement after weeks of negotiation.", vi: "Họ đã ký một hiệp định thương mại chính thức sau nhiều tuần đàm phán." },
          { en: "Are we in agreement about the main terms of the contract?", vi: "Chúng ta có đồng thuận về các điều khoản chính của hợp đồng không?" },
          { en: "The agreement was terminated due to a violation by the partner.", vi: "Hợp đồng thỏa thuận đã bị chấm dứt do sự vi phạm của đối tác." },
        ],
        notes: "Văn bản hoặc sự đồng thuận chung mang tính pháp lý hoặc ngoại giao.",
      },
      {
        id: "law20",
        term: "Plaintiff",
        phonetic: "/ˈpleɪntɪf/",
        translation: "Nguyên đơn, người khởi kiện",
        examples: [
          { en: "The plaintiff is claiming damages for the injury caused by the accident.", vi: "Nguyên đơn đang yêu cầu bồi thường thiệt hại cho chấn thương do tai nạn gây ra." },
          { en: "The lawyer representing the plaintiff presented new evidence.", vi: "Luật sư đại diện cho nguyên đơn đã trình bày bằng chứng mới." },
          { en: "The judge asked the plaintiff to describe the event.", vi: "Thẩm phán yêu cầu nguyên đơn mô tả lại sự việc." },
        ],
        notes: "Cá nhân hoặc tổ chức chính thức đệ đơn kiện ai đó ra tòa án dân sự.",
      },
    ],
  },
  {
    id: "topic_business_startups_ta2",
    title: "Chủ đề: Kinh doanh & Khởi nghiệp",
    category: "topic",
    description: "Các mô hình khởi nghiệp, nguồn vốn đầu tư đầu tư thiên thần, chiến lược tiếp thị thị trường và phá sản.",
    color: "bg-indigo-900",
    words: [
      {
        id: "bus1",
        term: "Startup",
        phonetic: "/ˈstɑːtʌp/",
        translation: "Công ty khởi nghiệp, doanh nghiệp mới mở",
        examples: [
          { en: "She founded a technology startup specializing in AI healthcare.", vi: "Cô ấy đã thành lập một công ty khởi nghiệp công nghệ chuyên về chăm sóc sức khỏe bằng AI." },
          { en: "Many startups fail within their first three years of business.", vi: "Nhiều doanh nghiệp khởi nghiệp thất bại ngay trong ba năm đầu kinh doanh." },
          { en: "The startup raised five million dollars in its latest funding round.", vi: "Công ty khởi nghiệp đã huy động được năm triệu đô la trong vòng rót vốn mới nhất." },
        ],
        notes: "Công ty mới thành lập, thường có tính đổi mới sáng tạo đột phá.",
      },
      {
        id: "bus2",
        term: "Entrepreneur",
        phonetic: "/ˌɒntrəprəˈnɜː/",
        translation: "Doanh nhân, nhà khởi nghiệp độc lập",
        examples: [
          { en: "He is a creative entrepreneur who owns three different businesses.", vi: "Anh ấy là một nhà khởi nghiệp sáng tạo sở hữu ba doanh nghiệp khác nhau." },
          { en: "Starting a company requires the mind of a brave entrepreneur.", vi: "Thành lập một công ty đòi hỏi tư duy của một nhà khởi nghiệp dũng cảm." },
          { en: "The university hosts a seminar for young student entrepreneurs.", vi: "Trường đại học tổ chức một buổi hội thảo dành cho các doanh nhân học sinh trẻ tuổi." },
        ],
        notes: "Người tự mở doanh nghiệp, chấp nhận rủi ro tài chính để kiếm lợi nhuận.",
      },
      {
        id: "bus3",
        term: "Profit",
        phonetic: "/ˈprɒfɪt/",
        translation: "Lợi nhuận, tiền lãi",
        examples: [
          { en: "The company's net profit increased by twenty percent this quarter.", vi: "Lợi nhuận ròng của công ty đã tăng hai mươi phần trăm trong quý này." },
          { en: "They sold the property at a huge profit.", vi: "Họ đã bán bất động sản đó với một khoản lợi nhuận khổng lồ." },
          { en: "The main goal of any business is to maximize profit.", vi: "Mục tiêu chính của bất kỳ doanh nghiệp nào là tối đa hóa lợi nhuận." },
        ],
        notes: "Doanh thu trừ đi tổng chi phí.",
      },
      {
        id: "bus4",
        term: "Investment",
        phonetic: "/ɪnˈvestmənt/",
        translation: "Sự đầu tư, khoản đầu tư",
        examples: [
          { en: "Buying real estate is considered a long-term investment.", vi: "Mua bất động sản được coi là một khoản đầu tư dài hạn." },
          { en: "The startup is looking for an investment to expand its app.", vi: "Công ty khởi nghiệp đang tìm kiếm một khoản đầu tư để mở rộng ứng dụng." },
          { en: "He made a bad investment and lost half of his capital.", vi: "Anh ấy đã đầu tư sai lầm và mất một nửa số vốn đầu tư." },
        ],
        notes: "Danh từ của động từ 'invest' (đầu tư).",
      },
      {
        id: "bus5",
        term: "Strategy",
        phonetic: "/ˈstrætədʒi/",
        translation: "Chiến lược hành động lâu dài",
        examples: [
          { en: "The company needs a new marketing strategy to attract teenagers.", vi: "Công ty cần một chiến lược tiếp thị mới để thu hút giới trẻ." },
          { en: "They developed a long-term business strategy for global growth.", vi: "Họ đã phát triển một chiến lược kinh doanh dài hạn cho sự tăng trưởng toàn cầu." },
          { en: "We must change our strategy if the competitor cuts prices.", vi: "Chúng ta phải thay đổi chiến lược nếu đối thủ cạnh tranh cắt giảm giá bán." },
        ],
        notes: "Kế hoạch tổng thể để đạt được mục tiêu lâu dài.",
      },
      {
        id: "bus6",
        term: "Competitor",
        phonetic: "/kəmˈpetɪtə/",
        translation: "Đối thủ cạnh tranh",
        examples: [
          { en: "We must monitor our competitors' product launches closely.", vi: "Chúng ta phải giám sát chặt chẽ các đợt tung sản phẩm mới của đối thủ cạnh tranh." },
          { en: "The firm is trying to offer better services than its competitors.", vi: "Hãng đang nỗ lực cung cấp các dịch vụ tốt hơn so với đối thủ cạnh tranh." },
          { en: "They bought out their main competitor in the local market.", vi: "Họ đã mua lại đối thủ cạnh tranh chính của mình tại thị trường địa phương." },
        ],
        notes: "Doanh nghiệp hoặc người cạnh tranh trực tiếp trong cùng lĩnh vực.",
      },
      {
        id: "bus7",
        term: "Revenue",
        phonetic: "/ˈrevənjuː/",
        translation: "Doanh thu, tổng thu nhập kinh doanh",
        examples: [
          { en: "The advertising campaigns helped double the company's revenue.", vi: "Các chiến dịch quảng cáo đã giúp tăng gấp đôi doanh thu của công ty." },
          { en: "Our annual revenue reached ten million dollars last year.", vi: "Tổng doanh thu hàng năm của chúng tôi đạt mười triệu đô la vào năm ngoái." },
          { en: "The government is trying to find ways to increase tax revenue.", vi: "Chính phủ đang nỗ lực tìm cách tăng doanh thu thuế thu nhập." },
        ],
        notes: "Tổng số tiền doanh nghiệp thu được trước khi trừ chi phí.",
      },
      {
        id: "bus8",
        term: "Budget",
        phonetic: "/ˈbʌdʒɪt/",
        translation: "Ngân sách chi tiêu / Lên kế hoạch ngân sách",
        examples: [
          { en: "We must complete the project within the limited budget.", vi: "Chúng ta phải hoàn thành dự án trong phạm vi ngân sách có hạn." },
          { en: "She learned how to budget her monthly salary carefully.", vi: "Cô ấy đã học cách lập ngân sách chi tiêu cẩn thận cho tiền lương tháng của mình." },
          { en: "The marketing budget was cut by thirty percent.", vi: "Ngân sách tiếp thị đã bị cắt giảm ba mươi phần trăm." },
        ],
        notes: "Kế hoạch chi tiết về việc phân bổ nguồn lực tài chính.",
      },
      {
        id: "bus9",
        term: "Partner",
        phonetic: "/ˈpɑːtnə/",
        translation: "Đối tác kinh doanh / Bạn đời",
        examples: [
          { en: "He found a reliable business partner to start the firm with.", vi: "Anh ấy đã tìm thấy một đối tác kinh doanh đáng tin cậy để cùng thành lập công ty." },
          { en: "They signed a contract to become strategic trading partners.", vi: "Họ đã ký hợp đồng để trở thành những đối tác thương mại chiến lược của nhau." },
          { en: "She introduced her life partner to her parents.", vi: "Cô ấy đã giới thiệu bạn đời của mình cho bố mẹ cô." },
        ],
        notes: "Cá nhân hoặc tổ chức cùng hợp tác chung mục đích.",
      },
      {
        id: "bus10",
        term: "Launch",
        phonetic: "/lɔːntʃ/",
        translation: "Ra mắt sản phẩm, tung ra thị trường / Phóng (tên lửa)",
        examples: [
          { en: "The tech startup is preparing to launch its new application.", vi: "Doanh nghiệp khởi nghiệp công nghệ đang chuẩn bị ra mắt ứng dụng mới của mình." },
          { en: "We attended the product launch party last night.", vi: "Chúng tôi đã tham dự bữa tiệc ra mắt sản phẩm mới vào tối qua." },
          { en: "They successfully launched a satellite into orbit.", vi: "Họ đã phóng thành công một vệ tinh vào quỹ đạo." },
        ],
        notes: "Vừa là động từ vừa là danh từ.",
      },
      {
        id: "bus11",
        term: "Capital",
        phonetic: "/ˈkæpɪtl/",
        translation: "Vốn đầu tư, nguồn vốn / Thủ đô / Chữ viết hoa",
        examples: [
          { en: "The entrepreneur raised sufficient capital to start his factory.", vi: "Nhà khởi nghiệp đã huy động đủ vốn đầu tư để xây dựng nhà máy." },
          { en: "London is the capital city of the United Kingdom.", vi: "Luân Đôn là thủ đô của Vương quốc Anh." },
          { en: "Write your name in capital letters, please.", vi: "Vui lòng viết tên của bạn bằng chữ viết hoa." },
        ],
        notes: "Trong kinh tế học, chỉ nguồn lực tài chính ban đầu để mở doanh nghiệp.",
      },
      {
        id: "bus12",
        term: "Consumer",
        phonetic: "/kənˈsjuːmə/",
        translation: "Người tiêu dùng, người sử dụng dịch vụ",
        examples: [
          { en: "The survey analyzed consumer behavior and buying habits.", vi: "Cuộc khảo sát đã phân tích hành vi của người tiêu dùng và thói quen mua sắm." },
          { en: "We need to protect consumers from misleading advertisements.", vi: "Chúng ta cần bảo vệ người tiêu dùng khỏi những quảng cáo gây hiểu lầm." },
          { en: "Organic foods are becoming popular among health-conscious consumers.", vi: "Thực phẩm hữu cơ đang trở nên phổ biến đối với những người tiêu dùng quan tâm đến sức khỏe." },
        ],
        notes: "Người trực tiếp sử dụng hàng hóa, rộng hơn 'customer' (chỉ người mua).",
      },
      {
        id: "bus13",
        term: "Risk",
        phonetic: "/rɪsk/",
        translation: "Rủi ro, mối nguy / Liều lĩnh rủi ro",
        examples: [
          { en: "Starting a startup always involves a high financial risk.", vi: "Khởi nghiệp kinh doanh luôn bao gồm một rủi ro tài chính cao." },
          { en: "You shouldn't risk your health by working too much overtime.", vi: "Bạn không nên liều lĩnh sức khỏe của mình bằng việc làm tăng ca quá nhiều." },
          { en: "The investment was risky, but the profit was enormous.", vi: "Khoản đầu tư đã rất rủi ro, nhưng lợi nhuận mang lại thì khổng lồ." },
        ],
        notes: "Vừa là danh từ vừa là động từ. Tính từ là 'risky'.",
      },
      {
        id: "bus14",
        term: "Scale",
        phonetic: "/skeɪl/",
        translation: "Mở rộng quy mô / Cái cân / Thang đo tỷ lệ",
        examples: [
          { en: "The startup plans to scale up its operations to other countries.", vi: "Công ty khởi nghiệp có kế hoạch mở rộng quy mô hoạt động sang các nước khác." },
          { en: "On a scale of one to ten, how would you rate this service?", vi: "Trên thang điểm từ một đến mười, bạn đánh giá dịch vụ này thế nào?" },
          { en: "She weighed the ingredients on the kitchen scale.", vi: "Cô ấy đã cân các nguyên liệu trên chiếc cân nhà bếp." },
        ],
        notes: "Cụm 'scale up' là thuật ngữ kinh tế cốt lõi chỉ việc mở rộng kinh doanh nhanh chóng.",
      },
      {
        id: "bus15",
        term: "Funding",
        phonetic: "/ˈfʌndɪŋ/",
        translation: "Sự rót vốn, quỹ tài trợ",
        examples: [
          { en: "The research project received funding from the state government.", vi: "Dự án nghiên cứu đã nhận được sự rót vốn từ chính phủ bang." },
          { en: "They are struggling to secure funding for their new startup.", vi: "Họ đang chật vật để đảm bảo có được nguồn vốn cho dự án khởi nghiệp mới." },
          { en: "The school built a new campus using private funding.", vi: "Trường học đã xây dựng khuôn viên mới bằng nguồn tài trợ tư nhân." },
        ],
        notes: "Danh từ không đếm được chỉ tiền cấp cho một mục đích hoặc dự án.",
      },
      {
        id: "bus16",
        term: "Bankruptcy",
        phonetic: "/ˈbæŋkrəptsi/",
        translation: "Sự phá sản, tình trạng vỡ nợ",
        examples: [
          { en: "The economic recession drove many small shops into bankruptcy.", vi: "Suy thoái kinh tế đã đẩy nhiều cửa hàng nhỏ vào tình trạng phá sản." },
          { en: "The company filed for bankruptcy after failing to pay its debts.", vi: "Công ty đã nộp đơn xin phá sản sau khi không trả được các khoản nợ." },
          { en: "He managed to save his firm from bankruptcy at the last minute.", vi: "Anh ấy đã xoay xở cứu công ty của mình khỏi bờ vực phá sản vào phút cuối." },
        ],
        notes: "Trạng thái pháp lý khi cá nhân/doanh nghiệp không thể hoàn trả nợ.",
      },
      {
        id: "bus17",
        term: "Acquisition",
        phonetic: "/ˌækwɪˈzɪʃn/",
        translation: "Sự mua lại doanh nghiệp / Đạt được kỹ năng học vấn",
        examples: [
          { en: "The corporation announced the acquisition of a rival startup.", vi: "Tập đoàn đã công bố thương vụ mua lại một công ty khởi nghiệp đối thủ." },
          { en: "Language acquisition is easier for young children than adults.", vi: "Việc tiếp thu ngôn ngữ thì dễ dàng đối với trẻ nhỏ hơn là người lớn." },
          { en: "The library expanded its collection through several new acquisitions.", vi: "Thư viện đã mở rộng bộ sưu tập của mình qua nhiều hiện vật mua lại mới." },
        ],
        notes: "Trong kinh doanh, chỉ hoạt động mua lại một công ty khác (M&A).",
      },
      {
        id: "bus18",
        term: "Niche market",
        phonetic: "/niːʃ ˈmɑːkɪt/",
        translation: "Thị trường ngách, phân khúc nhỏ",
        examples: [
          { en: "Organic pet food is a highly profitable niche market.", vi: "Thức ăn hữu cơ cho thú cưng là một thị trường ngách mang lại lợi nhuận cao." },
          { en: "The startup found success by targeting a specific niche market.", vi: "Công ty khởi nghiệp đã tìm thấy thành công bằng cách nhắm tới một thị trường ngách cụ thể." },
          { en: "It is easier to compete in a niche market than a mass market.", vi: "Cạnh tranh trong một thị trường ngách thì dễ dàng hơn trong một thị trường đại chúng." },
        ],
        notes: "Phân khúc thị trường hẹp, chuyên biệt bỏ qua bởi các đối thủ lớn.",
      },
      {
        id: "bus19",
        term: "Pitch",
        phonetic: "/pɪtʃ/",
        translation: "Buổi thuyết trình thuyết phục rót vốn / Sân bóng đá cỏ",
        examples: [
          { en: "The entrepreneur made a brilliant pitch to the angel investors.", vi: "Nhà khởi nghiệp đã có một buổi thuyết trình gọi vốn tuyệt vời trước các nhà đầu tư thiên thần." },
          { en: "The soccer team trained on the wet grass pitch.", vi: "Đội bóng đá đã tập luyện trên sân cỏ ướt." },
          { en: "She spent all night preparing her business sales pitch.", vi: "Cô ấy dành cả đêm để chuẩn bị bài thuyết trình chào hàng kinh doanh của mình." },
        ],
        notes: "Bài phát biểu ngắn gọn hấp dẫn để thuyết phục nhà đầu tư bỏ vốn.",
      },
      {
        id: "bus20",
        term: "Equity",
        phonetic: "/ˈekwəti/",
        translation: "Cổ phần doanh nghiệp / Sự công bằng đạo lý",
        examples: [
          { en: "The founders offered ten percent equity to the angel investor.", vi: "Những nhà sáng lập đã đề xuất mười phần trăm cổ phần cho nhà đầu tư thiên thần." },
          { en: "She plans to buy equity in several promising startups.", vi: "Cô ấy có kế hoạch mua cổ phần trong một vài doanh nghiệp khởi nghiệp đầy hứa hẹn." },
          { en: "The government is trying to promote equity in the education system.", vi: "Chính phủ đang nỗ lực thúc đẩy sự công bằng trong hệ thống giáo dục." },
        ],
        notes: "Tỷ lệ sở hữu hợp pháp của một cá nhân trong doanh nghiệp.",
      },
    ],
  },
  {
    id: "topic_general_medicine_ta2",
    title: "Chủ đề: Y học phổ thông",
    category: "topic",
    description: "Các phương pháp điều trị y sinh chuyên biệt, phẫu thuật ngoại khoa, vắc-xin và chẩn đoán lâm sàng.",
    color: "bg-indigo-900",
    words: [
      {
        id: "med1",
        term: "Physician",
        phonetic: "/fɪˈzɪʃn/",
        translation: "Bác sĩ đa khoa, bác sĩ điều trị chuyên sâu",
        examples: [
          { en: "He works as a primary care physician in a local hospital.", vi: "Anh ấy làm việc với tư cách là bác sĩ chăm sóc ban đầu tại một bệnh viện địa phương." },
          { en: "The physician recommended a change in his diet.", vi: "Bác sĩ điều trị đã khuyên nên thay đổi chế độ ăn uống của anh." },
          { en: "She consulted several physicians regarding her chronic pain.", vi: "Cô ấy đã tham khảo ý kiến của vài bác sĩ điều trị về cơn đau mãn tính của mình." },
        ],
        notes: "Từ trang trọng chỉ bác sĩ y khoa, phân biệt với bác sĩ ngoại khoa (surgeon).",
      },
      {
        id: "med2",
        term: "Therapy",
        phonetic: "/ˈθerəpi/",
        translation: "Liệu pháp, quá trình trị liệu y học",
        examples: [
          { en: "Music therapy is helpful for patients suffering from stress.", vi: "Liệu pháp âm nhạc rất hữu ích cho các bệnh nhân đang chịu đựng sự căng thẳng." },
          { en: "She is undergoing physical therapy to recover her strength.", vi: "Cô ấy đang trải qua trị liệu vật lý để phục hồi sức lực của mình." },
          { en: "The cancer patient responded well to the radiation therapy.", vi: "Bệnh nhân ung thư đã phản ứng tốt với liệu pháp xạ trị." },
        ],
        notes: "Quá trình chữa trị bệnh tật hoặc vấn đề tâm lý không thông qua phẫu thuật.",
      },
      {
        id: "med3",
        term: "Prevention",
        phonetic: "/prɪˈvenʃn/",
        translation: "Sự phòng bệnh, phòng ngừa",
        examples: [
          { en: "Prevention is always better than cure.", vi: "Phòng bệnh bao giờ cũng tốt hơn chữa bệnh." },
          { en: "The campaign focuses on the prevention of infectious diseases.", vi: "Chiến dịch tập trung vào việc phòng ngừa các bệnh truyền nhiễm." },
          { en: "Daily exercise is crucial for the prevention of heart disease.", vi: "Tập thể dục hàng ngày là tối quan trọng cho việc phòng ngừa bệnh tim." },
        ],
        notes: "Danh từ của động từ 'prevent' (phòng ngừa).",
      },
      {
        id: "med4",
        term: "Surgery",
        phonetic: "/ˈsɜːdʒəri/",
        translation: "Ca phẫu thuật, ngoại khoa",
        examples: [
          { en: "The surgeon performed a complex heart surgery yesterday.", vi: "Bác sĩ ngoại khoa đã thực hiện một ca phẫu thuật tim phức tạp vào ngày hôm qua." },
          { en: "He is recovering in the hospital after knee surgery.", vi: "Cậu ấy đang hồi phục trong bệnh viện sau ca phẫu thuật đầu gối." },
          { en: "The patient does not need major surgery; medication is sufficient.", vi: "Bệnh nhân không cần phẫu thuật lớn; dùng thuốc là đủ rồi." },
        ],
        notes: "Chữa bệnh bằng phương pháp mổ sẻ vật lý do bác sĩ phẫu thuật thực hiện.",
      },
      {
        id: "med5",
        term: "Dosage",
        phonetic: "/ˈdəʊsɪdʒ/",
        translation: "Liều lượng thuốc chỉ định",
        examples: [
          { en: "Do not exceed the recommended dosage on the medicine label.", vi: "Không được vượt quá liều lượng thuốc được khuyến nghị trên nhãn thuốc." },
          { en: "The doctor adjusted the dosage of his medication.", vi: "Bác sĩ đã điều chỉnh liều lượng thuốc điều trị của ông." },
          { en: "A high dosage of this painkiller can be harmful to liver.", vi: "Một liều lượng cao của thuốc giảm đau này có thể gây hại cho gan." },
        ],
        notes: "Lượng thuốc chính xác được chỉ định sử dụng mỗi lần hoặc mỗi ngày.",
      },
      {
        id: "med6",
        term: "Immune",
        phonetic: "/ɪˈmjuːn/",
        translation: "Miễn dịch, được miễn khỏi",
        examples: [
          { en: "Vaccine helps the body build an immune response.", vi: "Vắc-xin giúp cơ thể xây dựng phản ứng miễn dịch." },
          { en: "Some people are naturally immune to this virus.", vi: "Một số người được miễn dịch tự nhiên với loại vi-rút này." },
          { en: "Healthy food strengthens your immune system.", vi: "Thực phẩm lành mạnh tăng cường hệ thống miễn dịch của bạn." },
        ],
        notes: "Trạng thái cơ thể có khả năng kháng cự mầm bệnh.",
      },
      {
        id: "med7",
        term: "Vaccine",
        phonetic: "/ˈvæksiːn/",
        translation: "Vắc-xin",
        examples: [
          { en: "Scientists developed an effective vaccine against the virus.", vi: "Các nhà khoa học đã phát triển một loại vắc-xin hiệu quả chống lại vi-rút." },
          { en: "The government launched a free vaccine campaign for children.", vi: "Chính phủ đã khởi động chiến dịch tiêm vắc-xin miễn phí cho trẻ em." },
          { en: "Have you received your flu vaccine this year?", vi: "Bạn đã tiêm phòng vắc-xin cúm năm nay chưa?" },
        ],
        notes: "Chế phẩm sinh học tạo miễn dịch chủ động.",
      },
      {
        id: "med8",
        term: "Diagnosis",
        phonetic: "/ˌdaɪəɡˈnəʊsɪs/",
        translation: "Sự chẩn đoán bệnh",
        examples: [
          { en: "An accurate diagnosis is necessary before starting treatment.", vi: "Một sự chẩn đoán chính xác là cần thiết trước khi bắt đầu điều trị." },
          { en: "The doctor confirmed the diagnosis after analyzing the blood test.", vi: "Bác sĩ đã xác nhận chẩn đoán bệnh sau khi phân tích xét nghiệm máu." },
          { en: "Her diagnosis showed that she has a minor skin allergy.", vi: "Chẩn đoán của cô cho thấy cô bị dị ứng da nhẹ." },
        ],
        notes: "Hành động xác định bệnh tật qua triệu chứng lâm sàng. Số nhiều là 'diagnoses'.",
      },
      {
        id: "med9",
        term: "Prescribe",
        phonetic: "/prɪˈskraɪb/",
        translation: "Kê đơn thuốc, ra toa thuốc",
        examples: [
          { en: "The doctor prescribed some antibiotics for her sore throat.", vi: "Bác sĩ đã kê đơn một số loại kháng sinh cho chứng viêm họng của cô ấy." },
          { en: "You shouldn't take medicine unless a physician prescribes it.", vi: "Bạn không nên uống thuốc trừ khi bác sĩ kê đơn thuốc đó." },
          { en: "The specialist prescribed a special cream for my dry skin.", vi: "Chuyên gia đã kê một loại kem đặc trị cho làn da khô của tôi." },
        ],
        notes: "Hành động bác sĩ viết đơn thuốc cho phép bệnh nhân mua thuốc đặc trị.",
      },
      {
        id: "med10",
        term: "Clinic",
        phonetic: "/ˈklɪnɪk/",
        translation: "Phòng khám bệnh tư nhân hoặc chuyên khoa",
        examples: [
          { en: "She works as a dental assistant in a modern clinic.", vi: "Cô ấy làm việc với tư cách trợ tá nha khoa tại một phòng khám hiện đại." },
          { en: "We visited the local health clinic for a quick checkup.", vi: "Chúng tôi đã đến phòng khám sức khỏe địa phương để khám nhanh." },
          { en: "The university clinic provides free medical advice to students.", vi: "Phòng khám trường đại học cung cấp tư vấn y tế miễn phí cho sinh viên." },
        ],
        notes: "Nơi khám chữa bệnh nhỏ hơn bệnh viện (hospital).",
      },
      {
        id: "med11",
        term: "Emergency",
        phonetic: "/ɪˈmɜːdʒənsi/",
        translation: "Tình trạng khẩn cấp, cấp cứu",
        examples: [
          { en: "In case of emergency, please dial nine-one-one immediately.", vi: "Trong trường hợp khẩn cấp, vui lòng quay số 911 ngay lập tức." },
          { en: "He was rushed to the hospital emergency room last night.", vi: "Anh ấy đã được đưa gấp tới phòng cấp cứu của bệnh viện vào tối qua." },
          { en: "The country declared a state of medical emergency during the epidemic.", vi: "Đất nước đã tuyên bố tình trạng khẩn cấp y tế trong suốt đợt dịch bệnh." },
        ],
        notes: "Tình huống nguy hiểm đe dọa trực tiếp tính mạng cần xử lý ngay lập tức.",
      },
      {
        id: "med12",
        term: "Chronic",
        phonetic: "/ˈkrɒnɪk/",
        translation: "Mãn tính, kéo dài không dứt",
        examples: [
          { en: "Asthma is a common chronic respiratory disease.", vi: "Hen suyễn là một bệnh đường hô hấp mãn tính phổ biến." },
          { en: "My grandfather suffers from chronic back pain.", vi: "Ông tôi phải chịu đựng chứng đau lưng mãn tính kéo dài." },
          { en: "It is difficult to treat chronic infections without strong drugs.", vi: "Rất khó để điều trị các bệnh viêm nhiễm mãn tính nếu không có thuốc mạnh." },
        ],
        notes: "Bệnh tật kéo dài lâu ngày hoặc lặp đi lặp lại thường xuyên, trái nghĩa với 'acute' (cấp tính).",
      },
      {
        id: "med13",
        term: "Rehabilitation",
        phonetic: "/ˌriːəˌbɪlɪˈteɪʃn/",
        translation: "Sự phục hồi chức năng sau chấn thương",
        examples: [
          { en: "The athlete underwent physical rehabilitation after the surgery.", vi: "Vận động viên đã trải qua phục hồi chức năng thể chất sau ca phẫu thuật." },
          { en: "He spent three months in the rehabilitation center learning to walk again.", vi: "Ông đã dành ba tháng tại trung tâm phục hồi chức năng để tập đi trở lại." },
          { en: "The stroke patient requires ongoing rehabilitation therapy.", vi: "Bệnh nhân đột quỵ yêu cầu liệu pháp phục hồi chức năng liên tục." },
        ],
        notes: "Quá trình lấy lại kỹ năng vận động bị mất do chấn thương hoặc tai biến.",
      },
      {
        id: "med14",
        term: "First aid",
        phonetic: "/ˌfɜːst ˈeɪd/",
        translation: "Sơ cứu, sự sơ cứu ban đầu",
        examples: [
          { en: "All school staff are trained to administer basic first aid.", vi: "Tất cả nhân viên trường học đều được đào tạo để thực hiện sơ cứu cơ bản." },
          { en: "Keep a first aid kit in your car in case of accidents.", vi: "Hãy giữ một bộ dụng cụ sơ cứu trong xe hơi của bạn phòng khi có tai nạn." },
          { en: "The teacher applied first aid to the bleeding cut.", vi: "Giáo viên đã tiến hành sơ cứu cho vết đứt chảy máu." },
        ],
        notes: "Sự hỗ trợ y tế khẩn cấp ban đầu trước khi có bác sĩ chuyên nghiệp.",
      },
      {
        id: "med15",
        term: "Blood donor",
        phonetic: "/ˈblʌd ˌdəʊnə/",
        translation: "Người hiến máu nhân đạo",
        examples: [
          { en: "The hospital is looking for blood donors of O-negative type.", vi: "Bệnh viện đang tìm kiếm những người hiến máu thuộc nhóm máu O âm tính." },
          { en: "He has been a regular blood donor for over ten years.", vi: "Anh ấy đã là một người hiến máu thường xuyên suốt hơn mười năm qua." },
          { en: "The university hosted a campaign to recruit new blood donors.", vi: "Trường đại học đã tổ chức một chiến dịch để tuyển thêm những người hiến máu mới." },
        ],
        notes: "Người tự nguyện cho máu để phục vụ cấp cứu y tế.",
      },
      {
        id: "med16",
        term: "Organ transplant",
        phonetic: "/ˈɔːɡən ˌtrænsplɑːnt/",
        translation: "Sự cấy ghép nội tạng",
        examples: [
          { en: "The patient is waiting for a kidney organ transplant.", vi: "Bệnh nhân đang chờ đợi một ca cấy ghép nội tạng thận." },
          { en: "Organ transplant surgery requires high professional skills.", vi: "Phẫu thuật ghép tạng đòi hỏi các kỹ năng chuyên môn cực kỳ cao." },
          { en: "The successful organ transplant saved his life.", vi: "Ca cấy ghép tạng thành công đã cứu sống tính mạng của anh ấy." },
        ],
        notes: "Quy trình y khoa phẫu thuật thay thế cơ quan nội tạng bị hỏng bằng tạng khỏe mạnh.",
      },
      {
        id: "med17",
        term: "Side effect",
        phonetic: "/ˈsaɪd ɪˌfekt/",
        translation: "Tác dụng phụ của thuốc",
        examples: [
          { en: "Drowsiness is a common side effect of this cold medicine.", vi: "Buồn ngủ là một tác dụng phụ phổ biến của loại thuốc cảm lạnh này." },
          { en: "If you experience any unusual side effects, stop taking the pills.", vi: "Nếu bạn gặp bất kỳ tác dụng phụ bất thường nào, hãy ngừng uống thuốc." },
          { en: "The antibiotic helped treat the infection but had mild side effects.", vi: "Thuốc kháng sinh đã giúp điều trị nhiễm trùng nhưng lại có những tác dụng phụ nhẹ." },
        ],
        notes: "Tác động không mong muốn xuất hiện khi dùng thuốc chữa bệnh.",
      },
      {
        id: "med18",
        term: "Symptomatic",
        phonetic: "/ˌsɪmptəˈmætɪk/",
        translation: "Thuộc về triệu chứng, có triệu chứng",
        examples: [
          { en: "He tested positive for the virus but remained non-symptomatic.", vi: "Cậu ấy đã xét nghiệm dương tính với vi-rút nhưng không xuất hiện triệu chứng." },
          { en: "The doctor offered a symptomatic treatment to reduce the fever.", vi: "Bác sĩ đưa ra một phương pháp điều trị triệu chứng để giảm bớt cơn sốt." },
          { en: "Frequent coughing is symptomatic of respiratory infection.", vi: "Ho thường xuyên là biểu hiện triệu chứng của viêm nhiễm đường hô hấp." },
        ],
        notes: "Tính từ của danh từ 'symptom' (triệu chứng).",
      },
      {
        id: "med19",
        term: "Anesthesia",
        phonetic: "/ˌænəsˈθiːziə/",
        translation: "Sự gây mê, thuốc gây mê",
        examples: [
          { en: "The patient was put under general anesthesia before the surgery.", vi: "Bệnh nhân đã được gây mê toàn thân trước khi tiến hành phẫu thuật." },
          { en: "The dentist applied a local anesthesia to numb the gums.", vi: "Nha sĩ đã sử dụng thuốc gây tê cục bộ để làm tê nướu răng." },
          { en: "She felt dizzy as the effects of the anesthesia wore off.", vi: "Cô ấy cảm thấy chóng mặt khi tác dụng của thuốc gây mê hết dần." },
        ],
        notes: "Chất hoặc phương pháp làm mất cảm giác tạm thời để phẫu thuật không đau.",
      },
      {
        id: "med20",
        term: "Cardiology",
        phonetic: "/ˌkɑːdiˈɒlədʒi/",
        translation: "Khoa tim mạch, chuyên khoa tim",
        examples: [
          { en: "He was referred to the cardiology department for further tests.", vi: "Anh ấy đã được chuyển đến khoa tim mạch để thực hiện thêm các xét nghiệm." },
          { en: "Cardiology focuses on diagnosing and treating heart diseases.", vi: "Khoa tim mạch tập trung vào việc chẩn đoán và điều trị các bệnh về tim." },
          { en: "She works as a senior researcher in the cardiology institute.", vi: "Cô ấy làm việc với tư cách là nhà nghiên cứu cao cấp tại viện tim mạch." },
        ],
        notes: "Ngành chuyên khoa sâu nghiên cứu về cấu trúc và bệnh lý tim mạch.",
      },
    ],
  },
];
