export const tierEmeraldII = [
  {
    id: "topic_travel_e2",
    title: "Du lịch & Khách sạn",
    category: "topic",
    description: "Các thủ tục đặt phòng khách sạn, hành lý và hoạt động trải nghiệm văn hóa du lịch.",
    color: "bg-teal-600",
    words: [
      {
        id: "tra1",
        term: "Luggage",
        phonetic: "/ˈlʌɡɪdʒ/",
        translation: "Hành lý",
        examples: [
          { en: "We left our heavy luggage at the hotel reception.", vi: "Chúng tôi đã để lại hành lý nặng của mình tại quầy lễ tân khách sạn." },
          { en: "Please keep an eye on your luggage at the airport.", vi: "Vui lòng để mắt tới hành lý của bạn tại sân bay." },
          { en: "How much luggage can we carry on this flight?", vi: "Chúng ta được phép mang bao nhiêu hành lý trong chuyến bay này?" },
        ],
        notes: "Danh từ không đếm được, tương tự như 'baggage'.",
      },
      {
        id: "tra2",
        term: "Guide",
        phonetic: "/ɡaɪd/",
        translation: "Người hướng dẫn, hướng dẫn viên",
        examples: [
          { en: "The tour guide explained the history of the ancient temple.", vi: "Hướng dẫn viên du lịch giải thích lịch sử của ngôi đền cổ." },
          { en: "We bought a city guide book before our trip.", vi: "Chúng tôi đã mua một cuốn sách hướng dẫn thành phố trước chuyến đi." },
          { en: "Let the map guide you through the streets.", vi: "Hãy để tấm bản đồ hướng dẫn bạn đi qua các con đường." },
        ],
        notes: "Vừa là danh từ (người hướng dẫn / sách hướng dẫn) vừa là động từ.",
      },
      {
        id: "tra3",
        term: "Passport",
        phonetic: "/ˈpɑːspɔːt/",
        translation: "Hộ chiếu",
        examples: [
          { en: "You need a valid passport to travel abroad.", vi: "Bạn cần một hộ chiếu còn hiệu lực để đi du lịch nước ngoài." },
          { en: "She kept her passport in a safe pocket.", vi: "Cô ấy giữ hộ chiếu của mình trong một chiếc túi an toàn." },
          { en: "He had his passport checked at the border.", vi: "Anh ấy đã được kiểm tra hộ chiếu tại biên giới." },
        ],
        notes: "Giấy tờ tùy thân bắt buộc khi xuất nhập cảnh quốc gia.",
      },
      {
        id: "tra4",
        term: "Pack",
        phonetic: "/pæk/",
        translation: "Đóng gói (hành lý), xếp đồ",
        examples: [
          { en: "I need to pack my suitcase tonight because we leave early.", vi: "Tôi cần xếp đồ vào vali tối nay vì chúng tôi sẽ rời đi sớm." },
          { en: "He packed some warm clothes for the mountain trip.", vi: "Anh ấy đã xếp vài bộ quần áo ấm cho chuyến đi leo núi." },
          { en: "Don't pack too many heavy items.", vi: "Đừng đóng gói quá nhiều món đồ nặng." },
        ],
        notes: "Trái nghĩa là 'unpack' (dỡ hành lý ra).",
      },
      {
        id: "tra5",
        term: "Check-in",
        phonetic: "/ˈtʃek ɪn/",
        translation: "Thủ tục nhận phòng / Đăng ký chuyến bay",
        examples: [
          { en: "The standard hotel check-in time is two o'clock.", vi: "Thời gian nhận phòng tiêu chuẩn của khách sạn là hai giờ." },
          { en: "We completed our flight check-in online.", vi: "Chúng tôi đã hoàn thành thủ tục đăng ký chuyến bay trực tuyến." },
          { en: "Please go to the check-in desk to drop your bags.", vi: "Vui lòng đến bàn làm thủ tục để gửi hành lý của bạn." },
        ],
        notes: "Trái nghĩa là 'check-out' (trả phòng / làm thủ tục ra).",
      },
      {
        id: "tra6",
        term: "Reception",
        phonetic: "/rɪˈsepʃn/",
        translation: "Quầy lễ tân / Sự đón tiếp",
        examples: [
          { en: "Ask the receptionist at the reception desk for a map.", vi: "Hãy hỏi nhân viên lễ tân tại quầy lễ tân để lấy một tấm bản đồ." },
          { en: "The hotel has a twenty-four-hour reception desk.", vi: "Khách sạn có một quầy lễ tân phục vụ hai mươi tư giờ." },
          { en: "We received a warm reception upon arrival.", vi: "Chúng tôi đã nhận được sự đón tiếp ấm áp ngay khi đến nơi." },
        ],
        notes: "Nơi đón tiếp và xử lý thủ tục của khách tại khách sạn hoặc tòa nhà.",
      },
      {
        id: "tra7",
        term: "Reservation",
        phonetic: "/ˌrezəˈveɪʃn/",
        translation: "Sự đặt phòng trước, đặt bàn trước",
        examples: [
          { en: "I made a reservation for a double room last week.", vi: "Tôi đã đặt một phòng đôi từ tuần trước." },
          { en: "The restaurant is very popular; you need a reservation.", vi: "Nhà hàng này rất nổi tiếng; bạn cần đặt bàn trước." },
          { en: "They confirmed my reservation via email.", vi: "Họ đã xác nhận việc đặt chỗ của tôi qua email." },
        ],
        notes: "Danh từ của động từ 'reserve'.",
      },
      {
        id: "tra8",
        term: "Destination",
        phonetic: "/ˌdestɪˈneɪʃn/",
        translation: "Điểm đến, nơi đến",
        examples: [
          { en: "Halong Bay is a famous tourist destination in Vietnam.", vi: "Vịnh Hạ Long là một điểm đến du lịch nổi tiếng ở Việt Nam." },
          { en: "The train will reach its destination in two hours.", vi: "Chuyến tàu sẽ đến điểm đích trong vòng hai tiếng nữa." },
          { en: "Paris is our final destination.", vi: "Paris là điểm đến cuối cùng của chúng tôi." },
        ],
        notes: "Nơi mà ai đó hoặc thứ gì đó đang đi tới.",
      },
      {
        id: "tra9",
        term: "Flight",
        phonetic: "/flaɪt/",
        translation: "Chuyến bay",
        examples: [
          { en: "The flight was delayed due to heavy rain.", vi: "Chuyến bay đã bị hoãn vì lý do mưa lớn." },
          { en: "Have a safe flight!", vi: "Chúc bạn có một chuyến bay an toàn!" },
          { en: "We booked a direct flight to Tokyo.", vi: "Chúng tôi đã đặt một chuyến bay thẳng đến Tokyo." },
        ],
        notes: "Hành trình di chuyển bằng đường hàng không.",
      },
      {
        id: "tra10",
        term: "Suitcase",
        phonetic: "/ˈsuːtkeɪs/",
        translation: "Cái vali",
        examples: [
          { en: "She struggled to lift the heavy suitcase.", vi: "Cô ấy đã chật vật để nhấc chiếc vali nặng lên." },
          { en: "My suitcase is blue with wheels.", vi: "Vali của tôi màu xanh dương và có bánh xe." },
          { en: "He put a name tag on his suitcase.", vi: "Anh ấy đã gắn một thẻ tên lên chiếc vali của mình." },
        ],
        notes: "Hộp lớn có tay cầm dùng để đựng quần áo khi đi du lịch.",
      },
      {
        id: "tra11",
        term: "Sightseeing",
        phonetic: "/ˈsaɪtsiːɪŋ/",
        translation: "Hoạt động tham quan, ngắm cảnh",
        examples: [
          { en: "We spent the afternoon sightseeing around the old town.", vi: "Chúng tôi dành cả buổi chiều để tham quan ngắm cảnh quanh phố cổ." },
          { en: "They rented bicycles to go sightseeing.", vi: "Họ đã thuê xe đạp để đi ngắm cảnh." },
          { en: "There are many opportunities for sightseeing in Kyoto.", vi: "Có rất nhiều cơ hội để tham quan ngắm cảnh ở Kyoto." },
        ],
        notes: "Thường đi kèm động từ 'go' ('go sightseeing').",
      },
      {
        id: "tra12",
        term: "Itinerary",
        phonetic: "/aɪˈtɪnərəri/",
        translation: "Hành trình, lịch trình chuyến đi",
        examples: [
          { en: "The travel agency gave us a detailed itinerary.", vi: "Đại lý du lịch đã đưa cho chúng tôi một lịch trình chuyến đi chi tiết." },
          { en: "We need to plan our travel itinerary carefully.", vi: "Chúng ta cần lên lịch trình chuyến đi của mình thật cẩn thận." },
          { en: "Visiting the museum is the first item on our itinerary.", vi: "Tham quan bảo tàng là mục đầu tiên trong hành trình của chúng tôi." },
        ],
        notes: "Kế hoạch ghi rõ các địa điểm và thời gian của chuyến đi.",
      },
      {
        id: "tra13",
        term: "Souvenir",
        phonetic: "/ˌsuːvəˈnɪə/",
        translation: "Quà lưu niệm",
        examples: [
          { en: "She bought a keychain as a souvenir of her trip.", vi: "Cô ấy đã mua một chiếc móc khóa làm quà lưu niệm cho chuyến đi của mình." },
          { en: "There are many souvenir shops near the temple.", vi: "Có rất nhiều cửa hàng quà lưu niệm ở gần ngôi đền." },
          { en: "I always buy souvenirs for my family when I travel.", vi: "Tôi luôn mua quà lưu niệm cho gia đình khi đi du lịch." },
        ],
        notes: "Vật lưu niệm giữ lại để nhớ về một địa điểm hoặc kỳ nghỉ.",
      },
      {
        id: "tra14",
        term: "Delay",
        phonetic: "/dɪˈleɪ/",
        translation: "Trì hoãn, hoãn lại / Sự chậm trễ",
        examples: [
          { en: "The bad weather caused a long delay at the airport.", vi: "Thời tiết xấu đã gây ra sự trì hoãn kéo dài tại sân bay." },
          { en: "Our train was delayed for forty minutes.", vi: "Chuyến tàu của chúng tôi đã bị trì hoãn bốn mươi phút." },
          { en: "We apologize for the delay.", vi: "Chúng tôi xin lỗi vì sự chậm trễ này." },
        ],
        notes: "Vừa là động từ vừa là danh từ.",
      },
      {
        id: "tra15",
        term: "Agency",
        phonetic: "/ˈeɪdʒənsi/",
        translation: "Đại lý, cơ quan",
        examples: [
          { en: "We booked our holiday through a local travel agency.", vi: "Chúng tôi đã đặt kỳ nghỉ của mình thông qua một đại lý du lịch địa phương." },
          { en: "The agency helped us with our visa application.", vi: "Đại lý đã giúp đỡ chúng tôi trong việc nộp đơn xin thị thực." },
          { en: "He works at a creative advertising agency.", vi: "Anh ấy làm việc tại một cơ quan quảng cáo sáng tạo." },
        ],
        notes: "Doanh nghiệp hoặc tổ chức cung cấp dịch vụ thay mặt bên khác.",
      },
      {
        id: "tra16",
        term: "Passenger",
        phonetic: "/ˈpæsɪndʒə/",
        translation: "Hành khách",
        examples: [
          { en: "The flight attendant welcomed the passengers on board.", vi: "Tiếp viên hàng không đã chào đón hành khách lên máy bay." },
          { en: "Only passenger cars are allowed on this street.", vi: "Chỉ có xe chở khách mới được phép đi trên con phố này." },
          { en: "A passenger was sick during the flight.", vi: "Một hành khách đã bị ốm trong suốt chuyến bay." },
        ],
        notes: "Người di chuyển trên phương tiện nhưng không phải là lái xe hay phi hành đoàn.",
      },
      {
        id: "tra17",
        term: "Foreign",
        phonetic: "/ˈfɒrən/",
        translation: "Nước ngoài, ngoại quốc",
        examples: [
          { en: "Learning a foreign language is beneficial.", vi: "Học một ngoại ngữ mang lại rất nhiều lợi ích." },
          { en: "The hotel has many foreign guests this summer.", vi: "Khách sạn có rất nhiều khách nước ngoài vào mùa hè này." },
          { en: "She enjoys traveling to foreign countries.", vi: "Cô ấy thích đi du lịch đến các quốc gia nước ngoài." },
        ],
        notes: "Liên quan đến một quốc gia khác ngoài nước mình.",
      },
      {
        id: "tra18",
        term: "Boarding pass",
        phonetic: "/ˈbɔːdɪŋ pɑːs/",
        translation: "Thẻ lên máy bay / vé lên tàu",
        examples: [
          { en: "Please show your boarding pass and passport at the gate.", vi: "Vui lòng xuất trình thẻ lên máy bay và hộ chiếu của bạn tại cổng." },
          { en: "You can download your boarding pass to your smartphone.", vi: "Bạn có thể tải thẻ lên máy bay về điện thoại thông minh của mình." },
          { en: "I accidentally dropped my boarding pass on the floor.", vi: "Tôi vô tình làm rơi thẻ lên máy bay xuống sàn nhà." },
        ],
        notes: "Vé chính thức được cấp sau khi check-in để lên máy bay.",
      },
      {
        id: "tra19",
        term: "Accommodation",
        phonetic: "/əˌkɒməˈdeɪʃn/",
        translation: "Chỗ ở, nơi lưu trú",
        examples: [
          { en: "Finding cheap accommodation in Paris is difficult.", vi: "Tìm kiếm chỗ ở giá rẻ ở Paris là một điều khó khăn." },
          { en: "The price includes meals and accommodation.", vi: "Giá đã bao gồm các bữa ăn và chỗ ở lưu trú." },
          { en: "We booked our accommodation online.", vi: "Chúng tôi đã đặt chỗ ở của mình trực tuyến." },
        ],
        notes: "Danh từ không đếm được chỉ nơi để ở, trú ngụ khi đi xa.",
      },
      {
        id: "tra20",
        term: "Explore",
        phonetic: "/ɪkˈsplɔː/",
        translation: "Khám phá, thám hiểm",
        examples: [
          { en: "They rented a scooter to explore the island.", vi: "Họ đã thuê một chiếc xe ga để khám phá hòn đảo." },
          { en: "We love to explore old villages and historic buildings.", vi: "Chúng tôi thích khám phá các ngôi làng cổ và tòa nhà lịch sử." },
          { en: "He wants to explore new business opportunities.", vi: "Anh ấy muốn khám phá những cơ hội kinh doanh mới." },
        ],
        notes: "Hành động đi tìm hiểu một địa điểm hoặc một lĩnh vực mới mẻ.",
      },
    ],
  },
  {
    id: "topic_health_e2",
    title: "Sức khỏe & Lối sống",
    category: "topic",
    description: "Các thói quen lành mạnh, thuật ngữ y tế cơ bản và lối sống cân bằng.",
    color: "bg-teal-600",
    words: [
      {
        id: "hea1",
        term: "Medicine",
        phonetic: "/ˈmedsn/",
        translation: "Thuốc uống / Y học",
        examples: [
          { en: "Take this medicine twice a day after meals.", vi: "Hãy uống loại thuốc này hai lần một ngày sau bữa ăn." },
          { en: "He is studying medicine to become a doctor.", vi: "Cậu ấy đang học ngành y để trở thành một bác sĩ." },
          { en: "The medicine has some side effects.", vi: "Thuốc này có một số tác dụng phụ." },
        ],
        notes: "Chất dùng để chữa bệnh hoặc ngành học về sức khỏe.",
      },
      {
        id: "hea2",
        term: "Exercise",
        phonetic: "/ˈeksəsaɪz/",
        translation: "Tập thể dục, bài tập thể chất",
        examples: [
          { en: "Regular exercise is good for your heart.", vi: "Tập thể dục thường xuyên rất tốt cho tim mạch của bạn." },
          { en: "He does stretching exercises every morning.", vi: "Cậu ấy tập các bài tập kéo giãn cơ mỗi buổi sáng." },
          { en: "Do you prefer to exercise at home or at the gym?", vi: "Bạn thích tập thể dục ở nhà hay ở phòng gym hơn?" },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "hea3",
        term: "Diet",
        phonetic: "/ˈdaɪət/",
        translation: "Chế độ ăn uống, ăn kiêng",
        examples: [
          { en: "She eats a balanced diet with plenty of fruit.", vi: "Cô ấy ăn một chế độ ăn uống cân bằng với nhiều trái cây." },
          { en: "The doctor put him on a low-salt diet.", vi: "Bác sĩ đã yêu cầu anh ấy thực hiện chế độ ăn giảm muối." },
          { en: "I am on a diet to lose some weight.", vi: "Tôi đang trong chế độ ăn kiêng để giảm cân." },
        ],
        notes: "Thói quen ăn uống thông thường hoặc chế độ ăn đặc biệt để giảm cân/trị bệnh.",
      },
      {
        id: "hea4",
        term: "Stress",
        phonetic: "/stres/",
        translation: "Sự căng thẳng, áp lực",
        examples: [
          { en: "Yoga is a great way to reduce stress.", vi: "Yoga là một cách tuyệt vời để giảm căng thẳng." },
          { en: "He is under a lot of stress at work.", vi: "Anh ấy đang chịu rất nhiều áp lực căng thẳng trong công việc." },
          { en: "Stress can affect your physical health.", vi: "Sự căng thẳng có thể ảnh hưởng đến sức khỏe thể chất của bạn." },
        ],
        notes: "Trạng thái mệt mỏi về mặt tinh thần.",
      },
      {
        id: "hea5",
        term: "Habit",
        phonetic: "/ˈhæbɪt/",
        translation: "Thói quen",
        examples: [
          { en: "Biting nails is a bad habit.", vi: "Cắn móng tay là một thói quen xấu." },
          { en: "She wants to build the habit of drinking more water.", vi: "Cô ấy muốn xây dựng thói quen uống nhiều nước hơn." },
          { en: "It takes time to break an old habit.", vi: "Cần có thời gian để từ bỏ một thói quen cũ." },
        ],
        notes: "Hành vi được lặp đi lặp lại thường xuyên.",
      },
      {
        id: "hea6",
        term: "Energy",
        phonetic: "/ˈenədʒi/",
        translation: "Năng lượng, sức lực",
        examples: [
          { en: "Eating breakfast gives you energy for the day.", vi: "Ăn sáng cung cấp cho bạn năng lượng cho cả ngày." },
          { en: "I don't have the energy to clean the house today.", vi: "Hôm nay tôi không có sức lực để dọn dẹp nhà cửa." },
          { en: "Solar power is a source of clean energy.", vi: "Năng lượng mặt trời là một nguồn năng lượng sạch." },
        ],
        notes: "Danh từ không đếm được chỉ thể chất dẻo dai hoặc nguồn lực vật lý.",
      },
      {
        id: "hea7",
        term: "Checkup",
        phonetic: "/ˈtʃekʌp/",
        translation: "Sự kiểm tra sức khỏe, khám tổng quát",
        examples: [
          { en: "You should go for a medical checkup once a year.", vi: "Bạn nên đi kiểm tra sức khỏe định kỳ mỗi năm một lần." },
          { en: "She went to the dentist for a regular checkup.", vi: "Cô ấy đã đến nha sĩ để khám răng định kỳ." },
          { en: "The routine checkup showed that he is perfectly healthy.", vi: "Cuộc kiểm tra định kỳ cho thấy anh ấy hoàn toàn khỏe mạnh." },
        ],
        notes: "Khám sức khỏe tổng thể để phòng bệnh.",
      },
      {
        id: "hea8",
        term: "Recover",
        phonetic: "/rɪˈkʌvə/",
        translation: "Hồi phục, khỏe lại / Tìm lại được",
        examples: [
          { en: "It took him two weeks to recover from the flu.", vi: "Anh ấy phải mất hai tuần để hồi phục sau khi bị cúm." },
          { en: "She is recovering slowly after the operation.", vi: "Cô ấy đang hồi phục một cách chậm rãi sau ca phẫu thuật." },
          { en: "He hopes to recover his lost keys.", vi: "Anh ấy hy vọng tìm lại được chiếc chìa khóa bị mất của mình." },
        ],
        notes: "Lấy lại thể chất khỏe mạnh sau chấn thương hoặc ốm đau.",
      },
      {
        id: "hea9",
        term: "Symptom",
        phonetic: "/ˈsɪmptəm/",
        translation: "Triệu chứng",
        examples: [
          { en: "A fever is a common symptom of a cold.", vi: "Sốt là một triệu chứng phổ biến của bệnh cảm lạnh." },
          { en: "If you experience any unusual symptoms, see a doctor.", vi: "Nếu bạn gặp bất kỳ triệu chứng bất thường nào, hãy đi khám bác sĩ." },
          { en: "The medicine helped relieve his symptoms.", vi: "Thuốc đã giúp làm giảm các triệu chứng của anh ấy." },
        ],
        notes: "Biểu hiện bên ngoài cho thấy cơ thể đang mắc bệnh.",
      },
      {
        id: "hea10",
        term: "Prescription",
        phonetic: "/prɪˈskrɪpʃn/",
        translation: "Đơn thuốc, toa thuốc của bác sĩ",
        examples: [
          { en: "The doctor wrote a prescription for some antibiotics.", vi: "Bác sĩ đã viết một đơn thuốc để lấy một số loại kháng sinh." },
          { en: "You cannot buy this medicine without a prescription.", vi: "Bạn không thể mua loại thuốc này nếu không có toa thuốc." },
          { en: "She took the prescription to the local pharmacy.", vi: "Cô ấy đã mang đơn thuốc đến nhà thuốc địa phương." },
        ],
        notes: "Giấy chỉ định của bác sĩ để mua thuốc đặc trị.",
      },
      {
        id: "hea11",
        term: "Infection",
        phonetic: "/ɪnˈfekʃn/",
        translation: "Sự nhiễm trùng, viêm nhiễm",
        examples: [
          { en: "Wash the cut with soap to prevent infection.", vi: "Hãy rửa vết đứt bằng xà phòng để ngăn ngừa nhiễm trùng." },
          { en: "He has an ear infection and needs ear drops.", vi: "Cậu ấy bị viêm tai và cần sử dụng thuốc nhỏ tai." },
          { en: "Bacterial infections can be treated with antibiotics.", vi: "Nhiễm trùng do vi khuẩn có thể được điều trị bằng kháng sinh." },
        ],
        notes: "Sự xâm nhập của vi khuẩn, virus vào cơ thể gây bệnh.",
      },
      {
        id: "hea12",
        term: "Healthy",
        phonetic: "/ˈhelθi/",
        translation: "Khỏe mạnh, lành mạnh",
        examples: [
          { en: "He has a healthy lifestyle; he runs and eats vegetables.", vi: "Anh ấy có một lối sống lành mạnh; anh ấy chạy bộ và ăn rau." },
          { en: "Fresh fruit is a healthy snack choice.", vi: "Trái cây tươi là một lựa chọn đồ ăn nhẹ lành mạnh." },
          { en: "The baby looks very healthy.", vi: "Em bé trông rất khỏe mạnh." },
        ],
        notes: "Tính từ của danh từ 'health'.",
      },
      {
        id: "hea13",
        term: "Pain",
        phonetic: "/peɪn/",
        translation: "Cơn đau, sự đau đớn",
        examples: [
          { en: "She felt a sharp pain in her back.", vi: "Cô ấy cảm thấy một cơn đau nhói ở lưng." },
          { en: "Take this pill; it will relieve the pain.", vi: "Hãy uống viên thuốc này; nó sẽ giảm bớt cơn đau." },
          { en: "He has been in constant pain since yesterday.", vi: "Anh ấy đã bị đau liên tục từ ngày hôm qua." },
        ],
        notes: "Cảm giác đau đớn khó chịu về thể xác.",
      },
      {
        id: "hea14",
        term: "Prevent",
        phonetic: "/rɪˈvent/",
        translation: "Ngăn chặn, phòng ngừa",
        examples: [
          { en: "Regular hand washing helps prevent the spread of diseases.", vi: "Rửa tay thường xuyên giúp phòng ngừa sự lây lan của dịch bệnh." },
          { en: "We must take action to prevent accidents.", vi: "Chúng ta phải hành động để ngăn chặn tai nạn xảy ra." },
          { en: "Vaccines are used to prevent serious infections.", vi: "Vắc-xin được sử dụng để phòng ngừa các bệnh nhiễm trùng nghiêm trọng." },
        ],
        notes: "Hành động làm cho một việc gì đó không xảy ra.",
      },
      {
        id: "hea15",
        term: "Avoid",
        phonetic: "/əˈvɔɪd/",
        translation: "Tránh, né tránh",
        examples: [
          { en: "You should avoid eating too much sugar.", vi: "Bạn nên tránh ăn quá nhiều đường." },
          { en: "He tried to avoid the heavy traffic on the highway.", vi: "Cậu ấy đã cố gắng tránh lượng giao thông đông đúc trên đường cao tốc." },
          { en: "Avoid touching your eyes with dirty hands.", vi: "Tránh chạm vào mắt bằng bàn tay bẩn." },
        ],
        notes: "Theo sau động từ 'avoid' luôn là một danh từ hoặc động từ đuôi V-ing.",
      },
      {
        id: "hea16",
        term: "Fitness",
        phonetic: "/ˈfɪtnəs/",
        translation: "Sự sung sức, thể trạng khỏe khoắn",
        examples: [
          { en: "She does swimming to improve her fitness.", vi: "Cô ấy bơi lội để cải thiện thể trạng khỏe khoắn của mình." },
          { en: "He works as a fitness instructor.", vi: "Anh ấy làm công việc hướng dẫn viên thể hình." },
          { en: "Regular exercise is essential for physical fitness.", vi: "Tập thể dục thường xuyên là rất cần thiết cho sự sung sức của thể chất." },
        ],
        notes: "Trạng thái khỏe mạnh, cân đối về thể chất.",
      },
      {
        id: "hea17",
        term: "Treatment",
        phonetic: "/ˈtriːtmənt/",
        translation: "Sự điều trị, phương pháp chữa trị",
        examples: [
          { en: "The doctor recommended a new treatment for his disease.", vi: "Bác sĩ khuyên dùng một phương pháp điều trị mới cho căn bệnh của anh ấy." },
          { en: "She responded well to the medical treatment.", vi: "Cô ấy đã phản ứng tốt với quá trình điều trị y tế." },
          { en: "The hospital offers free treatment for poor children.", vi: "Bệnh viện cung cấp dịch vụ chữa trị miễn phí cho trẻ em nghèo." },
        ],
        notes: "Danh từ của động từ 'treat' (điều trị / đối xử).",
      },
      {
        id: "hea18",
        term: "Allergy",
        phonetic: "/ˈælədʒi/",
        translation: "Sự dị ứng",
        examples: [
          { en: "He has an allergy to seafood.", vi: "Cậu ấy bị dị ứng với hải sản." },
          { en: "Peanuts can cause a dangerous allergy in some people.", vi: "Lạc có thể gây ra phản ứng dị ứng nguy hiểm ở một số người." },
          { en: "She sneezes because of her allergy to dust.", vi: "Cô ấy hắt hơi vì bị dị ứng với bụi." },
        ],
        notes: "Phản ứng của hệ miễn dịch với chất lạ bên ngoài cơ thể.",
      },
      {
        id: "hea19",
        term: "Lifestyle",
        phonetic: "/ˈlaɪfstaɪl/",
        translation: "Lối sống, phong cách sống",
        examples: [
          { en: "Modern technology has changed our lifestyle.", vi: "Công nghệ hiện đại đã thay đổi lối sống của chúng ta." },
          { en: "They want to adopt a simpler lifestyle in the country.", vi: "Họ muốn áp dụng một lối sống đơn giản hơn ở vùng nông thôn." },
          { en: "A sedentary lifestyle is bad for your health.", vi: "Lối sống ít vận động rất có hại cho sức khỏe của bạn." },
        ],
        notes: "Cách sống của một người hoặc một nhóm người.",
      },
      {
        id: "hea20",
        term: "Mental",
        phonetic: "/ˈmentl/",
        translation: "Thuộc về tinh thần, tâm thần",
        examples: [
          { en: "Mental health is as important as physical health.", vi: "Sức khỏe tinh thần cũng quan trọng như sức khỏe thể chất." },
          { en: "Solving puzzles is good for your mental fitness.", vi: "Giải đố rất tốt cho sự rèn luyện trí óc tinh thần của bạn." },
          { en: "He suffered from mental stress due to the exam.", vi: "Cậu ấy đã phải chịu đựng sự căng thẳng tinh thần do kỳ thi." },
        ],
        notes: "Liên quan đến tâm trí, trí tuệ hoặc tinh thần, trái nghĩa với 'physical'.",
      },
    ],
  },
  {
    id: "topic_emotions_e2",
    title: "Cảm xúc & Tâm trạng",
    category: "topic",
    description: "Các trạng thái tâm lý từ tiêu cực đến tích cực và cách diễn đạt cảm xúc.",
    color: "bg-teal-600",
    words: [
      {
        id: "emo1",
        term: "Excited",
        phonetic: "/ɪkˈsaɪtɪd/",
        translation: "Hào hứng, phấn khích",
        examples: [
          { en: "The children were excited about the trip to the zoo.", vi: "Trẻ em đã hào hứng phấn khích về chuyến đi chơi sở thú." },
          { en: "I am so excited to see my best friend again.", vi: "Tôi vô cùng hào hứng khi được gặp lại người bạn thân nhất của mình." },
          { en: "He looked excited when he heard the good news.", vi: "Trông anh ấy thật phấn khích khi nghe được tin tốt lành." },
        ],
        notes: "Cảm giác vui vẻ, mong đợi điều gì sắp diễn ra.",
      },
      {
        id: "emo2",
        term: "Bored",
        phonetic: "/bɔːd/",
        translation: "Buồn chán, chán nản",
        examples: [
          { en: "She felt bored because she had nothing to do.", vi: "Cô ấy cảm thấy buồn chán vì không có việc gì để làm." },
          { en: "I was bored with the long and quiet movie.", vi: "Tôi đã thấy phát chán với bộ phim dài và tẻ nhạt yên lặng." },
          { en: "The students looked bored during the lecture.", vi: "Các học sinh trông có vẻ chán nản trong suốt bài giảng." },
        ],
        notes: "Cảm xúc chán nản khi thiếu hoạt động hoặc không có hứng thú.",
      },
      {
        id: "emo3",
        term: "Surprised",
        phonetic: "/səˈpraɪzd/",
        translation: "Bất ngờ, ngạc nhiên",
        examples: [
          { en: "She was surprised by the unexpected birthday party.", vi: "Cô ấy đã rất bất ngờ trước bữa tiệc sinh nhật không báo trước." },
          { en: "He looked surprised to see his old teacher at the cafe.", vi: "Anh ấy trông ngạc nhiên khi thấy người thầy giáo cũ ở quán cà phê." },
          { en: "We were surprised at how fast he solved the problem.", vi: "Chúng tôi ngạc nhiên về việc cậu ấy giải quyết vấn đề nhanh như thế nào." },
        ],
        notes: "Cảm giác khi gặp điều gì đó bất ngờ xảy ra.",
      },
      {
        id: "emo4",
        term: "Proud",
        phonetic: "/praʊd/",
        translation: "Tự hào, kiêu hãnh",
        examples: [
          { en: "Her parents are very proud of her academic success.", vi: "Bố mẹ cô ấy rất tự hào về thành công học tập của cô." },
          { en: "He felt proud when he received the gold medal.", vi: "Anh ấy cảm thấy tự hào khi nhận được huy chương vàng." },
          { en: "We are proud to be a part of this team.", vi: "Chúng tôi tự hào là một thành viên của đội bóng này." },
        ],
        notes: "Thường đi kèm giới từ 'of' ('proud of').",
      },
      {
        id: "emo5",
        term: "Nervous",
        phonetic: "/ˈnɜːvəs/",
        translation: "Lo lắng, bồn chồn (trước sự kiện)",
        examples: [
          { en: "He always feels nervous before a job interview.", vi: "Anh ấy luôn luôn cảm thấy lo lắng bồn chồn trước một buổi phỏng vấn xin việc." },
          { en: "The student was nervous about the upcoming exam.", vi: "Học sinh lo lắng bồn chồn về kỳ thi sắp tới." },
          { en: "Don't be nervous; take a deep breath and start.", vi: "Đừng lo lắng quá; hãy hít một hơi thật sâu và bắt đầu." },
        ],
        notes: "Cảm giác lo âu, hồi hộp khi sắp làm một việc quan trọng.",
      },
      {
        id: "emo6",
        term: "Calm",
        phonetic: "/kɑːm/",
        translation: "Bình tĩnh, điềm tĩnh",
        examples: [
          { en: "Please stay calm and wait for instructions.", vi: "Vui lòng giữ bình tĩnh và chờ đợi hướng dẫn." },
          { en: "His calm voice helped ease her worry.", vi: "Giọng nói điềm tĩnh của anh ấy đã giúp làm vơi đi nỗi lo của cô." },
          { en: "The sea was calm after the storm.", vi: "Mặt biển đã bình lặng sau trận bão." },
        ],
        notes: "Âm 'l' trong 'calm' là âm câm, phát âm là /kɑːm/.",
      },
      {
        id: "emo7",
        term: "Lonely",
        phonetic: "/ˈləʊnli/",
        translation: "Cô đơn, đơn độc",
        examples: [
          { en: "He felt lonely living alone in the big city.", vi: "Anh ấy cảm thấy cô đơn khi sống một mình ở thành phố lớn." },
          { en: "She reads books when she feels lonely.", vi: "Cô ấy đọc sách khi cô ấy thấy cô đơn." },
          { en: "It can be a lonely job to work at night.", vi: "Làm việc vào ban đêm có thể là một công việc rất đơn độc." },
        ],
        notes: "Trạng thái buồn bã do không có bạn bè hoặc người thân ở cạnh.",
      },
      {
        id: "emo8",
        term: "Confused",
        phonetic: "/kənˈfjuːzd/",
        translation: "Bối rối, lúng túng, khó hiểu",
        examples: [
          { en: "The difficult question made her confused.", vi: "Câu hỏi khó đã làm cho cô ấy bối rối khó hiểu." },
          { en: "I was confused by the complicated street signs.", vi: "Tôi đã bị lúng túng bởi những biển báo đường phố phức tạp." },
          { en: "He looked confused when she said goodbye.", vi: "Trông anh ấy có vẻ bối rối khi cô nói lời tạm biệt." },
        ],
        notes: "Cảm xúc khi không hiểu rõ hoặc không thể suy nghĩ thấu đáo.",
      },
      {
        id: "emo9",
        term: "Worried",
        phonetic: "/ˈwʌrid/",
        translation: "Lo lắng, ái ngại",
        examples: [
          { en: "She is worried about her mother's health.", vi: "Cô ấy đang lo lắng về sức khỏe của mẹ cô ấy." },
          { en: "The parents were worried when the children were late.", vi: "Bố mẹ đã lo lắng khi các con trở về muộn." },
          { en: "He has a worried look on his face.", vi: "Anh ấy có một nét mặt lo lắng trên khuôn mặt." },
        ],
        notes: "Thường đi kèm giới từ 'about' ('worried about').",
      },
      {
        id: "emo10",
        term: "Hopeful",
        phonetic: "/ˈhəʊpfl/",
        translation: "Đầy hy vọng, triển vọng",
        examples: [
          { en: "They are hopeful about the new treatment.", vi: "Họ đầy hy vọng về phương pháp điều trị mới." },
          { en: "She gave him a hopeful look.", vi: "Cô ấy đã dành cho anh một ánh nhìn đầy hy vọng." },
          { en: "We remain hopeful that the situation will improve.", vi: "Chúng tôi vẫn giữ hy vọng rằng tình hình sẽ cải thiện." },
        ],
        notes: "Tính từ chỉ tâm trạng lạc quan mong muốn điều tốt sẽ đến.",
      },
      {
        id: "emo11",
        term: "Jealous",
        phonetic: "/ˈdʒeləs/",
        translation: "Ghen tị, đố kỵ",
        examples: [
          { en: "He felt jealous when his friend bought a sports car.", vi: "Anh ấy cảm thấy ghen tị khi bạn mình mua một chiếc xe thể thao." },
          { en: "Why are you so jealous of his success?", vi: "Tại sao bạn lại ghen tị với thành công của anh ấy thế?" },
          { en: "The little child is jealous of his baby sister.", vi: "Đứa trẻ nhỏ ghen tị đố kỵ với cô em gái nhỏ của mình." },
        ],
        notes: "Thường đi kèm giới từ 'of' ('jealous of').",
      },
      {
        id: "emo12",
        term: "Angry",
        phonetic: "/ˈæŋɡri/",
        translation: "Tức giận, giận dữ",
        examples: [
          { en: "He was angry with his brother for breaking his toy.", vi: "Anh ấy đã rất tức giận với em trai vì làm hỏng đồ chơi của mình." },
          { en: "Please do not make her angry.", vi: "Vui lòng đừng làm cô ấy tức giận." },
          { en: "She had an angry look on her face.", vi: "Cô ấy đã có một nét mặt giận dữ trên khuôn mặt." },
        ],
        notes: "Thường đi kèm giới từ 'with' hoặc 'at'.",
      },
      {
        id: "emo13",
        term: "Scared",
        phonetic: "/skeəd/",
        translation: "Sợ hãi, kinh hãi",
        examples: [
          { en: "The dog was scared of the loud thunder.", vi: "Con chó đã sợ hãi vì tiếng sấm lớn." },
          { en: "She is too scared to watch horror movies alone.", vi: "Cô ấy quá sợ hãi để xem phim kinh dị một mình." },
          { en: "He looked scared when the snake crawled near him.", vi: "Cậu ấy trông hoảng sợ khi con rắn bò lại gần mình." },
        ],
        notes: "Cảm giác sợ hãi trước mối đe dọa.",
      },
      {
        id: "emo14",
        term: "Disappointed",
        phonetic: "/ˌdɪsəˈpɔɪntɪd/",
        translation: "Thất vọng",
        examples: [
          { en: "We were disappointed by the poor service at the hotel.", vi: "Chúng tôi đã thất vọng bởi dịch vụ kém tại khách sạn." },
          { en: "He felt disappointed when he lost the tennis match.", vi: "Anh ấy cảm thấy thất vọng khi thua trận quần vợt." },
          { en: "She tried not to look disappointed with her grade.", vi: "Cô ấy cố gắng không tỏ vẻ thất vọng với điểm số của mình." },
        ],
        notes: "Tâm trạng buồn bã khi kết quả không đạt như kỳ vọng.",
      },
      {
        id: "emo15",
        term: "Grateful",
        phonetic: "/ˈɡreɪtfl/",
        translation: "Biết ơn",
        examples: [
          { en: "I am extremely grateful for your kind help.", vi: "Tôi vô cùng biết ơn sự giúp đỡ tử tế của bạn." },
          { en: "She wrote a grateful note to her teacher.", vi: "Cô ấy đã viết một bức thư biết ơn gửi cho giáo viên của mình." },
          { en: "We should be grateful for what we have.", vi: "Chúng ta nên biết ơn những gì chúng ta đang có." },
        ],
        notes: "Cảm xúc trân trọng khi nhận được lòng tốt.",
      },
      {
        id: "emo16",
        term: "Shame",
        phonetic: "/ʃeɪm/",
        translation: "Sự xấu hổ, hổ thẹn / Điều đáng tiếc",
        examples: [
          { en: "He felt a deep sense of shame for telling a lie.", vi: "Anh ấy cảm thấy một sự hổ thẹn sâu sắc vì đã nói dối." },
          { en: "It is a shame that you cannot attend the party.", vi: "Thật là một điều đáng tiếc khi bạn không thể tham dự bữa tiệc." },
          { en: "She hung her head in shame.", vi: "Cô ấy cúi đầu xấu hổ." },
        ],
        notes: "Vừa mang nghĩa hổ thẹn vì lỗi lầm, vừa mang nghĩa đáng tiếc ('What a shame!').",
      },
      {
        id: "emo17",
        term: "Anxious",
        phonetic: "/ˈæŋkʃəs/",
        translation: "Lo âu, sốt ruột",
        examples: [
          { en: "She is anxious about her father's health.", vi: "Cô ấy đang lo âu về sức khỏe của bố cô ấy." },
          { en: "The students are anxious to hear their test results.", vi: "Các học sinh đang rất sốt ruột muốn nghe kết quả bài kiểm tra." },
          { en: "He felt anxious standing in front of the big crowd.", vi: "Anh ấy cảm thấy lo âu khi đứng trước đám đông lớn." },
        ],
        notes: "Lo lắng ở mức độ cao hơn 'nervous', thường liên quan đến tương lai bất định.",
      },
      {
        id: "emo18",
        term: "Mood",
        phonetic: "/muːd/",
        translation: "Tâm trạng, khí sắc",
        examples: [
          { en: "He is in a good mood because he got a promotion.", vi: "Anh ấy đang có tâm trạng tốt vì anh ấy được thăng chức." },
          { en: "Don't ask him now; he is in a bad mood.", vi: "Đừng hỏi anh ấy lúc này; anh ấy đang có tâm trạng không tốt." },
          { en: "The warm weather put everyone in a cheerful mood.", vi: "Thời tiết ấm áp đưa mọi người vào một tâm trạng vui vẻ." },
        ],
        notes: "Trạng thái cảm xúc kéo dài tại một thời điểm.",
      },
      {
        id: "emo19",
        term: "Frustrated",
        phonetic: "/frʌˈstreɪtɪd/",
        translation: "Bực bội, nản lòng",
        examples: [
          { en: "I feel frustrated when the computer crashes.", vi: "Tôi thấy bực bội nản lòng mỗi khi máy tính bị hỏng." },
          { en: "The slow progress made the team frustrated.", vi: "Sự tiến triển chậm chạp khiến cả đội nản lòng bực bội." },
          { en: "He was frustrated because he couldn't solve the puzzle.", vi: "Cậu ấy đã bực bội vì không thể giải được câu đố." },
        ],
        notes: "Sự bực dọc sinh ra khi gặp cản trở không thể đạt được mục đích.",
      },
      {
        id: "emo20",
        term: "Satisfied",
        phonetic: "/ˈsætɪsfaɪd/",
        translation: "Hài lòng, thỏa mãn",
        examples: [
          { en: "She was satisfied with the results of her exam.", vi: "Cô ấy đã hài lòng với kết quả thi của mình." },
          { en: "The teacher looked satisfied with the students' homework.", vi: "Giáo viên trông có vẻ hài lòng với bài tập về nhà của học sinh." },
          { en: "Are you satisfied with our service?", vi: "Bạn có hài lòng với dịch vụ của chúng tôi không?" },
        ],
        notes: "Cảm giác vui vẻ khi đạt được đúng mong ước.",
      },
    ],
  },
];
