export const tierSilverIII = [
  {
    id: "topic_greetings",
    title: "Chào hỏi & Giới thiệu",
    category: "topic",
    description: "Các từ vựng cơ bản dùng để chào hỏi và giới thiệu bản thân hàng ngày.",
    color: "bg-green-500",
    words: [
      {
        id: "g1",
        term: "Hello",
        phonetic: "/həˈləʊ/",
        translation: "Xin chào",
        examples: [
          { en: "Hello, how are you?", vi: "Xin chào, bạn khỏe không?" },
          { en: "She said hello to me.", vi: "Cô ấy đã chào tôi." },
          { en: "Hello everyone, welcome!", vi: "Xin chào mọi người, chào mừng các bạn!" },
        ],
        notes: "Cách chào lịch sự, dùng được trong hầu hết mọi ngữ cảnh.",
      },
      {
        id: "g2",
        term: "Goodbye",
        phonetic: "/ˌɡʊdˈbaɪ/",
        translation: "Tạm biệt",
        examples: [
          { en: "Goodbye, see you tomorrow.", vi: "Tạm biệt, hẹn gặp lại bạn ngày mai." },
          { en: "It is time to say goodbye.", vi: "Đã đến lúc phải nói lời tạm biệt." },
          { en: "She waved goodbye to her friend.", vi: "Cô ấy vẫy tay chào tạm biệt bạn mình." },
        ],
        notes: "Có thể rút gọn thành 'Bye' trong văn nói thân mật.",
      },
      {
        id: "g3",
        term: "Name",
        phonetic: "/neɪm/",
        translation: "Tên",
        examples: [
          { en: "What is your name?", vi: "Tên của bạn là gì?" },
          { en: "My name is John.", vi: "Tên của tôi là John." },
          { en: "Please write your name here.", vi: "Vui lòng viết tên của bạn ở đây." },
        ],
        notes: "Dùng làm danh từ (tên gọi) hoặc động từ (đặt tên).",
      },
      {
        id: "g4",
        term: "Meet",
        phonetic: "/miːt/",
        translation: "Gặp gỡ, gặp mặt",
        examples: [
          { en: "Nice to meet you.", vi: "Rất vui được gặp bạn." },
          { en: "We meet every Sunday.", vi: "Chúng tôi gặp nhau mỗi Chủ Nhật." },
          { en: "Where do you want to meet?", vi: "Bạn muốn gặp nhau ở đâu?" },
        ],
        notes: "Động từ bất quy tắc (quá khứ là 'met').",
      },
      {
        id: "g5",
        term: "Friend",
        phonetic: "/frend/",
        translation: "Người bạn",
        examples: [
          { en: "He is my best friend.", vi: "Cậu ấy là người bạn thân nhất của tôi." },
          { en: "She has many friends at school.", vi: "Cô ấy có nhiều bạn ở trường." },
          { en: "They are friendly to everyone.", vi: "Họ rất thân thiện với mọi người." },
        ],
        notes: "Từ trái nghĩa là 'enemy' (kẻ thù).",
      },
      {
        id: "g6",
        term: "Please",
        phonetic: "/pliːz/",
        translation: "Vui lòng, làm ơn",
        examples: [
          { en: "Please sit down.", vi: "Xin vui lòng ngồi xuống." },
          { en: "Can you help me, please?", vi: "Bạn có thể giúp tôi được không, làm ơn?" },
          { en: "Coffee, please.", vi: "Cho tôi xin một ly cà phê." },
        ],
        notes: "Dùng để tăng tính lịch sự khi yêu cầu hoặc nhờ vả.",
      },
      {
        id: "g7",
        term: "Thank you",
        phonetic: "/ˈθæŋk juː/",
        translation: "Cảm ơn bạn",
        examples: [
          { en: "Thank you for the gift.", vi: "Cảm ơn bạn vì món quà." },
          { en: "Thank you very much.", vi: "Cảm ơn bạn rất nhiều." },
          { en: "I want to thank you for your help.", vi: "Tôi muốn cảm ơn bạn vì sự giúp đỡ của bạn." },
        ],
        notes: "Có thể nói ngắn gọn là 'Thanks' trong giao tiếp thân mật.",
      },
      {
        id: "g8",
        term: "Welcome",
        phonetic: "/ˈwelkəm/",
        translation: "Chào mừng / Không có gì (sau khi được cảm ơn)",
        examples: [
          { en: "Welcome to our home!", vi: "Chào mừng bạn đến với nhà của chúng tôi!" },
          { en: "You are welcome.", vi: "Không có gì đâu (phản hồi lại lời cảm ơn)." },
          { en: "The hotel welcomes new guests.", vi: "Khách sạn chào đón những vị khách mới." },
        ],
        notes: "Cụm từ 'You're welcome' là cách trả lời lịch sự khi ai đó cảm ơn.",
      },
      {
        id: "g9",
        term: "Sorry",
        phonetic: "/ˈsɒri/",
        translation: "Xin lỗi / Lấy làm tiếc",
        examples: [
          { en: "I am sorry for being late.", vi: "Tôi xin lỗi vì đã đến muộn." },
          { en: "I am sorry to hear that.", vi: "Tôi rất tiếc khi nghe điều đó." },
          { en: "Sorry, can you repeat that?", vi: "Xin lỗi, bạn có thể nhắc lại điều đó không?" },
        ],
        notes: "Thường dùng để xin lỗi lỗi lầm nhỏ hoặc thể hiện sự đồng cảm.",
      },
      {
        id: "g10",
        term: "Age",
        phonetic: "/eɪdʒ/",
        translation: "Tuổi, tuổi tác",
        examples: [
          { en: "What is your age?", vi: "Tuổi của bạn là bao nhiêu?" },
          { en: "Children of all ages love this game.", vi: "Trẻ em ở mọi lứa tuổi đều thích trò chơi này." },
          { en: "She looks young for her age.", vi: "Cô ấy nhìn trẻ hơn so với tuổi của mình." },
        ],
        notes: "Thường dùng cấu trúc 'How old are you?' để hỏi tuổi phổ biến hơn.",
      },
      {
        id: "g11",
        term: "Live",
        phonetic: "/lɪv/",
        translation: "Sống, sinh sống",
        examples: [
          { en: "I live in Hanoi.", vi: "Tôi sống ở Hà Nội." },
          { en: "Where do you live?", vi: "Bạn sống ở đâu?" },
          { en: "They live in a small house.", vi: "Họ sống trong một ngôi nhà nhỏ." },
        ],
        notes: "Tránh nhầm lẫn cách phát âm với từ 'live' (trực tiếp - phát âm là /laɪv/).",
      },
      {
        id: "g12",
        term: "From",
        phonetic: "/frɒm/",
        translation: "Từ, đến từ",
        examples: [
          { en: "I am from Vietnam.", vi: "Tôi đến từ Việt Nam." },
          { en: "Where are you from?", vi: "Bạn từ đâu đến?" },
          { en: "This letter is from my mother.", vi: "Lá thư này là từ mẹ của tôi." },
        ],
        notes: "Thường đi kèm giới từ để chỉ nguồn gốc hoặc xuất xứ.",
      },
      {
        id: "g13",
        term: "Job",
        phonetic: "/dʒɒb/",
        translation: "Công việc, nghề nghiệp",
        examples: [
          { en: "What is your job?", vi: "Công việc của bạn là gì?" },
          { en: "He is looking for a new job.", vi: "Anh ấy đang tìm kiếm một công việc mới." },
          { en: "She loves her job.", vi: "Cô ấy yêu công việc của mình." },
        ],
        notes: "Là danh từ đếm được, khác với 'work' (thường không đếm được).",
      },
      {
        id: "g14",
        term: "Fine",
        phonetic: "/faɪn/",
        translation: "Khỏe, tốt",
        examples: [
          { en: "I am fine, thank you.", vi: "Tôi khỏe, cảm ơn bạn." },
          { en: "The weather is fine today.", vi: "Thời tiết hôm nay rất đẹp." },
          { en: "Everything will be fine.", vi: "Mọi thứ rồi sẽ ổn thôi." },
        ],
        notes: "Trong ngữ cảnh khác, 'fine' còn có nghĩa là tiền phạt.",
      },
      {
        id: "g15",
        term: "Morning",
        phonetic: "/ˈmɔːnɪŋ/",
        translation: "Buổi sáng",
        examples: [
          { en: "Good morning, teacher.", vi: "Em chào thầy/cô buổi sáng ạ." },
          { en: "I drink milk in the morning.", vi: "Tôi uống sữa vào buổi sáng." },
          { en: "It was a cold morning.", vi: "Đó đã là một buổi sáng lạnh giá." },
        ],
        notes: "Thường đi với giới từ 'in the morning'.",
      },
      {
        id: "g16",
        term: "Nice",
        phonetic: "/naɪs/",
        translation: "Tốt, đẹp, dễ chịu",
        examples: [
          { en: "Have a nice day!", vi: "Chúc bạn một ngày tốt lành!" },
          { en: "This is a very nice place.", vi: "Đây là một nơi rất đẹp." },
          { en: "He is a nice person.", vi: "Anh ấy là một người tốt bụng." },
        ],
        notes: "Dùng để khen ngợi hoặc chúc tụng một cách xã giao.",
      },
      {
        id: "g17",
        term: "Spell",
        phonetic: "/spel/",
        translation: "Đánh vần",
        examples: [
          { en: "How do you spell your name?", vi: "Bạn đánh vần tên của mình như thế nào?" },
          { en: "Can you spell that word, please?", vi: "Bạn có thể đánh vần từ đó được không?" },
          { en: "I cannot spell this difficult name.", vi: "Tôi không thể đánh vần cái tên khó này." },
        ],
        notes: "Động từ rất hữu ích khi giới thiệu tên cho người nước ngoài.",
      },
      {
        id: "g18",
        term: "Introduce",
        phonetic: "/ˌɪntrəˈdjuːs/",
        translation: "Giới thiệu",
        examples: [
          { en: "Let me introduce myself.", vi: "Để tôi tự giới thiệu bản thân." },
          { en: "He wants to introduce his sister.", vi: "Anh ấy muốn giới thiệu em gái mình." },
          { en: "Can you introduce your friend to me?", vi: "Bạn có thể giới thiệu bạn của bạn cho tôi không?" },
        ],
        notes: "Danh từ của nó là 'introduction' (sự giới thiệu, lời mở đầu).",
      },
      {
        id: "g19",
        term: "Happy",
        phonetic: "/ˈhæpi/",
        translation: "Vui vẻ, hạnh phúc",
        examples: [
          { en: "Happy birthday to you!", vi: "Chúc mừng sinh nhật bạn!" },
          { en: "She looks very happy today.", vi: "Hôm nay trông cô ấy rất hạnh phúc." },
          { en: "They are a happy family.", vi: "Họ là một gia đình hạnh phúc." },
        ],
        notes: "Trái nghĩa là 'sad' (buồn bã).",
      },
      {
        id: "g20",
        term: "Question",
        phonetic: "/ˈkwestʃən/",
        translation: "Câu hỏi",
        examples: [
          { en: "Can I ask a question?", vi: "Tôi có thể hỏi một câu hỏi không?" },
          { en: "This is an easy question.", vi: "Đây là một câu hỏi dễ." },
          { en: "He did not answer my question.", vi: "Anh ấy đã không trả lời câu hỏi của tôi." },
        ],
        notes: "Trái nghĩa là 'answer' (câu trả lời / trả lời).",
      },
    ],
  },
  {
    id: "topic_numbers_colors",
    title: "Số đếm & Màu sắc",
    category: "topic",
    description: "Các số đếm cơ bản và những màu sắc thông dụng nhất trong tiếng Anh.",
    color: "bg-yellow-500",
    words: [
      {
        id: "nc1",
        term: "One",
        phonetic: "/wʌn/",
        translation: "Số một",
        examples: [
          { en: "I have one apple.", vi: "Tôi có một quả táo." },
          { en: "There is only one solution.", vi: "Chỉ có duy nhất một giải pháp." },
          { en: "He is number one in the class.", vi: "Cậu ấy là người đứng đầu lớp." },
        ],
        notes: "Số đếm cơ bản đầu tiên.",
      },
      {
        id: "nc2",
        term: "Ten",
        phonetic: "/ten/",
        translation: "Số mười",
        examples: [
          { en: "I have ten fingers.", vi: "Tôi có mười ngón tay." },
          { en: "The meeting ends in ten minutes.", vi: "Cuộc họp kết thúc trong mười phút nữa." },
          { en: "There are ten students in the room.", vi: "Có mười học sinh ở trong phòng." },
        ],
        notes: "Số cơ bản làm mốc đếm.",
      },
      {
        id: "nc3",
        term: "Hundred",
        phonetic: "/ˈhʌndrəd/",
        translation: "Trăm, một trăm",
        examples: [
          { en: "There are one hundred pages in this book.", vi: "Có một trăm trang trong cuốn sách này." },
          { en: "He can count to one hundred.", vi: "Cậu ấy có thể đếm đến một trăm." },
          { en: "The ticket costs a hundred dollars.", vi: "Vé có giá một trăm đô la." },
        ],
        notes: "Thường đi kèm với 'a' hoặc 'one' ở phía trước.",
      },
      {
        id: "nc4",
        term: "Red",
        phonetic: "/red/",
        translation: "Màu đỏ",
        examples: [
          { en: "She has a red dress.", vi: "Cô ấy có một chiếc váy màu đỏ." },
          { en: "The apple is sweet and red.", vi: "Quả táo ngọt và có màu đỏ." },
          { en: "He drives a red car.", vi: "Anh ấy lái một chiếc xe hơi màu đỏ." },
        ],
        notes: "Màu sắc nổi bật, thường tượng trưng cho sự may mắn hoặc nguy hiểm.",
      },
      {
        id: "nc5",
        term: "Blue",
        phonetic: "/bluː/",
        translation: "Màu xanh dương",
        examples: [
          { en: "The sky is blue today.", vi: "Hôm nay bầu trời màu xanh dương." },
          { en: "She has beautiful blue eyes.", vi: "Cô ấy có đôi mắt màu xanh dương rất đẹp." },
          { en: "My favorite color is blue.", vi: "Màu sắc yêu thích của tôi là màu xanh dương." },
        ],
        notes: "Trong một số ngữ cảnh, 'feel blue' nghĩa là cảm thấy buồn bã.",
      },
      {
        id: "nc6",
        term: "Green",
        phonetic: "/ɡriːn/",
        translation: "Màu xanh lá cây",
        examples: [
          { en: "The grass is green in spring.", vi: "Cỏ có màu xanh lá vào mùa xuân." },
          { en: "I like eating green vegetables.", vi: "Tôi thích ăn các loại rau xanh." },
          { en: "The traffic light turned green.", vi: "Đèn giao thông đã chuyển sang màu xanh lá." },
        ],
        notes: "Thường tượng trưng cho thiên nhiên và sự tươi mát.",
      },
      {
        id: "nc7",
        term: "Yellow",
        phonetic: "/ˈjeləʊ/",
        translation: "Màu vàng",
        examples: [
          { en: "The sun is yellow.", vi: "Mặt trời có màu vàng." },
          { en: "She bought a yellow raincoat.", vi: "Cô ấy đã mua một chiếc áo mưa màu vàng." },
          { en: "Bananas turn yellow when ripe.", vi: "Chuối chuyển sang màu vàng khi chín." },
        ],
        notes: "Màu sắc ấm áp, tươi sáng.",
      },
      {
        id: "nc8",
        term: "Black",
        phonetic: "/blæk/",
        translation: "Màu đen",
        examples: [
          { en: "He is wearing a black suit.", vi: "Anh ấy đang mặc một bộ vest màu đen." },
          { en: "My cat has black fur.", vi: "Con mèo của tôi có bộ lông màu đen." },
          { en: "The room was completely black.", vi: "Căn phòng đã hoàn toàn tối đen." },
        ],
        notes: "Trái nghĩa với 'white' (màu trắng).",
      },
      {
        id: "nc9",
        term: "White",
        phonetic: "/waɪt/",
        translation: "Màu trắng",
        examples: [
          { en: "Snow is white and cold.", vi: "Tuyết màu trắng và lạnh." },
          { en: "She has beautiful white teeth.", vi: "Cô ấy có hàm răng trắng đẹp." },
          { en: "He wrote on the white paper.", vi: "Anh ấy đã viết lên tờ giấy trắng." },
        ],
        notes: "Trái nghĩa với 'black' (màu đen).",
      },
      {
        id: "nc10",
        term: "Number",
        phonetic: "/ˈnʌmbə/",
        translation: "Con số, số lượng",
        examples: [
          { en: "Seven is my lucky number.", vi: "Số bảy là con số may mắn của tôi." },
          { en: "What is your phone number?", vi: "Số điện thoại của bạn là gì?" },
          { en: "Write the number on the board.", vi: "Hãy viết con số lên bảng." },
        ],
        notes: "Có thể viết tắt là 'No.'.",
      },
      {
        id: "nc11",
        term: "Color",
        phonetic: "/ˈkʌlə/",
        translation: "Màu sắc",
        examples: [
          { en: "What is your favorite color?", vi: "Màu sắc yêu thích của bạn là gì?" },
          { en: "This painting has bright colors.", vi: "Bức tranh này có những màu sắc tươi sáng." },
          { en: "Do you want to color this drawing?", vi: "Bạn có muốn tô màu cho bức vẽ này không?" },
        ],
        notes: "Tiếng Anh-Anh viết là 'colour', tiếng Anh-Mỹ viết là 'color'.",
      },
      {
        id: "nc12",
        term: "Count",
        phonetic: "/kaʊnt/",
        translation: "Đếm, tính toán",
        examples: [
          { en: "Can you count from one to ten?", vi: "Bạn có thể đếm từ một đến mười không?" },
          { en: "The little boy is learning to count.", vi: "Cậu bé đang học đếm." },
          { en: "Every vote counts in this election.", vi: "Mỗi lá phiếu đều có giá trị trong cuộc bầu cử này." },
        ],
        notes: "Dùng như một động từ.",
      },
      {
        id: "nc13",
        term: "Pink",
        phonetic: "/pɪŋk/",
        translation: "Màu hồng",
        examples: [
          { en: "She loves pink roses.", vi: "Cô ấy yêu hoa hồng màu hồng." },
          { en: "Her cheeks turned pink.", vi: "Đôi má của cô ấy ửng hồng." },
          { en: "The bedroom is painted pink.", vi: "Phòng ngủ được sơn màu hồng." },
        ],
        notes: "Màu sắc nhẹ nhàng, thường được phái nữ yêu thích.",
      },
      {
        id: "nc14",
        term: "Orange",
        phonetic: "/ˈɒrɪndʒ/",
        translation: "Màu cam / Quả cam",
        examples: [
          { en: "The sunset has a warm orange color.", vi: "Cảnh hoàng hôn có màu cam ấm áp." },
          { en: "I drink orange juice every morning.", vi: "Tôi uống nước cam mỗi sáng." },
          { en: "He bought three oranges.", vi: "Anh ấy đã mua ba quả cam." },
        ],
        notes: "Từ này vừa chỉ màu sắc vừa chỉ loại quả.",
      },
      {
        id: "nc15",
        term: "Purple",
        phonetic: "/ˈpɜːpəl/",
        translation: "Màu tím",
        examples: [
          { en: "She is wearing a purple scarf.", vi: "Cô ấy đang quàng một chiếc khăn màu tím." },
          { en: "Grapes can be green or purple.", vi: "Nho có thể có màu xanh hoặc màu tím." },
          { en: "Purple is the color of royalty.", vi: "Màu tím là màu của hoàng gia." },
        ],
        notes: "Sự pha trộn giữa màu đỏ và màu xanh dương.",
      },
      {
        id: "nc16",
        term: "Brown",
        phonetic: "/braʊn/",
        translation: "Màu nâu",
        examples: [
          { en: "Chocolate is brown.", vi: "Sô-cô-la có màu nâu." },
          { en: "The bear has thick brown fur.", vi: "Con gấu có bộ lông dày màu nâu." },
          { en: "He wears brown leather shoes.", vi: "Anh ấy đi giày da màu nâu." },
        ],
        notes: "Màu sắc phổ biến của đất và cây cối.",
      },
      {
        id: "nc17",
        term: "Gray",
        phonetic: "/ɡreɪ/",
        translation: "Màu xám",
        examples: [
          { en: "The sky is gray before the rain.", vi: "Bầu trời có màu xám trước khi mưa." },
          { en: "The old man has gray hair.", vi: "Ông cụ có mái tóc màu xám." },
          { en: "I bought a gray sweater.", vi: "Tôi đã mua một chiếc áo len màu xám." },
        ],
        notes: "Có thể viết là 'gray' (tiếng Anh-Mỹ) hoặc 'grey' (tiếng Anh-Anh).",
      },
      {
        id: "nc18",
        term: "First",
        phonetic: "/fɜːst/",
        translation: "Đầu tiên, thứ nhất",
        examples: [
          { en: "This is my first time in London.", vi: "Đây là lần đầu tiên tôi đến Luân Đôn." },
          { en: "He won the first prize.", vi: "Anh ấy đã giành giải nhất." },
          { en: "First, you need to open the book.", vi: "Đầu tiên, bạn cần mở sách ra." },
        ],
        notes: "Số thứ tự, viết tắt là '1st'.",
      },
      {
        id: "nc19",
        term: "Second",
        phonetic: "/ˈsekənd/",
        translation: "Thứ hai / Giây",
        examples: [
          { en: "He came second in the race.", vi: "Anh ấy đã về nhì trong cuộc đua." },
          { en: "Please wait for a second.", vi: "Vui lòng đợi một giây." },
          { en: "This is the second time I ask you.", vi: "Đây là lần thứ hai tôi hỏi bạn." },
        ],
        notes: "Số thứ tự viết tắt là '2nd'. Ở nghĩa khác, nó chỉ đơn vị thời gian (giây).",
      },
      {
        id: "nc20",
        term: "Many",
        phonetic: "/ˈmeni/",
        translation: "Nhiều",
        examples: [
          { en: "How many books do you have?", vi: "Bạn có bao nhiêu cuốn sách?" },
          { en: "There are many trees in the park.", vi: "Có nhiều cây xanh ở trong công viên." },
          { en: "Many people love this movie.", vi: "Nhiều người yêu thích bộ phim này." },
        ],
        notes: "Đi kèm với danh từ đếm được số nhiều.",
      },
    ],
  },
  {
    id: "topic_body_parts",
    title: "Các bộ phận cơ thể",
    category: "topic",
    description: "Các bộ phận cơ bản bên ngoài cơ thể con người.",
    color: "bg-blue-500",
    words: [
      {
        id: "bp1",
        term: "Head",
        phonetic: "/hed/",
        translation: "Đầu",
        examples: [
          { en: "He has a headache.", vi: "Anh ấy bị đau đầu." },
          { en: "She wears a hat on her head.", vi: "Cô ấy đội một chiếc mũ trên đầu." },
          { en: "He nodded his head in agreement.", vi: "Anh ấy gật đầu đồng ý." },
        ],
        notes: "Đầu (bộ phận cơ thể), nghĩa bóng là người đứng đầu.",
      },
      {
        id: "bp2",
        term: "Hair",
        phonetic: "/heə/",
        translation: "Tóc, lông",
        examples: [
          { en: "She has long black hair.", vi: "Cô ấy có mái tóc đen dài." },
          { en: "He needs to cut his hair.", vi: "Anh ấy cần cắt tóc." },
          { en: "The dog has white hair.", vi: "Con chó có bộ lông màu trắng." },
        ],
        notes: "Là danh từ không đếm được khi chỉ mái tóc, nhưng đếm được khi chỉ các sợi tóc riêng lẻ.",
      },
      {
        id: "bp3",
        term: "Eye",
        phonetic: "/aɪ/",
        translation: "Mắt, con mắt",
        examples: [
          { en: "Close your eyes and make a wish.", vi: "Hãy nhắm mắt lại và ước một điều ước." },
          { en: "She has green eyes.", vi: "Cô ấy có đôi mắt màu xanh lá." },
          { en: "He has an eye infection.", vi: "Anh ấy bị nhiễm trùng mắt." },
        ],
        notes: "Thường dùng dạng số nhiều 'eyes'.",
      },
      {
        id: "bp4",
        term: "Ear",
        phonetic: "/ɪə/",
        translation: "Tai, thính giác",
        examples: [
          { en: "We listen with our ears.", vi: "Chúng ta nghe bằng tai." },
          { en: "He whispered into her ear.", vi: "Anh ấy đã thì thầm vào tai cô ấy." },
          { en: "She wears gold earrings in her ears.", vi: "Cô ấy đeo khuyên tai vàng ở tai." },
        ],
        notes: "Thường dùng dạng số nhiều 'ears'.",
      },
      {
        id: "bp5",
        term: "Nose",
        phonetic: "/nəʊz/",
        translation: "Mũi",
        examples: [
          { en: "The dog has a cold nose.", vi: "Con chó có cái mũi lạnh." },
          { en: "He has a runny nose today.", vi: "Hôm nay anh ấy bị sổ mũi." },
          { en: "She smells the flower with her nose.", vi: "Cô ấy ngửi bông hoa bằng mũi của mình." },
        ],
        notes: "Dùng để ngửi và hô hấp.",
      },
      {
        id: "bp6",
        term: "Mouth",
        phonetic: "/maʊθ/",
        translation: "Miệng",
        examples: [
          { en: "Open your mouth, please.", vi: "Vui lòng mở miệng ra." },
          { en: "She put the sweet into her mouth.", vi: "Cô ấy bỏ viên kẹo vào miệng." },
          { en: "Do not speak with your mouth full.", vi: "Đừng nói chuyện khi miệng đầy thức ăn." },
        ],
        notes: "Dùng để ăn uống và giao tiếp.",
      },
      {
        id: "bp7",
        term: "Face",
        phonetic: "/feɪs/",
        translation: "Khuôn mặt",
        examples: [
          { en: "She washed her face with cold water.", vi: "Cô ấy rửa mặt bằng nước lạnh." },
          { en: "He has a big smile on his face.", vi: "Anh ấy có một nụ cười rạng rỡ trên khuôn mặt." },
          { en: "I remember her face but forgot her name.", vi: "Tôi nhớ mặt cô ấy nhưng quên mất tên." },
        ],
        notes: "Vừa là danh từ (khuôn mặt) vừa là động từ (đối mặt).",
      },
      {
        id: "bp8",
        term: "Hand",
        phonetic: "/hænd/",
        translation: "Bàn tay",
        examples: [
          { en: "Hold my hand, please.", vi: "Làm ơn hãy nắm lấy tay tôi." },
          { en: "Wash your hands before eating.", vi: "Hãy rửa tay trước khi ăn." },
          { en: "He writes with his left hand.", vi: "Anh ấy viết bằng tay trái." },
        ],
        notes: "Khác với 'arm' (cánh tay).",
      },
      {
        id: "bp9",
        term: "Finger",
        phonetic: "/ˈfɪŋɡə/",
        translation: "Ngón tay",
        examples: [
          { en: "She wears a ring on her finger.", vi: "Cô ấy đeo một chiếc nhẫn trên ngón tay." },
          { en: "I cut my finger yesterday.", vi: "Tôi đã bị đứt tay vào ngày hôm qua." },
          { en: "He pointed his finger at the map.", vi: "Anh ấy đã chỉ ngón tay vào bản đồ." },
        ],
        notes: "Bàn tay người bình thường có 5 ngón (fingers).",
      },
      {
        id: "bp10",
        term: "Arm",
        phonetic: "/ɑːm/",
        translation: "Cánh tay",
        examples: [
          { en: "He broke his arm during the game.", vi: "Anh ấy bị gãy tay trong trận đấu." },
          { en: "She held the baby in her arms.", vi: "Cô ấy bồng em bé trong vòng tay mình." },
          { en: "Put your arms around me.", vi: "Hãy ôm lấy tôi (vòng tay quanh tôi)." },
        ],
        notes: "Cánh tay (từ vai đến cổ tay).",
      },
      {
        id: "bp11",
        term: "Leg",
        phonetic: "/leɡ/",
        translation: "Chân (cẳng chân)",
        examples: [
          { en: "She has long legs.", vi: "Cô ấy có đôi chân dài." },
          { en: "The table has four legs.", vi: "Chiếc bàn có bốn chân." },
          { en: "My legs hurt after running.", vi: "Chân tôi bị đau sau khi chạy." },
        ],
        notes: "Khác với 'foot' (bàn chân).",
      },
      {
        id: "bp12",
        term: "Foot",
        phonetic: "/fʊt/",
        translation: "Bàn chân",
        examples: [
          { en: "He has big feet.", vi: "Cậu ấy có bàn chân lớn." },
          { en: "I go to school on foot.", vi: "Tôi đi bộ đến trường." },
          { en: "She hurt her left foot.", vi: "Cô ấy bị đau bàn chân trái." },
        ],
        notes: "Số nhiều của 'foot' là 'feet' (bất quy tắc).",
      },
      {
        id: "bp13",
        term: "Tooth",
        phonetic: "/tuːθ/",
        translation: "Răng",
        examples: [
          { en: "I brush my teeth twice a day.", vi: "Tôi đánh răng hai lần một ngày." },
          { en: "She has a loose tooth.", vi: "Cô ấy bị lung lay một chiếc răng." },
          { en: "The baby only has two teeth.", vi: "Em bé mới chỉ mọc hai chiếc răng." },
        ],
        notes: "Số nhiều của 'tooth' là 'teeth' (bất quy tắc).",
      },
      {
        id: "bp14",
        term: "Tongue",
        phonetic: "/tʌŋ/",
        translation: "Cái lưỡi",
        examples: [
          { en: "He burnt his tongue on the hot soup.", vi: "Anh ấy bị bỏng lưỡi vì súp nóng." },
          { en: "The doctor asked him to stick out his tongue.", vi: "Bác sĩ yêu cầu anh ấy lè lưỡi ra." },
          { en: "The dog was panting with its tongue out.", vi: "Con chó đang thở dốc và thè lưỡi ra." },
        ],
        notes: "Vừa có nghĩa là bộ phận cơ thể, vừa có nghĩa là ngôn ngữ (mother tongue).",
      },
      {
        id: "bp15",
        term: "Shoulder",
        phonetic: "/ˈʃəʊldə/",
        translation: "Bờ vai, vai",
        examples: [
          { en: "He put his hand on my shoulder.", vi: "Anh ấy đặt tay lên vai tôi." },
          { en: "She carries a bag on her shoulder.", vi: "Cô ấy đeo một chiếc túi trên vai." },
          { en: "His shoulders are broad.", vi: "Vai của anh ấy rất rộng." },
        ],
        notes: "Phần khớp nối cánh tay với thân mình.",
      },
      {
        id: "bp16",
        term: "Knee",
        phonetic: "/niː/",
        translation: "Đầu gối",
        examples: [
          { en: "He fell and hurt his knee.", vi: "Cậu ấy ngã và bị đau đầu gối." },
          { en: "She was sitting with her knees bent.", vi: "Cô ấy đang ngồi gập đầu gối." },
          { en: "The skirt covers her knees.", vi: "Chiếc váy che khuất đầu gối cô ấy." },
        ],
        notes: "Âm 'k' trong 'knee' là âm câm, không phát âm.",
      },
      {
        id: "bp17",
        term: "Neck",
        phonetic: "/nek/",
        translation: "Cổ",
        examples: [
          { en: "She wears a gold necklace around her neck.", vi: "Cô ấy đeo một sợi dây chuyền vàng quanh cổ." },
          { en: "The giraffe has a very long neck.", vi: "Hươu cao cổ có cái cổ rất dài." },
          { en: "He turned his neck to look back.", vi: "Anh ấy quay cổ lại để nhìn về phía sau." },
        ],
        notes: "Phần kết nối giữa đầu và thân mình.",
      },
      {
        id: "bp18",
        term: "Heart",
        phonetic: "/hɑːt/",
        translation: "Trái tim",
        examples: [
          { en: "My heart is beating fast.", vi: "Tim tôi đang đập nhanh." },
          { en: "He drew a picture of a heart.", vi: "Cậu ấy đã vẽ một bức tranh hình trái tim." },
          { en: "She has a kind heart.", vi: "Cô ấy có một tấm lòng nhân hậu." },
        ],
        notes: "Vừa chỉ cơ quan nội tạng vừa mang nghĩa biểu tượng cho cảm xúc.",
      },
      {
        id: "bp19",
        term: "Body",
        phonetic: "/ˈbɒdi/",
        translation: "Cơ thể",
        examples: [
          { en: "Keep your body warm in winter.", vi: "Hãy giữ ấm cơ thể vào mùa đông." },
          { en: "Exercise is good for your body.", vi: "Tập thể dục rất tốt cho cơ thể của bạn." },
          { en: "She has a healthy body.", vi: "Cô ấy có một cơ thể khỏe mạnh." },
        ],
        notes: "Khái niệm chỉ toàn bộ thể chất.",
      },
      {
        id: "bp20",
        term: "Skin",
        phonetic: "/skɪn/",
        translation: "Làn da, da",
        examples: [
          { en: "Her skin is very soft.", vi: "Da của cô ấy rất mềm mại." },
          { en: "Protect your skin from the sun.", vi: "Hãy bảo vệ làn da của bạn khỏi ánh nắng mặt trời." },
          { en: "This cream is good for dry skin.", vi: "Kem này rất tốt cho da khô." },
        ],
        notes: "Lớp bọc ngoài bảo vệ cơ thể.",
      },
    ],
  },
  {
    id: "topic_school_supplies",
    title: "Đồ dùng học tập",
    category: "topic",
    description: "Từ vựng cơ bản về các đồ dùng, dụng cụ học tập trong lớp học hàng ngày.",
    color: "bg-pink-500",
    words: [
      {
        id: "sch1",
        term: "Pen",
        phonetic: "/pen/",
        translation: "Bút mực, cây bút",
        examples: [
          { en: "I write with a blue pen.", vi: "Tôi viết bằng bút mực màu xanh dương." },
          { en: "Can I borrow your pen?", vi: "Tôi có thể mượn bút của bạn được không?" },
          { en: "He lost his favorite pen.", vi: "Anh ấy đã làm mất chiếc bút yêu thích của mình." },
        ],
        notes: "Chỉ chung các loại bút viết bằng mực.",
      },
      {
        id: "sch2",
        term: "Pencil",
        phonetic: "/ˈtensl/",
        translation: "Bút chì",
        examples: [
          { en: "I need a pencil to draw.", vi: "Tôi cần một chiếc bút chì để vẽ." },
          { en: "Do you have a pencil?", vi: "Bạn có bút chì không?" },
          { en: "The pencil has an eraser on top.", vi: "Chiếc bút chì có một cục tẩy ở trên đầu." },
        ],
        notes: "Có thể gọt nhọn hoặc dùng bút chì kim.",
      },
      {
        id: "sch3",
        term: "Book",
        phonetic: "/bʊk/",
        translation: "Quyển sách",
        examples: [
          { en: "I read a book every night.", vi: "Tôi đọc một quyển sách mỗi tối." },
          { en: "This is an English book.", vi: "Đây là một quyển sách tiếng Anh." },
          { en: "Please open your book to page ten.", vi: "Vui lòng mở sách của bạn ở trang mười." },
        ],
        notes: "Vừa là danh từ (quyển sách), vừa là động từ (đặt chỗ).",
      },
      {
        id: "sch4",
        term: "Notebook",
        phonetic: "/ˈnəʊtbʊk/",
        translation: "Quyển vở, tập ghi chép",
        examples: [
          { en: "She writes her homework in a notebook.", vi: "Cô ấy viết bài tập về nhà vào vở." },
          { en: "I bought a new notebook yesterday.", vi: "Hôm qua tôi đã mua một quyển vở mới." },
          { en: "Keep your notebook clean.", vi: "Hãy giữ cho vở ghi chép của bạn sạch sẽ." },
        ],
        notes: "Vở có dòng kẻ để ghi chép bài học.",
      },
      {
        id: "sch5",
        term: "Eraser",
        phonetic: "/ɪˈreɪzə/",
        translation: "Cục tẩy, cục gôm",
        examples: [
          { en: "I use an eraser to clean my mistakes.", vi: "Tôi dùng cục tẩy để xóa những lỗi sai của mình." },
          { en: "Do you have an eraser?", vi: "Bạn có cục tẩy không?" },
          { en: "This pink eraser is very cute.", vi: "Cục tẩy màu hồng này rất dễ thương." },
        ],
        notes: "Tiếng Anh-Mỹ dùng 'eraser', tiếng Anh-Anh thường dùng 'rubber'.",
      },
      {
        id: "sch6",
        term: "Ruler",
        phonetic: "/ˈruːlə/",
        translation: "Thước kẻ",
        examples: [
          { en: "Use a ruler to draw a straight line.", vi: "Hãy dùng thước kẻ để vẽ một đường thẳng." },
          { en: "My ruler is thirty centimeters long.", vi: "Thước kẻ của tôi dài ba mươi xăng-ti-mét." },
          { en: "Can I borrow your ruler?", vi: "Tôi có thể mượn chiếc thước kẻ của bạn được không?" },
        ],
        notes: "Dụng cụ dùng để đo độ dài và kẻ đường thẳng.",
      },
      {
        id: "sch7",
        term: "Schoolbag",
        phonetic: "/ˈskuːlbæɡ/",
        translation: "Cặp học sinh, ba lô",
        examples: [
          { en: "My schoolbag is very heavy today.", vi: "Cặp sách của tôi hôm nay rất nặng." },
          { en: "She put her books into her schoolbag.", vi: "Cô ấy bỏ sách vào trong cặp của mình." },
          { en: "He has a blue schoolbag.", vi: "Cậu ấy có một chiếc ba lô màu xanh dương." },
        ],
        notes: "Túi hoặc ba lô dùng để mang đồ dùng học tập đến trường.",
      },
      {
        id: "sch8",
        term: "Desk",
        phonetic: "/desk/",
        translation: "Bàn học, bàn làm việc",
        examples: [
          { en: "I sit at my desk to study.", vi: "Tôi ngồi tại bàn học để học bài." },
          { en: "There is a lamp on the desk.", vi: "Có một chiếc đèn ở trên bàn học." },
          { en: "Keep your desk tidy.", vi: "Hãy giữ cho bàn học của bạn ngăn nắp." },
        ],
        notes: "Khác với 'table' (thường dùng để ăn uống, không có hộc tủ).",
      },
      {
        id: "sch9",
        term: "Board",
        phonetic: "/bɔːd/",
        translation: "Cái bảng",
        examples: [
          { en: "The teacher writes on the board.", vi: "Giáo viên viết lên bảng." },
          { en: "Look at the board, please.", vi: "Vui lòng nhìn lên bảng." },
          { en: "He cleaned the board after class.", vi: "Cậu ấy đã lau bảng sau giờ học." },
        ],
        notes: "Chỉ chung bảng đen (blackboard) hoặc bảng trắng (whiteboard).",
      },
      {
        id: "sch10",
        term: "Pencil case",
        phonetic: "/ˈpensl keɪs/",
        translation: "Hộp bút, bóp viết",
        examples: [
          { en: "I put my pens in my pencil case.", vi: "Tôi cất bút vào trong hộp bút." },
          { en: "Where is your pencil case?", vi: "Hộp bút của bạn ở đâu?" },
          { en: "She bought a colorful pencil case.", vi: "She bought a colorful pencil case." },
        ],
        notes: "Hộp nhỏ bằng nhựa hoặc vải để giữ bút thước.",
      },
      {
        id: "sch11",
        term: "Paper",
        phonetic: "/ˈpeɪpə/",
        translation: "Giấy, tờ giấy",
        examples: [
          { en: "I need a sheet of paper to write.", vi: "Tôi cần một tờ giấy để viết." },
          { en: "Draw a picture on the paper.", vi: "Hãy vẽ một bức tranh lên tờ giấy." },
          { en: "The paper is white.", vi: "Tờ giấy màu trắng." },
        ],
        notes: "Danh từ không đếm được, nếu muốn đếm phải dùng 'a sheet of paper'.",
      },
      {
        id: "sch12",
        term: "Scissors",
        phonetic: "/ˈsɪzəz/",
        translation: "Cái kéo",
        examples: [
          { en: "Scissors are sharp, be careful.", vi: "Kéo rất sắc, hãy cẩn thận." },
          { en: "Can you pass me the scissors, please?", vi: "Bạn có thể chuyển cho tôi chiếc kéo được không?" },
          { en: "She cuts paper with scissors.", vi: "Cô ấy cắt giấy bằng kéo." },
        ],
        notes: "Luôn chia ở dạng số nhiều và đi kèm động từ số nhiều.",
      },
      {
        id: "sch13",
        term: "Glue",
        phonetic: "/ɡluː/",
        translation: "Keo dán, hồ dán",
        examples: [
          { en: "Use glue to stick the paper.", vi: "Hãy dùng keo để dán tờ giấy." },
          { en: "Do we have any glue left?", vi: "Chúng ta còn ít hồ dán nào không?" },
          { en: "The glue is very sticky.", vi: "Keo dán này rất dính." },
        ],
        notes: "Chất lỏng hoặc dạng thỏi dùng để gắn kết các vật liệu.",
      },
      {
        id: "sch14",
        term: "Crayon",
        phonetic: "/ˈkreɪən/",
        translation: "Bút màu sáp",
        examples: [
          { en: "The children are drawing with crayons.", vi: "Trẻ em đang vẽ bằng bút màu sáp." },
          { en: "Can I use your green crayon?", vi: "Tôi có thể dùng chiếc bút màu sáp xanh lá của bạn không?" },
          { en: "He bought a box of twenty-four crayons.", vi: "Cậu ấy đã mua một hộp gồm hai mươi tư chiếc bút màu sáp." },
        ],
        notes: "Bút màu làm bằng sáp màu mềm.",
      },
      {
        id: "sch15",
        term: "Marker",
        phonetic: "/ˈmɑːkə/",
        translation: "Bút lông, bút dạ",
        examples: [
          { en: "The teacher uses a black marker.", vi: "Giáo viên sử dụng một chiếc bút lông màu đen." },
          { en: "Write your name with a marker.", vi: "Hãy viết tên của bạn bằng bút lông." },
          { en: "The marker is out of ink.", vi: "Chiếc bút lông đã hết mực rồi." },
        ],
        notes: "Loại bút ngòi dạ có mực đậm, dùng vẽ hoặc viết bảng.",
      },
      {
        id: "sch16",
        term: "Sharpener",
        phonetic: "/ˈʃɑːpənə/",
        translation: "Cái gọt bút chì",
        examples: [
          { en: "I need a sharpener for my pencil.", vi: "Tôi cần một chiếc gọt bút chì cho bút của mình." },
          { en: "Can I borrow your pencil sharpener?", vi: "Tôi có thể mượn cái gọt bút chì của bạn được không?" },
          { en: "The sharpener is in the drawer.", vi: "Cái gọt bút chì ở trong ngăn kéo." },
        ],
        notes: "Còn được gọi đầy đủ là 'pencil sharpener'.",
      },
      {
        id: "sch17",
        term: "Calculator",
        phonetic: "/ˈkælkjʊleɪtə/",
        translation: "Máy tính cầm tay",
        examples: [
          { en: "We use a calculator in math class.", vi: "Chúng tôi sử dụng máy tính cầm tay trong giờ học toán." },
          { en: "My calculator needs a new battery.", vi: "Máy tính của tôi cần pin mới." },
          { en: "Do you have a calculator?", vi: "Bạn có máy tính cầm tay không?" },
        ],
        notes: "Thiết bị điện tử cầm tay dùng để tính toán số liệu.",
      },
      {
        id: "sch18",
        term: "Dictionary",
        phonetic: "/ˈdɪkʃənri/",
        translation: "Từ điển",
        examples: [
          { en: "Look up the word in the dictionary.", vi: "Hãy tra cứu từ đó trong từ điển." },
          { en: "I have a small English dictionary.", vi: "Tôi có một cuốn từ điển tiếng Anh nhỏ." },
          { en: "The dictionary is very thick.", vi: "Cuốn từ điển này rất dày." },
        ],
        notes: "Sách tra cứu nghĩa, phát âm của từ vựng.",
      },
      {
        id: "sch19",
        term: "Map",
        phonetic: "/mæp/",
        translation: "Bản đồ",
        examples: [
          { en: "There is a world map on the wall.", vi: "Có một tấm bản đồ thế giới trên tường." },
          { en: "We study geography with a map.", vi: "Chúng tôi học địa lý với một tấm bản đồ." },
          { en: "He looked at the map to find the way.", vi: "Cậu ấy nhìn vào bản đồ để tìm đường." },
        ],
        notes: "Bản đồ địa lý của quốc gia hoặc thế giới.",
      },
      {
        id: "sch20",
        term: "Folder",
        phonetic: "/ˈfəʊldə/",
        translation: "Bìa hồ sơ, kẹp tài liệu",
        examples: [
          { en: "I keep my drawings in a folder.", vi: "Tôi giữ các bức vẽ của mình trong một chiếc kẹp tài liệu." },
          { en: "Put your test paper in the folder.", vi: "Hãy bỏ bài kiểm tra của bạn vào kẹp tài liệu." },
          { en: "She bought a plastic folder yesterday.", vi: "Hôm qua cô ấy đã mua một cái bìa hồ sơ bằng nhựa." },
        ],
        notes: "Dùng để lưu trữ giấy tờ, bài kiểm tra phẳng phiu.",
      },
    ],
  },
];
