export const tierEmeraldI = [
  {
    id: "topic_culture_e1",
    title: "Lễ hội & Văn hóa",
    category: "topic",
    description: "Các sự kiện văn hóa, phong tục truyền thống và nghi lễ của các quốc gia trên thế giới.",
    color: "bg-teal-700",
    words: [
      {
        id: "cul1",
        term: "Festival",
        phonetic: "/ˈfestɪvl/",
        translation: "Lễ hội",
        examples: [
          { en: "The annual flower festival is celebrated in Da Lat every winter.", vi: "Lễ hội hoa thường niên được tổ chức ở Đà Lạt vào mỗi mùa đông." },
          { en: "They performed traditional dances at the local festival.", vi: "Họ đã biểu diễn các điệu nhảy truyền thống tại lễ hội địa phương." },
          { en: "The music festival attracted thousands of young people.", vi: "Lễ hội âm nhạc đã thu hút hàng ngàn bạn trẻ." },
        ],
        notes: "Sự kiện văn hóa hoặc tôn giáo được tổ chức định kỳ.",
      },
      {
        id: "cul2",
        term: "Culture",
        phonetic: "/ˈkʌltʃə/",
        translation: "Văn hóa",
        examples: [
          { en: "It is important to respect the local culture when traveling.", vi: "Tôn trọng văn hóa địa phương khi đi du lịch là điều rất quan trọng." },
          { en: "We learned a lot about Japanese culture during our stay in Tokyo.", vi: "Chúng tôi đã học được rất nhiều về văn hóa Nhật Bản trong thời gian ở Tokyo." },
          { en: "Language is a key part of any national culture.", vi: "Ngôn ngữ là một phần cốt lõi của bất kỳ nền văn hóa dân tộc nào." },
        ],
        notes: "Lối sống, phong tục và tín ngưỡng của một cộng đồng.",
      },
      {
        id: "cul3",
        term: "Tradition",
        phonetic: "/trəˈdɪʃn/",
        translation: "Truyền thống",
        examples: [
          { en: "According to tradition, people wear new clothes on Lunar New Year.", vi: "Theo truyền thống, mọi người thường mặc quần áo mới vào dịp Tết Nguyên Đán." },
          { en: "They are trying to preserve their ancient family traditions.", vi: "Họ đang cố gắng bảo tồn những truyền thống lâu đời của gia đình mình." },
          { en: "It has become a tradition for us to gather here every Christmas.", vi: "Việc tụ họp tại đây vào mỗi dịp Giáng sinh đã trở thành một truyền thống của chúng tôi." },
        ],
        notes: "Thói quen, tập tục được truyền từ đời này sang đời khác.",
      },
      {
        id: "cul4",
        term: "Celebrate",
        phonetic: "/ˈselɪbreɪt/",
        translation: "Ăn mừng, kỷ niệm",
        examples: [
          { en: "How do you celebrate Thanksgiving in your country?", vi: "Các bạn kỷ niệm Ngày Lễ Tạ Ơn ở nước bạn như thế nào?" },
          { en: "They had a big party to celebrate their wedding anniversary.", vi: "Họ đã tổ chức một bữa tiệc lớn để kỷ niệm ngày cưới của mình." },
          { en: "We celebrated his promotion with a delicious dinner.", vi: "Chúng tôi đã ăn mừng sự thăng chức của anh ấy bằng một bữa tối ngon miệng." },
        ],
        notes: "Động từ chỉ hoạt động chúc mừng một sự kiện đặc biệt.",
      },
      {
        id: "cul5",
        term: "Custom",
        phonetic: "/ˈkʌstəm/",
        translation: "Phong tục, tập quán",
        examples: [
          { en: "It is a local custom to remove your shoes before entering a house.", vi: "Cởi giày trước khi vào nhà là một phong tục của địa phương." },
          { en: "Every country has its own unique social customs.", vi: "Mỗi quốc gia đều có những phong tục xã hội độc đáo riêng." },
          { en: "He did research on the ancient customs of the tribe.", vi: "Anh ấy đã nghiên cứu về những phong tục cổ xưa của bộ lạc." },
        ],
        notes: "Hành vi được thừa nhận rộng rãi như một thói quen của xã hội.",
      },
      {
        id: "cul6",
        term: "Ceremony",
        phonetic: "/ˈserəməni/",
        translation: "Nghi lễ, nghi thức",
        examples: [
          { en: "The wedding ceremony took place in a beautiful garden.", vi: "Nghi lễ đám cưới đã diễn ra trong một khu vườn xinh đẹp." },
          { en: "She received a certificate at the graduation ceremony.", vi: "Cô ấy đã nhận được chứng chỉ tại lễ tốt nghiệp." },
          { en: "The opening ceremony of the Olympics was spectacular.", vi: "Lễ khai mạc Thế vận hội rất hoành tráng." },
        ],
        notes: "Sự kiện trang trọng được tiến hành theo các quy tắc xã hội hoặc tôn giáo.",
      },
      {
        id: "cul7",
        term: "Costume",
        phonetic: "/ˈkɒstjuːm/",
        translation: "Trang phục truyền thống, đồ hóa trang",
        examples: [
          { en: "She wore a traditional costume of her country to the festival.", vi: "Cô ấy đã mặc trang phục truyền thống của nước mình đến lễ hội." },
          { en: "Children wear scary costumes on Halloween.", vi: "Trẻ em mặc những bộ đồ hóa trang đáng sợ vào dịp Halloween." },
          { en: "The actors wore colorful historical costumes.", vi: "Các diễn viên đã mặc những bộ trang phục lịch sử đầy màu sắc." },
        ],
        notes: "Trang phục đặc thù cho một quốc gia, giai đoạn lịch sử hoặc lễ hội hóa trang.",
      },
      {
        id: "cul8",
        term: "Parade",
        phonetic: "/pəˈreɪd/",
        translation: "Cuộc diễu hành",
        examples: [
          { en: "Thousands of people lined the streets to watch the National Day parade.", vi: "Hàng ngàn người đã xếp hàng trên đường phố để xem cuộc diễu hành Ngày Quốc khánh." },
          { en: "There is a colorful parade in the city center today.", vi: "Hôm nay có một cuộc diễu hành rực rỡ sắc màu ở trung tâm thành phố." },
          { en: "The band practiced for weeks before the big parade.", vi: "Ban nhạc đã tập luyện hàng tuần trước cuộc diễu hành lớn." },
        ],
        notes: "Hoạt động di chuyển trang trọng của một đoàn người nhằm kỷ niệm.",
      },
      {
        id: "cul9",
        term: "Performance",
        phonetic: "/pəˈfɔːməns/",
        translation: "Buổi biểu diễn, màn trình diễn",
        examples: [
          { en: "The singer gave an outstanding live performance.", vi: "Ca sĩ đã mang lại một màn trình diễn trực tiếp xuất sắc." },
          { en: "We enjoyed the puppet performance very much.", vi: "Chúng tôi đã rất thích buổi biểu diễn múa rối." },
          { en: "The theater offers daily performances at eight.", vi: "Nhà hát có các buổi biểu diễn hàng ngày vào lúc tám giờ." },
        ],
        notes: "Danh từ của động từ 'perform' (biểu diễn / thực hiện).",
      },
      {
        id: "cul10",
        term: "Decoration",
        phonetic: "/ˌdekəˈreɪʃn/",
        translation: "Sự trang trí, đồ trang trí",
        examples: [
          { en: "They put up beautiful Christmas decorations in the living room.", vi: "Họ đã treo những món đồ trang trí Giáng sinh đẹp mắt ở phòng khách." },
          { en: "The cake was finished with chocolate decorations.", vi: "Chiếc bánh ngọt đã được hoàn thành với các chi tiết trang trí bằng sô-cô-la." },
          { en: "She is in charge of the table decoration for the party.", vi: "Cô ấy chịu trách nhiệm trang trí bàn tiệc cho bữa tiệc." },
        ],
        notes: "Vật phẩm dùng để làm đẹp cho một không gian hoặc bề mặt.",
      },
      {
        id: "cul11",
        term: "Gift",
        phonetic: "/ɡɪft/",
        translation: "Quà tặng, món quà / Tài năng thiên bẩm",
        examples: [
          { en: "He bought a expensive gift for his mother's birthday.", vi: "Anh ấy đã mua một món quà đắt tiền cho ngày sinh nhật của mẹ." },
          { en: "She has a natural gift for learning languages.", vi: "Cô ấy có một tài năng thiên bẩm đối với việc học ngôn ngữ." },
          { en: "This free book is our gift to you.", vi: "Cuốn sách miễn phí này là món quà của chúng tôi dành cho bạn." },
        ],
        notes: "Từ đồng nghĩa thông dụng nhất là 'present'.",
      },
      {
        id: "cul12",
        term: "Symbol",
        phonetic: "/ˈsɪmbl/",
        translation: "Biểu tượng",
        examples: [
          { en: "The lotus is the national symbol of Vietnam.", vi: "Hoa sen là biểu tượng quốc gia của Việt Nam." },
          { en: "The white dove is a universal symbol of peace.", vi: "Chim bồ câu trắng là biểu tượng hòa bình phổ quát trên toàn thế giới." },
          { en: "What does this traffic symbol mean?", vi: "Biểu tượng giao thông này có nghĩa là gì?" },
        ],
        notes: "Hình ảnh, dấu hiệu đại diện cho một ý tưởng hay một quốc gia.",
      },
      {
        id: "cul13",
        term: "Belief",
        phonetic: "/bɪˈliːf/",
        translation: "Tín ngưỡng, niềm tin",
        examples: [
          { en: "Respecting elders is a core belief in Asian culture.", vi: "Tôn trọng người lớn tuổi là một niềm tin cốt lõi trong văn hóa châu Á." },
          { en: "They have strong religious beliefs.", vi: "Họ có những tín ngưỡng tôn giáo rất mạnh mẽ." },
          { en: "My belief in his honesty never changed.", vi: "Niềm tin của tôi vào sự trung thực của anh ấy chưa bao giờ thay đổi." },
        ],
        notes: "Danh từ của động từ 'believe' (tin tưởng).",
      },
      {
        id: "cul14",
        term: "Event",
        phonetic: "/ɪˈvent/",
        translation: "Sự kiện",
        examples: [
          { en: "The annual sports competition is a major event for the school.", vi: "Cuộc thi thể thao thường niên là một sự kiện lớn của trường học." },
          { en: "The local government planned a charity event to help the poor.", vi: "Chính quyền địa phương đã lên kế hoạch một sự kiện từ thiện để giúp đỡ người nghèo." },
          { en: "We attended a formal event last night.", vi: "Chúng tôi đã tham dự một sự kiện trang trọng vào tối qua." },
        ],
        notes: "Một sự việc, chương trình có tầm ảnh hưởng được lên kế hoạch trước.",
      },
      {
        id: "cul15",
        term: "Gathering",
        phonetic: "/ˈɡæðərɪŋ/",
        translation: "Cuộc tụ họp, sum vầy",
        examples: [
          { en: "They had a family gathering to celebrate Lunar New Year.", vi: "Họ đã tổ chức một cuộc tụ họp gia đình để đón Tết Nguyên Đán." },
          { en: "The local community held a social gathering in the park.", vi: "Cộng đồng địa phương đã tổ chức một buổi tụ họp giao lưu ở công viên." },
          { en: "I enjoy informal gatherings with my close friends.", vi: "Tôi thích những buổi tụ tập thân mật với những người bạn thân của mình." },
        ],
        notes: "Danh từ chỉ hoạt động họp mặt, hội ngộ nhiều người.",
      },
      {
        id: "cul16",
        term: "Feast",
        phonetic: "/fiːst/",
        translation: "Yến tiệc, bữa tiệc lớn thịnh soạn",
        examples: [
          { en: "They prepared a massive feast for the wedding guests.", vi: "Họ đã chuẩn bị một yến tiệc khổng lồ cho các khách mời đám cưới." },
          { en: "We sat down to a delicious feast of seafood.", vi: "Chúng tôi ngồi vào bàn thưởng thức một bữa tiệc hải sản thịnh soạn ngon miệng." },
          { en: "The festival ended with a traditional community feast.", vi: "Lễ hội kết thúc bằng một bữa tiệc cộng đồng truyền thống." },
        ],
        notes: "Bữa ăn thịnh soạn kỷ niệm một sự kiện đặc biệt.",
      },
      {
        id: "cul17",
        term: "Folk",
        phonetic: "/fəʊk/",
        translation: "Dân gian, dân tộc / Người",
        examples: [
          { en: "I love listening to traditional Vietnamese folk music.", vi: "Tôi thích nghe nhạc dân gian truyền thống của Việt Nam." },
          { en: "Folk tales are often passed down from parents to children.", vi: "Các câu chuyện dân gian thường được truyền từ cha mẹ sang con cái." },
          { en: "Country folk are usually very friendly.", vi: "Người dân ở nông thôn thường rất thân thiện." },
        ],
        notes: "Liên quan đến đời sống văn hóa bình dân, dân dã lâu đời.",
      },
      {
        id: "cul18",
        term: "Value",
        phonetic: "/ˈvæljuː/",
        translation: "Giá trị (văn hóa, đạo đức) / Trị giá tiền",
        examples: [
          { en: "We should teach traditional cultural values to our children.", vi: "Chúng ta nên dạy các giá trị văn hóa truyền thống cho con em mình." },
          { en: "Honesty is a highly respected moral value.", vi: "Trung thực là một giá trị đạo đức rất được tôn trọng." },
          { en: "The economic value of this building is enormous.", vi: "Giá trị kinh tế của tòa nhà này là vô cùng to lớn." },
        ],
        notes: "Quan điểm, chuẩn mực được xã hội coi trọng.",
      },
      {
        id: "cul19",
        term: "Heritage",
        phonetic: "/ˈherɪtɪdʒ/",
        translation: "Di sản",
        examples: [
          { en: "Hoi An Ancient Town is a world cultural heritage site.", vi: "Phố cổ Hội An là một khu di sản văn hóa thế giới." },
          { en: "We must protect our natural heritage for future generations.", vi: "Chúng ta phải bảo vệ di sản thiên nhiên của mình cho thế hệ tương lai." },
          { en: "The museum displays artifacts showing the country's rich heritage.", vi: "Bảo tàng trưng bày các cổ vật thể hiện di sản phong phú của đất nước." },
        ],
        notes: "Những giá trị, di tích lịch sử hoặc tự nhiên được lưu giữ lại.",
      },
      {
        id: "cul20",
        term: "Respect",
        phonetic: "/rɪˈspekt/",
        translation: "Tôn trọng, kính trọng",
        examples: [
          { en: "Children are taught to respect their teachers and parents.", vi: "Trẻ em được dạy phải tôn trọng thầy cô và cha mẹ." },
          { en: "You should show respect for foreign cultures.", vi: "Bạn nên thể hiện sự tôn trọng đối với các nền văn hóa nước ngoài." },
          { en: "He gained the respect of his colleagues through hard work.", vi: "Anh ấy đã nhận được sự tôn trọng của đồng nghiệp nhờ làm việc chăm chỉ." },
        ],
        notes: "Vừa là động từ vừa là danh từ không đếm được.",
      },
    ],
  },
  {
    id: "topic_jobs_e1",
    title: "Công việc cơ bản",
    category: "topic",
    description: "Các khía cạnh của nghề nghiệp, hồ sơ tuyển dụng, môi trường công sở và thăng tiến.",
    color: "bg-teal-700",
    words: [
      {
        id: "job1",
        term: "Employee",
        phonetic: "/ɪmˈplɔɪiː/",
        translation: "Nhân viên, người lao động",
        examples: [
          { en: "The company has more than five hundred employees.", vi: "Công ty có hơn năm trăm nhân viên." },
          { en: "She is a dedicated and hard-working employee.", vi: "Cô ấy là một nhân viên tận tụy và chăm chỉ." },
          { en: "Employees must wear name tags at the office.", vi: "Nhân viên phải đeo thẻ tên khi ở văn phòng." },
        ],
        notes: "Người được thuê làm việc và nhận lương.",
      },
      {
        id: "job2",
        term: "Employer",
        phonetic: "/ɪmˈplɔɪə/",
        translation: "Người sử dụng lao động, chủ thuê",
        examples: [
          { en: "My employer offered me a free training course.", vi: "Chủ thuê của tôi đã đề xuất cho tôi một khóa đào tạo miễn phí." },
          { en: "A good employer cares about the safety of workers.", vi: "Một người sử dụng lao động tốt luôn quan tâm đến sự an toàn của công nhân." },
          { en: "The government is a major employer in this country.", vi: "Chính phủ là một nhà sử dụng lao động lớn ở đất nước này." },
        ],
        notes: "Cá nhân hoặc tổ chức thuê nhân công làm việc.",
      },
      {
        id: "job3",
        term: "Manager",
        phonetic: "/ˈmænɪdʒə/",
        translation: "Quản lý, người điều hành",
        examples: [
          { en: "The project manager coordinates the whole team.", vi: "Quản lý dự án điều phối toàn bộ đội ngũ." },
          { en: "He was promoted to sales manager last month.", vi: "Anh ấy đã được thăng chức lên quản lý bán hàng vào tháng trước." },
          { en: "If you have a complaint, speak to the hotel manager.", vi: "Nếu bạn có khiếu nại, hãy nói chuyện với quản lý khách sạn." },
        ],
        notes: "Người phụ trách điều hành một bộ phận hoặc dự án.",
      },
      {
        id: "job4",
        term: "Career",
        phonetic: "/kəˈrɪə/",
        translation: "Sự nghiệp",
        examples: [
          { en: "She wants to pursue a career in medicine.", vi: "Cô ấy muốn theo đuổi một sự nghiệp trong ngành y." },
          { en: "He had a successful career as an engineer.", vi: "Anh ấy đã có một sự nghiệp thành công với tư cách là kỹ sư." },
          { en: "Changing your career path can be challenging.", vi: "Thay đổi con đường sự nghiệp có thể là một thử thách lớn." },
        ],
        notes: "Cả quá trình làm việc và phát triển nghề nghiệp lâu dài.",
      },
      {
        id: "job5",
        term: "Profession",
        phonetic: "/prəˈfeʃn/",
        translation: "Nghề nghiệp chuyên môn (yêu cầu học vấn cao)",
        examples: [
          { en: "Teaching is a highly respected profession.", vi: "Giáo viên là một nghề nghiệp chuyên môn rất được tôn trọng." },
          { en: "He entered the legal profession after passing the exam.", vi: "Anh ấy đã gia nhập ngành luật sau khi vượt qua kỳ thi." },
          { en: "You need formal training to join this medical profession.", vi: "Bạn cần được đào tạo chính quy để tham gia vào ngành y tế chuyên môn này." },
        ],
        notes: "Chỉ các nghề cần trình độ chuyên môn cao như luật, y, giáo dục.",
      },
      {
        id: "job6",
        term: "Qualification",
        phonetic: "/ˌkwɒlɪfɪˈkeɪʃn/",
        translation: "Bằng cấp, trình độ chuyên môn đạt chuẩn",
        examples: [
          { en: "You need good qualifications to get this job.", vi: "Bạn cần có những bằng cấp tốt để nhận được công việc này." },
          { en: "She is study to gain a professional qualification in accounting.", vi: "Cô ấy đang học để lấy chứng chỉ chuyên môn về kế toán." },
          { en: "His academic qualifications are outstanding.", vi: "Bằng cấp học tập của anh ấy rất xuất sắc." },
        ],
        notes: "Bằng cấp chính thức hoặc năng lực được chứng nhận.",
      },
      {
        id: "job7",
        term: "Interview",
        phonetic: "/ˈɪntəvjuː/",
        translation: "Cuộc phỏng vấn",
        examples: [
          { en: "I have a job interview at ten o'clock tomorrow.", vi: "Tôi có một cuộc phỏng vấn xin việc lúc mười giờ ngày mai." },
          { en: "The manager conducted several interviews today.", vi: "Người quản lý đã thực hiện vài cuộc phỏng vấn vào ngày hôm nay." },
          { en: "Prepare carefully for your interview questions.", vi: "Hãy chuẩn bị cẩn thận cho các câu hỏi phỏng vấn của bạn." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "job8",
        term: "Salary",
        phonetic: "/ˈsæləri/",
        translation: "Lương tháng, tiền lương định kỳ",
        examples: [
          { en: "The company offers a highly competitive salary.", vi: "Công ty đưa ra một mức lương tháng vô cùng cạnh tranh." },
          { en: "She receives her salary on the last day of the month.", vi: "Cô ấy nhận lương vào ngày cuối cùng của tháng." },
          { en: "They agreed on a starting salary of three thousand dollars.", vi: "Họ đã đồng ý với mức lương khởi điểm là ba ngàn đô la." },
        ],
        notes: "Tiền lương trả cố định hàng tháng, phân biệt với 'wage' (trả theo tuần hoặc giờ).",
      },
      {
        id: "job9",
        term: "Office",
        phonetic: "/ˈɒfɪs/",
        translation: "Văn phòng, nơi làm việc",
        examples: [
          { en: "Our office is located in the city center.", vi: "Văn phòng của chúng tôi nằm ở trung tâm thành phố." },
          { en: "She works in a quiet private office.", vi: "Cô ấy làm việc trong một văn phòng tư nhân yên tĩnh." },
          { en: "He arrived at the office early this morning.", vi: "Anh ấy đã đến văn phòng sớm vào sáng nay." },
        ],
        notes: "Địa điểm làm việc bàn giấy hành chính.",
      },
      {
        id: "job10",
        term: "Customer service",
        phonetic: "/ˈkʌstəmə ˈsɜːvɪs/",
        translation: "Dịch vụ khách hàng, chăm sóc khách hàng",
        examples: [
          { en: "Excellent customer service is essential for any business.", vi: "Dịch vụ khách hàng xuất sắc là điều thiết yếu đối với bất kỳ doanh nghiệp nào." },
          { en: "He works as a customer service representative.", vi: "Anh ấy làm việc với tư cách là một đại diện chăm sóc khách hàng." },
          { en: "The company has a good reputation for customer service.", vi: "Công ty có tiếng tăm tốt về dịch vụ khách hàng." },
        ],
        notes: "Bộ phận hoặc hoạt động hỗ trợ người mua hàng.",
      },
      {
        id: "job11",
        term: "Skill",
        phonetic: "/skɪl/",
        translation: "Kỹ năng",
        examples: [
          { en: "Communication is an important skill in the workplace.", vi: "Giao tiếp là một kỹ năng quan trọng ở nơi làm việc." },
          { en: "She is trying to improve her computer skills.", vi: "Cô ấy đang cố gắng cải thiện kỹ năng máy tính của mình." },
          { en: "The job requires excellent technical skills.", vi: "Công việc yêu cầu các kỹ năng kỹ thuật xuất sắc." },
        ],
        notes: "Khả năng làm tốt việc nhờ luyện tập và đào tạo.",
      },
      {
        id: "job12",
        term: "Retire",
        phonetic: "/rɪˈtaɪə/",
        translation: "Nghỉ hưu",
        examples: [
          { en: "My father plans to retire at the age of sixty-two.", vi: "Bố tôi có kế hoạch nghỉ hưu ở tuổi sáu mươi hai." },
          { en: "She retired from teaching after thirty years of service.", vi: "Bà ấy đã nghỉ hưu sau ba mươi năm cống hiến cho nghề giáo." },
          { en: "He enjoys gardening now that he has retired.", vi: "Bây giờ khi đã nghỉ hưu, ông ấy thích công việc làm vườn." },
        ],
        notes: "Ngừng làm việc do đã đến độ tuổi quy định.",
      },
      {
        id: "job13",
        term: "Unemployed",
        phonetic: "/ˌʌnɪmˈplɔɪd/",
        translation: "Thất nghiệp",
        examples: [
          { en: "The factory closed down, leaving many workers unemployed.", vi: "Nhà máy đóng cửa, khiến nhiều công nhân bị thất nghiệp." },
          { en: "He has been unemployed for three months.", vi: "Anh ấy đã bị thất nghiệp được ba tháng rồi." },
          { en: "The government provides support for unemployed people.", vi: "Chính phủ cung cấp sự hỗ trợ cho những người thất nghiệp." },
        ],
        notes: "Tính từ chỉ tình trạng không có việc làm.",
      },
      {
        id: "job14",
        term: "Part-time",
        phonetic: "/ˌpɑːt ˈtaɪm/",
        translation: "Bán thời gian",
        examples: [
          { en: "Students often work part-time to pay for university.", vi: "Sinh viên thường làm việc bán thời gian để trang trải chi phí đại học." },
          { en: "She got a part-time job as a receptionist.", vi: "Cô ấy đã nhận một công việc bán thời gian làm lễ tân." },
          { en: "He works part-time, only twenty hours a week.", vi: "Anh ấy làm việc bán thời gian, chỉ hai mươi giờ một tuần." },
        ],
        notes: "Làm việc ít giờ hơn tiêu chuẩn toàn thời gian.",
      },
      {
        id: "job15",
        term: "Full-time",
        phonetic: "/ˌfʊl ˈtaɪm/",
        translation: "Toàn thời gian",
        examples: [
          { en: "She wants to find a stable full-time job.", vi: "Cô ấy muốn tìm một công việc toàn thời gian ổn định." },
          { en: "He works full-time from nine to five.", vi: "Anh ấy làm việc toàn thời gian từ chín giờ sáng đến năm giờ chiều." },
          { en: "This is a full-time position with health benefits.", vi: "Đây là một vị trí toàn thời gian có đi kèm các quyền lợi y tế." },
        ],
        notes: "Làm việc theo đúng số giờ quy định tiêu chuẩn (thường 40 giờ/tuần).",
      },
      {
        id: "job16",
        term: "Resign",
        phonetic: "/rɪˈzaɪn/",
        translation: "Từ chức, xin thôi việc",
        examples: [
          { en: "He decided to resign from his position due to stress.", vi: "Anh ấy đã quyết định từ chức khỏi vị trí của mình vì áp lực căng thẳng." },
          { en: "The manager resigned last week to start his own company.", vi: "Người quản lý đã thôi việc vào tuần trước để lập công ty riêng." },
          { en: "She gave two weeks' notice before she resigned.", vi: "Cô ấy đã thông báo trước hai tuần trước khi chính thức thôi việc." },
        ],
        notes: "Chủ động rời bỏ vị trí công việc hiện tại.",
      },
      {
        id: "job17",
        term: "Colleague",
        phonetic: "/ˈkɒliːɡ/",
        translation: "Đồng nghiệp",
        examples: [
          { en: "She enjoys working with her supportive colleagues.", vi: "Cô ấy thích làm việc với những người đồng nghiệp hỗ trợ hết mình." },
          { en: "We had lunch with some colleagues from the marketing team.", vi: "Chúng tôi đã ăn trưa với vài đồng nghiệp từ nhóm tiếp thị." },
          { en: "He is highly respected by his colleagues.", vi: "Anh ấy rất được kính trọng bởi các đồng nghiệp của mình." },
        ],
        notes: "Người làm việc cùng cơ quan, công ty. Đồng nghĩa với 'coworker'.",
      },
      {
        id: "job18",
        term: "Task",
        phonetic: "/tɑːsk/",
        translation: "Nhiệm vụ, công việc được giao",
        examples: [
          { en: "The manager assigned a difficult task to me.", vi: "Người quản lý đã giao một nhiệm vụ khó khăn cho tôi." },
          { en: "We must complete this task before the deadline.", vi: "Chúng ta phải hoàn thành công việc được giao này trước hạn chót." },
          { en: "She focused on her daily tasks at the office.", vi: "Cô ấy tập trung vào các công việc hàng ngày của mình tại văn phòng." },
        ],
        notes: "Phần việc nhỏ cần hoàn thành trong một khoảng thời gian.",
      },
      {
        id: "job19",
        term: "Promotion",
        phonetic: "/prəˈməʊʃn/",
        translation: "Sự thăng chức / Sự khuyến mãi",
        examples: [
          { en: "He is hoping to get a promotion next year.", vi: "Anh ấy đang hy vọng sẽ được thăng chức vào năm tới." },
          { en: "Her hard work led to a promotion to senior developer.", vi: "Sự làm việc chăm chỉ của cô ấy đã dẫn tới một đợt thăng chức lên nhà phát triển cao cấp." },
          { en: "The supermarket is having a special spring promotion.", vi: "Siêu thị đang có một đợt khuyến mãi đặc biệt dịp mùa xuân." },
        ],
        notes: "Sự nâng lên vị trí cao hơn trong công việc.",
      },
      {
        id: "job20",
        term: "Experience",
        phonetic: "/ɪkˈspɪəriəns/",
        translation: "Kinh nghiệm / Trải nghiệm",
        examples: [
          { en: "She has ten years of experience in customer service.", vi: "Cô ấy có mười năm kinh nghiệm trong ngành dịch vụ khách hàng." },
          { en: "They are looking for candidates with experience.", vi: "Họ đang tìm kiếm những ứng viên có kinh nghiệm." },
          { en: "Traveling around Asia was a wonderful experience.", vi: "Đi du lịch vòng quanh châu Á đã là một trải nghiệm tuyệt vời." },
        ],
        notes: "Vừa là danh từ không đếm được (kinh nghiệm làm việc), vừa là danh từ đếm được (trải nghiệm cuộc sống).",
      },
    ],
  },
  {
    id: "topic_media_e1",
    title: "Phương tiện truyền thông",
    category: "topic",
    description: "Các kênh báo chí, truyền hình, quảng cáo và phương thức giao tiếp số hóa hiện đại.",
    color: "bg-teal-700",
    words: [
      {
        id: "med1",
        term: "Media",
        phonetic: "/ˈmiːdiə/",
        translation: "Phương tiện truyền thông, giới truyền thông",
        examples: [
          { en: "The news was widely reported by the national media.", vi: "Tin tức đã được đưa tin rộng rãi bởi các phương tiện truyền thông quốc gia." },
          { en: "Social media has changed the way we communicate.", vi: "Mạng xã hội đã thay đổi cách thức chúng ta giao tiếp." },
          { en: "He works as a media consultant for a big brand.", vi: "Anh ấy làm tư vấn truyền thông cho một thương hiệu lớn." },
        ],
        notes: "Danh từ số nhiều của 'medium', nhưng thường dùng chỉ chung giới báo chí, truyền hình, mạng xã hội.",
      },
      {
        id: "med2",
        term: "News",
        phonetic: "/njuːz/",
        translation: "Tin tức, bản tin",
        examples: [
          { en: "I watch the evening news on TV every day.", vi: "Tôi xem bản tin buổi tối trên ti vi mỗi ngày." },
          { en: "That is wonderful news; congratulations!", vi: "Đó thật là một tin tức tuyệt vời; chúc mừng bạn nhé!" },
          { en: "The news about the storm spread quickly.", vi: "Tin tức về cơn bão đã lan truyền rất nhanh." },
        ],
        notes: "Danh từ không đếm được, luôn có đuôi 's' nhưng đi kèm động từ số ít.",
      },
      {
        id: "med3",
        term: "Newspaper",
        phonetic: "/ˈnjuːzpeɪpə/",
        translation: "Báo giấy, tờ báo",
        examples: [
          { en: "My grandfather reads the daily newspaper with his coffee.", vi: "Ông tôi đọc tờ báo hàng ngày bên cạnh ly cà phê của mình." },
          { en: "She works as a reporter for a local newspaper.", vi: "Cô ấy làm phóng viên cho một tờ báo địa phương." },
          { en: "We use old newspapers to clean the windows.", vi: "Chúng tôi sử dụng báo cũ để lau cửa sổ." },
        ],
        notes: "Ấn phẩm báo in bằng giấy phát hành định kỳ.",
      },
      {
        id: "med4",
        term: "Journalist",
        phonetic: "/ˈdʒɜːnəlɪst/",
        translation: "Nhà báo, người làm báo",
        examples: [
          { en: "The journalist interviewed the president yesterday.", vi: "Nhà báo đã phỏng vấn tổng thống vào ngày hôm qua." },
          { en: "She is an investigative journalist specializing in finance.", vi: "Cô ấy là một nhà báo điều tra chuyên về lĩnh vực tài chính." },
          { en: "Journalists should report stories honestly.", vi: "Các nhà báo nên đưa tin các câu chuyện một cách trung thực." },
        ],
        notes: "Người viết tin bài cho báo chí hoặc truyền hình.",
      },
      {
        id: "med5",
        term: "Article",
        phonetic: "/ˈɑːtɪkl/",
        translation: "Bài viết, bài báo / Mạo từ",
        examples: [
          { en: "He wrote an interesting article about social media.", vi: "Anh ấy đã viết một bài báo rất thú vị về mạng xã hội." },
          { en: "The front page article was about the economic growth.", vi: "Bài viết trên trang nhất là về sự tăng trưởng kinh tế." },
          { en: "In English, 'a' and 'the' are articles.", vi: "Trong tiếng Anh, 'a' và 'the' là các mạo từ." },
        ],
        notes: "Vừa có nghĩa là bài viết trên báo chí, vừa là thuật ngữ ngữ pháp (mạo từ).",
      },
      {
        id: "med6",
        term: "Channel",
        phonetic: "/ˈtʃænl/",
        translation: "Kênh truyền hình, kênh truyền thông",
        examples: [
          { en: "What channel is the football match on?", vi: "Trận đấu bóng đá đang phát sóng trên kênh nào vậy?" },
          { en: "She has a popular cooking channel on YouTube.", vi: "Cô ấy có một kênh nấu ăn rất được yêu thích trên YouTube." },
          { en: "The news channel provides twenty-four-hour updates.", vi: "Kênh tin tức cung cấp các bản cập nhật liên tục hai mươi tư giờ." },
        ],
        notes: "Băng tần truyền hình hoặc một tài khoản phát sóng nội dung.",
      },
      {
        id: "med7",
        term: "Broadcast",
        phonetic: "/ˈbrɔːdkɑːst/",
        translation: "Phát sóng, trình chiếu chương trình",
        examples: [
          { en: "The soccer match will be broadcast live tonight.", vi: "Trận bóng đá sẽ được phát sóng trực tiếp vào tối nay." },
          { en: "The radio station broadcasts classical music daily.", vi: "Đài phát thanh phát sóng nhạc cổ điển hàng ngày." },
          { en: "The broadcast was interrupted by a power failure.", vi: "Buổi phát sóng đã bị gián đoạn do mất điện." },
        ],
        notes: "Động từ bất quy tắc giữ nguyên dạng (broadcast-broadcast-broadcast) hoặc thêm '-ed'.",
      },
      {
        id: "med8",
        term: "Advertisement",
        phonetic: "/ədˈvɜːtɪsmənt/",
        translation: "Quảng cáo, mẩu quảng cáo",
        examples: [
          { en: "The magazine contains too many advertisements.", vi: "Tạp chí chứa quá nhiều mẩu quảng cáo." },
          { en: "They put an advertisement in the newspaper to sell their car.", vi: "Họ đã đăng một mẩu quảng cáo trên báo để bán xe hơi." },
          { en: "We watched an creative television advertisement.", vi: "Chúng tôi đã xem một quảng cáo truyền hình đầy sáng tạo." },
        ],
        notes: "Thường viết tắt là 'ad' hoặc 'advert'.",
      },
      {
        id: "med9",
        term: "Internet",
        phonetic: "/ˈɪntənet/",
        translation: "Mạng internet",
        examples: [
          { en: "The internet has changed the way we access information.", vi: "Mạng internet đã thay đổi cách chúng ta tiếp cận thông tin." },
          { en: "Our house has a fast internet connection.", vi: "Nhà của chúng tôi có kết nối internet rất nhanh." },
          { en: "You can find almost anything on the internet.", vi: "Bạn có thể tìm thấy hầu như mọi thứ trên mạng internet." },
        ],
        notes: "Luôn viết hoa chữ 'I' và đi kèm mạo từ 'the' ('the Internet').",
      },
      {
        id: "med10",
        term: "Website",
        phonetic: "/ˈwebsaɪt/",
        translation: "Trang web",
        examples: [
          { en: "They designed a modern website for their business.", vi: "Họ đã thiết kế một trang web hiện đại cho doanh nghiệp của mình." },
          { en: "Visit our website for more details, please.", vi: "Vui lòng truy cập trang web của chúng tôi để biết thêm chi tiết." },
          { en: "This educational website is free for students.", vi: "Trang web giáo dục này miễn phí dành cho học sinh." },
        ],
        notes: "Tập hợp các trang thông tin trên mạng internet thuộc một địa chỉ.",
      },
      {
        id: "med11",
        term: "Social media",
        phonetic: "/ˌsəʊʃl ˈmiːdiə/",
        translation: "Mạng xã hội",
        examples: [
          { en: "Young people spend several hours on social media every day.", vi: "Người trẻ dành vài giờ đồng hồ trên mạng xã hội mỗi ngày." },
          { en: "She uses social media to stay in touch with friends.", vi: "Cô ấy sử dụng mạng xã hội để giữ liên lạc với bạn bè." },
          { en: "Social media advertising is very effective.", vi: "Quảng cáo trên mạng xã hội rất hiệu quả." },
        ],
        notes: "Các nền tảng tương tác trực tuyến như Facebook, TikTok, Instagram.",
      },
      {
        id: "med12",
        term: "Audience",
        phonetic: "/ˈɔːdiəns/",
        translation: "Khán giả, thính giả (nghe/xem trực tiếp)",
        examples: [
          { en: "The audience clapped loudly after the performance.", vi: "Khán giả đã vỗ tay rầm rộ sau màn biểu diễn." },
          { en: "The film attracted a large young audience.", vi: "Bộ phim đã thu hút một lượng lớn khán giả trẻ tuổi." },
          { en: "He felt nervous speaking in front of a massive audience.", vi: "Anh ấy cảm thấy lo lắng khi phát biểu trước một khán giả khổng lồ." },
        ],
        notes: "Nhóm người xem kịch, nghe ca nhạc hoặc hội thảo trực tiếp.",
      },
      {
        id: "med13",
        term: "Program",
        phonetic: "/ˈprəʊɡræm/",
        translation: "Chương trình truyền hình / Chương trình máy tính",
        examples: [
          { en: "I watched an interesting nature program on TV.", vi: "Tôi đã xem một chương trình thiên nhiên rất thú vị trên ti vi." },
          { en: "What is your favorite television program?", vi: "Chương trình truyền hình yêu thích của bạn là gì?" },
          { en: "He is learning to write a simple computer program.", vi: "Cậu ấy đang học cách viết một chương trình máy tính đơn giản." },
        ],
        notes: "Tiếng Anh-Anh thường viết là 'programme'.",
      },
      {
        id: "med14",
        term: "Publish",
        phonetic: "/ˈpʌblɪʃ/",
        translation: "Xuất bản, đăng tải",
        examples: [
          { en: "The company will publish his new novel next month.", vi: "Công ty sẽ xuất bản cuốn tiểu thuyết mới của anh ấy vào tháng tới." },
          { en: "She publishes articles on her personal blog.", vi: "Cô ấy đăng tải các bài viết trên trang nhật ký cá nhân." },
          { en: "The report was published yesterday.", vi: "Bản báo cáo đã được công bố xuất bản vào ngày hôm qua." },
        ],
        notes: "Hành động in ấn sách báo hoặc công bố tài liệu ra công chúng.",
      },
      {
        id: "med15",
        term: "Headline",
        phonetic: "/ˈhedlaɪn/",
        translation: "Tiêu đề lớn, dòng tít (trang nhất báo chí)",
        examples: [
          { en: "The newspaper headline caught my attention immediately.", vi: "Dòng tít lớn trên tờ báo đã ngay lập tức thu hút sự chú ý của tôi." },
          { en: "The headlines were about the peace agreement.", vi: "Các dòng tít lớn đều đưa tin về thỏa thuận hòa bình." },
          { en: "I only read the headlines this morning; I didn't have time.", vi: "Sáng nay tôi chỉ đọc qua các tiêu đề lớn; tôi không có thời gian." },
        ],
        notes: "Tiêu đề in chữ lớn ở đầu trang nhất hoặc mục tin nổi bật.",
      },
      {
        id: "med16",
        term: "Information",
        phonetic: "/ˌɪnfəˈmeɪʃn/",
        translation: "Thông tin",
        examples: [
          { en: "Where can I find more information about this course?", vi: "Tôi có thể tìm thấy thêm thông tin về khóa học này ở đâu?" },
          { en: "The website provides useful information for tourists.", vi: "Trang web cung cấp những thông tin hữu ích cho khách du lịch." },
          { en: "Make sure the information is accurate before sharing.", vi: "Hãy chắc chắn rằng thông tin chính xác trước khi chia sẻ." },
        ],
        notes: "Danh từ không đếm được. Dùng 'a piece of information' nếu muốn đếm số lượng.",
      },
      {
        id: "med17",
        term: "Review",
        phonetic: "/rɪˈvjuː/",
        translation: "Bài đánh giá, nhận xét / Sự ôn tập",
        examples: [
          { en: "She wrote an excellent review of the new restaurant.", vi: "Cô ấy đã viết một bài đánh giá xuất sắc về nhà hàng mới." },
          { en: "I always read book reviews before buying them.", vi: "Tôi luôn đọc các bài nhận xét sách trước khi mua chúng." },
          { en: "We need to do a review of our lessons before the test.", vi: "Chúng ta cần ôn tập lại bài học trước kỳ thi." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "med18",
        term: "Report",
        phonetic: "/rɪˈpɔːt/",
        translation: "Bản báo cáo, tin tường thuật / Báo cáo",
        examples: [
          { en: "He prepared a detailed sales report for the meeting.", vi: "Anh ấy đã chuẩn bị một bản báo cáo doanh thu chi tiết cho cuộc họp." },
          { en: "The weather report says it will rain tomorrow.", vi: "Bản tin thời tiết báo cáo rằng trời sẽ mưa vào ngày mai." },
          { en: "Please report any suspicious behavior to the police.", vi: "Vui lòng báo cáo bất kỳ hành vi đáng ngờ nào cho cảnh sát." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "med19",
        term: "Press",
        phonetic: "/pres/",
        translation: "Giới báo chí / Nhấn, ấn nút",
        examples: [
          { en: "A crowd of press reporters waited outside the court.", vi: "Một đám đông các phóng viên báo chí đã chờ đợi bên ngoài tòa án." },
          { en: "Members of the press must show their badges.", vi: "Các thành viên của giới báo chí phải xuất trình thẻ phù hiệu." },
          { en: "Press this green button to start the machine.", vi: "Hãy nhấn nút xanh này để khởi động máy." },
        ],
        notes: "Danh từ chỉ chung giới báo chí bưu truyền thông.",
      },
      {
        id: "med20",
        term: "Communication",
        phonetic: "/kəˌmjuːnɪˈkeɪʃn/",
        translation: "Sự giao tiếp, sự truyền thông",
        examples: [
          { en: "Good communication is the key to a healthy relationship.", vi: "Giao tiếp tốt là chìa khóa cho một mối quan hệ lành mạnh." },
          { en: "The modern technology improves international communication.", vi: "Công nghệ hiện đại cải thiện sự truyền thông quốc tế." },
          { en: "She works as a communication manager for a global brand.", vi: "Cô ấy làm quản lý truyền thông cho một thương hiệu toàn cầu." },
        ],
        notes: "Danh từ không đếm được chỉ hoạt động trao đổi thông tin.",
      },
    ],
  },
];
