export const tierEmeraldIV = [
  {
    id: "topic_transport_e4",
    title: "Phương tiện giao thông",
    category: "topic",
    description: "Các phương tiện đi lại thông dụng và từ vựng liên quan đến hệ thống giao thông.",
    color: "bg-teal-500",
    words: [
      {
        id: "tr1",
        term: "Car",
        phonetic: "/kɑː/",
        translation: "Xe hơi, ô tô",
        examples: [
          { en: "My family prefers to travel by car because it is comfortable.", vi: "Gia đình tôi thích đi du lịch bằng xe hơi hơn vì nó thoải mái." },
          { en: "He washed his new car in the yard yesterday.", vi: "Hôm qua anh ấy đã rửa chiếc xe hơi mới của mình ở ngoài sân." },
          { en: "There is a parking lot for cars behind the building.", vi: "Có một bãi đỗ xe hơi ở phía sau tòa nhà." },
        ],
        notes: "Phương tiện giao thông cá nhân phổ biến.",
      },
      {
        id: "tr2",
        term: "Bus",
        phonetic: "/bʌs/",
        translation: "Xe buýt",
        examples: [
          { en: "The school bus always arrives on time.", vi: "Xe buýt của trường luôn luôn đến đúng giờ." },
          { en: "She missed the bus because she woke up late.", vi: "Cô ấy bị lỡ xe buýt vì thức dậy muộn." },
          { en: "You can catch a bus from the main station.", vi: "Bạn có thể bắt xe buýt từ nhà ga chính." },
        ],
        notes: "Phương tiện công cộng giá rẻ.",
      },
      {
        id: "tr3",
        term: "Bicycle",
        phonetic: "/ˈbaɪsɪkl/",
        translation: "Xe đạp",
        examples: [
          { en: "Riding a bicycle is good for the environment.", vi: "Đi xe đạp rất tốt cho môi trường." },
          { en: "He received a new bicycle for his birthday.", vi: "Cậu ấy đã nhận được một chiếc xe đạp mới vào dịp sinh nhật." },
          { en: "You should lock your bicycle when you leave it.", vi: "Bạn nên khóa xe đạp lại khi rời đi." },
        ],
        notes: "Có thể viết tắt là 'bike'.",
      },
      {
        id: "tr4",
        term: "Motorbike",
        phonetic: "/ˈməʊtəbaɪk/",
        translation: "Xe máy, xe mô tô",
        examples: [
          { en: "Almost everyone in Vietnam owns a motorbike.", vi: "Hầu như tất cả mọi người ở Việt Nam đều sở hữu một chiếc xe máy." },
          { en: "Please wear a helmet when you ride a motorbike.", vi: "Vui lòng đội mũ bảo hiểm khi bạn đi xe máy." },
          { en: "He bought a second-hand motorbike.", vi: "Anh ấy đã mua một chiếc xe máy cũ." },
        ],
        notes: "Cũng có thể dùng từ 'motorcycle'.",
      },
      {
        id: "tr5",
        term: "Train",
        phonetic: "/treɪn/",
        translation: "Tàu hỏa, xe lửa",
        examples: [
          { en: "We took a night train to the mountains.", vi: "Chúng tôi đã đi một chuyến tàu đêm lên vùng núi." },
          { en: "The train leaves at exactly eight o'clock.", vi: "Tàu hỏa khởi hành vào đúng tám giờ." },
          { en: "I like looking out of the window while traveling by train.", vi: "Tôi thích nhìn ra ngoài cửa sổ khi đi du lịch bằng tàu hỏa." },
        ],
        notes: "Chạy trên đường ray (railway).",
      },
      {
        id: "tr6",
        term: "Airplane",
        phonetic: "/ˈeəpleɪn/",
        translation: "Máy bay",
        examples: [
          { en: "The airplane flew high above the clouds.", vi: "Chiếc máy bay đã bay cao trên những đám mây." },
          { en: "I feel excited when the airplane takes off.", vi: "Tôi cảm thấy hào hứng khi máy bay cất cánh." },
          { en: "You need to turn off your phone on the airplane.", vi: "Bạn cần tắt điện thoại khi ở trên máy bay." },
        ],
        notes: "Có thể viết tắt là 'plane'.",
      },
      {
        id: "tr7",
        term: "Boat",
        phonetic: "/bəʊt/",
        translation: "Thuyền, tàu nhỏ",
        examples: [
          { en: "They rented a small boat to go fishing on the lake.", vi: "Họ đã thuê một chiếc thuyền nhỏ để đi câu cá trên hồ." },
          { en: "The boat slowly moved along the river.", vi: "Chiếc thuyền chậm rãi di chuyển dọc theo dòng sông." },
          { en: "We took a boat tour around the island.", vi: "Chúng tôi đã có một chuyến tham quan bằng thuyền quanh hòn đảo." },
        ],
        notes: "Thường chỉ thuyền nhỏ, di chuyển trên sông hoặc gần bờ.",
      },
      {
        id: "tr8",
        term: "Ship",
        phonetic: "/ʃɪp/",
        translation: "Tàu thủy lớn, tàu biển",
        examples: [
          { en: "The massive cargo ship arrived at the port.", vi: "Chiếc tàu chở hàng khổng lồ đã cập cảng." },
          { en: "She went on a cruise ship holiday last year.", vi: "Cô ấy đã đi nghỉ dưỡng trên một chiếc tàu du lịch vào năm ngoái." },
          { en: "A ship needs a skilled captain.", vi: "Một con tàu lớn cần một người thuyền trưởng lành nghề." },
        ],
        notes: "Tàu lớn, di chuyển trên đại dương hoặc vùng nước sâu.",
      },
      {
        id: "tr9",
        term: "Helicopter",
        phonetic: "/ˈhelɪkɒptə/",
        translation: "Máy bay trực thăng",
        examples: [
          { en: "The police helicopter searched for the lost hikers.", vi: "Trực thăng của cảnh sát đã tìm kiếm những người đi bộ bị lạc." },
          { en: "A helicopter landed on the roof of the hospital.", vi: "Một chiếc trực thăng đã hạ cánh trên mái của bệnh viện." },
          { en: "I can hear the loud sound of a helicopter.", vi: "Tôi có thể nghe thấy âm thanh lớn của một chiếc trực thăng." },
        ],
        notes: "Có cánh quạt nâng trực tiếp, cất cánh thẳng đứng.",
      },
      {
        id: "tr10",
        term: "Subway",
        phonetic: "/ˈsʌbweɪ/",
        translation: "Tàu điện ngầm",
        examples: [
          { en: "Taking the subway is the fastest way to travel in New York.", vi: "Đi tàu điện ngầm là cách nhanh nhất để di chuyển ở New York." },
          { en: "The subway station is crowded during rush hour.", vi: "Ga tàu điện ngầm rất đông đúc vào giờ cao điểm." },
          { en: "He reads a book while riding the subway.", vi: "Cậu ấy đọc một cuốn sách khi đi tàu điện ngầm." },
        ],
        notes: "Tiếng Anh-Anh thường gọi là 'the Underground' hoặc 'the Tube'.",
      },
      {
        id: "tr11",
        term: "Truck",
        phonetic: "/trʌk/",
        translation: "Xe tải",
        examples: [
          { en: "A big truck delivered the new furniture to our house.", vi: "Một chiếc xe tải lớn đã giao đồ nội thất mới đến nhà chúng tôi." },
          { en: "The truck driver was tired after a long journey.", vi: "Tài xế xe tải đã mệt mỏi sau một hành trình dài." },
          { en: "He drives a red truck for work.", vi: "Anh ấy lái một chiếc xe tải màu đỏ để phục vụ công việc." },
        ],
        notes: "Tiếng Anh-Anh thường gọi là 'lorry'.",
      },
      {
        id: "tr12",
        term: "Taxi",
        phonetic: "/ˈtæksi/",
        translation: "Xe taxi",
        examples: [
          { en: "We called a taxi because it started to rain heavily.", vi: "Chúng tôi đã gọi một chiếc taxi vì trời bắt đầu mưa lớn." },
          { en: "The taxi driver was very friendly and helpful.", vi: "Tài xế taxi rất thân thiện và nhiệt tình giúp đỡ." },
          { en: "How much is the taxi fare from the airport?", vi: "Giá cước xe taxi từ sân bay là bao nhiêu?" },
        ],
        notes: "Có thể dùng từ 'cab' tương đương.",
      },
      {
        id: "tr13",
        term: "Scooter",
        phonetic: "/ˈskuːtə/",
        translation: "Xe tay ga, xe trượt",
        examples: [
          { en: "She rides her electric scooter to the office every day.", vi: "Cô ấy lái chiếc xe trượt điện của mình đến văn phòng mỗi ngày." },
          { en: "He bought a new scooter because it is easy to park.", vi: "Anh ấy đã mua một chiếc xe tay ga mới vì nó rất dễ đỗ." },
          { en: "The child is playing with a colorful scooter.", vi: "Đứa trẻ đang chơi với một chiếc xe trượt nhiều màu sắc." },
        ],
        notes: "Vừa chỉ xe tay ga loại nhỏ vừa chỉ xe trượt hai bánh của trẻ em.",
      },
      {
        id: "tr14",
        term: "Tram",
        phonetic: "/træm/",
        translation: "Tàu điện trên đường phố",
        examples: [
          { en: "Melbourne is famous for its historic tram network.", vi: "Melbourne nổi tiếng với mạng lưới tàu điện đường phố lâu đời." },
          { en: "We waited for the tram at the street corner.", vi: "Chúng tôi đợi tàu điện ở góc đường." },
          { en: "The tram runs quietly through the city center.", vi: "Tàu điện chạy êm ái xuyên qua trung tâm thành phố." },
        ],
        notes: "Tàu chạy bằng điện chạy trên đường ray đặt ngay trên lòng đường.",
      },
      {
        id: "tr15",
        term: "Vehicle",
        phonetic: "/ˈviːəkl/",
        translation: "Phương tiện giao thông, xe cộ",
        examples: [
          { en: "Are you the owner of this white vehicle?", vi: "Bạn có phải là chủ sở hữu của chiếc phương tiện màu trắng này không?" },
          { en: "Many vehicles were stuck in the traffic jam.", vi: "Nhiều xe cộ đã bị kẹt trong đám tắc đường." },
          { en: "Electric vehicles are becoming more popular.", vi: "Các phương tiện chạy bằng điện đang ngày càng trở nên phổ biến." },
        ],
        notes: "Từ mang tính trang trọng, chỉ chung các loại xe cộ trên đường.",
      },
      {
        id: "tr16",
        term: "Ticket",
        phonetic: "/ˈtɪkɪt/",
        translation: "Vé (tàu, xe, máy bay)",
        examples: [
          { en: "You must buy a ticket before boarding the train.", vi: "Bạn phải mua vé trước khi bước lên tàu." },
          { en: "He lost his train ticket on the way to the station.", vi: "Anh ấy đã làm mất vé tàu trên đường đến ga." },
          { en: "Show your ticket to the officer, please.", vi: "Vui lòng xuất trình vé của bạn cho nhân viên." },
        ],
        notes: "Giấy chứng nhận đã thanh toán dịch vụ.",
      },
      {
        id: "tr17",
        term: "Station",
        phonetic: "/ˈsteɪʃn/",
        translation: "Nhà ga, bến xe",
        examples: [
          { en: "Meet me outside the central station at noon.", vi: "Hãy gặp tôi ở bên ngoài ga trung tâm vào buổi trưa." },
          { en: "The bus station was very crowded on Friday night.", vi: "Bến xe buýt rất đông đúc vào tối thứ Sáu." },
          { en: "Which station does this train stop at first?", vi: "Chuyến tàu này dừng lại ở ga nào đầu tiên?" },
        ],
        notes: "Nơi dừng đón trả khách của tàu hỏa hoặc xe buýt.",
      },
      {
        id: "tr18",
        term: "Driver",
        phonetic: "/ˈdraɪvə/",
        translation: "Tài xế, người lái xe",
        examples: [
          { en: "The bus driver greeted the passengers warmly.", vi: "Tài xế xe buýt đã chào đón hành khách một cách ấm áp." },
          { en: "He works as a delivery truck driver.", vi: "Anh ấy làm công việc lái xe tải giao hàng." },
          { en: "Please do not talk to the driver while the bus is moving.", vi: "Vui lòng không trò chuyện với tài xế khi xe đang di chuyển." },
        ],
        notes: "Người điều khiển phương tiện giao thông đường bộ.",
      },
      {
        id: "tr19",
        term: "Passenger",
        phonetic: "/ˈpæsɪndʒə/",
        translation: "Hành khách",
        examples: [
          { en: "The plane carries more than two hundred passengers.", vi: "Chiếc máy bay chở hơn hai trăm hành khách." },
          { en: "Passengers are waiting at the gate.", vi: "Các hành khách đang chờ ở cổng lên máy bay." },
          { en: "The driver asked the passengers to buckle up.", vi: "Tài xế đã yêu cầu hành khách thắt dây an toàn." },
        ],
        notes: "Người di chuyển trên xe nhưng không phải là người lái.",
      },
      {
        id: "tr20",
        term: "Traffic",
        phonetic: "/ˈtræfɪk/",
        translation: "Giao thông, lượng xe cộ",
        examples: [
          { en: "There is a lot of traffic on the highway today.", vi: "Hôm nay có rất nhiều xe cộ đi lại trên đường cao tốc." },
          { en: "I was late because of the heavy traffic.", vi: "Tôi đã bị muộn vì giao thông quá đông đúc." },
          { en: "We should obey the traffic rules.", vi: "Chúng ta nên tuân thủ luật lệ giao thông." },
        ],
        notes: "Danh từ không đếm được.",
      },
    ],
  },
  {
    id: "topic_city_places_e4",
    title: "Địa điểm trong thành phố",
    category: "topic",
    description: "Các tòa nhà công cộng, dịch vụ xã hội và địa điểm quen thuộc trong đô thị.",
    color: "bg-blue-500",
    words: [
      {
        id: "cp1",
        term: "Supermarket",
        phonetic: "/ˈsuːpəmɑːkɪt/",
        translation: "Siêu thị",
        examples: [
          { en: "I need to go to the supermarket to buy some groceries.", vi: "Tôi cần đi siêu thị để mua một số thực phẩm." },
          { en: "The new supermarket near my house is very big.", vi: "Siêu thị mới gần nhà tôi rất lớn." },
          { en: "They work at the checkout counter of a supermarket.", vi: "Họ làm việc tại quầy thanh toán của một siêu thị." },
        ],
        notes: "Nơi bán lẻ tự phục vụ lớn.",
      },
      {
        id: "cp2",
        term: "Hospital",
        phonetic: "/ˈhɒspɪtl/",
        translation: "Bệnh viện",
        examples: [
          { en: "He was taken to the hospital after the accident.", vi: "Anh ấy đã được đưa đến bệnh viện sau vụ tai nạn." },
          { en: "My aunt works as a nurse in a children's hospital.", vi: "Dì của tôi làm y tá trong một bệnh viện nhi." },
          { en: "There is a hospital at the end of this street.", vi: "Có một bệnh viện nằm ở cuối con phố này." },
        ],
        notes: "Nơi khám chữa bệnh chuyên sâu.",
      },
      {
        id: "cp3",
        term: "School",
        phonetic: "/skuːl/",
        translation: "Trường học",
        examples: [
          { en: "She walks to school with her friends.", vi: "Cô ấy đi bộ đến trường cùng với bạn bè của mình." },
          { en: "The primary school has a big playground.", vi: "Trường tiểu học có một sân chơi lớn." },
          { en: "I finished high school three years ago.", vi: "Tôi đã tốt nghiệp trung học phổ thông ba năm trước." },
        ],
        notes: "Nơi học sinh đến học.",
      },
      {
        id: "cp4",
        term: "Library",
        phonetic: "/ˈlaɪbrəri/",
        translation: "Thư viện",
        examples: [
          { en: "I often study in the quiet library.", vi: "Tôi thường học ở trong thư viện yên tĩnh." },
          { en: "You can borrow up to five books from the library.", vi: "Bạn có thể mượn tối đa năm cuốn sách từ thư viện." },
          { en: "The city library is closed on Mondays.", vi: "Thư viện thành phố đóng cửa vào các ngày thứ Hai." },
        ],
        notes: "Nơi lưu trữ sách báo để mượn hoặc đọc tại chỗ.",
      },
      {
        id: "cp5",
        term: "Park",
        phonetic: "/pɑːk/",
        translation: "Công viên",
        examples: [
          { en: "Children are playing football in the park.", vi: "Trẻ em đang chơi bóng đá trong công viên." },
          { en: "The park in the city center is beautiful.", vi: "Công viên ở trung tâm thành phố rất đẹp." },
          { en: "We often go for a jog in the park.", vi: "Chúng tôi thường đi chạy bộ trong công viên." },
        ],
        notes: "Khu vực cây xanh công cộng để vui chơi, thư giãn.",
      },
      {
        id: "cp6",
        term: "Restaurant",
        phonetic: "/ˈrestrɒnt/",
        translation: "Nhà hàng",
        examples: [
          { en: "We had dinner at an expensive restaurant last night.", vi: "Tối qua chúng tôi đã ăn tối tại một nhà hàng đắt đỏ." },
          { en: "This restaurant is famous for its Italian food.", vi: "Nhà hàng này nổi tiếng với các món ăn Ý." },
          { en: "He works as a chef in a French restaurant.", vi: "Anh ấy làm đầu bếp trong một nhà hàng Pháp." },
        ],
        notes: "Nơi bán món ăn chế biến sẵn cho khách ăn tại chỗ.",
      },
      {
        id: "cp7",
        term: "Cinema",
        phonetic: "/ˈsɪnəmə/",
        translation: "Rạp chiếu phim",
        examples: [
          { en: "Let's go to the cinema to watch the new action movie.", vi: "Hãy cùng đến rạp chiếu phim để xem bộ phim hành động mới đi." },
          { en: "I like buying popcorn at the cinema.", vi: "Tôi thích mua bỏng ngô ở rạp chiếu phim." },
          { en: "The cinema was completely full on Friday night.", vi: "Rạp chiếu phim đã hoàn toàn kín chỗ vào tối thứ Sáu." },
        ],
        notes: "Tiếng Anh-Mỹ thường dùng 'movie theater'.",
      },
      {
        id: "cp8",
        term: "Museum",
        phonetic: "/mjuˈziːəm/",
        translation: "Bảo tàng",
        examples: [
          { en: "The history museum has many old artifacts.", vi: "Bảo tàng lịch sử có nhiều cổ vật lâu đời." },
          { en: "We visited the science museum during our field trip.", vi: "Chúng tôi đã tham quan bảo tàng khoa học trong chuyến đi thực tế." },
          { en: "Entry to the local museum is free on weekends.", vi: "Vé vào cửa bảo tàng địa phương được miễn phí vào cuối tuần." },
        ],
        notes: "Nơi trưng bày các tác phẩm nghệ thuật, lịch sử hoặc khoa học.",
      },
      {
        id: "cp9",
        term: "Bank",
        phonetic: "/bæŋk/",
        translation: "Ngân hàng",
        examples: [
          { en: "I need to go to the bank to open an account.", vi: "Tôi cần đến ngân hàng để mở một tài khoản." },
          { en: "She works as a cashier at a big bank.", vi: "Cô ấy làm thu ngân tại một ngân hàng lớn." },
          { en: "There is an ATM outside the bank.", vi: "Có một máy rút tiền tự động ATM ở bên ngoài ngân hàng." },
        ],
        notes: "Tổ chức tài chính để gửi tiền, vay tiền.",
      },
      {
        id: "cp10",
        term: "Post office",
        phonetic: "/ˈpəʊst ɒfɪs/",
        translation: "Bưu điện",
        examples: [
          { en: "She went to the post office to send a letter.", vi: "Cô ấy đã đến bưu điện để gửi một bức thư." },
          { en: "Can you buy some stamps at the post office?", vi: "Bạn có thể mua một vài con tem ở bưu điện được không?" },
          { en: "The post office is near the bus station.", vi: "Bưu điện nằm ở gần bến xe buýt." },
        ],
        notes: "Nơi gửi thư từ, bưu phẩm.",
      },
      {
        id: "cp11",
        term: "Police station",
        phonetic: "/pəˈliːs ˈsteɪʃn/",
        translation: "Đồn cảnh sát",
        examples: [
          { en: "He reported his lost wallet at the police station.", vi: "Anh ấy đã báo cáo về việc mất ví tại đồn cảnh sát." },
          { en: "The police station is open twenty-four hours a day.", vi: "Đồn cảnh sát mở cửa hai mươi tư giờ một ngày." },
          { en: "We saw several police cars outside the station.", vi: "Chúng tôi đã nhìn thấy vài chiếc xe cảnh sát bên ngoài đồn." },
        ],
        notes: "Trụ sở làm việc của lực lượng cảnh sát địa phương.",
      },
      {
        id: "cp12",
        term: "Bakery",
        phonetic: "/ˈbeɪkəri/",
        translation: "Tiệm bánh, lò bánh mì",
        examples: [
          { en: "The bakery smells of warm fresh bread.", vi: "Tiệm bánh tỏa ra mùi bánh mì ấm nóng tươi ngon." },
          { en: "She bought some cakes from the bakery.", vi: "Cô ấy đã mua vài chiếc bánh ngọt ở tiệm bánh." },
          { en: "I work part-time at the local bakery.", vi: "Tôi làm việc bán thời gian tại tiệm bánh địa phương." },
        ],
        notes: "Nơi làm và bán các loại bánh ngọt, bánh mì.",
      },
      {
        id: "cp13",
        term: "Pharmacy",
        phonetic: "/ˈfɑːməsi/",
        translation: "Nhà thuốc, tiệm thuốc",
        examples: [
          { en: "You can buy aspirin at the pharmacy.", vi: "Bạn có thể mua aspirin ở nhà thuốc." },
          { en: "The pharmacist recommended a medicine for my cough.", vi: "Dược sĩ đã khuyên dùng một loại thuốc trị ho cho tôi." },
          { en: "Is there a pharmacy open late near here?", vi: "Có nhà thuốc nào mở cửa muộn ở gần đây không?" },
        ],
        notes: "Tiếng Anh-Mỹ thường dùng 'drugstore', tiếng Anh-Anh dùng 'chemist's'.",
      },
      {
        id: "cp14",
        term: "Cafe",
        phonetic: "/ˈkæfeɪ/",
        translation: "Quán cà phê, quán nước",
        examples: [
          { en: "We met our friends at a small cafe.", vi: "Chúng tôi đã gặp bạn bè của mình tại một quán cà phê nhỏ." },
          { en: "The cafe has free Wi-Fi and comfortable seats.", vi: "Quán nước có kết nối Wi-Fi miễn phí và ghế ngồi thoải mái." },
          { en: "She ordered a slice of cake and a hot latte at the cafe.", vi: "Cô ấy gọi một lát bánh ngọt và một ly latte nóng tại quán." },
        ],
        notes: "Nơi bán đồ uống và đồ ăn nhẹ.",
      },
      {
        id: "cp15",
        term: "Hotel",
        phonetic: "/həʊˈtel/",
        translation: "Khách sạn",
        examples: [
          { en: "We booked a room at a five-star hotel near the beach.", vi: "Chúng tôi đã đặt một phòng tại khách sạn năm sao gần bãi biển." },
          { en: "The hotel receptionist was very polite.", vi: "Nhân viên lễ tân khách sạn rất lịch sự." },
          { en: "Our hotel offers free breakfast for guests.", vi: "Khách sạn của chúng tôi cung cấp bữa sáng miễn phí cho khách lưu trú." },
        ],
        notes: "Dịch vụ lưu trú có trả phí ngắn hạn.",
      },
      {
        id: "cp16",
        term: "Church",
        phonetic: "/tʃɜːtʃ/",
        translation: "Nhà thờ (Công giáo/Tin lành)",
        examples: [
          { en: "The historic church has beautiful glass windows.", vi: "Nhà thờ cổ kính có những ô cửa sổ bằng kính rất đẹp." },
          { en: "My family goes to church every Sunday morning.", vi: "Gia đình tôi đi nhà thờ vào mỗi sáng Chủ Nhật." },
          { en: "The church bells rang at noon.", vi: "Chuông nhà thờ đã vang lên vào buổi trưa." },
        ],
        notes: "Nơi thờ phụng và tiến hành nghi lễ tôn giáo của đạo Kitô.",
      },
      {
        id: "cp17",
        term: "Zoo",
        phonetic: "/zuː/",
        translation: "Sở thú, vườn bách thú",
        examples: [
          { en: "Children love seeing wild animals at the zoo.", vi: "Trẻ em rất thích ngắm nhìn các động vật hoang dã ở sở thú." },
          { en: "The city zoo has a new family of giraffes.", vi: "Sở thú thành phố mới có một gia đình hươu cao cổ mới." },
          { en: "Please do not feed the animals at the zoo.", vi: "Vui lòng không cho động vật ở sở thú ăn." },
        ],
        notes: "Nơi nuôi dưỡng và trưng bày động vật để công chúng tham quan.",
      },
      {
        id: "cp18",
        term: "Stadium",
        phonetic: "/ˈsteɪdiəm/",
        translation: "Sân vận động",
        examples: [
          { en: "The national stadium can hold fifty thousand people.", vi: "Sân vận động quốc gia có thể chứa được năm mươi nghìn người." },
          { en: "We watched a live football match at the stadium.", vi: "Chúng tôi đã xem một trận bóng đá trực tiếp tại sân vận động." },
          { en: "The rock concert was held at the stadium.", vi: "Buổi hòa nhạc rock đã được tổ chức tại sân vận động." },
        ],
        notes: "Khu vực rộng lớn có khán đài cho người xem thể thao hoặc sự kiện.",
      },
      {
        id: "cp19",
        term: "Market",
        phonetic: "/ˈmɑːkɪt/",
        translation: "Chợ",
        examples: [
          { en: "My mother buys fresh fish at the local market.", vi: "Mẹ tôi mua cá tươi ở chợ địa phương." },
          { en: "The outdoor market is very crowded on weekends.", vi: "Khu chợ ngoài trời rất đông đúc vào dịp cuối tuần." },
          { en: "You can find many traditional foods at the market.", vi: "Bạn có thể tìm thấy nhiều món ăn truyền thống tại chợ." },
        ],
        notes: "Nơi mua bán trực tiếp của tiểu thương.",
      },
      {
        id: "cp20",
        term: "Gym",
        phonetic: "/dʒɪm/",
        translation: "Phòng tập thể dục, phòng gym",
        examples: [
          { en: "He goes to the gym three times a week to lift weights.", vi: "Anh ấy đến phòng tập thể dục ba lần một tuần để nâng tạ." },
          { en: "The new gym has modern training equipment.", vi: "Phòng gym mới có các thiết bị tập luyện hiện đại." },
          { en: "I decided to join the gym to improve my health.", vi: "Tôi đã quyết định tham gia phòng tập thể dục để cải thiện sức khỏe." },
        ],
        notes: "Nơi tập luyện nâng cao thể chất.",
      },
    ],
  },
  {
    id: "topic_hobbies_e4",
    title: "Sở thích & Giải trí",
    category: "topic",
    description: "Từ vựng về các thói quen cá nhân, hoạt động giải trí và nghệ thuật phổ biến.",
    color: "bg-yellow-500",
    words: [
      {
        id: "hb1",
        term: "Hobby",
        phonetic: "/ˈhɒbi/",
        translation: "Sở thích",
        examples: [
          { en: "My favorite hobby is reading history books.", vi: "Sở thích yêu thích của tôi là đọc sách lịch sử." },
          { en: "He has many hobbies, such as swimming and painting.", vi: "Anh ấy có nhiều sở thích, chẳng hạn như bơi lội và vẽ tranh." },
          { en: "Do you have any interesting hobbies?", vi: "Bạn có sở thích nào thú vị không?" },
        ],
        notes: "Hoạt động làm để giải trí vào lúc rảnh rỗi. Số nhiều là 'hobbies'.",
      },
      {
        id: "hb2",
        term: "Music",
        phonetic: "/ˈmjuːzɪk/",
        translation: "Âm nhạc",
        examples: [
          { en: "Listening to classical music helps me study better.", vi: "Nghe nhạc cổ điển giúp tôi học bài tốt hơn." },
          { en: "She wants to study music at university.", vi: "Cô ấy muốn học ngành âm nhạc tại trường đại học." },
          { en: "They are playing live music at the cafe.", vi: "Họ đang chơi nhạc sống tại quán cà phê." },
        ],
        notes: "Danh từ không đếm được.",
      },
      {
        id: "hb3",
        term: "Photography",
        phonetic: "/fəˈtɒɡrəfi/",
        translation: "Nhiếp ảnh, bộ môn chụp ảnh",
        examples: [
          { en: "Photography is a very expensive hobby.", vi: "Nhiếp ảnh là một sở thích rất đắt đỏ." },
          { en: "He learned photography by watching online tutorials.", vi: "Cậu ấy đã học bộ môn chụp ảnh bằng cách xem các bài hướng dẫn trực tuyến." },
          { en: "She bought a digital camera to practice photography.", vi: "Cô ấy đã mua một chiếc máy ảnh kỹ thuật số để luyện tập nhiếp ảnh." },
        ],
        notes: "Danh từ không đếm được. Người chụp ảnh là 'photographer'.",
      },
      {
        id: "hb4",
        term: "Painting",
        phonetic: "/ˈpeɪntɪŋ/",
        translation: "Vẽ tranh, hội họa",
        examples: [
          { en: "Painting helps her express her feelings.", vi: "Vẽ tranh giúp cô ấy bày tỏ cảm xúc của mình." },
          { en: "We attended a painting class last night.", vi: "Chúng tôi đã tham gia một lớp học vẽ vào tối qua." },
          { en: "He is very good at oil painting.", vi: "Cậu ấy vẽ tranh sơn dầu rất giỏi." },
        ],
        notes: "Vừa chỉ hoạt động vẽ tranh vừa chỉ bức tranh vẽ bằng màu.",
      },
      {
        id: "hb5",
        term: "Gardening",
        phonetic: "/ˈɡɑːdnɪŋ/",
        translation: "Làm vườn",
        examples: [
          { en: "My parents enjoy gardening on sunny weekends.", vi: "Bố mẹ tôi thích làm vườn vào những ngày cuối tuần đầy nắng." },
          { en: "Gardening is a relaxing activity.", vi: "Làm vườn là một hoạt động thư giãn." },
          { en: "She spent all afternoon doing gardening.", vi: "Cô ấy đã dành cả buổi chiều để làm vườn." },
        ],
        notes: "Hoạt động chăm sóc cây cối, hoa quả trong vườn.",
      },
      {
        id: "hb6",
        term: "Cooking",
        phonetic: "/ˈkʊkɪŋ/",
        translation: "Nấu ăn, việc bếp núc",
        examples: [
          { en: "My sister is excellent at baking and cooking.", vi: "Em gái tôi nấu ăn và làm bánh rất xuất sắc." },
          { en: "He considers cooking a great way to relieve stress.", vi: "Cậu ấy coi nấu ăn là một cách tuyệt vời để giải tỏa căng thẳng." },
          { en: "I learned cooking from my mother.", vi: "Tôi đã học nấu ăn từ mẹ của mình." },
        ],
        notes: "Danh từ không đếm được.",
      },
      {
        id: "hb7",
        term: "Reading",
        phonetic: "/ˈriːdɪŋ/",
        translation: "Đọc sách, việc đọc",
        examples: [
          { en: "Reading helps expand your vocabulary.", vi: "Đọc sách giúp mở rộng vốn từ vựng của bạn." },
          { en: "She spends her free time reading novels.", vi: "Cô ấy dành thời gian rảnh rỗi để đọc tiểu thuyết." },
          { en: "He developed a love for reading at a young age.", vi: "Cậu ấy đã xây dựng tình yêu với việc đọc sách từ khi còn nhỏ." },
        ],
        notes: "Kỹ năng hoặc thói quen đọc chữ.",
      },
      {
        id: "hb8",
        term: "Camping",
        phonetic: "/ˈkæmpɪŋ/",
        translation: "Cắm trại, đi dã ngoại",
        examples: [
          { en: "We go camping in the forest every summer.", vi: "Chúng tôi đi cắm trại ở trong rừng mỗi mùa hè." },
          { en: "He bought a new tent for our camping trip.", vi: "Anh ấy đã mua một chiếc lều mới cho chuyến đi cắm trại của chúng tôi." },
          { en: "Do you prefer camping or staying at a hotel?", vi: "Bạn thích đi cắm trại hay ở khách sạn hơn?" },
        ],
        notes: "Hoạt động dựng lều sinh hoạt ngoài trời.",
      },
      {
        id: "hb9",
        term: "Fishing",
        phonetic: "/ˈfɪʃɪŋ/",
        translation: "Câu cá",
        examples: [
          { en: "My uncle goes fishing near the river every morning.", vi: "Chú tôi đi câu cá ở gần sông vào mỗi buổi sáng." },
          { en: "He caught a very big fish while fishing.", vi: "Cậu ấy đã bắt được một con cá rất lớn khi đi câu." },
          { en: "Fishing requires a lot of patience.", vi: "Câu cá đòi hỏi rất nhiều sự kiên nhẫn." },
        ],
        notes: "Hoạt động săn bắt cá bằng cần câu hoặc lưới.",
      },
      {
        id: "hb10",
        term: "Dancing",
        phonetic: "/ˈdɑːnsɪŋ/",
        translation: "Nhảy múa, khiêu vũ",
        examples: [
          { en: "She takes dancing lessons once a week.", vi: "Cô ấy tham gia các bài học nhảy múa một lần một tuần." },
          { en: "They are dancing to their favorite song.", vi: "Họ đang nhảy múa theo bài hát yêu thích của mình." },
          { en: "He is very good at traditional dancing.", vi: "Anh ấy nhảy múa các điệu nhảy truyền thống rất giỏi." },
        ],
        notes: "Hoạt động di chuyển cơ thể theo nhạc nhịp điệu.",
      },
      {
        id: "hb11",
        term: "Swimming",
        phonetic: "/ˈswɪmɪŋ/",
        translation: "Bơi lội",
        examples: [
          { en: "Swimming is a great exercise for your whole body.", vi: "Bơi lội là một bài tập tuyệt vời cho toàn bộ cơ thể của bạn." },
          { en: "We went swimming in the sea yesterday.", vi: "Hôm qua chúng tôi đã đi bơi ở biển." },
          { en: "She won a gold medal in swimming.", vi: "Cô ấy đã giành được huy chương vàng môn bơi lội." },
        ],
        notes: "Môn thể thao hoặc hoạt động di chuyển dưới nước.",
      },
      {
        id: "hb12",
        term: "Travel",
        phonetic: "/ˈtrævl/",
        translation: "Du lịch, đi lại",
        examples: [
          { en: "She loves to travel to foreign countries.", vi: "Cô ấy thích đi du lịch đến các quốc gia nước ngoài." },
          { en: "Air travel has become much cheaper.", vi: "Du lịch bằng đường hàng không đã trở nên rẻ hơn nhiều." },
          { en: "I want to travel around the world.", vi: "Tôi muốn đi du lịch vòng quanh thế giới." },
        ],
        notes: "Vừa là động từ vừa là danh từ không đếm được.",
      },
      {
        id: "hb13",
        term: "Shopping",
        phonetic: "/ˈʃɒpɪŋ/",
        translation: "Mua sắm",
        examples: [
          { en: "She went shopping for some new clothes.", vi: "Cô ấy đã đi mua sắm một số quần áo mới." },
          { en: "I dislike doing the weekly food shopping.", vi: "Tôi không thích việc đi mua sắm thực phẩm hàng tuần." },
          { en: "The shopping mall is crowded with people.", vi: "Trung tâm mua sắm đông đúc người qua lại." },
        ],
        notes: "Thường đi kèm động từ 'go' thành 'go shopping'.",
      },
      {
        id: "hb14",
        term: "Video game",
        phonetic: "/ˈvɪdiəʊ ɡeɪm/",
        translation: "Trò chơi điện tử",
        examples: [
          { en: "Playing video games for too long can hurt your eyes.", vi: "Chơi trò chơi điện tử quá lâu có thể làm đau mắt bạn." },
          { en: "My brother bought a new video game console.", vi: "Em trai tôi đã mua một chiếc máy chơi game điện tử mới." },
          { en: "They are playing a multiplayer video game online.", vi: "Họ đang chơi một trò chơi điện tử nhiều người chơi trực tuyến." },
        ],
        notes: "Trò chơi tương tác trên màn hình điện tử.",
      },
      {
        id: "hb15",
        term: "Sport",
        phonetic: "/spɔːt/",
        translation: "Thể thao, môn thể thao",
        examples: [
          { en: "What is your favorite sport?", vi: "Môn thể thao yêu thích của bạn là gì?" },
          { en: "Playing sports keeps us active and healthy.", vi: "Chơi các môn thể thao giúp chúng ta năng động và khỏe mạnh." },
          { en: "Football is the most popular sport in the world.", vi: "Bóng đá là môn thể thao phổ biến nhất trên thế giới." },
        ],
        notes: "Hoạt động rèn luyện thể chất có quy tắc.",
      },
      {
        id: "hb16",
        term: "Movie",
        phonetic: "/ˈmuːvi/",
        translation: "Bộ phim, phim ảnh",
        examples: [
          { en: "We watched an exciting action movie last night.", vi: "Tối qua chúng tôi đã xem một bộ phim hành động rất thú vị." },
          { en: "Do you prefer comedies or horror movies?", vi: "Bạn thích phim hài hay phim kinh dị hơn?" },
          { en: "He writes reviews for new movies.", vi: "Anh ấy viết các bài đánh giá cho các bộ phim mới." },
        ],
        notes: "Từ đồng nghĩa thông dụng là 'film'.",
      },
      {
        id: "hb17",
        term: "Instrument",
        phonetic: "/ˈɪnstrəmənt/",
        translation: "Nhạc cụ",
        examples: [
          { en: "Can you play any musical instruments?", vi: "Bạn có thể chơi bất kỳ loại nhạc cụ nào không?" },
          { en: "The piano is a very beautiful instrument.", vi: "Đàn dương cầm là một loại nhạc cụ rất đẹp." },
          { en: "He is learning to play a string instrument.", vi: "Cậu ấy đang học chơi một loại nhạc cụ dây." },
        ],
        notes: "Vừa có nghĩa là nhạc cụ (musical instrument) vừa có nghĩa là công cụ khoa học/kỹ thuật.",
      },
      {
        id: "hb18",
        term: "Concert",
        phonetic: "/ˈkɒnsət/",
        translation: "Buổi hòa nhạc, buổi biểu diễn",
        examples: [
          { en: "We bought tickets for the pop star's concert.", vi: "Chúng tôi đã mua vé xem buổi biểu diễn của ngôi sao nhạc pop." },
          { en: "The concert was held in a massive park.", vi: "Buổi hòa nhạc đã được tổ chức tại một công viên khổng lồ." },
          { en: "He played the violin at the school concert.", vi: "Cậu ấy đã chơi đàn vĩ cầm tại buổi hòa nhạc của trường học." },
        ],
        notes: "Sự kiện biểu diễn âm nhạc trước đám đông.",
      },
      {
        id: "hb19",
        term: "Collector",
        phonetic: "/kəˈlektə/",
        translation: "Người sưu tầm",
        examples: [
          { en: "My grandfather is a famous coin collector.", vi: "Ông tôi là một người sưu tầm tiền xu nổi tiếng." },
          { en: "She is an art collector with many rare paintings.", vi: "Bà ấy là một nhà sưu tầm nghệ thuật sở hữu nhiều bức tranh quý hiếm." },
          { en: "He has been a stamp collector since childhood.", vi: "Anh ấy đã là một người sưu tầm tem từ thời thơ ấu." },
        ],
        notes: "Người có sở thích thu thập các vật phẩm đặc biệt.",
      },
      {
        id: "hb20",
        term: "Relax",
        phonetic: "/rɪˈlæks/",
        translation: "Thư giãn, nghỉ ngơi",
        examples: [
          { en: "I like to relax with a cup of hot tea after work.", vi: "Tôi thích thư giãn với một tách trà nóng sau giờ làm việc." },
          { en: "Listening to the sound of rain helps me relax.", vi: "Nghe tiếng mưa rơi giúp tôi thư giãn." },
          { en: "We need to relax during the weekend.", vi: "Chúng ta cần nghỉ ngơi trong dịp cuối tuần." },
        ],
        notes: "Động từ, trái nghĩa là 'stress' (căng thẳng).",
      },
    ],
  },
];
