export const tierEliteV = [
  {
    id: "topic_education_ta5",
    title: "Giáo dục & Trường học",
    category: "topic",
    description: "Các thuật ngữ học thuật, quy trình tuyển sinh, chương trình đào tạo và đời sống sinh viên.",
    color: "bg-indigo-600",
    words: [
      {
        id: "edu1",
        term: "Academic",
        phonetic: "/ˌækəˈdemɪk/",
        translation: "Thuộc học thuật, thuộc trường đại học",
        examples: [
          { en: "The university has high academic standards for admission.", vi: "Trường đại học có các tiêu chuẩn học thuật rất cao cho việc tuyển sinh." },
          { en: "He won an award for his outstanding academic achievements.", vi: "Anh ấy đã giành được một giải thưởng cho những thành tích học tập xuất sắc của mình." },
          { en: "We need to focus on academic research rather than theory.", vi: "Chúng ta cần tập trung vào nghiên cứu học thuật hơn là lý thuyết suông." },
        ],
        notes: "Tính từ chỉ những gì liên quan đến việc học tập, nghiên cứu chính quy.",
      },
      {
        id: "edu2",
        term: "Curriculum",
        phonetic: "/kəˈrɪkjələm/",
        translation: "Chương trình học, khung giáo trình",
        examples: [
          { en: "The school curriculum includes several foreign languages.", vi: "Chương trình học của trường bao gồm một vài ngôn ngữ nước ngoài." },
          { en: "They are designing a new IT curriculum for primary students.", vi: "Họ đang thiết kế một khung giáo trình công nghệ thông tin mới cho học sinh tiểu học." },
          { en: "The university curriculum needs constant updates to match the job market.", vi: "Chương trình đào tạo đại học cần được cập nhật liên tục để phù hợp với thị trường việc làm." },
        ],
        notes: "Toàn bộ nội dung học tập được thiết kế cho một khóa học. Số nhiều là 'curricula'.",
      },
      {
        id: "edu3",
        term: "Subject",
        phonetic: "/ˈsʌbdʒɪkt/",
        translation: "Môn học / Chủ đề, chủ ngữ",
        examples: [
          { en: "Math is my favorite subject because I like solving problems.", vi: "Toán là môn học yêu thích của tôi vì tôi thích giải quyết các bài toán." },
          { en: "The professor lectured on a very controversial subject.", vi: "Giáo sư đã thuyết giảng về một chủ đề gây rất nhiều tranh cãi." },
          { en: "They are studying several science subjects this semester.", vi: "Họ đang học một vài môn khoa học trong học kỳ này." },
        ],
        notes: "Chỉ môn học hoặc đề tài thảo luận.",
      },
      {
        id: "edu4",
        term: "Degree",
        phonetic: "/dɪˈɡriː/",
        translation: "Bằng cấp (sau đại học) / Độ (nhiệt độ/góc)",
        examples: [
          { en: "She obtained a bachelor's degree in business administration.", vi: "Cô ấy đã lấy được bằng cử nhân quản trị kinh doanh." },
          { en: "A master's degree can help improve your job opportunities.", vi: "Bằng thạc sĩ có thể giúp cải thiện cơ hội việc làm của bạn." },
          { en: "The water temperature was forty degrees Celsius.", vi: "Nhiệt độ nước đã ở mức bốn mươi độ C." },
        ],
        notes: "Bằng cấp đại học chính quy (bachelor's, master's, doctor's degree).",
      },
      {
        id: "edu5",
        term: "Assignment",
        phonetic: "/əˈsaɪnmənt/",
        translation: "Bài tập lớn, nhiệm vụ được giao",
        examples: [
          { en: "We must submit the history assignment before Friday afternoon.", vi: "Chúng ta phải nộp bài tập lịch sử trước chiều thứ Sáu." },
          { en: "The teacher gave us a difficult written assignment.", vi: "Giáo viên đã giao cho chúng tôi một bài tập viết rất khó khăn." },
          { en: "He is busy completing a project assignment for work.", vi: "Anh ấy đang bận hoàn thành một nhiệm vụ dự án được giao cho công việc." },
        ],
        notes: "Phần việc hoặc bài tập lớn được giao để hoàn thành.",
      },
      {
        id: "edu6",
        term: "Graduate",
        phonetic: "/ˈɡrædʒueɪt/",
        translation: "Tốt nghiệp / Người đã tốt nghiệp",
        examples: [
          { en: "She graduated from Harvard University last year.", vi: "Cô ấy đã tốt nghiệp Đại học Harvard vào năm ngoái." },
          { en: "The company is looking to hire fresh graduates.", vi: "Công ty đang tìm kiếm để thuê những sinh viên mới tốt nghiệp." },
          { en: "He plans to go to graduate school to study science.", vi: "Cậu ấy có kế hoạch học lên cao học để nghiên cứu khoa học." },
        ],
        notes: "Vừa là động từ (tốt nghiệp) vừa là danh từ (người tốt nghiệp).",
      },
      {
        id: "edu7",
        term: "Scholarship",
        phonetic: "/ˈskɒləʃɪp/",
        translation: "Học bổng",
        examples: [
          { en: "He won a full scholarship to study in the United Kingdom.", vi: "Cậu ấy đã giành được một học bổng toàn phần để đi học tại Vương quốc Anh." },
          { en: "She applied for a research scholarship last month.", vi: "Cô ấy đã nộp đơn xin một suất học bổng nghiên cứu vào tháng trước." },
          { en: "Scholarships are usually awarded based on academic merit.", vi: "Học bổng thường được trao dựa trên thành tích học tập xuất sắc." },
        ],
        notes: "Khoản hỗ trợ tài chính cho sinh viên học tập.",
      },
      {
        id: "edu8",
        term: "Lecture",
        phonetic: "/ˈlektʃə/",
        translation: "Bài thuyết giảng, bài giảng đại học",
        examples: [
          { en: "The professor gave an interesting lecture on modern history.", vi: "Giáo sư đã đưa ra một bài thuyết giảng rất thú vị về lịch sử hiện đại." },
          { en: "I missed the morning lecture because of the rain.", vi: "Tôi đã bị lỡ bài giảng buổi sáng vì trời mưa." },
          { en: "Students took notes during the geology lecture.", vi: "Sinh viên đã ghi chép trong suốt bài giảng địa chất." },
        ],
        notes: "Bài giảng mang tính học thuật trước đám đông, thường ở bậc đại học.",
      },
      {
        id: "edu9",
        term: "Tuition fee",
        phonetic: "/tjuˈɪʃn fiː/",
        translation: "Học phí",
        examples: [
          { en: "Tuition fees have increased significantly over the past five years.", vi: "Học phí đã tăng lên đáng kể trong vòng năm năm qua." },
          { en: "He works a part-time job to pay his tuition fees.", vi: "Cậu ấy làm một công việc bán thời gian để đóng học phí." },
          { en: "The university offers a discount on tuition fees for siblings.", vi: "Trường đại học cung cấp một đợt giảm học phí cho anh chị em ruột cùng học." },
        ],
        notes: "Khoản tiền trả cho việc giảng dạy tại trường học.",
      },
      {
        id: "edu10",
        term: "Certificate",
        phonetic: "/səˈtɪfɪkət/",
        translation: "Chứng chỉ, giấy chứng nhận",
        examples: [
          { en: "You will receive a certificate after completing the training course.", vi: "Bạn sẽ nhận được một giấy chứng nhận sau khi hoàn thành khóa đào tạo." },
          { en: "He gained an English certificate with a high score.", vi: "Anh ấy đã đạt được một chứng chỉ tiếng Anh với điểm số cao." },
          { en: "A birth certificate is a necessary legal document.", vi: "Giấy khai sinh là một tài liệu pháp lý cần thiết." },
        ],
        notes: "Văn bản chính thức chứng nhận sự thật hoặc hoàn thành khóa học ngắn hạn.",
      },
      {
        id: "edu11",
        term: "Professor",
        phonetic: "/prəˈfesə/",
        translation: "Giáo sư",
        examples: [
          { en: "The chemistry professor explained the reaction clearly.", vi: "Giáo sư hóa học đã giải thích phản ứng một cách rõ ràng." },
          { en: "He is an assistant professor at the state university.", vi: "Anh ấy là một phó giáo sư tại trường đại học bang." },
          { en: "Professor Smith is writing a book on economics.", vi: "Giáo sư Smith đang viết một cuốn sách về kinh tế học." },
        ],
        notes: "Giảng viên có học hàm cao nhất tại các trường đại học.",
      },
      {
        id: "edu12",
        term: "Campus",
        phonetic: "/ˈkæmpəs/",
        translation: "Khuôn viên trường học (đại học)",
        examples: [
          { en: "The university campus has a modern library and a sports center.", vi: "Khuôn viên trường đại học có một thư viện hiện đại và một trung tâm thể thao." },
          { en: "Students love gathering on the green campus during breaks.", vi: "Sinh viên thích tụ tập trên khuôn viên xanh mát của trường trong giờ nghỉ." },
          { en: "He lives in a dormitory on the university campus.", vi: "Cậu ấy sống trong ký túc xá nằm ngay trong khuôn viên trường đại học." },
        ],
        notes: "Toàn bộ khu đất và các tòa nhà thuộc một trường đại học.",
      },
      {
        id: "edu13",
        term: "Major",
        phonetic: "/ˈmeɪdʒə/",
        translation: "Chuyên ngành / Chính, chủ yếu",
        examples: [
          { en: "My major is computer science, but I also study business.", vi: "Chuyên ngành của tôi là khoa học máy tính, nhưng tôi cũng học thêm về kinh doanh." },
          { en: "He decided to major in English literature.", vi: "Cậu ấy đã quyết định chọn chuyên ngành văn học Anh." },
          { en: "The budget cuts are a major problem for the school.", vi: "Việc cắt giảm ngân sách là một vấn đề chính yếu đối với trường học." },
        ],
        notes: "Vừa là danh từ (chuyên ngành đại học) vừa là tính từ (chính, quan trọng).",
      },
      {
        id: "edu14",
        term: "Semester",
        phonetic: "/sɪˈmestə/",
        translation: "Học kỳ (thường là 6 tháng)",
        examples: [
          { en: "The autumn semester starts in September.", vi: "Học kỳ mùa thu bắt đầu vào tháng Chín." },
          { en: "She got excellent grades last semester.", vi: "Cô ấy đã đạt điểm số xuất sắc vào học kỳ trước." },
          { en: "We have three exams at the end of this semester.", vi: "Chúng tôi có ba kỳ thi vào cuối học kỳ này." },
        ],
        notes: "Một trong hai kỳ học chính của năm học.",
      },
      {
        id: "edu15",
        term: "Research",
        phonetic: "/rɪˈsɜːtʃ/",
        translation: "Nghiên cứu / Tiến hành nghiên cứu",
        examples: [
          { en: "She is doing scientific research on cancer treatment.", vi: "Cô ấy đang thực hiện nghiên cứu khoa học về phương pháp điều trị ung thư." },
          { en: "The research shows that exercise improves memory.", vi: "Nghiên cứu chỉ ra rằng tập thể dục cải thiện trí nhớ." },
          { en: "They need to research the market before launching the product.", vi: "Họ cần nghiên cứu thị trường trước khi tung ra sản phẩm." },
        ],
        notes: "Vừa là danh từ không đếm được vừa là động từ.",
      },
      {
        id: "edu16",
        term: "Syllabus",
        phonetic: "/ˈsɪləbəs/",
        translation: "Đề cương khóa học, chương trình chi tiết",
        examples: [
          { en: "The teacher handed out the course syllabus on the first day.", vi: "Giáo viên đã phát đề cương khóa học vào ngày học đầu tiên." },
          { en: "Please read the syllabus carefully to know the exam dates.", vi: "Vui lòng đọc kỹ đề cương để biết ngày thi." },
          { en: "The biology syllabus covers genetics and ecosystems.", vi: "Đề cương môn sinh học bao gồm di truyền học và hệ sinh thái." },
        ],
        notes: "Bản tóm tắt các nội dung và yêu cầu của một môn học cụ thể.",
      },
      {
        id: "edu17",
        term: "Knowledge",
        phonetic: "/ˈnɒlɪdʒ/",
        translation: "Kiến thức, sự hiểu biết",
        examples: [
          { en: "He has deep knowledge of ancient history.", vi: "Anh ấy có kiến thức sâu rộng về lịch sử cổ đại." },
          { en: "Books are a great source of useful knowledge.", vi: "Sách là một nguồn kiến thức hữu ích vô cùng tuyệt vời." },
          { en: "She wants to expand her practical knowledge of accounting.", vi: "Cô ấy muốn mở rộng kiến thức thực tế của mình về kế toán." },
        ],
        notes: "Danh từ không đếm được.",
      },
      {
        id: "edu18",
        term: "Enroll",
        phonetic: "/ɪnˈrəʊl/",
        translation: "Đăng ký học, nhập học, tuyển sinh",
        examples: [
          { en: "She decided to enroll in an online English course.", vi: "Cô ấy đã quyết định đăng ký học một khóa học tiếng Anh trực tuyến." },
          { en: "The university hopes to enroll more international students.", vi: "Trường đại học hy vọng tuyển sinh được nhiều sinh viên quốc tế hơn." },
          { en: "We must enroll before the end of August.", vi: "Chúng ta phải đăng ký nhập học trước cuối tháng Tám." },
        ],
        notes: "Hành động chính thức tham gia một lớp học hoặc một trường học.",
      },
      {
        id: "edu19",
        term: "Extracurricular",
        phonetic: "/ˌekstrəkəˈrɪkjələ/",
        translation: "Thuộc hoạt động ngoại khóa",
        examples: [
          { en: "Extracurricular activities help students develop soft skills.", vi: "Các hoạt động ngoại khóa giúp học sinh phát triển kỹ năng mềm." },
          { en: "He participates in many extracurricular programs, such as charity.", vi: "Anh ấy tham gia nhiều chương trình ngoại khóa, chẳng hạn như từ thiện." },
          { en: "The school offers a variety of extracurricular sports.", vi: "Nhà trường cung cấp nhiều môn thể thao ngoại khóa đa dạng." },
        ],
        notes: "Các hoạt động nằm ngoài chương trình học chính quy.",
      },
      {
        id: "edu20",
        term: "Scholar",
        phonetic: "/ˈskɒlə/",
        translation: "Học giả, nhà nghiên cứu uyên bác",
        examples: [
          { en: "He is a respected scholar of East Asian literature.", vi: "Ông là một học giả đáng kính về văn học Đông Á." },
          { en: "The university hosted a conference for young scholars.", vi: "Trường đại học đã tổ chức một hội nghị dành cho các nhà nghiên cứu trẻ." },
          { en: "She spent years working as a visiting scholar in Oxford.", vi: "Cô ấy dành nhiều năm làm việc với tư cách học giả thỉnh giảng ở Oxford." },
        ],
        notes: "Người dành cả đời nghiên cứu sâu sắc về một lĩnh vực học thuật.",
      },
    ],
  },
  {
    id: "topic_environment_ta5",
    title: "Môi trường & Thiên nhiên",
    category: "topic",
    description: "Các vấn đề biến đổi khí hậu toàn cầu, bảo tồn đa dạng sinh học và phát triển bền vững.",
    color: "bg-indigo-600",
    words: [
      {
        id: "env1",
        term: "Pollution",
        phonetic: "/pəˈluːʃn/",
        translation: "Sự ô nhiễm",
        examples: [
          { en: "Air pollution has reached dangerous levels in some major cities.", vi: "Ô nhiễm không khí đã đạt tới mức độ nguy hiểm ở một số thành phố lớn." },
          { en: "Plastic waste is the main cause of ocean pollution.", vi: "Rác thải nhựa là nguyên nhân chính gây ra ô nhiễm đại dương." },
          { en: "They are trying to reduce water pollution from local factories.", vi: "Họ đang cố gắng giảm thiểu ô nhiễm nguồn nước từ các nhà máy địa phương." },
        ],
        notes: "Sự làm bẩn môi trường bằng chất độc hại.",
      },
      {
        id: "env2",
        term: "Climate change",
        phonetic: "/ˈklaɪmət tʃeɪndʒ/",
        translation: "Biến đổi khí hậu",
        examples: [
          { en: "Climate change is causing sea levels to rise rapidly.", vi: "Biến đổi khí hậu đang khiến mực nước biển dâng lên nhanh chóng." },
          { en: "We must take immediate action to fight climate change.", vi: "Chúng ta phải hành động ngay lập tức để chống lại biến đổi khí hậu." },
          { en: "Many species are threatened by climate change.", vi: "Nhiều loài sinh vật đang bị đe dọa bởi biến đổi khí hậu." },
        ],
        notes: "Sự thay đổi dài hạn của nhiệt độ và các kiểu thời tiết toàn cầu.",
      },
      {
        id: "env3",
        term: "Conservation",
        phonetic: "/ˌkɒnsəˈveɪʃn/",
        translation: "Sự bảo tồn (thiên nhiên, tài nguyên)",
        examples: [
          { en: "Water conservation is essential during hot dry summers.", vi: "Việc bảo tồn nguồn nước là rất thiết yếu trong những mùa hè khô nóng." },
          { en: "He works for a wildlife conservation organization.", vi: "Anh ấy làm việc cho một tổ chức bảo tồn động vật hoang dã." },
          { en: "The government is focused on forest conservation.", vi: "Chính phủ đang tập trung vào việc bảo tồn rừng." },
        ],
        notes: "Hành động bảo vệ thiên nhiên và tránh lãng phí tài nguyên.",
      },
      {
        id: "env4",
        term: "Biodiversity",
        phonetic: "/ˌbaɪəʊdaɪˈvɜːsəti/",
        translation: "Đa dạng sinh học",
        examples: [
          { en: "Protecting biodiversity is vital for a healthy ecosystem.", vi: "Bảo vệ sự đa dạng sinh học là cực kỳ quan trọng cho một hệ sinh thái khỏe mạnh." },
          { en: "The rainforest has an incredible level of biodiversity.", vi: "Rừng mưa nhiệt đới có một mức độ đa dạng sinh học đáng kinh ngạc." },
          { en: "Human activities are leading to a loss of biodiversity.", vi: "Các hoạt động của con người đang dẫn tới sự mất đi đa dạng sinh học." },
        ],
        notes: "Sự phong phú về các loài sinh vật sống trong một khu vực.",
      },
      {
        id: "env5",
        term: "Ecosystem",
        phonetic: "/ˈiːkəʊsɪstəm/",
        translation: "Hệ sinh thái",
        examples: [
          { en: "Pollution can destroy the delicate marine ecosystem.", vi: "Ô nhiễm có thể phá hủy hệ sinh thái biển vô cùng nhạy cảm." },
          { en: "Every animal plays an important role in the ecosystem.", vi: "Mỗi loài động vật đều đóng một vai trò quan trọng trong hệ sinh thái." },
          { en: "The forest ecosystem needs protection from deforestation.", vi: "Hệ sinh thái rừng cần được bảo vệ khỏi nạn phá rừng." },
        ],
        notes: "Môi trường sống bao gồm cả sinh vật sống và các yếu tố vô sinh tương tác.",
      },
      {
        id: "env6",
        term: "Recycle",
        phonetic: "/ˌriːˈsaɪkl/",
        translation: "Tái chế",
        examples: [
          { en: "We should recycle paper and plastic to reduce waste.", vi: "Chúng ta nên tái chế giấy và nhựa để giảm thiểu chất thải." },
          { en: "The city wants to encourage citizens to recycle.", vi: "Thành phố muốn khuyến khích người dân thực hiện tái chế." },
          { en: "This bottle is made from recycled materials.", vi: "Chiếc chai này được làm từ các vật liệu tái chế." },
        ],
        notes: "Xử lý rác thải thành nguyên liệu mới để sử dụng lại.",
      },
      {
        id: "env7",
        term: "Renewable",
        phonetic: "/rɪˈnjuːəbl/",
        translation: "Có thể tái tạo, vô hạn",
        examples: [
          { en: "Solar and wind are forms of renewable energy.", vi: "Năng lượng mặt trời và năng lượng gió là các dạng năng lượng có thể tái tạo." },
          { en: "We need to invest more in renewable resources.", vi: "Chúng ta cần đầu tư nhiều hơn vào các nguồn tài nguyên tái tạo." },
          { en: "Renewable energy helps reduce carbon emissions.", vi: "Năng lượng tái tạo giúp giảm lượng khí thải carbon." },
        ],
        notes: "Nguồn tài nguyên tự bổ sung vô hạn tự nhiên (nắng, gió, nước).",
      },
      {
        id: "env8",
        term: "Habitat",
        phonetic: "/ˈhæbɪtæt/",
        translation: "Môi trường sống tự nhiên của sinh vật",
        examples: [
          { en: "Forests are the natural habitat of many wild animals.", vi: "Rừng là môi trường sống tự nhiên của nhiều động vật hoang dã." },
          { en: "Climate change is destroying the polar bear's habitat.", vi: "Biến đổi khí hậu đang phá hủy môi trường sống của gấu bắc cực." },
          { en: "They are working to restore the wetlands habitat.", vi: "Họ đang nỗ lực khôi phục lại môi trường sống ở vùng đất ngập nước." },
        ],
        notes: "Nơi cư trú tự nhiên của một loài động vật hoặc thực vật.",
      },
      {
        id: "env9",
        term: "Deforestation",
        phonetic: "/ˌdiːˌfɒrɪˈsteɪʃn/",
        translation: "Nạn phá rừng, sự tàn phá rừng",
        examples: [
          { en: "Deforestation is leading to a loss of habitat for many species.", vi: "Nạn phá rừng đang dẫn tới sự mất đi môi trường sống của nhiều loài sinh vật." },
          { en: "We must stop illegal deforestation to protect our planet.", vi: "Chúng ta phải ngăn chặn nạn phá rừng trái phép để bảo vệ hành tinh." },
          { en: "Deforestation contributes to global warming.", vi: "Sự tàn phá rừng góp phần gây ra hiện tượng nóng lên toàn cầu." },
        ],
        notes: "Hành động chặt phá rừng quy mô lớn.",
      },
      {
        id: "env10",
        term: "Endangered",
        phonetic: "/ɪnˈdeɪndʒəd/",
        translation: "Bị đe dọa tuyệt chủng, nguy cấp",
        examples: [
          { en: "The giant panda is an endangered species.", vi: "Gấu trúc khổng lồ là một loài có nguy cơ tuyệt chủng." },
          { en: "We must protect endangered animals from illegal hunting.", vi: "Chúng ta phải bảo vệ các động vật nguy cấp khỏi nạn săn bắn trái phép." },
          { en: "The list of endangered plants is growing every year.", vi: "Danh sách các loài thực vật nguy cấp đang tăng lên mỗi năm." },
        ],
        notes: "Có nguy cơ cao bị biến mất hoàn toàn trên Trái Đất.",
      },
      {
        id: "env11",
        term: "Resource",
        phonetic: "/rɪˈsɔːs/",
        translation: "Tài nguyên, nguồn lực",
        examples: [
          { en: "Water is our most precious natural resource.", vi: "Nước là tài nguyên thiên nhiên quý giá nhất của chúng ta." },
          { en: "We must not waste our limited natural resources.", vi: "Chúng ta không được lãng phí tài nguyên thiên nhiên có hạn của mình." },
          { en: "The library is an excellent resource for students.", vi: "Thư viện là một nguồn lực học tập tuyệt vời cho học sinh." },
        ],
        notes: "Nguồn cung cấp của cải hữu ích có sẵn trong tự nhiên.",
      },
      {
        id: "env12",
        term: "Emission",
        phonetic: "/ɪˈmɪʃn/",
        translation: "Sự phát thải, khí thải",
        examples: [
          { en: "The agreement aims to reduce greenhouse gas emissions.", vi: "Hiệp định nhằm mục đích giảm lượng phát thải khí nhà kính." },
          { en: "Car emissions contribute to poor air quality in cities.", vi: "Khí thải từ ô tô góp phần làm chất lượng không khí kém ở các thành phố." },
          { en: "Factories must cut down their chemical emissions.", vi: "Các nhà máy phải cắt giảm lượng khí thải hóa chất của họ." },
        ],
        notes: "Khí hoặc chất độc hại thải ra không khí từ động cơ, nhà máy.",
      },
      {
        id: "env13",
        term: "Waste",
        phonetic: "/weɪst/",
        translation: "Rác thải, chất thải / Lãng phí",
        examples: [
          { en: "They are trying to find a safe way to dispose of nuclear waste.", vi: "Họ đang cố gắng tìm một phương thức an toàn để xử lý chất thải hạt nhân." },
          { en: "Leaving the lights on is a waste of electricity.", vi: "Để đèn sáng là một sự lãng phí điện năng." },
          { en: "Do not waste water; the supply is limited.", vi: "Đừng lãng phí nước; nguồn cung cấp có hạn." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "env14",
        term: "Wildlife",
        phonetic: "/ˈwaɪldlaɪf/",
        translation: "Động vật hoang dã",
        examples: [
          { en: "The national park protects local wildlife and plants.", vi: "Công viên quốc gia bảo vệ động vật hoang dã và thực vật địa phương." },
          { en: "He loves photographing wildlife in its natural habitat.", vi: "Anh ấy thích chụp ảnh động vật hoang dã trong môi trường sống tự nhiên của chúng." },
          { en: "Human activities can disturb wildlife.", vi: "Các hoạt động của con người có thể làm xáo trộn cuộc sống động vật hoang dã." },
        ],
        notes: "Danh từ không đếm được chỉ các động vật chưa được thuần hóa.",
      },
      {
        id: "env15",
        term: "Sustainable",
        phonetic: "/səˈsteɪnəbl/",
        translation: "Bền vững, lâu dài và thân thiện",
        examples: [
          { en: "We need to promote sustainable development in rural areas.", vi: "Chúng ta cần thúc đẩy sự phát triển bền vững ở các vùng nông thôn." },
          { en: "Using solar power is a sustainable energy solution.", vi: "Sử dụng năng lượng mặt trời là một giải pháp năng lượng bền vững." },
          { en: "Organic farming is more sustainable than chemical farming.", vi: "Canh tác hữu cơ bền vững thân thiện hơn canh tác hóa chất." },
        ],
        notes: "Tính từ chỉ khả năng duy trì lâu dài mà không gây hại cho tương lai.",
      },
      {
        id: "env16",
        term: "Disaster",
        phonetic: "/dɪˈzɑːstə/",
        translation: "Thảm họa, thiên tai",
        examples: [
          { en: "The earthquake was a major natural disaster.", vi: "Trận động đất đã là một thảm họa thiên nhiên lớn." },
          { en: "If we don't act, climate change will lead to a global disaster.", vi: "Nếu chúng ta không hành động, biến đổi khí hậu sẽ dẫn tới một thảm họa toàn cầu." },
          { en: "The oil spill caused an environmental disaster.", vi: "Sự cố tràn dầu đã gây ra một thảm họa môi trường." },
        ],
        notes: "Sự kiện tàn phá khủng khiếp do thiên nhiên hoặc con người.",
      },
      {
        id: "env17",
        term: "Carbon footprint",
        phonetic: "/ˌkɑːbən ˈfʊtprɪnt/",
        translation: "Dấu chân carbon, lượng khí thải cá nhân",
        examples: [
          { en: "We can reduce our carbon footprint by walking instead of driving.", vi: "Chúng ta có thể giảm lượng dấu chân carbon bằng cách đi bộ thay vì lái xe." },
          { en: "The company is trying to lower its carbon footprint.", vi: "Công ty đang nỗ lực giảm thiểu dấu chân carbon của mình." },
          { en: "Eating local food helps reduce your carbon footprint.", vi: "Ăn thực phẩm địa phương giúp giảm dấu chân carbon cá nhân." },
        ],
        notes: "Lượng khí nhà kính do một người hoặc một tổ chức thải ra.",
      },
      {
        id: "env18",
        term: "Greenhouse effect",
        phonetic: "/ˈɡriːnhaʊs ɪˈfekt/",
        translation: "Hiệu ứng nhà kính",
        examples: [
          { en: "The greenhouse effect is necessary for life, but too much of it is dangerous.", vi: "Hiệu ứng nhà kính là cần thiết cho sự sống, nhưng quá nhiều thì lại nguy hiểm." },
          { en: "Carbon dioxide contributes to the greenhouse effect.", vi: "Khí carbon dioxide đóng góp vào hiệu ứng nhà kính." },
          { en: "The greenhouse effect causes global temperatures to rise.", vi: "Hiệu ứng nhà kính khiến nhiệt độ toàn cầu tăng lên." },
        ],
        notes: "Hiện tượng khí quyển giữ lại năng lượng mặt trời làm Trái Đất ấm lên.",
      },
      {
        id: "env19",
        term: "Organic",
        phonetic: "/ɔːˈɡænɪk/",
        translation: "Hữu cơ, tự nhiên không dùng hóa chất",
        examples: [
          { en: "Organic vegetables are grown without chemical fertilizers.", vi: "Rau hữu cơ được trồng mà không sử dụng phân bón hóa học." },
          { en: "The store sells a variety of organic foods.", vi: "Cửa hàng bán nhiều loại thực phẩm hữu cơ đa dạng." },
          { en: "He prefers organic honey to processed honey.", vi: "Anh ấy thích mật ong hữu cơ hơn mật ong đã qua xử lý." },
        ],
        notes: "Sản xuất nông nghiệp hoàn toàn tự nhiên.",
      },
      {
        id: "env20",
        term: "Alternative",
        phonetic: "/ɔːlˈtɜːnətɪv/",
        translation: "Thay thế, sự thay thế",
        examples: [
          { en: "We need to find alternative energy sources to replace oil.", vi: "Chúng ta cần tìm kiếm các nguồn năng lượng thay thế để thế chỗ dầu mỏ." },
          { en: "Do you have an alternative plan if it rains?", vi: "Bạn có kế hoạch thay thế nào phòng trường hợp trời mưa không?" },
          { en: "There is no alternative but to close the factory.", vi: "Không có sự lựa chọn thay thế nào khác ngoài việc đóng cửa nhà máy." },
        ],
        notes: "Lựa chọn hoặc phương án khác có thể dùng thay thế cái hiện tại.",
      },
    ],
  },
  {
    id: "topic_it_ta5",
    title: "Công nghệ thông tin",
    category: "topic",
    description: "Các thiết bị số, phần mềm, cơ sở dữ liệu và các vấn đề an ninh mạng thời đại số.",
    color: "bg-indigo-600",
    words: [
      {
        id: "it1",
        term: "Software",
        phonetic: "/ˈsɒftweə/",
        translation: "Phần mềm máy tính",
        examples: [
          { en: "She installed a new software program on her laptop.", vi: "Cô ấy đã cài đặt một chương trình phần mềm mới trên máy tính xách tay của mình." },
          { en: "The software is designed to protect your files from viruses.", vi: "Phần mềm được thiết kế để bảo vệ các tệp tin của bạn khỏi vi-rút." },
          { en: "We need to update our anti-virus software regularly.", vi: "Chúng ta cần cập nhật phần mềm diệt vi-rút thường xuyên." },
        ],
        notes: "Danh từ không đếm được chỉ các chương trình chạy trên máy tính.",
      },
      {
        id: "it2",
        term: "Hardware",
        phonetic: "/ˈhɑːdweə/",
        translation: "Phần cứng máy tính",
        examples: [
          { en: "The computer store sells both hardware and software.", vi: "Cửa hàng máy tính bán cả phần cứng và phần mềm." },
          { en: "You need to upgrade your hardware to play this heavy game.", vi: "Bạn cần nâng cấp phần cứng để chơi được tựa game nặng này." },
          { en: "The mouse and keyboard are computer hardware.", vi: "Chuột và bàn phím là phần cứng máy tính." },
        ],
        notes: "Danh từ không đếm được chỉ các linh kiện vật lý của máy tính.",
      },
      {
        id: "it3",
        term: "Network",
        phonetic: "/ˈnetwɜːk/",
        translation: "Mạng lưới, mạng kết nối",
        examples: [
          { en: "The office computer network is secured with a password.", vi: "Mạng máy tính văn phòng được bảo mật bằng mật khẩu." },
          { en: "Social networks have changed how people build relationships.", vi: "Mạng xã hội đã thay đổi cách mọi người xây dựng mối quan hệ." },
          { en: "The television network has channels worldwide.", vi: "Mạng lưới truyền hình có các kênh trên toàn thế giới." },
        ],
        notes: "Hệ thống kết nối các thiết bị hoặc con người với nhau.",
      },
      {
        id: "it4",
        term: "Database",
        phonetic: "/ˈdeɪtəbeɪs/",
        translation: "Cơ sở dữ liệu",
        examples: [
          { en: "The student database contains contact details for everyone.", vi: "Cơ sở dữ liệu học sinh chứa thông tin liên lạc của tất cả mọi người." },
          { en: "They are updating the customer database today.", vi: "Hôm nay họ đang cập nhật cơ sở dữ liệu khách hàng." },
          { en: "He manages the large company database.", vi: "Anh ấy quản lý cơ sở dữ liệu lớn của công ty." },
        ],
        notes: "Hệ thống lưu trữ thông tin dữ liệu có cấu trúc trên máy tính.",
      },
      {
        id: "it5",
        term: "Cybersecurity",
        phonetic: "/ˌsaɪbəsɪˈkjʊərəti/",
        translation: "An ninh mạng, bảo mật thông tin",
        examples: [
          { en: "The bank invests a lot of money in cybersecurity.", vi: "Ngân hàng đầu tư rất nhiều tiền vào an ninh mạng." },
          { en: "She works as a cybersecurity expert for a tech firm.", vi: "Cô ấy làm việc với tư cách là chuyên gia an ninh mạng cho một hãng công nghệ." },
          { en: "Using weak passwords is a major cybersecurity risk.", vi: "Sử dụng mật khẩu yếu là một rủi ro lớn đối với bảo mật an ninh mạng." },
        ],
        notes: "Hoạt động bảo vệ hệ thống và mạng internet khỏi các cuộc tấn công số.",
      },
      {
        id: "it6",
        term: "Application",
        phonetic: "/ˌæplɪˈkeɪʃn/",
        translation: "Ứng dụng phần mềm / Đơn xin việc",
        examples: [
          { en: "I downloaded a new language application on my phone.", vi: "Tôi đã tải xuống một ứng dụng ngôn ngữ mới trên điện thoại." },
          { en: "This application runs smoothly on both iOS and Android.", vi: "Ứng dụng này chạy trơn tru trên cả iOS và Android." },
          { en: "She submitted a job application to the company.", vi: "Cô ấy đã nộp đơn xin việc tới công ty." },
        ],
        notes: "Thường viết tắt là 'app' trong lĩnh vực công nghệ.",
      },
      {
        id: "it7",
        term: "Programming",
        phonetic: "/ˈprəʊɡræmɪŋ/",
        translation: "Lập trình máy tính",
        examples: [
          { en: "He is learning computer programming at university.", vi: "Cậu ấy đang học lập trình máy tính tại trường đại học." },
          { en: "Python is a popular programming language.", vi: "Python là một ngôn ngữ lập trình phổ biến." },
          { en: "She works in a software development programming team.", vi: "Cô ấy làm việc trong một nhóm lập trình phát triển phần mềm." },
        ],
        notes: "Hoạt động viết các đoạn mã lệnh (code) cho máy tính thực thi.",
      },
      {
        id: "it8",
        term: "Device",
        phonetic: "/dɪˈvaɪs/",
        translation: "Thiết bị số, linh kiện",
        examples: [
          { en: "A smartphone is a pocket-sized mobile device.", vi: "Điện thoại thông minh là một thiết bị di động kích cỡ bỏ túi." },
          { en: "Please disconnect your electronic devices before takeoff.", vi: "Vui lòng ngắt kết nối các thiết bị điện tử trước khi cất cánh." },
          { en: "This small device is used to measure heart rates.", vi: "Thiết bị nhỏ này được sử dụng để đo nhịp tim." },
        ],
        notes: "Công cụ cơ khí hoặc điện tử có chức năng chuyên biệt.",
      },
      {
        id: "it9",
        term: "Algorithm",
        phonetic: "/ˈælɡərɪðəm/",
        translation: "Thuật toán",
        examples: [
          { en: "Social media use algorithms to recommend videos to users.", vi: "Mạng xã hội sử dụng thuật toán để gợi ý video cho người dùng." },
          { en: "The search engine developed a new search algorithm.", vi: "Công cụ tìm kiếm đã phát triển một thuật toán tìm kiếm mới." },
          { en: "This complex algorithm solves mathematical equations quickly.", vi: "Thuật toán phức tạp này giải phương trình toán học rất nhanh." },
        ],
        notes: "Tập hợp các bước và quy tắc toán học để giải quyết vấn đề.",
      },
      {
        id: "it10",
        term: "Cloud computing",
        phonetic: "/ˌklaʊd kəmˈpjuːtɪŋ/",
        translation: "Điện toán đám mây",
        examples: [
          { en: "Cloud computing allows users to store files online.", vi: "Điện toán đám mây cho phép người dùng lưu trữ các tệp tin trực tuyến." },
          { en: "Many companies are moving their data to cloud computing.", vi: "Nhiều công ty đang chuyển dịch dữ liệu của họ lên điện toán đám mây." },
          { en: "Services like Google Drive use cloud computing.", vi: "Các dịch vụ như Google Drive sử dụng điện toán đám mây." },
        ],
        notes: "Dịch vụ lưu trữ và tính toán thông qua mạng internet thay vì ổ cứng vật lý.",
      },
      {
        id: "it11",
        term: "Backup",
        phonetic: "/ˈbækʌp/",
        translation: "Sao lưu dữ liệu dự phòng",
        examples: [
          { en: "You should make a backup copy of your important files.", vi: "Bạn nên tạo một bản sao lưu dự phòng cho các tệp tin quan trọng của mình." },
          { en: "The system does an automatic database backup every night.", vi: "Hệ thống tự động thực hiện sao lưu cơ sở dữ liệu mỗi tối." },
          { en: "If the main server fails, we can use the backup data.", vi: "Nếu máy chủ chính bị lỗi, chúng ta có thể sử dụng dữ liệu sao lưu dự phòng." },
        ],
        notes: "Bản sao lưu để phòng tránh mất dữ liệu gốc.",
      },
      {
        id: "it12",
        term: "Server",
        phonetic: "/ˈsɜːvə/",
        translation: "Máy chủ máy tính",
        examples: [
          { en: "The company server went down, so we couldn't send emails.", vi: "Máy chủ của công ty bị hỏng, vì vậy chúng tôi không thể gửi email." },
          { en: "Websites are stored on powerful computer servers.", vi: "Các trang web được lưu trữ trên những máy chủ máy tính mạnh mẽ." },
          { en: "They need to upgrade their web server to handle more traffic.", vi: "Họ cần nâng cấp máy chủ web để xử lý lượng truy cập lớn hơn." },
        ],
        notes: "Hệ thống máy tính trung tâm lưu trữ và xử lý thông tin cho toàn mạng lưới.",
      },
      {
        id: "it13",
        term: "Interface",
        phonetic: "/ˈɪntəfeɪs/",
        translation: "Giao diện người dùng",
        examples: [
          { en: "The application has a user-friendly interface.", vi: "Ứng dụng có một giao diện thân thiện với người dùng." },
          { en: "The designer improved the mobile interface of the website.", vi: "Nhà thiết kế đã cải thiện giao diện di động của trang web." },
          { en: "A simple interface makes the software easy to use.", vi: "Một giao diện đơn giản giúp phần mềm dễ sử dụng hơn." },
        ],
        notes: "Phần hiển thị đồ họa tương tác giữa người dùng và máy tính (UI).",
      },
      {
        id: "it14",
        term: "Update",
        phonetic: "/ˌʌpˈdeɪt/",
        translation: "Cập nhật, bản cập nhật",
        examples: [
          { en: "You must update your operating system to patch security gaps.", vi: "Bạn phải cập nhật hệ điều hành để vá các lỗ hổng bảo mật." },
          { en: "I received an update notification for the application.", vi: "Tôi đã nhận được một thông báo bản cập nhật dành cho ứng dụng." },
          { en: "Please update your contact details on our database.", vi: "Vui lòng cập nhật chi tiết liên lạc của bạn trên cơ sở dữ liệu của chúng tôi." },
        ],
        notes: "Vừa là động từ vừa là danh từ.",
      },
      {
        id: "it15",
        term: "Virus",
        phonetic: "/ˈvaɪrəs/",
        translation: "Vi-rút máy tính / Vi-rút sinh học",
        examples: [
          { en: "A computer virus deleted all his important documents.", vi: "Một con vi-rút máy tính đã xóa toàn bộ tài liệu quan trọng của anh ấy." },
          { en: "He got a cold caused by a common virus.", vi: "Anh ấy bị cảm lạnh do một loại vi-rút thông thường gây ra." },
          { en: "The anti-virus software detected a virus on the USB.", vi: "Phần mềm diệt vi-rút đã phát hiện ra một con vi-rút trên ổ USB." },
        ],
        notes: "Đoạn mã độc hại phá hủy hệ điều hành máy tính.",
      },
      {
        id: "it16",
        term: "AI (Artificial Intelligence)",
        phonetic: "/ˌɑːtɪfɪʃl ɪnˈtelɪɡəns/",
        translation: "Trí tuệ nhân tạo",
        examples: [
          { en: "AI is being used to analyze large amounts of medical data.", vi: "Trí tuệ nhân tạo AI đang được sử dụng để phân tích khối lượng lớn dữ liệu y tế." },
          { en: "Many people worry that AI will replace human jobs.", vi: "Nhiều người lo lắng rằng trí tuệ nhân tạo AI sẽ thay thế các công việc của con người." },
          { en: "The application uses AI to translate languages instantly.", vi: "Ứng dụng sử dụng trí tuệ nhân tạo AI để dịch thuật ngôn ngữ ngay lập tức." },
        ],
        notes: "Lĩnh vực máy tính mô phỏng trí tuệ con người.",
      },
      {
        id: "it17",
        term: "Download",
        phonetic: "/ˌdaʊnˈləʊd/",
        translation: "Tải xuống, download",
        examples: [
          { en: "You can download the PDF file from our website.", vi: "Bạn có thể tải xuống tệp tin PDF từ trang web của chúng tôi." },
          { en: "The download was fast because of the fiber internet.", vi: "Quá trình tải xuống diễn ra rất nhanh nhờ internet cáp quang." },
          { en: "Do not download files from unknown senders.", vi: "Đừng tải xuống các tệp tin từ những người gửi không quen biết." },
        ],
        notes: "Vừa là động từ vừa là danh từ chỉ hành động sao chép dữ liệu từ internet về máy.",
      },
      {
        id: "it18",
        term: "Upload",
        phonetic: "/ˌʌpˈləʊd/",
        translation: "Tải lên mạng, upload",
        examples: [
          { en: "She uploaded her vacation photos to her social media profile.", vi: "Cô ấy đã tải những bức ảnh kỳ nghỉ của mình lên trang cá nhân mạng xã hội." },
          { en: "It took ten minutes to upload the heavy video file.", vi: "Mất mười phút để tải tệp video nặng lên mạng." },
          { en: "You need to upload a copy of your ID card.", vi: "Bạn cần tải lên một bản sao thẻ chứng minh nhân dân của mình." },
        ],
        notes: "Trái nghĩa với 'download', gửi dữ liệu từ máy cá nhân lên mạng.",
      },
      {
        id: "it19",
        term: "Encryption",
        phonetic: "/ɪnˈkrɪpʃn/",
        translation: "Sự mã hóa dữ liệu",
        examples: [
          { en: "Data encryption keeps your credit card details safe online.", vi: "Sự mã hóa dữ liệu giúp giữ thông tin thẻ tín dụng của bạn an toàn trên mạng." },
          { en: "The application uses end-to-end encryption for private messages.", vi: "Ứng dụng sử dụng mã hóa đầu cuối cho các tin nhắn riêng tư." },
          { en: "Without encryption, hackers can easily steal password data.", vi: "Nếu không có sự mã hóa, tin tặc có thể dễ dàng ăn cắp dữ liệu mật khẩu." },
        ],
        notes: "Chuyển đổi thông tin thông thường thành mật mã để bảo mật.",
      },
      {
        id: "it20",
        term: "Broadband",
        phonetic: "/ˈbrɔːdbænd/",
        translation: "Mạng băng thông rộng, internet tốc độ cao",
        examples: [
          { en: "Broadband internet is now available in almost all rural areas.", vi: "Internet băng thông rộng hiện đã có mặt ở hầu hết các vùng nông thôn." },
          { en: "We subscribed to a high-speed broadband plan.", vi: "Chúng tôi đã đăng ký một gói cước internet băng thông rộng tốc độ cao." },
          { en: "The introduction of broadband changed how we watch movies online.", vi: "Sự ra đời của băng thông rộng đã thay đổi cách chúng ta xem phim trực tuyến." },
        ],
        notes: "Mạng truyền dữ liệu tốc độ cao qua cáp hoặc vệ tinh.",
      },
    ],
  },
];
