export const tierEliteIII = [
  {
    id: "topic_art_cinema_ta3",
    title: "Nghệ thuật & Điện ảnh",
    category: "topic",
    description: "Các thuật ngữ phê bình nghệ thuật, kỹ thuật hội họa, sản xuất điện ảnh và trường phái thẩm mỹ.",
    color: "bg-indigo-800",
    words: [
      {
        id: "art1",
        term: "Masterpiece",
        phonetic: "/ˈmɑːstəpiːs/",
        translation: "Kiệt tác, tác phẩm nghệ thuật xuất sắc",
        examples: [
          { en: "Da Vinci's Mona Lisa is widely considered a masterpiece of the Renaissance.", vi: "Bức họa Mona Lisa của Da Vinci được coi là một kiệt tác của thời kỳ Phục hưng." },
          { en: "The director's latest film is nothing short of a cinematic masterpiece.", vi: "Bộ phim mới nhất của vị đạo diễn này không khác gì một kiệt tác điện ảnh thực thụ." },
          { en: "He spent his entire life working on what he hoped would be his masterpiece.", vi: "Ông dành cả đời để thực hiện tác phẩm mà ông hy vọng sẽ là kiệt tác để đời của mình." },
        ],
        notes: "Tác phẩm xuất sắc nhất trong sự nghiệp của một nghệ sĩ hoặc đạo diễn.",
      },
      {
        id: "art2",
        term: "Portrait",
        phonetic: "/ˈpɔːtreɪt/",
        translation: "Tranh chân dung, ảnh chân dung",
        examples: [
          { en: "The museum displays a famous self-portrait of Vincent van Gogh.", vi: "Bảo tàng trưng bày một bức tự họa chân dung nổi tiếng của Vincent van Gogh." },
          { en: "She commissioned an artist to paint a portrait of her family.", vi: "Bà ấy đã thuê một họa sĩ vẽ một bức chân dung cho gia đình mình." },
          {
            en: "His novels provide a vivid portrait of life in nineteenth-century England.",
            vi: "Những cuốn tiểu thuyết của ông phác họa một bức chân dung sống động về cuộc sống ở nước Anh thế kỷ 19.",
          },
        ],
        notes: "Tranh hoặc ảnh mô tả khuôn mặt và biểu cảm của một người.",
      },
      {
        id: "art3",
        term: "Sculpture",
        phonetic: "/ˈskʌlptʃə/",
        translation: "Tác phẩm điêu khắc, nghệ thuật điêu khắc",
        examples: [
          { en: "The bronze sculpture was installed in the main hall of the gallery.", vi: "Bức tượng điêu khắc bằng đồng đã được lắp đặt tại sảnh chính của phòng triển lãm." },
          { en: "He studied classical Greek sculpture at the art academy.", vi: "Anh ấy đã học nghệ thuật điêu khắc Hy Lạp cổ điển tại học viện nghệ thuật." },
          { en: "She uses recycled metal to create abstract sculptures.", vi: "Cô ấy sử dụng kim loại tái chế để tạo ra những tác phẩm điêu khắc trừu tượng." },
        ],
        notes: "Vừa là danh từ chỉ tác phẩm điêu khắc vừa chỉ ngành nghệ thuật điêu khắc.",
      },
      {
        id: "art4",
        term: "Genre",
        phonetic: "/ˈʒɒnrə/",
        translation: "Thể loại (nghệ thuật, phim, văn học)",
        examples: [
          { en: "Science fiction is a popular literary and cinematic genre.", vi: "Khoa học viễn tưởng là một thể loại văn học và điện ảnh rất được ưa chuộng." },
          { en: "He has written successful novels in several different genres.", vi: "Ông ấy đã viết những cuốn tiểu thuyết thành công ở nhiều thể loại khác nhau." },
          { en: "What musical genre do you enjoy listening to the most?", vi: "Bạn thích nghe thể loại âm nhạc nào nhất?" },
        ],
        notes: "Phát âm theo tiếng Pháp là /ˈʒɒnrə/.",
      },
      {
        id: "art5",
        term: "Director",
        phonetic: "/daɪˈrektə/",
        translation: "Đạo diễn (phim) / Giám đốc",
        examples: [
          { en: "The film director was praised for his unique visual style.", vi: "Vị đạo diễn phim đã được ca ngợi vì phong cách hình ảnh độc đáo của mình." },
          { en: "She works closely with the director to design the sets.", vi: "Cô ấy làm việc chặt chẽ với đạo diễn để thiết kế bối cảnh sân khấu." },
          { en: "He is the creative director of a major advertising agency.", vi: "Anh ấy là giám đốc sáng tạo của một cơ quan quảng cáo lớn." },
        ],
        notes: "Người chịu trách nhiệm nghệ thuật và dẫn dắt diễn viên khi quay phim.",
      },
      {
        id: "art6",
        term: "Soundtrack",
        phonetic: "/ˈsaʊndtræk/",
        translation: "Nhạc phim, dải âm thanh trong phim",
        examples: [
          { en: "The movie has an emotional soundtrack composed by Hans Zimmer.", vi: "Bộ phim có một bản nhạc phim đầy cảm xúc được sáng tác bởi Hans Zimmer." },
          { en: "I bought the official soundtrack of the film on vinyl.", vi: "Tôi đã mua đĩa nhạc phim chính thức của bộ phim dưới dạng đĩa than." },
          { en: "The beautiful soundtrack enhanced the dramatic tension of the scene.", vi: "Nhạc phim tuyệt đẹp đã làm tăng thêm sự căng thẳng kịch tính của phân cảnh." },
        ],
        notes: "Toàn bộ âm nhạc được sử dụng trong một bộ phim.",
      },
      {
        id: "art7",
        term: "Premiere",
        phonetic: "/ˈpremieə/",
        translation: "Buổi công chiếu đầu tiên, buổi ra mắt",
        examples: [
          { en: "Many Hollywood stars attended the world premiere of the blockbuster.", vi: "Nhiều ngôi sao Hollywood đã tham dự buổi công chiếu đầu tiên trên toàn thế giới của bộ phim bom tấn." },
          { en: "The play is set to premiere at the National Theatre next month.", vi: "Vở kịch dự kiến sẽ được ra mắt tại Nhà hát Quốc gia vào tháng tới." },
          { en: "Tickets for the opening night premiere sold out in minutes.", vi: "Vé cho buổi ra mắt đêm mở màn đã bán hết sạch trong vòng vài phút." },
        ],
        notes: "Vừa là danh từ vừa là động từ chỉ buổi ra mắt phim hoặc kịch đầu tiên.",
      },
      {
        id: "art8",
        term: "Exhibition",
        phonetic: "/ˌeksɪˈbɪʃn/",
        translation: "Cuộc triển lãm, buổi trưng bày",
        examples: [
          { en: "The gallery is hosting a temporary exhibition of modern photography.", vi: "Phòng trưng bày đang tổ chức một cuộc triển lãm tạm thời về nhiếp ảnh hiện đại." },
          { en: "We went to see the new art exhibition yesterday afternoon.", vi: "Hôm qua chúng tôi đã đi xem cuộc triển lãm nghệ thuật mới." },
          { en: "The international exhibition attracted scholars from all over the world.", vi: "Cuộc triển lãm quốc tế đã thu hút các học giả từ khắp nơi trên thế giới." },
        ],
        notes: "Danh từ của động từ 'exhibit' (trưng bày, triển lãm).",
      },
      {
        id: "art9",
        term: "Abstract",
        phonetic: "/ˈæbstrækt/",
        translation: "Trừu tượng, trường phái trừu tượng",
        examples: [
          { en: "She prefers abstract painting to traditional landscape art.", vi: "Cô ấy thích hội họa trừu tượng hơn là nghệ thuật phong cảnh truyền thống." },
          { en: "The concept of beauty is highly abstract and subjective.", vi: "Khái niệm về cái đẹp mang tính trừu tượng và chủ quan cao." },
          { en: "It is difficult for beginners to understand abstract sculptures.", vi: "Thật khó cho người mới bắt đầu để hiểu được các bức tượng điêu khắc trừu tượng." },
        ],
        notes: "Nghệ thuật không mô tả sự vật một cách chân thực mà qua hình khối và màu sắc.",
      },
      {
        id: "art10",
        term: "Critic",
        phonetic: "/ˈkrɪtɪk/",
        translation: "Nhà phê bình, người đánh giá chuyên môn",
        examples: [
          { en: "The film critic gave the movie a highly positive review.", vi: "Nhà phê bình điện ảnh đã dành cho bộ phim một bài nhận xét vô cùng tích cực." },
          { en: "She is a well-known literary critic for a major newspaper.", vi: "Bà ấy là một nhà phê bình văn học nổi tiếng của một tờ báo lớn." },
          { en: "Critics argued that the plot of the play was too predictable.", vi: "Các nhà phê bình lập luận rằng cốt truyện của vở kịch quá dễ đoán." },
        ],
        notes: "Người chuyên đưa ra nhận xét, đánh giá chuyên sâu về tác phẩm nghệ thuật.",
      },
      {
        id: "art11",
        term: "Blockbuster",
        phonetic: "/ˈblɒkbʌstə/",
        translation: "Phim bom tấn, tác phẩm thành công vang dội",
        examples: [
          { en: "The studio invested millions in their summer action blockbuster.", vi: "Hãng phim đã đầu tư hàng triệu đô la vào bộ phim hành động bom tấn mùa hè của họ." },
          { en: "The new fantasy movie became an instant global blockbuster.", vi: "Bộ phim giả tưởng mới đã ngay lập tức trở thành một bom tấn toàn cầu." },
          { en: "I prefer independent movies to Hollywood blockbusters.", vi: "Tôi thích các bộ phim độc lập hơn là những bom tấn Hollywood." },
        ],
        notes: "Bộ phim được đầu tư lớn và đạt doanh thu phòng vé khổng lồ.",
      },
      {
        id: "art12",
        term: "Screenplay",
        phonetic: "/ˈskriːnpleɪ/",
        translation: "Kịch bản phim, kịch bản điện ảnh",
        examples: [
          { en: "The movie won an Oscar for Best Original Screenplay.", vi: "Bộ phim đã giành giải Oscar cho Kịch bản gốc xuất sắc nhất." },
          { en: "He spent two years writing the screenplay for his first film.", vi: "Anh ấy đã dành hai năm để viết kịch bản điện ảnh cho bộ phim đầu tay của mình." },
          { en: "The director decided to change several lines in the screenplay.", vi: "Đạo diễn đã quyết định thay đổi vài câu thoại trong kịch bản." },
        ],
        notes: "Bản thảo chi tiết của phim bao gồm lời thoại và hướng dẫn diễn xuất.",
      },
      {
        id: "art13",
        term: "Aesthetic",
        phonetic: "/iːsˈθetɪk/",
        translation: "Tính thẩm mỹ, mỹ học",
        examples: [
          { en: "The new building design balances functionality and aesthetic appeal.", vi: "Thiết kế tòa nhà mới cân bằng giữa tính thực dụng và sức hút thẩm mỹ." },
          { en: "She appreciation for the clean minimalist aesthetic of the furniture.", vi: "Cô ấy trân trọng vẻ đẹp thẩm mỹ tối giản sạch sẽ của đồ nội thất." },
          { en: "The cinematography contributed to the film's unique aesthetic.", vi: "Nghệ thuật quay phim đã đóng góp vào tính thẩm mỹ độc đáo của bộ phim." },
        ],
        notes: "Tính từ hoặc danh từ liên quan đến vẻ đẹp và nghệ thuật học.",
      },
      {
        id: "art14",
        term: "Cast",
        phonetic: "/kɑːst/",
        translation: "Dàn diễn viên / Phân vai diễn",
        examples: [
          { en: "The director is currently looking to cast the lead role.", vi: "Đạo diễn hiện đang tìm kiếm để phân vai cho vai diễn nam chính." },
          { en: "The film features an all-star cast of talented actors.", vi: "Bộ phim có sự góp mặt của một dàn diễn viên toàn sao đầy tài năng." },
          { en: "She was cast as the queen in the historical drama.", vi: "Cô ấy đã được chọn phân vai nữ hoàng trong bộ phim truyền hình lịch sử." },
        ],
        notes: "Vừa là danh từ (dàn diễn viên) vừa là động từ (giao vai diễn).",
      },
      {
        id: "art15",
        term: "Canvas",
        phonetic: "/ˈkænvəs/",
        translation: "Vải bạt vẽ tranh, tấm toan",
        examples: [
          { en: "The artist stretched the canvas before applying oil paint.", vi: "Họa sĩ đã căng tấm toan vẽ tranh trước khi phủ sơn dầu lên." },
          { en: "He painted a stunning sunset on a large canvas.", vi: "Cậu ấy đã vẽ một cảnh hoàng hôn tuyệt đẹp trên một tấm vải bạt lớn." },
          { en: "Oil on canvas is a very traditional painting technique.", vi: "Sơn dầu trên vải toan là một kỹ thuật vẽ tranh rất truyền thống." },
        ],
        notes: "Loại vải thô dày chuyên dụng để họa sĩ vẽ tranh dầu hoặc acrylic.",
      },
      {
        id: "art16",
        term: "Sketch",
        phonetic: "/sketʃ/",
        translation: "Bản phác thảo, vẽ phác họa",
        examples: [
          { en: "The architect drew a quick sketch of the building layout.", vi: "Kiến trúc sư đã vẽ một bản phác thảo nhanh về bố cục tòa nhà." },
          { en: "She likes to sketch flowers in her notebook.", vi: "Cô ấy thích vẽ phác họa các loài hoa vào cuốn sổ của mình." },
          { en: "He made several sketches before starting the final painting.", vi: "Cậu ấy đã vẽ vài bản phác thảo trước khi bắt đầu bức tranh hoàn chỉnh cuối cùng." },
        ],
        notes: "Bản vẽ nhanh, đơn giản để ghi lại ý tưởng trước khi vẽ chi tiết.",
      },
      {
        id: "art17",
        term: "Cinematography",
        phonetic: "/ˌsɪnəməˈtɒɡrəfi/",
        translation: "Nghệ thuật quay phim, kỹ thuật điện ảnh",
        examples: [
          { en: "The breathtaking cinematography captured the beauty of the desert.", vi: "Nghệ thuật quay phim ngoạn mục đã ghi lại được vẻ đẹp của sa mạc." },
          { en: "He won an award for the cinematography of the documentary.", vi: "Anh ấy đã giành được một giải thưởng nhờ kỹ thuật quay phim của bộ phim tài liệu." },
          { en: "Excellent cinematography is crucial for sci-fi movies.", vi: "Kỹ thuật quay phim xuất sắc là điều tối quan trọng đối với các phim khoa học viễn tưởng." },
        ],
        notes: "Nghệ thuật và kỹ thuật sử dụng máy quay và ánh sáng trong điện ảnh.",
      },
      {
        id: "art18",
        term: "Gallery",
        phonetic: "/ˈɡæləri/",
        translation: "Phòng triển lãm nghệ thuật, nhà trưng bày",
        examples: [
          { en: "The local art gallery is showing paintings by local artists.", vi: "Phòng triển lãm nghệ thuật địa phương đang trưng bày các bức tranh của nghệ sĩ bản địa." },
          {
            en: "He was invited to exhibit his sculptures at a prestigious gallery in Paris.",
            vi: "Anh ấy đã được mời trưng bày các tác phẩm điêu khắc của mình tại một phòng triển lãm uy tín ở Paris.",
          },
          { en: "We spent hours walking through the modern art gallery.", vi: "Chúng tôi dành hàng giờ đồng hồ rảo bước qua phòng triển lãm nghệ thuật hiện đại." },
        ],
        notes: "Địa điểm chuyên trưng bày hoặc mua bán các tác phẩm nghệ thuật nghệ thuật.",
      },
      {
        id: "art19",
        term: "Masterful",
        phonetic: "/ˈmɑːstəfl/",
        translation: "Điêu luyện, tài tình, bậc thầy",
        examples: [
          { en: "The pianist gave a masterful performance of Beethoven's sonata.", vi: "Nghệ sĩ dương cầm đã mang lại một màn biểu diễn điêu luyện bản sonata của Beethoven." },
          { en: "The novel features a masterful description of the city's atmosphere.", vi: "Cuốn tiểu thuyết có một sự mô tả tài tình về bầu không khí của thành phố." },
          { en: "He is known for his masterful use of color in oil painting.", vi: "Ông nổi tiếng với việc sử dụng màu sắc bậc thầy điêu luyện trong tranh sơn dầu." },
        ],
        notes: "Tính từ chỉ kỹ năng cực kỳ điêu luyện của một chuyên gia hoặc nghệ sĩ.",
      },
      {
        id: "art20",
        term: "Adapt",
        phonetic: "/əˈdæpt/",
        translation: "Chuyển thể (phim, kịch) / Thích nghi",
        examples: [
          { en: "The studio plans to adapt the best-selling book into a movie.", vi: "Hãng phim có kế hoạch chuyển thể cuốn sách bán chạy nhất thành một bộ phim." },
          { en: "It takes time for international students to adapt to a new culture.", vi: "Phải mất thời gian để các sinh viên quốc tế thích nghi với một nền văn hóa mới." },
          { en: "The play was successfully adapted for a modern audience.", vi: "Vở kịch đã được chuyển thể thành công cho khán giả hiện đại thưởng thức." },
        ],
        notes: "Hành động biến đổi một tác phẩm văn học sang hình thức sân khấu hoặc điện ảnh.",
      },
    ],
  },
  {
    id: "topic_history_events_ta3",
    title: "Lịch sử & Sự kiện quốc tế",
    category: "topic",
    description: "Các sự kiện cột mốc, khảo cổ học cổ vật, chính sách ngoại giao và chế độ chính trị lịch sử.",
    color: "bg-indigo-800",
    words: [
      {
        id: "his1",
        term: "Empire",
        phonetic: "/ˈempaɪə/",
        translation: "Đế chế, đế quốc",
        examples: [
          { en: "The Roman Empire ruled over a vast territory for centuries.", vi: "Đế chế La Mã đã cai trị một vùng lãnh thổ rộng lớn suốt nhiều thế kỷ." },
          { en: "The book describes the rise and fall of the British Empire.", vi: "Cuốn sách mô tả sự hưng thịnh và suy tàn của Đế quốc Anh." },
          { en: "Historians study the economic factors of the ancient empire.", vi: "Các nhà sử học nghiên cứu các yếu tố kinh tế của đế chế cổ đại." },
        ],
        notes: "Nhóm quốc gia chịu sự cai trị của một hoàng đế hoặc chính phủ trung ương mạnh.",
      },
      {
        id: "his2",
        term: "Treaty",
        phonetic: "/ˈtriːti/",
        translation: "Hiệp ước quốc tế, hòa ước",
        examples: [
          { en: "The peace treaty was signed by both nations after long negotiations.", vi: "Hiệp ước hòa bình đã được ký kết bởi cả hai quốc gia sau những đàm phán dài." },
          { en: "They agreed to abide by the terms of the international environmental treaty.", vi: "Họ đồng ý tuân thủ các điều khoản của hiệp ước môi trường quốc tế." },
          { en: "The historic treaty led to a significant reduction in weapons.", vi: "Hiệp ước lịch sử đã dẫn đến sự cắt giảm vũ khí đáng kể." },
        ],
        notes: "Thỏa thuận chính thức bằng văn bản ký kết giữa các quốc gia.",
      },
      {
        id: "his3",
        term: "Revolution",
        phonetic: "/ˌrevəˈluːʃn/",
        translation: "Cuộc cách mạng",
        examples: [
          { en: "The French Revolution changed the political structure of Europe.", vi: "Cuộc Cách mạng Pháp đã thay đổi cấu trúc chính trị của châu Âu." },
          { en: "The industrial revolution led to rapid urbanization.", vi: "Cuộc cách mạng công nghiệp đã dẫn tới sự đô thị hóa nhanh chóng." },
          { en: "The introduction of the internet caused a revolution in communication.", vi: "Sự ra đời của internet đã tạo ra một cuộc cách mạng trong truyền thông." },
        ],
        notes: "Sự thay đổi căn bản, toàn diện về chế độ hoặc phương thức xã hội.",
      },
      {
        id: "his4",
        term: "Independence",
        phonetic: "/ˌɪndɪˈpendəns/",
        translation: "Sự độc lập, nền độc lập",
        examples: [
          { en: "Vietnam declared its independence on September second, 1945.", vi: "Việt Nam tuyên bố độc lập vào ngày hai tháng Chín năm 1945." },
          { en: "The colony fought a long war to gain its independence.", vi: "Thuộc địa đã chiến đấu một cuộc chiến dài để giành độc lập." },
          { en: "She enjoys the financial independence of having her own job.", vi: "Cô ấy tận hưởng sự độc lập về tài chính khi có công việc riêng của mình." },
        ],
        notes: "Danh từ của tính từ 'independent' (độc lập).",
      },
      {
        id: "his5",
        term: "Colony",
        phonetic: "/ˈkɒləni/",
        translation: "Thuộc địa / Bầy đàn côn trùng",
        examples: [
          { en: "America was once a British colony before gaining independence.", vi: "Mỹ từng là thuộc địa của Anh trước khi giành độc lập." },
          { en: "The country established colonies along the coast to trade.", vi: "Quốc gia này đã thành lập các thuộc địa dọc bờ biển để giao thương." },
          { en: "Scientists studied a colony of ants in the forest.", vi: "Các nhà khoa học đã nghiên cứu một đàn kiến trong rừng." },
        ],
        notes: "Vùng đất bị quốc gia khác xâm chiếm và kiểm soát chính trị.",
      },
      {
        id: "his6",
        term: "Alliance",
        phonetic: "/əˈlaɪəns/",
        translation: "Liên minh, khối liên minh",
        examples: [
          { en: "The two countries formed a military alliance to protect themselves.", vi: "Hai nước đã thành lập một liên minh quân sự để tự bảo vệ mình." },
          { en: "The political alliance helped them win the local election.", vi: "Liên minh chính trị đã giúp họ giành chiến thắng trong cuộc bầu cử địa phương." },
          { en: "They are entering into a strategic business alliance.", vi: "Họ đang bước vào một liên minh kinh doanh chiến lược." },
        ],
        notes: "Sự hợp tác chặt chẽ giữa các quốc gia hoặc tổ chức vì lợi ích chung.",
      },
      {
        id: "his7",
        term: "Conflict",
        phonetic: "/ˈkɒnflɪkt/",
        translation: "Cuộc xung đột, sự mâu thuẫn",
        examples: [
          { en: "Diplomats are trying to resolve the border conflict peacefully.", vi: "Các nhà ngoại giao đang nỗ lực giải quyết cuộc xung đột biên giới một cách hòa bình." },
          { en: "There is a conflict of interest in this business decision.", vi: "Có một sự mâu thuẫn lợi ích trong quyết định kinh doanh này." },
          { en: "His opinion conflicts with the official report of the committee.", vi: "Ý kiến của anh ấy mâu thuẫn trái ngược với báo cáo chính thức của ủy ban." },
        ],
        notes: "Vừa là danh từ (cuộc xung đột) vừa là động từ (mâu thuẫn, xung đột).",
      },
      {
        id: "his8",
        term: "Negotiation",
        phonetic: "/nɪˌɡəʊʃiˈeɪʃn/",
        translation: "Cuộc đàm phán, thương nghị",
        examples: [
          { en: "The negotiation between the two nations lasted for three days.", vi: "Cuộc đàm phán giữa hai nước đã kéo dài trong ba ngày." },
          { en: "They entered into trade negotiations last week.", vi: "Họ đã bước vào các cuộc đàm phán thương mại vào tuần trước." },
          { en: "Successful negotiation requires compromise from both sides.", vi: "Đàm phán thành công đòi hỏi sự thỏa hiệp từ cả hai bên." },
        ],
        notes: "Danh từ của động từ 'negotiate' (đàm phán).",
      },
      {
        id: "his9",
        term: "Civilization",
        phonetic: "/ˌsɪvəlaɪˈzeɪʃn/",
        translation: "Nền văn minh, sự khai hóa",
        examples: [
          { en: "Archaeologists study the ruins of ancient civilizations.", vi: "Các nhà khảo cổ học nghiên cứu tàn tích của các nền văn minh cổ đại." },
          { en: "Writing was a major step forward for human civilization.", vi: "Chữ viết đã là một bước tiến lớn đối với nền văn minh nhân loại." },
          { en: "They discovered traces of an advanced civilization in the jungle.", vi: "Họ đã phát hiện ra dấu vết của một nền văn minh tiên tiến trong rừng rậm." },
        ],
        notes: "Xã hội loài người đạt trình độ phát triển cao về văn hóa và tổ chức.",
      },
      {
        id: "his10",
        term: "Archaeology",
        phonetic: "/ˌɑːkiˈɒlədʒi/",
        translation: "Khảo cổ học",
        examples: [
          { en: "Archaeology helps us understand how prehistoric humans lived.", vi: "Khảo cổ học giúp chúng ta hiểu được con người tiền sử đã sống như thế nào." },
          { en: "She decided to study classical archaeology at university.", vi: "Cô ấy đã quyết định học ngành khảo cổ học cổ điển tại trường đại học." },
          { en: "The discoveries in archaeology have rewritten regional history.", vi: "Những phát hiện trong khảo cổ học đã viết lại lịch sử của khu vực." },
        ],
        notes: "Ngành khoa học nghiên cứu lịch sử qua di vật đào được dưới đất.",
      },
      {
        id: "his11",
        term: "Artifact",
        phonetic: "/ˈɑːtɪfækt/",
        translation: "Cổ vật, hiện vật lịch sử có giá trị",
        examples: [
          { en: "The museum displays priceless gold artifacts from ancient Egypt.", vi: "Bảo tàng trưng bày các cổ vật bằng vàng vô giá từ Ai Cập cổ đại." },
          { en: "It is illegal to sell historical artifacts on the black market.", vi: "Bán các cổ vật lịch sử trên thị trường chợ đen là bất hợp pháp." },
          { en: "The dig yielded many iron age tools and artifacts.", vi: "Cuộc khai quật đã thu được nhiều công cụ và cổ vật thời kỳ đồ sắt." },
        ],
        notes: "Công cụ, vũ khí hoặc trang sức được chế tác thủ công từ thời cổ đại.",
      },
      {
        id: "his12",
        term: "Era",
        phonetic: "/ˈɪərə/",
        translation: "Thời đại, kỷ nguyên",
        examples: [
          { en: "The introduction of AI marked the beginning of a new technological era.", vi: "Sự ra đời của AI đã đánh dấu sự khởi đầu của một kỷ nguyên công nghệ mới." },
          { en: "She enjoys reading history books about the Victorian era.", vi: "Cô ấy thích đọc sách lịch sử về thời đại Victoria." },
          { en: "We are living in an era of rapid globalization.", vi: "Chúng ta đang sống trong một thời đại toàn cầu hóa nhanh chóng." },
        ],
        notes: "Giai đoạn lịch sử đặc trưng bởi những sự kiện hoặc phong cách nổi bật.",
      },
      {
        id: "his13",
        term: "Landmark",
        phonetic: "/ˈlændmɑːk/",
        translation: "Sự kiện mốc, cột mốc lịch sử / Địa danh nổi tiếng",
        examples: [
          { en: "The 1964 act was a landmark event in the fight for civil rights.", vi: "Đạo luật năm 1964 đã là một sự kiện cột mốc trong cuộc đấu tranh giành dân quyền." },
          { en: "The Eiffel Tower is a famous landmark in Paris.", vi: "Tháp Eiffel là một địa danh nổi tiếng ở Paris." },
          { en: "The court's landmark decision changed school policies nationwide.", vi: "Quyết định mang tính bước ngoặt của tòa án đã thay đổi các chính sách trường học trên toàn quốc." },
        ],
        notes: "Sự kiện đánh dấu bước phát triển mới hoặc công trình nổi bật dễ nhận biết.",
      },
      {
        id: "his14",
        term: "Reign",
        phonetic: "/reɪn/",
        translation: "Triều đại, sự trị vì / Trị vì, ngự trị",
        examples: [
          { en: "Queen Victoria's long reign lasted for sixty-three years.", vi: "Sự trị vì lâu dài của Nữ hoàng Victoria đã kéo dài sáu mươi ba năm." },
          { en: "The king reigned over the country during a period of peace and wealth.", vi: "Nhà vua đã trị vì đất nước trong một thời kỳ hòa bình và thịnh vượng." },
          { en: "The museum features art from the reign of the Ming Dynasty.", vi: "Bảo tàng trưng bày nghệ thuật từ triều đại nhà Minh." },
        ],
        notes: "Phát âm giống hệt từ 'rain' (mưa) hoặc 'rein' (dây cương).",
      },
      {
        id: "his15",
        term: "Diplomacy",
        phonetic: "/dɪˈpləʊməsi/",
        translation: "Ngoại giao, ngành ngoại giao",
        examples: [
          { en: "The international dispute was resolved through careful diplomacy.", vi: "Tranh chấp quốc tế đã được giải quyết thông qua ngoại giao cẩn trọng." },
          { en: "She plans to pursue a career in international diplomacy.", vi: "Cô ấy có kế hoạch theo đuổi sự nghiệp trong ngành ngoại giao quốc tế." },
          { en: "The summit was a triumph of modern diplomacy.", vi: "Hội nghị thượng đỉnh đã là một thắng lợi của ngoại giao hiện đại." },
        ],
        notes: "Hoạt động duy trì quan hệ chính thức giữa các quốc gia.",
      },
      {
        id: "his16",
        term: "Democracy",
        phonetic: "/dɪˈmɒkrəsi/",
        translation: "Chế độ dân chủ, nền dân chủ",
        examples: [
          { en: "Freedom of speech is an essential element of democracy.", vi: "Tự do ngôn luận là một yếu tố thiết yếu của nền dân chủ." },
          { en: "The country transitioned to a stable democracy in the late nineties.", vi: "Đất nước đã chuyển dịch sang một nền dân chủ ổn định vào cuối những năm chín mươi." },
          { en: "The citizens voted to protect their democracy.", vi: "Các công dân đã bỏ phiếu để bảo vệ nền dân chủ của họ." },
        ],
        notes: "Hệ thống chính trị mà quyền lực thuộc về người dân thông qua bỏ phiếu.",
      },
      {
        id: "his17",
        term: "Monarchy",
        phonetic: "/ˈmɒnəki/",
        translation: "Chế độ quân chủ",
        examples: [
          { en: "The country has been a constitutional monarchy for centuries.", vi: "Quốc gia này đã là một nền quân chủ lập hiến suốt nhiều thế kỷ." },
          { en: "The revolution aimed to overthrow the absolute monarchy.", vi: "Cuộc cách mạng nhằm mục đích lật đổ chế độ quân chủ chuyên chế." },
          { en: "A monarchy is ruled by a king or a queen.", vi: "Chế độ quân chủ được cai trị bởi một vị vua hoặc một nữ hoàng." },
        ],
        notes: "Hệ thống chính trị do vua/nữ hoàng đứng đầu, truyền ngôi cha truyền con nối.",
      },
      {
        id: "his18",
        term: "Predecessor",
        phonetic: "/ˈpriːdɪsesə/",
        translation: "Người tiền nhiệm / Thiết bị thế hệ trước",
        examples: [
          { en: "The new president adopted a different policy from his predecessor.", vi: "Vị tân tổng thống đã áp dụng một chính sách khác biệt so với người tiền nhiệm của mình." },
          { en: "The new laptop model is much lighter than its predecessor.", vi: "Mẫu máy tính xách tay mới nhẹ hơn nhiều so với thế hệ trước của nó." },
          { en: "She learned a lot from her predecessor at the office.", vi: "Cô ấy đã học hỏi được rất nhiều từ người tiền nhiệm của mình tại văn phòng." },
        ],
        notes: "Người giữ chức vụ trước người hiện tại, trái nghĩa với 'successor' (người kế nhiệm).",
      },
      {
        id: "his19",
        term: "Summit",
        phonetic: "/ˈsʌmɪt/",
        translation: "Hội nghị thượng đỉnh / Đỉnh núi",
        examples: [
          { en: "Leaders of twenty nations gathered for the economic summit.", vi: "Nhà lãnh đạo của hai mươi quốc gia đã tụ họp cho hội nghị thượng đỉnh kinh tế." },
          { en: "The climbers finally reached the snowy summit of the mountain.", vi: "Những người leo núi cuối cùng đã lên tới đỉnh núi phủ đầy tuyết." },
          { en: "The summit discussed critical climate change issues.", vi: "Hội nghị thượng đỉnh đã thảo luận về các vấn đề biến đổi khí hậu quan trọng." },
        ],
        notes: "Hội nghị cấp cao nhất của các nguyên thủ quốc gia.",
      },
      {
        id: "his20",
        term: "Treaty of peace",
        phonetic: "/ˈtriːti əv piːs/",
        translation: "Hòa ước, hiệp ước hòa bình",
        examples: [
          { en: "After five years of war, they signed a historic treaty of peace.", vi: "Sau năm năm chiến tranh, họ đã ký kết một hòa ước lịch sử." },
          { en: "The treaty of peace established new borders between the rivals.", vi: "Hiệp ước hòa bình đã thiết lập những biên giới mới giữa hai đối thủ." },
          { en: "The terms of the treaty of peace were celebrated by citizens.", vi: "Các điều khoản của hòa ước đã được người dân ăn mừng đón nhận." },
        ],
        notes: "Cụm danh từ cố định dùng trong lịch sử và luật ngoại giao quốc tế.",
      },
    ],
  },
  {
    id: "topic_cuisine_ta3",
    title: "Ẩm thực thế giới",
    category: "topic",
    description: "Các khái niệm ẩm thực cao cấp, phong cách ẩm thực đặc thù, nguyên liệu dinh dưỡng và nghệ thuật nấu nướng tinh tế.",
    color: "bg-indigo-800",
    words: [
      {
        id: "cui1",
        term: "Cuisine",
        phonetic: "/kwɪˈziːn/",
        translation: "Ẩm thực, phong cách ẩm thực đặc trưng",
        examples: [
          { en: "Italian cuisine is famous for its simple and fresh ingredients.", vi: "Ẩm thực Ý nổi tiếng với các nguyên liệu đơn giản và tươi ngon." },
          { en: "She loves trying traditional Asian cuisine when traveling.", vi: "Cô ấy thích thử ẩm thực châu Á truyền thống khi đi du lịch." },
          { en: "The hotel restaurant offers a fusion of French and Japanese cuisine.", vi: "Nhà hàng khách sạn cung cấp một sự kết hợp giữa ẩm thực Pháp và Nhật." },
        ],
        notes: "Phong cách nấu ăn đặc trưng của một quốc gia hoặc một vùng miền.",
      },
      {
        id: "cui2",
        term: "Ingredient",
        phonetic: "/ɪnˈɡriːdiənt/",
        translation: "Nguyên liệu chế biến / Thành phần",
        examples: [
          { en: "The chef uses only locally sourced organic ingredients.", vi: "Đầu bếp chỉ sử dụng các nguyên liệu hữu cơ có nguồn gốc tại địa phương." },
          { en: "Mix all the dry ingredients in a large bowl first.", vi: "Hãy trộn tất cả các nguyên liệu khô vào một chiếc bát lớn trước." },
          { en: "Trust is an essential ingredient in a successful friendship.", vi: "Sự tin tưởng là một thành phần thiết yếu trong một tình bạn thành công." },
        ],
        notes: "Các thành phần thực phẩm dùng để nấu thành một món ăn.",
      },
      {
        id: "cui3",
        term: "Recipe",
        phonetic: "/ˈresəpi/",
        translation: "Công thức nấu ăn, công thức chế biến",
        examples: [
          { en: "This is a secret family recipe passed down from my grandmother.", vi: "Đây là một công thức nấu ăn gia đình bí mật được truyền lại từ bà của tôi." },
          { en: "Follow the recipe carefully to get the perfect texture.", vi: "Hãy làm theo công thức một cách cẩn thận để có được kết cấu hoàn hảo." },
          { en: "Can you share the recipe for this delicious chocolate cake?", vi: "Bạn có thể chia sẻ công thức cho chiếc bánh ngọt sô-cô-la ngon tuyệt này không?" },
        ],
        notes: "Phát âm là /ˈresəpi/ (không đọc là re-cip).",
      },
      {
        id: "cui4",
        term: "Flavor",
        phonetic: "/ˈfleɪvə/",
        translation: "Hương vị / Thêm gia vị hương liệu",
        examples: [
          { en: "This ice cream has a strong vanilla flavor.", vi: "Món kem này có hương vị va-ni rất đậm đà." },
          { en: "The chef added fresh herbs to enhance the flavor of the soup.", vi: "Đầu bếp đã thêm thảo mộc tươi để làm tăng hương vị của món súp." },
          { en: "You can flavor the sauce with a squeeze of lemon.", vi: "Bạn có thể tạo hương vị cho nước sốt bằng một vắt chanh." },
        ],
        notes: "Tiếng Anh-Mỹ viết là 'flavor', tiếng Anh-Anh viết là 'flavour'.",
      },
      {
        id: "cui5",
        term: "Specialty",
        phonetic: "/ˈspeʃəlti/",
        translation: "Đặc sản địa phương / Chuyên môn chuyên sâu",
        examples: [
          { en: "Pho is a famous noodle specialty of northern Vietnam.", vi: "Phở là một đặc sản mì nổi tiếng của miền Bắc Việt Nam." },
          { en: "This small bakery's specialty is warm apple pie.", vi: "Đặc sản của tiệm bánh nhỏ này là bánh táo nướng ấm nóng." },
          { en: "Her specialty is corporate law, but she also does family law.", vi: "Chuyên môn của cô ấy là luật doanh nghiệp, nhưng cô cũng làm về luật gia đình." },
        ],
        notes: "Món ăn nổi tiếng nhất hoặc thế mạnh chuyên môn của một địa phương/cá nhân.",
      },
      {
        id: "cui6",
        term: "Nutritious",
        phonetic: "/njuˈtrɪʃəs/",
        translation: "Bổ dưỡng, giàu dinh dưỡng",
        examples: [
          { en: "A green salad is a light and nutritious lunch choice.", vi: "Rau xà lách trộn là một lựa chọn bữa trưa nhẹ nhàng và giàu dinh dưỡng." },
          { en: "Parents should provide nutritious meals for growing children.", vi: "Cha mẹ nên cung cấp các bữa ăn bổ dưỡng cho trẻ em đang phát triển." },
          { en: "Nuts are high in fiber and extremely nutritious.", vi: "Các loại hạt chứa nhiều chất xơ và vô cùng bổ dưỡng." },
        ],
        notes: "Tính từ chỉ thực phẩm tốt cho sức khỏe có lợi cho cơ thể.",
      },
      {
        id: "cui7",
        term: "Beverage",
        phonetic: "/ˈbevərɪdʒ/",
        translation: "Đồ uống, thức uống (từ trang trọng)",
        examples: [
          { en: "The hotel lounge offers a wide selection of hot beverages.", vi: "Phòng chờ khách sạn cung cấp một danh mục lựa chọn phong phú các thức uống nóng." },
          { en: "Alcoholic beverages are not allowed inside the stadium.", vi: "Các đồ uống có cồn không được phép mang vào bên trong sân vận động." },
          { en: "Water is the healthiest beverage for daily consumption.", vi: "Nước lọc là thức uống lành mạnh nhất để tiêu thụ hàng ngày." },
        ],
        notes: "Từ trang trọng chỉ các loại chất lỏng dùng để uống, ngoại trừ nước lọc thông thường.",
      },
      {
        id: "cui8",
        term: "Seasoning",
        phonetic: "/ˈsiːzənɪŋ/",
        translation: "Gia vị nêm nếm, bột nêm",
        examples: [
          { en: "The chef adjusted the seasoning by adding a pinch of salt.", vi: "Đầu bếp đã điều chỉnh gia vị nêm nếm bằng cách thêm một nhúm muối." },
          { en: "This salt-free seasoning contains garlic and pepper.", vi: "Loại bột gia vị không muối này chứa tỏi và tiêu." },
          { en: "The chicken has a perfect balance of sweet and savory seasoning.", vi: "Món thịt gà có một sự cân bằng hoàn hảo của gia vị ngọt và mặn." },
        ],
        notes: "Muối, tiêu hoặc thảo mộc thêm vào để tăng vị ngon của món ăn.",
      },
      {
        id: "cui9",
        term: "Appetizer",
        phonetic: "/ˈæpɪtaɪzə/",
        translation: "Món khai vị",
        examples: [
          { en: "We ordered garlic bread and soup as an appetizer.", vi: "Chúng tôi đã gọi bánh mì tỏi và súp để làm món khai vị." },
          { en: "The dinner began with a light seafood appetizer.", vi: "Bữa tối bắt đầu bằng một món khai vị hải sản nhẹ nhàng." },
          { en: "The restaurant offers free appetizers for birthday guests.", vi: "Nhà hàng cung cấp các món khai vị miễn phí cho khách hàng tổ chức sinh nhật." },
        ],
        notes: "Món ăn nhẹ phục vụ trước món chính để kích thích sự thèm ăn. Tiếng Anh-Anh dùng 'starter'.",
      },
      {
        id: "cui10",
        term: "Main course",
        phonetic: "/meɪn kɔːs/",
        translation: "Món chính (trong bữa ăn)",
        examples: [
          { en: "For the main course, I ordered the grilled salmon.", vi: "Cho món ăn chính, tôi đã gọi món cá hồi nướng." },
          { en: "The main course was served with a side of vegetables.", vi: "Món chính được phục vụ đi kèm với một phần rau củ bên cạnh." },
          { en: "Is the main course big enough for two people?", vi: "Món chính có đủ lớn cho hai người ăn không?" },
        ],
        notes: "Phần ăn quan trọng và nhiều nhất trong một bữa ăn hoàn chỉnh.",
      },
      {
        id: "cui11",
        term: "Dessert",
        phonetic: "/dɪˈzɜːt/",
        translation: "Món tráng miệng",
        examples: [
          { en: "We had a slice of chocolate cake for dessert.", vi: "Chúng tôi đã ăn một lát bánh ngọt sô-cô-la để làm món tráng miệng." },
          { en: "She brought fresh fruit as a healthy dessert choice.", vi: "Cô ấy đã mang trái cây tươi đến như một lựa chọn tráng miệng lành mạnh." },
          { en: "What is the special dessert of the day?", vi: "Món tráng miệng đặc biệt của ngày hôm nay là gì thế?" },
        ],
        notes: "Tránh nhầm lẫn cách viết và phát âm với từ 'desert' (sa mạc - phát âm là /ˈdezət/).",
      },
      {
        id: "cui12",
        term: "Culinary",
        phonetic: "/ˈkʌlɪnəri/",
        translation: "Thuộc bếp núc, ẩm thực, nấu nướng",
        examples: [
          { en: "He went to France to study classic French culinary arts.", vi: "Cậu ấy đã sang Pháp để học nghệ thuật ẩm thực Pháp cổ điển." },
          { en: "The city has a rich culinary heritage with many local specials.", vi: "Thành phố có di sản ẩm thực phong phú với nhiều đặc sản địa phương." },
          { en: "She enjoys exploring different culinary traditions from around the world.", vi: "Cô ấy thích khám phá các truyền thống ẩm thực khác nhau từ khắp nơi trên thế giới." },
        ],
        notes: "Tính từ trang trọng liên quan đến việc nấu nướng và đồ ăn ngon.",
      },
      {
        id: "cui13",
        term: "Delicacy",
        phonetic: "/ˈdelɪkəsi/",
        translation: "Sự tinh tế / Món ăn cao lương mỹ vị, đồ ăn hiếm",
        examples: [
          { en: "Caviar is considered an expensive delicacy worldwide.", vi: "Trứng cá tầm được coi là một món cao lương mỹ vị đắt đỏ trên toàn thế giới." },
          { en: "She handled the fragile ceramic bowl with great delicacy.", vi: "Cô ấy đã cầm chiếc bát gốm dễ vỡ bằng một sự gượng nhẹ vô cùng tinh tế." },
          { en: "The local market is famous for selling regional delicacies.", vi: "Khu chợ địa phương nổi tiếng với việc bán các món đặc sản hiếm của vùng." },
        ],
        notes: "Món ăn ngon, hiếm và thường có giá trị rất cao.",
      },
      {
        id: "cui14",
        term: "Gourmet",
        phonetic: "/ˈɡʊəmeɪ/",
        translation: "Người sành ăn / Thuộc ẩm thực cao cấp",
        examples: [
          { en: "He is a true gourmet who writes reviews for luxury restaurants.", vi: "Anh ấy là một người sành ăn thực thụ chuyên viết bài đánh giá cho các nhà hàng xa xỉ." },
          { en: "The shop sells gourmet coffees and fine cheeses.", vi: "Cửa hàng bán các loại cà phê cao cấp sành điệu và phô mai hảo hạng." },
          { en: "She prepared a gourmet dinner for her business partners.", vi: "Cô ấy đã chuẩn bị một bữa tối sành điệu hảo hạng cho các đối tác kinh doanh." },
        ],
        notes: "Liên quan đến thức ăn chất lượng cao hoặc người am hiểu sâu về ẩm thực.",
      },
      {
        id: "cui15",
        term: "Vegetarian",
        phonetic: "/ˌvedʒəˈteəriən/",
        translation: "Người ăn chay / Chay, thuộc ăn chay",
        examples: [
          { en: "He became a vegetarian because of animal welfare concerns.", vi: "Cậu ấy đã trở thành một người ăn chay vì những lo ngại về phúc lợi động vật." },
          { en: "The restaurant has a variety of delicious vegetarian options.", vi: "Nhà hàng có nhiều lựa chọn món chay ngon lành phong phú." },
          { en: "She enjoys cooking vegetarian meals for her family.", vi: "Cô ấy thích nấu các bữa ăn chay cho gia đình mình." },
        ],
        notes: "Người không ăn thịt động vật, đôi khi vẫn ăn sữa hoặc trứng.",
      },
      {
        id: "cui16",
        term: "Dine",
        phonetic: "/daɪn/",
        translation: "Dùng bữa, dùng tiệc, ăn tối tối",
        examples: [
          { en: "We decided to dine out at a quiet restaurant near the river.", vi: "Chúng tôi quyết định dùng bữa tối bên ngoài tại một nhà hàng yên tĩnh gần sông." },
          { en: "They dined on fresh lobster and fine wine.", vi: "Họ đã dùng bữa tiệc với tôm hùm tươi và rượu vang hảo hạng." },
          { en: "She was invited to dine with the director of the company.", vi: "Cô ấy đã được mời dùng bữa tối cùng với giám đốc của công ty." },
        ],
        notes: "Động từ trang trọng của danh từ 'dinner' (bữa tối).",
      },
      {
        id: "cui17",
        term: "Spice",
        phonetic: "/spaɪs/",
        translation: "Gia vị cay, hương liệu gia vị / Thêm vị cay",
        examples: [
          { en: "Indian food is famous for its rich use of spices and herbs.", vi: "Món ăn Ấn Độ nổi tiếng vì sử dụng phong phú các gia vị và thảo mộc." },
          { en: "He added some hot spice to the sauce to make it fiery.", vi: "Anh ấy đã thêm chút gia vị cay vào nước sốt để làm nó nóng bỏng cay xè." },
          { en: "Travel can spice up your routine life.", vi: "Du lịch có thể thêm chút gia vị làm sống động cuộc sống thường nhật của bạn." },
        ],
        notes: "Bột hoặc hạt từ thực vật (tiêu, ớt, gừng) tạo vị cho món ăn.",
      },
      {
        id: "cui18",
        term: "Staple",
        phonetic: "/ˈsteɪpl/",
        translation: "Thực phẩm chủ lực, món chính thiết yếu / Kim bấm giấy",
        examples: [
          { en: "Rice is the staple food for more than half of the world's population.", vi: "Cơm/Gạo là thực phẩm chủ lực của hơn một nửa dân số thế giới." },
          { en: "Potatoes were the staple of the Irish diet in the nineteenth century.", vi: "Khoai tây từng là món chủ lực chính trong chế độ ăn của người Ireland thế kỷ 19." },
          { en: "I need a box of staples for the office stapler.", vi: "Tôi cần một hộp kim bấm cho chiếc máy bấm kim văn phòng." },
        ],
        notes: "Thực phẩm chính, thiết yếu được ăn thường xuyên nhất bởi một cộng đồng cư dân.",
      },
      {
        id: "cui19",
        term: "Ferment",
        phonetic: "/fəˈment/",
        translation: "Lên men / Quá trình lên men",
        examples: [
          { en: "Yeast is used to ferment sugar into alcohol when making beer.", vi: "Men được sử dụng để lên men đường thành cồn khi làm bia." },
          { en: "Kimchi is made from cabbage that has been allowed to ferment.", vi: "Kimchi được làm từ cải thảo đã được cho phép lên men." },
          { en: "Fermented foods like yogurt are beneficial for digestion.", vi: "Các thực phẩm lên men như sữa chua rất có lợi cho việc tiêu hóa." },
        ],
        notes: "Quá trình biến đổi hóa học hữu cơ nhờ vi sinh vật.",
      },
      {
        id: "cui20",
        term: "Presentation",
        phonetic: "/ˌpreznˈteɪʃn/",
        translation: "Sự bày trí món ăn / Buổi thuyết trình trình bày",
        examples: [
          { en: "In fine dining, the presentation of the dish is as important as the taste.", vi: "Trong ẩm thực cao cấp, sự bày trí của món ăn cũng quan trọng như hương vị của nó." },
          { en: "The chef paid great attention to the aesthetic presentation of the dessert.", vi: "Đầu bếp đã dành sự chú ý lớn đến sự bày trí thẩm mỹ của món tráng miệng." },
          { en: "She gave an outstanding presentation on market trends.", vi: "Cô ấy đã đưa ra một bài thuyết trình xuất sắc về các xu hướng thị trường." },
        ],
        notes: "Trong ẩm thực chỉ cách bày trí đĩa ăn đẹp mắt.",
      },
    ],
  },
];
