export const tierSilverII = [
  {
    id: "topic_family_b2",
    title: "Chủ đề: Gia đình",
    category: "topic",
    description: "Từ vựng về các thành viên và các mối quan hệ cơ bản trong gia đình.",
    color: "bg-blue-500",
    words: [
      {
        id: "fam1",
        term: "Mother",
        phonetic: "/ˈmʌðə/",
        translation: "Mẹ",
        examples: [
          { en: "My mother cooks very well.", vi: "Mẹ tôi nấu ăn rất ngon." },
          { en: "I love my mother.", vi: "Tôi yêu mẹ của tôi." },
          { en: "She is a kind mother.", vi: "Bà ấy là một người mẹ hiền hậu." },
        ],
        notes: "Có thể dùng từ thân mật hơn là 'Mom' hoặc 'Mum'.",
      },
      {
        id: "fam2",
        term: "Brother",
        phonetic: "/ˈbrʌðə/",
        translation: "Anh/em trai",
        examples: [
          { en: "I have one older brother.", vi: "Tôi có một người anh trai." },
          { en: "My brother plays football.", vi: "Em trai tôi chơi đá bóng." },
          { en: "Are you his brother?", vi: "Bạn có phải là anh trai của cậu ấy không?" },
        ],
        notes: "Dùng 'older brother' cho anh trai và 'younger brother' cho em trai.",
      },
      {
        id: "fam3",
        term: "Sister",
        phonetic: "/ˈsɪstə/",
        translation: "Chị/em gái",
        examples: [
          { en: "My sister is a student.", vi: "Chị gái tôi là học sinh." },
          { en: "She has two younger sisters.", vi: "Cô ấy có hai người em gái." },
          { en: "I help my sister with her homework.", vi: "Tôi giúp em gái làm bài tập về nhà." },
        ],
        notes: "Dùng 'older sister' cho chị gái và 'younger sister' cho em gái.",
      },
      {
        id: "fam4",
        term: "Parent",
        phonetic: "/ˈpeərənt/",
        translation: "Cha, mẹ (phụ huynh)",
        examples: [
          { en: "Every parent loves their children.", vi: "Mỗi bậc cha mẹ đều yêu thương con cái của họ." },
          { en: "I live with my parents.", vi: "Tôi sống cùng với bố mẹ tôi." },
          { en: "Her parents are both teachers.", vi: "Bố mẹ cô ấy đều là giáo viên." },
        ],
        notes: "Dạng số nhiều 'parents' chỉ cả cha lẫn mẹ.",
      },
      {
        id: "fam5",
        term: "Grandmother",
        phonetic: "/ˈɡrænˌmʌðə/",
        translation: "Bà",
        examples: [
          { en: "My grandmother is eighty years old.", vi: "Bà của tôi tám mươi tuổi." },
          { en: "I visit my grandmother on weekends.", vi: "Tôi đến thăm bà vào những ngày cuối tuần." },
          { en: "She is a wonderful grandmother.", vi: "Bà là một người bà tuyệt vời." },
        ],
        notes: "Thường được gọi thân mật là 'Grandma' hoặc 'Granny'.",
      },
      {
        id: "fam6",
        term: "Grandfather",
        phonetic: "/ˈɡrændˌfɑːðə/",
        translation: "Ông",
        examples: [
          { en: "My grandfather likes reading newspapers.", vi: "Ông tôi thích đọc báo." },
          { en: "He lives with my grandfather.", vi: "Anh ấy sống cùng với ông nội." },
          { en: "My grandfather tells great stories.", vi: "Ông tôi kể những câu chuyện rất hay." },
        ],
        notes: "Thường được gọi thân mật là 'Grandpa'.",
      },
      {
        id: "fam7",
        term: "Son",
        phonetic: "/sʌn/",
        translation: "Con trai (đối với cha mẹ)",
        examples: [
          { en: "They have a ten-year-old son.", vi: "Họ có một người con trai mười tuổi." },
          { en: "He is the only son in the family.", vi: "Cậu ấy là đứa con trai duy nhất trong gia đình." },
          { en: "My son loves drawing.", vi: "Con trai tôi rất thích vẽ." },
        ],
        notes: "Tránh nhầm lẫn cách phát âm với từ 'sun' (mặt trời).",
      },
      {
        id: "fam8",
        term: "Daughter",
        phonetic: "/ˈdɔːtə/",
        translation: "Con gái (đối với cha mẹ)",
        examples: [
          { en: "Her daughter is very beautiful.", vi: "Con gái của cô ấy rất xinh đẹp." },
          { en: "They have two daughters.", vi: "Họ có hai người con gái." },
          { en: "I am the eldest daughter.", vi: "Tôi là con gái trưởng." },
        ],
        notes: "Trái nghĩa với 'son'.",
      },
      {
        id: "fam9",
        term: "Uncle",
        phonetic: "/ˈʌŋkl/",
        translation: "Chú, bác trai, cậu, dượng",
        examples: [
          { en: "My uncle lives in London.", vi: "Chú tôi sống ở Luân Đôn." },
          { en: "He is my father's brother, my uncle.", vi: "Bác ấy là anh trai của bố tôi, bác của tôi." },
          { en: "My uncle gave me a watch.", vi: "Dượng tôi đã tặng tôi một chiếc đồng hồ." },
        ],
        notes: "Dùng chung cho tất cả họ hàng nam giới lớn tuổi hơn thuộc thế hệ cha mẹ.",
      },
      {
        id: "fam10",
        term: "Aunt",
        phonetic: "/ɑːnt/",
        translation: "Cô, dì, bác gái, mợ, thím",
        examples: [
          { en: "My aunt is very friendly.", vi: "Dì của tôi rất thân thiện." },
          { en: "I go shopping with my aunt.", vi: "Tôi đi mua sắm với cô tôi." },
          { en: "She is an aunt of three children.", vi: "Bà ấy là cô của ba đứa trẻ." },
        ],
        notes: "Dùng chung cho tất cả họ hàng nữ giới lớn tuổi hơn thuộc thế hệ cha mẹ.",
      },
      {
        id: "fam11",
        term: "Cousin",
        phonetic: "/ˈkʌzn/",
        translation: "Anh, chị, em họ",
        examples: [
          { en: "He is my cousin, not my brother.", vi: "Cậu ấy là anh họ của tôi, không phải anh ruột." },
          { en: "I play video games with my cousins.", vi: "Tôi chơi trò chơi điện tử với các anh em họ của mình." },
          { en: "My cousin is visiting us today.", vi: "Hôm nay người em họ của tôi đến chơi." },
        ],
        notes: "Dùng cho cả nam lẫn nữ.",
      },
      {
        id: "fam12",
        term: "Husband",
        phonetic: "/ˈhʌzbənd/",
        translation: "Chồng",
        examples: [
          { en: "Her husband is a chef.", vi: "Chồng cô ấy là một đầu bếp." },
          { en: "He is a loving husband.", vi: "Anh ấy là một người chồng yêu thương gia đình." },
          { en: "She met her husband at university.", vi: "Cô ấy đã gặp chồng mình ở trường đại học." },
        ],
        notes: "Từ trái nghĩa là 'wife' (vợ).",
      },
      {
        id: "fam13",
        term: "Wife",
        phonetic: "/waɪf/",
        translation: "Vợ",
        examples: [
          { en: "My wife is a doctor.", vi: "Vợ tôi là bác sĩ." },
          { en: "He bought flowers for his wife.", vi: "Anh ấy đã mua hoa cho vợ mình." },
          { en: "They have been husband and wife for ten years.", vi: "Họ đã là vợ chồng được mười năm rồi." },
        ],
        notes: "Số nhiều của 'wife' là 'wives' (bất quy tắc).",
      },
      {
        id: "fam14",
        term: "Child",
        phonetic: "/tʃaɪld/",
        translation: "Đứa trẻ, con cái",
        examples: [
          { en: "The child is playing with a toy.", vi: "Đứa trẻ đang chơi với một món đồ chơi." },
          { en: "They have only one child.", vi: "Họ chỉ có một đứa con." },
          { en: "She works with children.", vi: "Cô ấy làm việc với trẻ em." },
        ],
        notes: "Số nhiều của 'child' là 'children' (bất quy tắc).",
      },
      {
        id: "fam15",
        term: "Baby",
        phonetic: "/ˈbeɪbi/",
        translation: "Em bé, trẻ sơ sinh",
        examples: [
          { en: "The baby is sleeping in the crib.", vi: "Em bé đang ngủ trong nôi." },
          { en: "She has a new baby.", vi: "Cô ấy mới sinh em bé." },
          { en: "The baby is crying.", vi: "Đứa bé đang khóc." },
        ],
        notes: "Dành cho trẻ rất nhỏ chưa biết đi hoặc mới sinh.",
      },
      {
        id: "fam16",
        term: "Family",
        phonetic: "/ˈfæməli/",
        translation: "Gia đình",
        examples: [
          { en: "I love my family.", vi: "Tôi yêu gia đình tôi." },
          { en: "We are a big family.", vi: "Chúng tôi là một gia đình lớn." },
          { en: "They had a family dinner last night.", vi: "Họ đã có một bữa tối gia đình vào tối qua." },
        ],
        notes: "Danh từ tập hợp, có thể đi với động từ số ít hoặc số nhiều tùy ngữ cảnh.",
      },
      {
        id: "fam17",
        term: "Relative",
        phonetic: "/ˈrelətɪv/",
        translation: "Họ hàng, người thân",
        examples: [
          { en: "We invited many relatives to the party.", vi: "Chúng tôi đã mời nhiều họ hàng đến bữa tiệc." },
          { en: "She is a distant relative of mine.", vi: "Cô ấy là một người họ hàng xa của tôi." },
          { en: "I have relatives living in America.", vi: "Tôi có họ hàng đang sống ở Mỹ." },
        ],
        notes: "Chỉ chung những người có quan hệ huyết thống hoặc hôn nhân.",
      },
      {
        id: "fam18",
        term: "Nephew",
        phonetic: "/ˈnefjuː/",
        translation: "Cháu trai (con của anh/chị/em)",
        examples: [
          { en: "My nephew is starting school today.", vi: "Cháu trai tôi bắt đầu đi học từ hôm nay." },
          { en: "He is the nephew of the president.", vi: "Cậu ấy là cháu trai của chủ tịch." },
          { en: "I bought a toy for my nephew.", vi: "Tôi đã mua một món đồ chơi cho cháu trai mình." },
        ],
        notes: "Chỉ cháu trai thế hệ dưới, phân biệt với cháu nội/ngoại (grandson).",
      },
      {
        id: "fam19",
        term: "Niece",
        phonetic: "/niːs/",
        translation: "Cháu gái (con của anh/chị/em)",
        examples: [
          { en: "My niece is very good at music.", vi: "Cháu gái tôi rất giỏi âm nhạc." },
          { en: "She takes care of her little niece.", vi: "Cô ấy chăm sóc đứa cháu gái nhỏ của mình." },
          { en: "We have three nieces.", vi: "Chúng tôi có ba đứa cháu gái." },
        ],
        notes: "Chỉ cháu gái thế hệ dưới, phân biệt với cháu nội/ngoại (granddaughter).",
      },
      {
        id: "fam20",
        term: "Married",
        phonetic: "/ˈmærid/",
        translation: "Đã kết hôn",
        examples: [
          { en: "They have been married for five years.", vi: "Họ đã kết hôn được năm năm." },
          { en: "Is she married?", vi: "Cô ấy đã kết hôn chưa?" },
          { en: "They are a happily married couple.", vi: "Họ là một cặp vợ chồng kết hôn hạnh phúc." },
        ],
        notes: "Tính từ, thường đi sau động từ 'get' hoặc 'be'.",
      },
    ],
  },
  {
    id: "topic_pets_b2",
    title: "Chủ đề: Động vật nuôi",
    category: "topic",
    description: "Các loại thú cưng và động vật nuôi quen thuộc xung quanh con người.",
    color: "bg-yellow-500",
    words: [
      {
        id: "pet1",
        term: "Dog",
        phonetic: "/dɒɡ/",
        translation: "Con chó",
        examples: [
          { en: "I walk my dog every evening.", vi: "Tôi dắt chó đi dạo mỗi tối." },
          { en: "The dog is barking loudly.", vi: "Con chó đang sủa rất to." },
          { en: "He has a small black dog.", vi: "Anh ấy có một con chó nhỏ màu đen." },
        ],
        notes: "Loài vật trung thành, thú cưng phổ biến nhất.",
      },
      {
        id: "pet2",
        term: "Cat",
        phonetic: "/kæt/",
        translation: "Con mèo",
        examples: [
          { en: "My cat likes sleeping on the sofa.", vi: "Con mèo của tôi thích ngủ trên ghế sofa." },
          { en: "The cat is chasing a mouse.", vi: "Con mèo đang đuổi theo một con chuột." },
          { en: "She fed her cat this morning.", vi: "Cô ấy đã cho mèo ăn sáng nay." },
        ],
        notes: "Thú cưng phổ biến thứ hai.",
      },
      {
        id: "pet3",
        term: "Fish",
        phonetic: "/fɪʃ/",
        translation: "Con cá",
        examples: [
          { en: "He keeps gold fish in a small bowl.", vi: "Anh ấy nuôi cá vàng trong một cái bể nhỏ." },
          { en: "Do you like eating fish?", vi: "Bạn có thích ăn cá không?" },
          { en: "There are many fish in the pond.", vi: "Có rất nhiều cá ở trong ao." },
        ],
        notes: "Danh từ số nhiều vẫn giữ nguyên là 'fish' (hoặc 'fishes' khi chỉ nhiều loài khác nhau).",
      },
      {
        id: "pet4",
        term: "Bird",
        phonetic: "/bɜːd/",
        translation: "Con chim",
        examples: [
          { en: "The bird is singing in the tree.", vi: "Con chim đang hót trên cây." },
          { en: "She has a pet bird in her room.", vi: "Cô ấy nuôi một con chim cảnh trong phòng." },
          { en: "Look at that beautiful blue bird.", vi: "Hãy nhìn con chim màu xanh dương xinh đẹp kia kìa." },
        ],
        notes: "Có thể dùng từ cụ thể hơn như 'canary' (yến yến) hay 'pigeon' (bồ câu).",
      },
      {
        id: "pet5",
        term: "Rabbit",
        phonetic: "/ˈræbɪt/",
        translation: "Con thỏ",
        examples: [
          { en: "The rabbit has long ears.", vi: "Con thỏ có đôi tai dài." },
          { en: "Rabbits love eating carrots.", vi: "Thỏ rất thích ăn cà rốt." },
          { en: "My younger sister wants a pet rabbit.", vi: "Em gái tôi muốn nuôi một chú thỏ cảnh." },
        ],
        notes: "Loài vật hiền lành, di chuyển bằng cách nhảy.",
      },
      {
        id: "pet6",
        term: "Chicken",
        phonetic: "/ˈtʃɪkɪn/",
        translation: "Con gà",
        examples: [
          { en: "The chicken is laying an egg.", vi: "Con gà đang đẻ trứng." },
          { en: "We raise chickens in the backyard.", vi: "Chúng tôi nuôi gà ở sân sau." },
          { en: "Do you want chicken for dinner?", vi: "Bạn có muốn ăn thịt gà vào bữa tối không?" },
        ],
        notes: "Chỉ chung cả gà sống lẫn thịt gà.",
      },
      {
        id: "pet7",
        term: "Duck",
        phonetic: "/dʌk/",
        translation: "Con vịt",
        examples: [
          { en: "The ducks are swimming in the lake.", vi: "Những con vịt đang bơi dưới hồ." },
          { en: "We heard the duck quack.", vi: "Chúng tôi nghe tiếng vịt kêu cạp cạp." },
          { en: "The baby duck is so cute.", vi: "Chú vịt con thật đáng yêu." },
        ],
        notes: "Vịt con được gọi là 'duckling'.",
      },
      {
        id: "pet8",
        term: "Pig",
        phonetic: "/pɪɡ/",
        translation: "Con lợn, heo",
        examples: [
          { en: "The pig is sleeping in the mud.", vi: "Con lợn đang ngủ trong bùn." },
          { en: "Farmers feed pigs with vegetables.", vi: "Người nông dân cho lợn ăn rau củ." },
          { en: "He bought a piglet yesterday.", vi: "Anh ấy đã mua một con lợn con hôm qua." },
        ],
        notes: "Lợn con được gọi là 'piglet'.",
      },
      {
        id: "pet9",
        term: "Cow",
        phonetic: "/kaʊ/",
        translation: "Con bò",
        examples: [
          { en: "The cow gives us milk.", vi: "Con bò cho chúng ta sữa." },
          { en: "There are ten cows on the farm.", vi: "Có mười con bò ở trang trại." },
          { en: "A cow is eating grass.", vi: "Một con bò đang ăn cỏ." },
        ],
        notes: "Thường chỉ bò sữa hoặc bò cái.",
      },
      {
        id: "pet10",
        term: "Horse",
        phonetic: "/hɔːs/",
        translation: "Con ngựa",
        examples: [
          { en: "Can you ride a horse?", vi: "Bạn có biết cưỡi ngựa không?" },
          { en: "The horse runs very fast.", vi: "Con ngựa chạy rất nhanh." },
          { en: "He fed the horse some apples.", vi: "Anh ấy đã cho con ngựa ăn vài quả táo." },
        ],
        notes: "Động vật có vú lớn, dùng để kéo xe hoặc cưỡi.",
      },
      {
        id: "pet11",
        term: "Sheep",
        phonetic: "/ʃiːp/",
        translation: "Con cừu",
        examples: [
          { en: "The sheep are grazing on the hill.", vi: "Đàn cừu đang gặm cỏ trên đồi." },
          { en: "We get wool from sheep.", vi: "Chúng ta lấy len từ cừu." },
          { en: "The white sheep looks soft.", vi: "Con cừu trắng trông thật mềm mại." },
        ],
        notes: "Số nhiều vẫn giữ nguyên là 'sheep'.",
      },
      {
        id: "pet12",
        term: "Goat",
        phonetic: "/ɡəʊt/",
        translation: "Con dê",
        examples: [
          { en: "The goat has sharp horns.", vi: "Con dê có cặp sừng sắc nhọn." },
          { en: "Goat milk is very healthy.", vi: "Sữa dê rất tốt cho sức khỏe." },
          { en: "A goat is jumping over the fence.", vi: "Một con dê đang nhảy qua hàng rào." },
        ],
        notes: "Động vật nhai lại, thích leo trèo.",
      },
      {
        id: "pet13",
        term: "Mouse",
        phonetic: "/maʊs/",
        translation: "Con chuột",
        examples: [
          { en: "A little mouse ran across the floor.", vi: "Một con chuột nhỏ chạy vụt qua sàn nhà." },
          { en: "The cat caught a mouse.", vi: "Con mèo đã bắt được một con chuột." },
          { en: "There is a mouse hole in the wall.", vi: "Có một cái tổ chuột ở trên tường." },
        ],
        notes: "Số nhiều là 'mice' (bất quy tắc).",
      },
      {
        id: "pet14",
        term: "Parrot",
        phonetic: "/ˈpærət/",
        translation: "Con vẹt",
        examples: [
          { en: "The parrot can repeat my words.", vi: "Con vẹt có thể nhắc lại những từ của tôi." },
          { en: "He bought a colorful parrot.", vi: "Anh ấy đã mua một con vẹt nhiều màu sắc." },
          { en: "A parrot can talk like a human.", vi: "Vẹt có thể nói chuyện như con người." },
        ],
        notes: "Loài chim thông minh, có khả năng bắt chước âm thanh.",
      },
      {
        id: "pet15",
        term: "Hamster",
        phonetic: "/ˈhæmstə/",
        translation: "Chuột hamster",
        examples: [
          { en: "My hamster loves running on the wheel.", vi: "Chú chuột hamster của tôi thích chạy trên bánh xe." },
          { en: "I feed my hamster sunflower seeds.", vi: "Tôi cho chú chuột hamster ăn hạt hướng dương." },
          { en: "The hamster is sleeping in its small house.", vi: "Chú chuột hamster đang ngủ trong ngôi nhà nhỏ của nó." },
        ],
        notes: "Thú cưng gặm nhấm nhỏ rất được yêu thích.",
      },
      {
        id: "pet16",
        term: "Pet",
        phonetic: "/pet/",
        translation: "Thú cưng, vật nuôi",
        examples: [
          { en: "Do you have any pets?", vi: "Bạn có nuôi thú cưng nào không?" },
          { en: "Keep your pet safe inside.", vi: "Hãy giữ thú cưng của bạn an toàn ở trong nhà." },
          { en: "She loves her pet very much.", vi: "Cô ấy yêu thú cưng của mình rất nhiều." },
        ],
        notes: "Chỉ chung các động vật nuôi trong nhà để làm bạn.",
      },
      {
        id: "pet17",
        term: "Tail",
        phonetic: "/teɪl/",
        translation: "Cái đuôi",
        examples: [
          { en: "The dog is wagging its tail.", vi: "Con chó đang vẫy đuôi." },
          { en: "The cat has a long black tail.", vi: "Con mèo có một cái đuôi dài màu đen." },
          { en: "A rabbit has a short tail.", vi: "Con thỏ có một cái đuôi ngắn." },
        ],
        notes: "Bộ phận ở phía sau thân của nhiều động vật.",
      },
      {
        id: "pet18",
        term: "Fur",
        phonetic: "/fɜː/",
        translation: "Lông thú (mềm)",
        examples: [
          { en: "The cat has very soft fur.", vi: "Con mèo có bộ lông rất mềm mại." },
          { en: "His coat is made of warm fur.", vi: "Chiếc áo khoác của anh ấy làm bằng lông thú ấm áp." },
          { en: "The dog's fur is brown.", vi: "Lông của con chó có màu nâu." },
        ],
        notes: "Chỉ lớp lông dày và mềm của động vật có vú, phân biệt với 'feather' (lông vũ).",
      },
      {
        id: "pet19",
        term: "Feed",
        phonetic: "/fiːd/",
        translation: "Cho ăn, nuôi nấng",
        examples: [
          { en: "Don't forget to feed the dog.", vi: "Đừng quên cho chó ăn nhé." },
          { en: "What do you feed your cat?", vi: "Bạn cho mèo của bạn ăn gì?" },
          { en: "She feeds the birds every morning.", vi: "Cô ấy cho chim ăn mỗi buổi sáng." },
        ],
        notes: "Động từ bất quy tắc (quá khứ là 'fed').",
      },
      {
        id: "pet20",
        term: "Cage",
        phonetic: "/keɪdʒ/",
        translation: "Cái lồng, chuồng",
        examples: [
          { en: "The bird is in its cage.", vi: "Con chim đang ở trong lồng của nó." },
          { en: "Please close the cage door.", vi: "Làm ơn hãy đóng cửa chuồng lại." },
          { en: "Do not keep animals in small cages.", vi: "Đừng nhốt động vật trong những cái lồng nhỏ." },
        ],
        notes: "Thường dùng để nhốt chim, thỏ hoặc chuột cảnh.",
      },
    ],
  },
  {
    id: "topic_food_b2",
    title: "Chủ đề: Đồ ăn & Thức uống",
    category: "topic",
    description: "Các món ăn, thức uống và gia vị thông thường hàng ngày.",
    color: "bg-green-500",
    words: [
      {
        id: "fod1",
        term: "Food",
        phonetic: "/fuːd/",
        translation: "Thức ăn, thực phẩm",
        examples: [
          { en: "We need food to live.", vi: "Chúng ta cần thức ăn để sống." },
          { en: "Do you like Italian food?", vi: "Bạn có thích món ăn Ý không?" },
          { en: "This supermarket sells fresh food.", vi: "Siêu thị này bán thực phẩm tươi sống." },
        ],
        notes: "Chỉ chung mọi loại đồ ăn.",
      },
      {
        id: "fod2",
        term: "Drink",
        phonetic: "/drɪŋk/",
        translation: "Đồ uống / Uống",
        examples: [
          { en: "Would you like something to drink?", vi: "Bạn có muốn uống thứ gì đó không?" },
          { en: "Water is the best drink for your health.", vi: "Nước là đồ uống tốt nhất cho sức khỏe của bạn." },
          { en: "He drinks tea without sugar.", vi: "Anh ấy uống trà không đường." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "fod3",
        term: "Water",
        phonetic: "/ˈwɔːtə/",
        translation: "Nước",
        examples: [
          { en: "Can I have a glass of water, please?", vi: "Cho tôi xin một cốc nước được không?" },
          { en: "Drink plenty of water every day.", vi: "Hãy uống nhiều nước mỗi ngày." },
          { en: "The water in this river is clean.", vi: "Nước ở dòng sông này rất sạch." },
        ],
        notes: "Danh từ không đếm được.",
      },
      {
        id: "fod4",
        term: "Bread",
        phonetic: "/bred/",
        translation: "Bánh mì",
        examples: [
          { en: "I eat bread with butter.", vi: "Tôi ăn bánh mì với bơ." },
          { en: "He bought a loaf of fresh bread.", vi: "Anh ấy đã mua một ổ bánh mì tươi." },
          { en: "We make sandwiches with bread.", vi: "Chúng tôi làm bánh kẹp bằng bánh mì." },
        ],
        notes: "Danh từ không đếm được, dùng 'a loaf of bread' để chỉ một ổ bánh mì.",
      },
      {
        id: "fod5",
        term: "Rice",
        phonetic: "/raɪs/",
        translation: "Cơm, gạo, lúa",
        examples: [
          { en: "Rice is very popular in Vietnam.", vi: "Cơm/Gạo rất phổ biến ở Việt Nam." },
          { en: "Do you want some more rice?", vi: "Bạn có muốn ăn thêm cơm không?" },
          { en: "They grow rice in the fields.", vi: "Họ trồng lúa trên những cánh đồng." },
        ],
        notes: "Món ăn chính của người châu Á.",
      },
      {
        id: "fod6",
        term: "Milk",
        phonetic: "/mɪlk/",
        translation: "Sữa",
        examples: [
          { en: "I drink hot milk before bed.", vi: "Tôi uống sữa nóng trước khi đi ngủ." },
          { en: "Do you put milk in your coffee?", vi: "Bạn có bỏ sữa vào cà phê không?" },
          { en: "Milk is rich in calcium.", vi: "Sữa rất giàu canxi." },
        ],
        notes: "Sữa bò được gọi là 'cow's milk'.",
      },
      {
        id: "fod7",
        term: "Tea",
        phonetic: "/tiː/",
        translation: "Trà, chè",
        examples: [
          { en: "She loves drinking green tea.", vi: "Cô ấy thích uống trà xanh." },
          { en: "Would you like a cup of tea?", vi: "Bạn có muốn một tách trà không?" },
          { en: "They serve tea with lemon.", vi: "Họ phục vụ trà kèm chanh." },
        ],
        notes: "Thức uống phổ biến trên thế giới.",
      },
      {
        id: "fod8",
        term: "Coffee",
        phonetic: "/ˈkɒfi/",
        translation: "Cà phê",
        examples: [
          { en: "He drinks black coffee in the morning.", vi: "Anh ấy uống cà phê đen vào buổi sáng." },
          { en: "Coffee can keep you awake.", vi: "Cà phê có thể giúp bạn tỉnh táo." },
          { en: "I prefer coffee to tea.", vi: "Tôi thích cà phê hơn trà." },
        ],
        notes: "Thường có chất caffeine giúp tỉnh táo.",
      },
      {
        id: "fod9",
        term: "Meat",
        phonetic: "/miːt/",
        translation: "Thịt (động vật nói chung)",
        examples: [
          { en: "He does not eat meat; he is a vegetarian.", vi: "Anh ấy không ăn thịt; anh ấy là người ăn chay." },
          { en: "I need to buy some fresh meat.", vi: "Tôi cần mua một ít thịt tươi." },
          { en: "This restaurant serves delicious grilled meat.", vi: "Nhà hàng này phục vụ món thịt nướng rất ngon." },
        ],
        notes: "Dùng chung cho thịt gia súc, gia cầm trước khi phân loại thành pork, beef...",
      },
      {
        id: "fod10",
        term: "Fruit",
        phonetic: "/fruːt/",
        translation: "Trái cây, hoa quả",
        examples: [
          { en: "Fruit is good for your health.", vi: "Trái cây rất tốt cho sức khỏe của bạn." },
          { en: "I love eating fresh fruit in summer.", vi: "Tôi thích ăn trái cây tươi vào mùa hè." },
          { en: "Apples and oranges are fruits.", vi: "Táo và cam là các loại trái cây." },
        ],
        notes: "Thường được dùng làm danh từ không đếm được.",
      },
      {
        id: "fod11",
        term: "Vegetable",
        phonetic: "/ˈvedʒtəbl/",
        translation: "Rau, củ",
        examples: [
          { en: "Children should eat more vegetables.", vi: "Trẻ em nên ăn nhiều rau củ hơn." },
          { en: "We grow vegetables in our garden.", vi: "Chúng tôi trồng rau trong vườn nhà." },
          { en: "Green vegetables are rich in vitamins.", vi: "Rau xanh rất giàu vitamin." },
        ],
        notes: "Danh từ đếm được, thường dùng dạng số nhiều 'vegetables'.",
      },
      {
        id: "fod12",
        term: "Apple",
        phonetic: "/ˈæpl/",
        translation: "Quả táo",
        examples: [
          { en: "An apple a day keeps the doctor away.", vi: "Mỗi ngày ăn một quả táo sẽ giúp bạn luôn khỏe mạnh." },
          { en: "He sliced the red apple.", vi: "Anh ấy đã thái lát quả táo đỏ." },
          { en: "I want an apple pie.", vi: "Tôi muốn một chiếc bánh táo." },
        ],
        notes: "Mẹo học: Đi với mạo từ 'an' vì bắt đầu bằng nguyên âm.",
      },
      {
        id: "fod13",
        term: "Sugar",
        phonetic: "/ˈʃʊɡə/",
        translation: "Đường (gia vị)",
        examples: [
          { en: "Do you take sugar in your tea?", vi: "Bạn có uống trà với đường không?" },
          { en: "Too much sugar is bad for your teeth.", vi: "Ăn quá nhiều đường không tốt cho răng của bạn." },
          { en: "Add a spoonful of sugar to the juice.", vi: "Hãy thêm một thìa đường vào nước ép." },
        ],
        notes: "Danh từ không đếm được.",
      },
      {
        id: "fod14",
        term: "Salt",
        phonetic: "/sɔːlt/",
        translation: "Muối",
        examples: [
          { en: "Pass me the salt, please.", vi: "Làm ơn chuyển lọ muối cho tôi." },
          { en: "The soup needs more salt.", vi: "Món súp này cần thêm muối." },
          { en: "Salt is used to preserve food.", vi: "Muối được sử dụng để bảo quản thực phẩm." },
        ],
        notes: "Danh từ không đếm được.",
      },
      {
        id: "fod15",
        term: "Egg",
        phonetic: "/eɡ/",
        translation: "Quả trứng",
        examples: [
          { en: "He boils an egg for breakfast.", vi: "Anh ấy luộc một quả trứng cho bữa sáng." },
          { en: "How many eggs do we have left?", vi: "Chúng ta còn lại bao nhiêu quả trứng?" },
          { en: "I like fried eggs.", vi: "Tôi thích ăn trứng rán." },
        ],
        notes: "Đi với mạo từ 'an'.",
      },
      {
        id: "fod16",
        term: "Cheese",
        phonetic: "/tʃiːz/",
        translation: "Phô mai",
        examples: [
          { en: "The mouse is eating a piece of cheese.", vi: "Con chuột đang ăn một miếng phô mai." },
          { en: "She loves cheese pizza.", vi: "Cô ấy thích bánh pizza phô mai." },
          { en: "This cheese is made from goat milk.", vi: "Loại phô mai này được làm từ sữa dê." },
        ],
        notes: "Sản phẩm làm từ sữa, giàu chất béo.",
      },
      {
        id: "fod17",
        term: "Juice",
        phonetic: "/dʒuːs/",
        translation: "Nước ép",
        examples: [
          { en: "Orange juice is fresh and cold.", vi: "Nước cam ép tươi và mát lạnh." },
          { en: "She drinks fruit juice every day.", vi: "Cô ấy uống nước ép trái cây mỗi ngày." },
          { en: "Can I have some apple juice?", vi: "Tôi có thể xin một ít nước ép táo không?" },
        ],
        notes: "Nước ép nguyên chất từ hoa quả.",
      },
      {
        id: "fod18",
        term: "Cake",
        phonetic: "/keɪk/",
        translation: "Bánh ngọt",
        examples: [
          { en: "She made a chocolate cake.", vi: "Cô ấy đã làm một chiếc bánh ngọt sô-cô-la." },
          { en: "We had birthday cake at the party.", vi: "Chúng tôi đã ăn bánh sinh nhật tại bữa tiệc." },
          { en: "A slice of cake costs two dollars.", vi: "Một lát bánh ngọt có giá hai đô la." },
        ],
        notes: "Thường có nhiều đường, bơ và được nướng chín.",
      },
      {
        id: "fod19",
        term: "Soup",
        phonetic: "/suːp/",
        translation: "Súp, canh",
        examples: [
          { en: "The chicken soup is warm and delicious.", vi: "Súp gà ấm áp và rất ngon miệng." },
          { en: "I eat hot soup when I am sick.", vi: "Tôi ăn súp nóng khi tôi bị ốm." },
          { en: "She is making potato soup.", vi: "Cô ấy đang nấu canh khoai tây." },
        ],
        notes: "Món ăn dạng lỏng, khai vị hoặc ăn cùng cơm.",
      },
      {
        id: "fod20",
        term: "Delicious",
        phonetic: "/dɪˈlɪʃəs/",
        translation: "Ngon miệng, ngon",
        examples: [
          { en: "This apple is delicious.", vi: "Quả táo này rất ngon." },
          { en: "Thank you for the delicious dinner.", vi: "Cảm ơn bạn vì bữa tối ngon miệng." },
          { en: "The cake smells delicious.", vi: "Chiếc bánh ngọt có mùi thơm phức." },
        ],
        notes: "Tính từ dùng để khen ngợi đồ ăn thức uống.",
      },
    ],
  },
  {
    id: "topic_weather_b2",
    title: "Chủ đề: Thời tiết",
    category: "topic",
    description: "Các hiện tượng thời tiết phổ biến và cách miêu tả khí hậu cơ bản.",
    color: "bg-blue-500",
    words: [
      {
        id: "wea1",
        term: "Weather",
        phonetic: "/ˈweðə/",
        translation: "Thời tiết",
        examples: [
          { en: "What is the weather like today?", vi: "Thời tiết hôm nay thế nào?" },
          { en: "The weather forecast says it will rain.", vi: "Dự báo thời tiết nói rằng trời sẽ mưa." },
          { en: "We love cold weather.", vi: "Chúng tôi thích thời tiết lạnh." },
        ],
        notes: "Tránh nhầm lẫn cách phát âm với từ 'whether' (liệu rằng).",
      },
      {
        id: "wea2",
        term: "Sun",
        phonetic: "/sʌn/",
        translation: "Mặt trời",
        examples: [
          { en: "The sun rises in the east.", vi: "Mặt trời mọc ở hướng đông." },
          { en: "The sun is shining brightly.", vi: "Mặt trời đang chiếu sáng rực rỡ." },
          { en: "The morning sun is warm.", vi: "Ánh mặt trời buổi sáng thật ấm áp." },
        ],
        notes: "Thường đi kèm với mạo từ 'the' ('the sun').",
      },
      {
        id: "wea3",
        term: "Rain",
        phonetic: "/reɪn/",
        translation: "Mưa / Cơn mưa",
        examples: [
          { en: "I love walking in the rain.", vi: "Tôi thích đi bộ dưới mưa." },
          { en: "It is starting to rain.", vi: "Trời đang bắt đầu mưa." },
          { en: "Heavy rain stopped the match.", vi: "Cơn mưa lớn đã làm tạm dừng trận đấu." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "wea4",
        term: "Wind",
        phonetic: "/wɪnd/",
        translation: "Gió",
        examples: [
          { en: "The wind is blowing hard.", vi: "Gió đang thổi rất mạnh." },
          { en: "My hat blew off in the wind.", vi: "Chiếc mũ của tôi đã bị gió thổi bay mất." },
          { en: "I can feel a cool wind.", vi: "Tôi có thể cảm nhận được một làn gió mát." },
        ],
        notes: "Dùng tính từ 'windy' để tả trời nhiều gió.",
      },
      {
        id: "wea5",
        term: "Cloud",
        phonetic: "/klaʊd/",
        translation: "Đám mây, mây",
        examples: [
          { en: "There are white clouds in the sky.", vi: "Có những đám mây trắng trên bầu trời." },
          { en: "A dark cloud covered the sun.", vi: "Một đám mây đen đã che khuất mặt trời." },
          { en: "There is not a single cloud today.", vi: "Hôm nay trời không có một bóng mây nào." },
        ],
        notes: "Dùng tính từ 'cloudy' để tả trời âm u nhiều mây.",
      },
      {
        id: "wea6",
        term: "Snow",
        phonetic: "/snəʊ/",
        translation: "Tuyết / Tuyết rơi",
        examples: [
          { en: "Children love playing with snow.", vi: "Trẻ em rất thích chơi đùa với tuyết." },
          { en: "It is snowing outside.", vi: "Ngoài trời tuyết đang rơi." },
          { en: "The ground was covered with white snow.", vi: "Mặt đất được phủ một lớp tuyết trắng dầy." },
        ],
        notes: "Thường có ở các quốc gia ôn đới vào mùa đông.",
      },
      {
        id: "wea7",
        term: "Hot",
        phonetic: "/hɒt/",
        translation: "Nóng, nóng bức",
        examples: [
          { en: "It is very hot in July.", vi: "Trời rất nóng vào tháng Bảy." },
          { en: "I need a hot drink.", vi: "Tôi cần một thức uống nóng." },
          { en: "The soup is too hot to eat.", vi: "Món súp quá nóng không thể ăn được." },
        ],
        notes: "Trái nghĩa với 'cold'.",
      },
      {
        id: "wea8",
        term: "Cold",
        phonetic: "/kəʊld/",
        translation: "Lạnh, lạnh giá",
        examples: [
          { en: "The water in the pool is very cold.", vi: "Nước trong bể bơi rất lạnh." },
          { en: "I feel cold; can you close the window?", vi: "Tôi thấy lạnh; bạn đóng cửa sổ lại được không?" },
          { en: "It gets cold at night.", vi: "Trời trở lạnh vào ban đêm." },
        ],
        notes: "Trái nghĩa với 'hot'.",
      },
      {
        id: "wea9",
        term: "Warm",
        phonetic: "/wɔːm/",
        translation: "Ấm áp, ấm",
        examples: [
          { en: "The room is warm and comfortable.", vi: "Căn phòng thật ấm áp và thoải mái." },
          { en: "We had warm weather last week.", vi: "Chúng tôi đã có thời tiết ấm áp vào tuần trước." },
          { en: "This blanket will keep you warm.", vi: "Chiếc chăn này sẽ giữ ấm cho bạn." },
        ],
        notes: "Nhiệt độ dễ chịu, dễ chịu hơn 'hot'.",
      },
      {
        id: "wea10",
        term: "Cool",
        phonetic: "/kuːl/",
        translation: "Mát mẻ, mát",
        examples: [
          { en: "Autumn has cool weather.", vi: "Mùa thu có thời tiết mát mẻ." },
          { en: "It is cool under the tree.", vi: "Trời mát mẻ ở dưới bóng cây." },
          { en: "A cool breeze is blowing.", vi: "Một làn gió mát đang thổi." },
        ],
        notes: "Nhiệt độ dễ chịu, mát hơn 'warm'.",
      },
      {
        id: "wea11",
        term: "Sunny",
        phonetic: "/ˈsʌni/",
        translation: "Có nắng, nắng rực rỡ",
        examples: [
          { en: "It was a sunny Sunday afternoon.", vi: "Đó đã là một chiều Chủ Nhật đầy nắng." },
          { en: "We went to the beach on a sunny day.", vi: "Chúng tôi đi biển vào một ngày nắng." },
          { en: "Tomorrow will be sunny and warm.", vi: "Ngày mai trời sẽ nắng và ấm áp." },
        ],
        notes: "Tính từ, chuyển đổi từ danh từ 'sun'.",
      },
      {
        id: "wea12",
        term: "Rainy",
        phonetic: "/ˈreɪni/",
        translation: "Có mưa, nhiều mưa",
        examples: [
          { en: "The rainy season lasts for three months.", vi: "Mùa mưa kéo dài trong ba tháng." },
          { en: "I stay at home on rainy days.", vi: "Tôi ở nhà vào những ngày mưa." },
          { en: "The sky looks dark and rainy.", vi: "Bầu trời trông tối sầm và nhiều mưa." },
        ],
        notes: "Tính từ, chuyển đổi từ danh từ 'rain'.",
      },
      {
        id: "wea13",
        term: "Windy",
        phonetic: "/ˈwɪndi/",
        translation: "Nhiều gió, có gió mạnh",
        examples: [
          { en: "It is too windy to play tennis.", vi: "Trời quá nhiều gió để chơi quần vợt." },
          { en: "Keep your jacket on; it is windy.", vi: "Hãy mặc áo khoác vào; trời nhiều gió đấy." },
          { en: "The windy weather broke some tree branches.", vi: "Thời tiết nhiều gió lớn đã làm gãy vài cành cây." },
        ],
        notes: "Tính từ, chuyển đổi từ danh từ 'wind'.",
      },
      {
        id: "wea14",
        term: "Cloudy",
        phonetic: "/ˈklaʊdi/",
        translation: "Nhiều mây, u ám",
        examples: [
          { en: "The sky is cloudy and dark.", vi: "Bầu trời nhiều mây và tối tăm." },
          { en: "It was a cloudy morning, but it didn't rain.", vi: "Đó đã là một buổi sáng nhiều mây, nhưng trời không mưa." },
          { en: "I cannot see the stars on cloudy nights.", vi: "Tôi không thể nhìn thấy những ngôi sao vào đêm nhiều mây." },
        ],
        notes: "Tính từ, chuyển đổi từ danh từ 'cloud'.",
      },
      {
        id: "wea15",
        term: "Storm",
        phonetic: "/stɔːm/",
        translation: "Cơn bão, giông bão",
        examples: [
          { en: "A heavy storm is coming.", vi: "Một cơn bão lớn đang kéo đến." },
          { en: "The storm damaged many houses.", vi: "Cơn bão đã làm hư hại nhiều ngôi nhà." },
          { en: "We stayed indoors during the storm.", vi: "Chúng tôi ở trong nhà trong suốt thời gian bão." },
        ],
        notes: "Thường đi kèm với mưa lớn và sấm chớp.",
      },
      {
        id: "wea16",
        term: "Dry",
        phonetic: "/draɪ/",
        translation: "Khô ráo, khô hanh",
        examples: [
          { en: "The weather is very dry in winter.", vi: "Thời tiết rất khô hanh vào mùa đông." },
          { en: "Make sure your clothes are completely dry.", vi: "Hãy chắc chắn rằng quần áo của bạn đã hoàn toàn khô ráo." },
          { en: "The leaves are dry and brown.", vi: "Những chiếc lá khô và có màu nâu." },
        ],
        notes: "Trái nghĩa với 'wet'.",
      },
      {
        id: "wea17",
        term: "Wet",
        phonetic: "/wet/",
        translation: "Ẩm ướt, ướt sũng",
        examples: [
          { en: "My shoes got wet in the rain.", vi: "Giày của tôi bị ướt sũng dưới trời mưa." },
          { en: "The grass is still wet with dew.", vi: "Cỏ vẫn còn ẩm ướt vì sương đêm." },
          { en: "Do not touch the plug with wet hands.", vi: "Đừng chạm vào ổ cắm điện với bàn tay đang ướt." },
        ],
        notes: "Trái nghĩa với 'dry'.",
      },
      {
        id: "wea18",
        term: "Umbrella",
        phonetic: "/ʌmˈbrelə/",
        translation: "Cái dù, chiếc ô",
        examples: [
          { en: "You should take an umbrella with you.", vi: "Bạn nên mang theo một chiếc ô bên mình." },
          { en: "We shared a large umbrella.", vi: "Chúng tôi đã che chung một chiếc ô lớn." },
          { en: "She opened her umbrella when it started to rain.", vi: "Cô ấy mở ô khi trời bắt đầu mưa." },
        ],
        notes: "Đi với mạo từ 'an'.",
      },
      {
        id: "wea19",
        term: "Sky",
        phonetic: "/skaɪ/",
        translation: "Bầu trời",
        examples: [
          { en: "There are no clouds in the sky today.", vi: "Hôm nay trên bầu trời không có một bóng mây." },
          { en: "The sky turned orange at sunset.", vi: "Bầu trời chuyển sang màu cam lúc hoàng hôn." },
          { en: "Birds fly in the sky.", vi: "Những chú chim bay lượn trên bầu trời." },
        ],
        notes: "Thường đi kèm mạo từ 'the'.",
      },
      {
        id: "wea20",
        term: "Temperature",
        phonetic: "/ˈtemprətʃə/",
        translation: "Nhiệt độ",
        examples: [
          { en: "The temperature is dropping tonight.", vi: "Nhiệt độ đang giảm xuống vào đêm nay." },
          { en: "What is the current temperature?", vi: "Nhiệt độ hiện tại là bao nhiêu?" },
          { en: "Keep the medicine at room temperature.", vi: "Hãy bảo quản thuốc ở nhiệt độ phòng." },
        ],
        notes: "Được đo bằng độ C (Celsius) hoặc độ F (Fahrenheit).",
      },
    ],
  },
];
