export const tierEliteIV = [
  {
    id: "topic_recruitment_ta4",
    title: "Chủ đề: Việc làm & Tuyển dụng",
    category: "topic",
    description: "Từ vựng nâng cao chuyên sâu về thủ tục săn đầu người, phúc lợi nhân sự và ký kết hợp đồng.",
    color: "bg-indigo-700",
    words: [
      {
        id: "rec1",
        term: "Recruitment",
        phonetic: "/rɪˈkluːtmənt/",
        translation: "Sự tuyển dụng, quy trình tuyển dụng",
        examples: [
          { en: "The company's new recruitment policy focuses on soft skills.", vi: "Chính sách tuyển dụng mới của công ty tập trung vào các kỹ năng mềm." },
          { en: "She works as a manager in the recruitment agency.", vi: "Cô ấy làm việc với tư cách là quản lý trong đại lý tuyển dụng nhân sự." },
          { en: "The recruitment process consists of three rounds of interviews.", vi: "Quy trình tuyển dụng bao gồm ba vòng phỏng vấn." },
        ],
        notes: "Hoạt động tìm kiếm và tuyển chọn nhân lực cho tổ chức.",
      },
      {
        id: "rec2",
        term: "Candidate",
        phonetic: "/ˈkændɪdət/",
        translation: "Ứng viên",
        examples: [
          { en: "He is a strong candidate for the sales manager position.", vi: "Anh ấy là một ứng viên nặng ký cho vị trí quản lý bán hàng." },
          { en: "They interviewed ten candidates but haven't hired anyone yet.", vi: "Họ đã phỏng vấn mười ứng viên nhưng vẫn chưa tuyển dụng ai cả." },
          { en: "The ideal candidate should have three years of experience.", vi: "Ứng viên lý tưởng nên có ba năm kinh nghiệm." },
        ],
        notes: "Người nộp đơn ứng tuyển cho một vị trí công việc hoặc kỳ bầu cử.",
      },
      {
        id: "rec3",
        term: "Resume",
        phonetic: "/ˈrezjuːmeɪ/",
        translation: "Sơ yếu lý lịch, bản tóm tắt hồ sơ (CV)",
        examples: [
          { en: "Please send your resume and cover letter to our email.", vi: "Vui lòng gửi sơ yếu lý lịch và thư xin việc của bạn tới email của chúng tôi." },
          { en: "She updated her resume before applying for the job.", vi: "Cô ấy đã cập nhật sơ yếu lý lịch trước khi nộp đơn xin việc." },
          { en: "An attractive resume should be clear and professional.", vi: "Một bản sơ yếu lý lịch thu hút nên rõ ràng và chuyên nghiệp." },
        ],
        notes: "Văn bản tóm tắt học vấn, kỹ năng và kinh nghiệm làm việc để xin việc.",
      },
      {
        id: "rec4",
        term: "Vacancy",
        phonetic: "/ˈveɪkənsi/",
        translation: "Vị trí tuyển dụng trống, phòng trống",
        examples: [
          { en: "The school has a vacancy for a biology teacher.", vi: "Trường học đang có một vị trí trống tuyển dụng giáo viên sinh học." },
          { en: "Are there any job vacancies in your department?", vi: "Có vị trí tuyển dụng trống nào trong phòng ban của bạn không?" },
          { en: "The hotel has no vacancies for tonight; we are full.", vi: "Khách sạn không còn phòng trống nào cho đêm nay; chúng tôi đã đầy khách." },
        ],
        notes: "Vị trí công việc chưa có người làm hoặc phòng khách sạn chưa có người ở.",
      },
      {
        id: "rec5",
        term: "Apply",
        phonetic: "/əˈplaɪ/",
        translation: "Nộp đơn ứng tuyển / Áp dụng",
        examples: [
          { en: "She wants to apply for the position of financial analyst.", vi: "Cô ấy muốn nộp đơn ứng tuyển cho vị trí nhà phân tích tài chính." },
          { en: "You can apply for the job online through their website.", vi: "Bạn có thể nộp đơn xin việc trực tuyến thông qua trang web của họ." },
          { en: "This rule does not apply to international students.", vi: "Quy tắc này không áp dụng đối với sinh viên quốc tế." },
        ],
        notes: "Đi kèm giới từ 'for' khi ứng tuyển vị trí, đi với 'to' khi muốn áp dụng quy tắc.",
      },
      {
        id: "rec6",
        term: "Benefit",
        phonetic: "/ˈbenɪfɪt/",
        translation: "Phúc lợi, lợi ích / Mang lại lợi ích",
        examples: [
          { en: "The job offer includes health insurance and other benefits.", vi: "Lời mời nhận việc bao gồm bảo hiểm y tế và các phúc lợi khác." },
          { en: "Learning English will bring many benefits to your career.", vi: "Học tiếng Anh sẽ mang lại nhiều lợi ích lớn cho sự nghiệp của bạn." },
          { en: "The local economy benefited from the new tourist attraction.", vi: "Nền kinh tế địa phương đã được hưởng lợi từ điểm thu hút du khách mới." },
        ],
        notes: "Trong tuyển dụng, chỉ các quyền lợi ngoài lương cứng (bảo hiểm, ngày nghỉ phép, tiền thưởng).",
      },
      {
        id: "rec7",
        term: "Contract",
        phonetic: "/ˈkɒntrækt/",
        translation: "Hợp đồng lao động, giao kèo",
        examples: [
          { en: "She signed a two-year employment contract yesterday.", vi: "Hôm qua cô ấy đã ký một hợp đồng lao động thời hạn hai năm." },
          { en: "Please read the contract details carefully before signing.", vi: "Vui lòng đọc kỹ các chi tiết trong hợp đồng trước khi ký kết." },
          { en: "The company has violated the terms of the contract.", vi: "Công ty đã vi phạm các điều khoản của hợp đồng." },
        ],
        notes: "Văn bản thỏa thuận pháp lý ràng buộc giữa hai bên.",
      },
      {
        id: "rec8",
        term: "Negotiate",
        phonetic: "/nɪˈɡəʊʃieɪt/",
        translation: "Đàm phán, thương lượng",
        examples: [
          { en: "The candidate tried to negotiate a higher starting salary.", vi: "Ứng viên đã cố gắng đàm phán một mức lương khởi điểm cao hơn." },
          { en: "They are negotiating the terms of the business agreement.", vi: "Họ đang thương lượng các điều khoản của thỏa thuận kinh doanh." },
          { en: "He managed to negotiate a discount on the new office chairs.", vi: "Anh ấy đã xoay xở để thương lượng giảm giá cho những chiếc ghế văn phòng mới." },
        ],
        notes: "Hành động bàn bạc để đạt được thỏa thuận chung.",
      },
      {
        id: "rec9",
        term: "Position",
        phonetic: "/pəˈzɪʃn/",
        translation: "Vị trí làm việc, chức vụ / Vị trí địa lý",
        examples: [
          { en: "He applied for a managerial position in the company.", vi: "Anh ấy đã nộp đơn xin một vị trí quản lý trong công ty." },
          { en: "What is your current position in the firm?", vi: "Chức vụ hiện tại của bạn trong hãng là gì?" },
          { en: "The radar detected the exact position of the ship.", vi: "Hệ thống radar đã phát hiện ra vị trí chính xác của con tàu." },
        ],
        notes: "Chức danh công việc của một cá nhân trong tổ chức.",
      },
      {
        id: "rec10",
        term: "Requirement",
        phonetic: "/rɪˈkwaɪəmənt/",
        translation: "Yêu cầu bắt buộc",
        examples: [
          { en: "A college degree is a standard requirement for this job.", vi: "Bằng đại học là một yêu cầu tiêu chuẩn bắt buộc cho công việc này." },
          { en: "The applicant met all the requirements of the vacancy.", vi: "Người nộp đơn đã đáp ứng đầy đủ các yêu cầu của vị trí trống." },
          { en: "We need to understand our client's requirements clearly.", vi: "Chúng ta cần hiểu rõ các yêu cầu bắt buộc của khách hàng." },
        ],
        notes: "Điều kiện cần phải được thỏa mãn trước khi làm việc gì đó.",
      },
      {
        id: "rec11",
        term: "Internship",
        phonetic: "/ˈɪntɜːnʃɪp/",
        translation: "Kỳ thực tập, giai đoạn thực tập",
        examples: [
          { en: "She completed a summer internship at a global bank.", vi: "Cô ấy đã hoàn thành một kỳ thực tập mùa hè tại một ngân hàng toàn cầu." },
          { en: "The internship offered valuable hands-on work experience.", vi: "Kỳ thực tập đã cung cấp những kinh nghiệm làm việc thực tế vô cùng quý báu." },
          { en: "He did an unpaid internship to build his resume.", vi: "Cậu ấy đã làm một kỳ thực tập không lương để làm đẹp sơ yếu lý lịch." },
        ],
        notes: "Giai đoạn làm việc của sinh viên chuẩn bị ra trường để lấy kinh nghiệm.",
      },
      {
        id: "rec12",
        term: "Layoff",
        phonetic: "/ˈleɪɒf/",
        translation: "Sự sa thải, giảm biên chế (do kinh tế khó khăn)",
        examples: [
          { en: "The tech firm announced layoffs of ten percent of its staff.", vi: "Hãng công nghệ đã công bố đợt sa thải giảm biên chế mười phần trăm nhân sự." },
          { en: "Economic recession led to widespread layoffs in the industry.", vi: "Suy thoái kinh tế dẫn đến các đợt sa thải lan rộng trong ngành." },
          { en: "He survived the corporate layoff and kept his job.", vi: "Anh ấy đã vượt qua đợt cắt giảm biên chế của công ty và giữ được việc làm." },
        ],
        notes: "Hành động chấm dứt hợp đồng lao động do nguyên nhân tài chính của công ty.",
      },
      {
        id: "rec13",
        term: "Reference",
        phonetic: "/ˈrefrəns/",
        translation: "Thư giới thiệu, người giới thiệu / Sự tham chiếu",
        examples: [
          { en: "My former boss agreed to write a job reference for me.", vi: "Sếp cũ của tôi đã đồng ý viết một bức thư giới thiệu xin việc cho tôi." },
          { en: "The company called his references before making the job offer.", vi: "Công ty đã gọi điện cho những người giới thiệu của anh ấy trước khi đưa ra lời mời nhận việc." },
          { en: "Please provide three professional references.", vi: "Vui lòng cung cấp thông tin của ba người giới thiệu chuyên môn." },
        ],
        notes: "Người hoặc tài liệu chứng thực năng lực làm việc trong quá khứ.",
      },
      {
        id: "rec14",
        term: "Overtime",
        phonetic: "/ˈəʊvətaɪm/",
        translation: "Sự làm thêm giờ, tăng ca",
        examples: [
          { en: "We had to work overtime to finish the project before Friday.", vi: "Chúng tôi đã phải làm việc thêm giờ để hoàn thành dự án trước thứ Sáu." },
          { en: "The factory pays double for working overtime on weekends.", vi: "Nhà máy trả gấp đôi lương cho việc tăng ca làm thêm giờ vào cuối tuần." },
          { en: "How much overtime did you do last month?", vi: "Bạn đã tăng ca tổng cộng bao nhiêu giờ vào tháng trước?" },
        ],
        notes: "Thời gian làm việc ngoài giờ hành chính quy định.",
      },
      {
        id: "rec15",
        term: "Fulfill",
        phonetic: "/fʊlˈfɪl/",
        translation: "Hoàn thành, đáp ứng, thực hiện",
        examples: [
          { en: "The candidate must fulfill all the educational requirements.", vi: "Ứng viên phải đáp ứng đầy đủ tất cả các yêu cầu về mặt học vấn." },
          { en: "He managed to fulfill his dream of starting a tech firm.", vi: "Anh ấy đã xoay xở để hiện thực hóa ước mơ thành lập hãng công nghệ của mình." },
          { en: "They struggled to fulfill the terms of the agreement.", vi: "Họ đã rất chật vật để hoàn thành các điều khoản của hiệp định." },
        ],
        notes: "Thực hiện thành công lời hứa, giấc mơ hoặc đáp ứng điều kiện.",
      },
      {
        id: "rec16",
        term: "Headhunter",
        phonetic: "/ˈhedhʌntə/",
        translation: "Người săn đầu người, chuyên viên tuyển mộ nhân tài",
        examples: [
          { en: "The headhunter contacted her regarding a director position.", vi: "Chuyên viên săn đầu người đã liên hệ với cô ấy về một vị trí giám đốc." },
          { en: "A professional headhunter can find candidates for senior jobs quickly.", vi: "Một chuyên viên săn đầu người chuyên nghiệp có thể tìm ứng viên cho vị trí cao cấp rất nhanh." },
          { en: "They hired a headhunter agency to recruit a new CEO.", vi: "Họ đã thuê một công ty săn đầu người để tuyển dụng một giám đốc điều hành mới." },
        ],
        notes: "Chuyên gia tìm kiếm ứng viên cao cấp cho doanh nghiệp khác.",
      },
      {
        id: "rec17",
        term: "Job description",
        phonetic: "/dʒɒb dɪˈskrɪpʃn/",
        translation: "Bản mô tả công việc (JD)",
        examples: [
          { en: "Please read the job description carefully before applying.", vi: "Vui lòng đọc kỹ bản mô tả công việc trước khi nộp đơn ứng tuyển." },
          { en: "The job description lists the main duties and daily tasks.", vi: "Bản mô tả công việc liệt kê các bổn phận chính và nhiệm vụ hàng ngày." },
          { en: "Her actual duties matched the initial job description.", vi: "Những bổn phận thực tế của cô ấy rất khớp với bản mô tả công việc ban đầu." },
        ],
        notes: "Văn bản chi tiết về trách nhiệm và yêu cầu của một công việc.",
      },
      {
        id: "rec18",
        term: "Probation",
        phonetic: "/prəˈbeɪʃn/",
        translation: "Thời gian thử việc / Án treo",
        examples: [
          { en: "New employees must complete a two-month probation period.", vi: "Nhân viên mới phải hoàn thành thời gian thử việc kéo dài hai tháng." },
          { en: "He did very well during his probation and got a permanent contract.", vi: "Anh ấy đã làm rất tốt trong thời gian thử việc và nhận được hợp đồng dài hạn." },
          { en: "The court put him on probation for six months.", vi: "Tòa án đã phán quyết cho anh ấy hưởng án treo trong vòng sáu tháng." },
        ],
        notes: "Giai đoạn kiểm tra năng lực trước khi nhận làm nhân viên chính thức.",
      },
      {
        id: "rec19",
        term: "Permanent",
        phonetic: "/ˈpɜːmənənt/",
        translation: "Vĩnh viễn, lâu dài, biên chế chính thức",
        examples: [
          { en: "She is looking for a permanent job rather than a temporary one.", vi: "Cô ấy đang tìm kiếm một công việc chính thức lâu dài hơn là một công việc tạm thời." },
          { en: "The ink leaves a permanent stain on clothing.", vi: "Mực này để lại vết bẩn vĩnh viễn không thể tẩy sạch trên quần áo." },
          { en: "He was offered a permanent position with the company.", vi: "Anh ấy đã được đề xuất một vị trí biên chế chính thức với công ty." },
        ],
        notes: "Chỉ tính chất ổn định, lâu dài hoặc biên chế chính thức, trái nghĩa với 'temporary'.",
      },
      {
        id: "rec20",
        term: "Salary review",
        phonetic: "/ˈsæləri rɪˈvjuː/",
        translation: "Sự xét tăng lương, đợt duyệt lương",
        examples: [
          { en: "We have an annual salary review at the end of December.", vi: "Chúng tôi có một đợt xét tăng lương hàng năm vào cuối tháng Mười Hai." },
          { en: "She is hoping for a positive salary review based on her performance.", vi: "Cô ấy đang hy vọng vào một đợt duyệt tăng lương tích cực dựa trên hiệu suất làm việc của mình." },
          { en: "During the salary review, the manager praised her hard work.", vi: "Trong đợt duyệt lương, quản lý đã ca ngợi sự chăm chỉ của cô ấy." },
        ],
        notes: "Quy trình đánh giá để quyết định điều chỉnh mức lương của nhân sự.",
      },
    ],
  },
  {
    id: "topic_urban_rural_ta4",
    title: "Chủ đề: Đời sống đô thị & Nông thôn",
    category: "topic",
    description: "Các vấn đề cơ sở hạ tầng đô thị, nhịp sống náo nhiệt, kẹt xe khói bụi và sự thanh bình vùng nông thôn.",
    color: "bg-indigo-700",
    words: [
      {
        id: "urb1",
        term: "Urban",
        phonetic: "/ˈɜːbən/",
        translation: "Thuộc đô thị, thành thị",
        examples: [
          { en: "Urban areas are usually crowded and noisy.", vi: "Các khu vực đô thị thường đông đúc và ồn ào." },
          { en: "The government is trying to solve urban planning problems.", vi: "Chính phủ đang cố gắng giải quyết các vấn đề quy hoạch đô thị." },
          { en: "Many young people leave villages for urban life.", vi: "Nhiều bạn trẻ rời bỏ làng quê để hướng tới cuộc sống thành thị." },
        ],
        notes: "Liên quan đến cuộc sống thành phố, trái nghĩa với 'rural'.",
      },
      {
        id: "urb2",
        term: "Rural",
        phonetic: "/ˈrʊərəl/",
        translation: "Thuộc nông thôn, làng quê",
        examples: [
          { en: "They live in a beautiful rural village near the lake.", vi: "Họ sống trong một ngôi làng nông thôn xinh đẹp gần hồ." },
          { en: "Medical facilities in rural areas are often limited.", vi: "Các cơ sở y tế ở vùng nông thôn thường bị hạn chế." },
          { en: "She enjoys the quiet pace of rural life.", vi: "Cô ấy thích nhịp điệu yên tĩnh của cuộc sống nông thôn." },
        ],
        notes: "Liên quan đến vùng quê hay nông thôn, trái nghĩa với 'urban'.",
      },
      {
        id: "urb3",
        term: "Suburb",
        phonetic: "/ˈsʌbɜːb/",
        translation: "Vùng ngoại ô, ngoại thành",
        examples: [
          { en: "They moved to the suburbs to have a larger house with a garden.", vi: "Họ đã chuyển ra vùng ngoại ô để có một ngôi nhà lớn hơn kèm theo vườn." },
          { en: "Commuting from the suburbs to the city center takes forty minutes.", vi: "Việc đi lại từ ngoại thành vào trung tâm thành phố mất bốn mươi phút." },
          { en: "It is quieter and safer to live in the suburbs.", vi: "Sống ở vùng ngoại ô thì yên tĩnh và an toàn hơn." },
        ],
        notes: "Khu dân cư nằm sát ranh giới thành phố lớn.",
      },
      {
        id: "urb4",
        term: "Population",
        phonetic: "/ˌpɒpjuˈleɪʃn/",
        translation: "Dân số, lượng cư dân",
        examples: [
          { en: "The city has a population of over eight million people.", vi: "Thành phố có dân số hơn tám triệu người." },
          { en: "The rural population is declining due to migration.", vi: "Dân số nông thôn đang sụt giảm do di cư tự do." },
          { en: "Governments must plan food supplies for the growing population.", vi: "Chính phủ phải lên kế hoạch cung cấp thực phẩm cho dân số đang tăng." },
        ],
        notes: "Tổng số người sinh sống tại một khu vực xác định.",
      },
      {
        id: "urb5",
        term: "Infrastructure",
        phonetic: "/ˈɪnfrəstrʌktʃə/",
        translation: "Cơ sở hạ tầng",
        examples: [
          { en: "The city needs to invest more in transportation infrastructure.", vi: "Thành phố cần đầu tư nhiều hơn vào cơ sở hạ tầng giao thông." },
          { en: "Good infrastructure is essential for economic growth.", vi: "Cơ sở hạ tầng tốt là điều cần thiết đối với sự tăng trưởng kinh tế." },
          { en: "They are upgrading the water supply infrastructure of the town.", vi: "Họ đang nâng cấp cơ sở hạ tầng cung cấp nước của thị trấn." },
        ],
        notes: "Hệ thống cơ bản phục vụ đời sống (đường, điện, nước, cầu cống).",
      },
      {
        id: "urb6",
        term: "Congestion",
        phonetic: "/kənˈdʒestʃən/",
        translation: "Sự tắc nghẽn, kẹt xe",
        examples: [
          { en: "Traffic congestion is a major problem in Hanoi.", vi: "Tắc nghẽn giao thông là một vấn đề lớn ở Hà Nội." },
          { en: "The government is trying to reduce road congestion.", vi: "Chính phủ đang nỗ lực giảm bớt sự tắc nghẽn đường bộ." },
          { en: "I was stuck in traffic congestion for an hour.", vi: "Tôi đã bị kẹt trong đám tắc nghẽn giao thông suốt một tiếng đồng hồ." },
        ],
        notes: "Tình trạng quá tải gây tắc nghẽn giao thông.",
      },
      {
        id: "urb7",
        term: "Facility",
        phonetic: "/fəˈsɪləti/",
        translation: "Tiện ích, cơ sở vật chất dịch vụ",
        examples: [
          { en: "The sports facility has an indoor swimming pool.", vi: "Cơ sở vật chất thể thao có một bể bơi trong nhà." },
          { en: "Residents can enjoy many modern facilities in this area.", vi: "Cư dân có thể tận hưởng nhiều tiện ích hiện đại ở khu vực này." },
          { en: "The hotel has excellent medical facilities for guests.", vi: "Khách sạn có cơ sở vật chất y tế vô cùng tuyệt vời cho khách." },
        ],
        notes: "Tòa nhà hoặc dịch vụ cung cấp nhằm phục vụ mục đích tiện ích cụ thể.",
      },
      {
        id: "urb8",
        term: "Agriculture",
        phonetic: "/ˈæɡrɪkʌltʃə/",
        translation: "Nông nghiệp, trồng trọt và chăn nuôi",
        examples: [
          { en: "Most people in this rural village work in agriculture.", vi: "Hầu hết người dân ở ngôi làng nông thôn này đều làm việc trong ngành nông nghiệp." },
          { en: "Modern technology has revolutionized agriculture.", vi: "Công nghệ hiện đại đã cách mạng hóa ngành nông nghiệp." },
          { en: "The area is perfect for organic agriculture.", vi: "Khu vực này hoàn hảo cho nông nghiệp hữu cơ tự nhiên." },
        ],
        notes: "Hoạt động sản xuất nông sản thực phẩm.",
      },
      {
        id: "urb9",
        term: "Development",
        phonetic: "/dɪˈveləpmənt/",
        translation: "Sự phát triển, mở rộng",
        examples: [
          { en: "The rapid economic development has improved lifestyles.", vi: "Sự phát triển kinh tế nhanh chóng đã cải thiện lối sống của người dân." },
          { en: "She is in charge of software research and development.", vi: "Cô ấy phụ trách nghiên cứu và phát triển phần mềm." },
          { en: "We support the sustainable development of rural areas.", vi: "Chúng tôi ủng hộ sự phát triển bền vững của các vùng nông thôn." },
        ],
        notes: "Danh từ của động từ 'develop'.",
      },
      {
        id: "urb10",
        term: "Smog",
        phonetic: "/smɒɡ/",
        translation: "Khói bụi ô nhiễm, sương khói độc hại",
        examples: [
          { en: "The city was covered in a thick layer of harmful smog.", vi: "Thành phố đã bị bao phủ trong một lớp sương khói độc hại dày đặc." },
          { en: "Smog is caused by car emissions and factory smoke.", vi: "Khói bụi ô nhiễm được gây ra bởi khí thải ô tô và khói nhà máy." },
          { en: "The government warned children to stay indoors due to the smog.", vi: "Chính phủ cảnh báo trẻ em nên ở trong nhà do lượng khói bụi ô nhiễm cao." },
        ],
        notes: "Sự pha trộn giữa khói và sương mù ô nhiễm đô thị lớn.",
      },
      {
        id: "urb11",
        term: "Landscape",
        phonetic: "/ˈlændskeɪp/",
        translation: "Phong cảnh, cảnh quan thiên nhiên",
        examples: [
          { en: "The mountain landscape was beautiful and peaceful.", vi: "Phong cảnh vùng núi thật xinh đẹp và yên bình." },
          { en: "He painted several beautiful rural landscapes.", vi: "Cậu ấy đã vẽ một vài bức tranh phong cảnh nông thôn tuyệt đẹp." },
          { en: "The green landscape attracted many nature lovers.", vi: "Cảnh quan xanh tươi thu hút nhiều người yêu thiên nhiên." },
        ],
        notes: "Diện mạo của một vùng đất rộng lớn, đặc biệt là vùng nông thôn.",
      },
      {
        id: "urb12",
        term: "Neighborhood",
        phonetic: "/ˈneɪbəhʊd/",
        translation: "Khu phố, vùng lân cận quanh nhà",
        examples: [
          { en: "We live in a quiet and safe neighborhood.", vi: "Chúng tôi sống trong một khu phố yên tĩnh và an toàn." },
          { en: "There are several grocery stores in our neighborhood.", vi: "Có một vài cửa hàng tạp hóa trong khu lân cận nhà chúng tôi." },
          { en: "The people in this neighborhood are very friendly.", vi: "Mọi người ở khu phố này rất thân thiện." },
        ],
        notes: "Khu vực dân cư nhỏ sinh sống quanh nơi ở.",
      },
      {
        id: "urb13",
        term: "Skyscraper",
        phonetic: "/ˈskaɪskreɪpə/",
        translation: "Tòa nhà chọc trời",
        examples: [
          { en: "The city skyline is dominated by modern skyscrapers.", vi: "Đường chân trời của thành phố được bao phủ bởi những tòa nhà chọc trời hiện đại." },
          { en: "He works on the fiftieth floor of a massive skyscraper.", vi: "Anh ấy làm việc trên tầng năm mươi của một tòa nhà chọc trời khổng lồ." },
          { en: "They are building several new skyscrapers in the business district.", vi: "Họ đang xây dựng vài tòa nhà chọc trời mới ở khu trung tâm thương mại." },
        ],
        notes: "Tòa nhà cao tầng rất đồ sộ ở các thành phố lớn.",
      },
      {
        id: "urb14",
        term: "Migration",
        phonetic: "/maɪˈɡreɪʃn/",
        translation: "Sự di cư (tự do hoặc theo bầy)",
        examples: [
          { en: "The rural-to-urban migration is putting pressure on city resources.", vi: "Sự di cư từ nông thôn ra thành thị đang gây áp lực lên tài nguyên thành phố." },
          { en: "We studied the annual migration of wild birds.", vi: "Chúng tôi đã nghiên cứu sự di cư hàng năm của các loài chim hoang dã." },
          { en: "Economic factors are the main cause of human migration.", vi: "Các yếu tố kinh tế là nguyên nhân chính dẫn đến sự di cư của con người." },
        ],
        notes: "Hành động di chuyển của đoàn người hoặc đàn vật sang nơi mới sống.",
      },
      {
        id: "urb15",
        term: "Peaceful",
        phonetic: "/ˈpiːsfl/",
        translation: "Yên bình, thanh bình, hòa bình",
        examples: [
          { en: "The countryside is very quiet and peaceful.", vi: "Vùng nông thôn rất yên tĩnh và thanh bình." },
          { en: "They want to find a peaceful solution to the conflict.", vi: "Họ muốn tìm một giải pháp hòa bình cho cuộc xung đột." },
          { en: "The sleeping baby looks so peaceful.", vi: "Em bé đang ngủ trông thật yên bình." },
        ],
        notes: "Tính từ chỉ trạng thái tĩnh lặng, không có bạo lực hay tiếng ồn.",
      },
      {
        id: "urb16",
        term: "Bustling",
        phonetic: "/ˈbʌslɪŋ/",
        translation: "Nhộn nhịp, hối hả, náo nhiệt",
        examples: [
          { en: "The bustling night market was crowded with tourists.", vi: "Khu chợ đêm nhộn nhịp hối hả đã chật kín khách du lịch." },
          { en: "Tokyo is a bustling city that never sleeps.", vi: "Tokyo là một thành phố náo nhiệt nhộn nhịp không bao giờ ngủ." },
          { en: "We sat at a cafe and watched the bustling streets.", vi: "Chúng tôi ngồi tại quán nước và ngắm nhìn đường phố hối hả nhộn nhịp." },
        ],
        notes: "Tính từ chỉ nơi có nhiều hoạt động, con người di chuyển liên tục.",
      },
      {
        id: "urb17",
        term: "Cost of living",
        phonetic: "/kɒst əv ˈlɪvɪŋ/",
        translation: "Chi phí sinh hoạt",
        examples: [
          { en: "The cost of living in New York is extremely high.", vi: "Chi phí sinh hoạt ở New York là cực kỳ đắt đỏ." },
          { en: "They moved to a small town because the cost of living is lower.", vi: "Họ đã chuyển tới thị trấn nhỏ vì chi phí sinh hoạt thấp hơn." },
          { en: "An increase in food prices raised the cost of living.", vi: "Việc tăng giá thực phẩm đã đẩy chi phí sinh hoạt lên cao." },
        ],
        notes: "Số tiền cần thiết để mua thực phẩm, quần áo, chỗ ở cơ bản.",
      },
      {
        id: "urb18",
        term: "Modernization",
        phonetic: "/ˌmɒdənaɪˈzeɪʃn/",
        translation: "Sự hiện đại hóa",
        examples: [
          { en: "The modernization of the railway network started last year.", vi: "Sự hiện đại hóa mạng lưới đường sắt đã bắt đầu từ năm ngoái." },
          { en: "Agriculture benefited from the rapid modernization.", vi: "Nông nghiệp đã được hưởng lợi từ sự hiện đại hóa nhanh chóng." },
          { en: "The city wants to balance modernization and cultural preservation.", vi: "Thành phố muốn cân bằng giữa hiện đại hóa và bảo tồn văn hóa." },
        ],
        notes: "Hành động cập nhật, đổi mới mọi thứ theo xu thế hiện đại.",
      },
      {
        id: "urb19",
        term: "Commute",
        phonetic: "/kəˈmjuːt/",
        translation: "Hành trình đi lại hàng ngày giữa nhà và nơi làm",
        examples: [
          { en: "His daily commute to the office takes one hour by train.", vi: "Hành trình đi làm hàng ngày tới văn phòng của anh ấy mất một tiếng đi tàu hỏa." },
          { en: "I read books during my morning commute.", vi: "Tôi đọc sách trong suốt hành trình đi làm vào buổi sáng." },
          { en: "She commutes from the suburbs to the city center every day.", vi: "Cô ấy di chuyển từ vùng ngoại ô vào trung tâm thành phố để đi làm mỗi ngày." },
        ],
        notes: "Vừa là danh từ vừa là động từ.",
      },
      {
        id: "urb20",
        term: "Public transit",
        phonetic: "/ˈpʌblɪk ˈtrænzɪt/",
        translation: "Hệ thống vận tải công cộng",
        examples: [
          { en: "Using public transit is cheaper than owning a car.", vi: "Sử dụng hệ thống vận tải công cộng rẻ hơn so với việc sở hữu một chiếc xe hơi." },
          { en: "The city has a clean and efficient public transit system.", vi: "Thành phố có một hệ thống vận tải công cộng sạch sẽ và hiệu quả." },
          { en: "We rely on public transit to travel around Singapore.", vi: "Chúng tôi tin dùng hệ thống vận tải công cộng để di chuyển quanh Singapore." },
        ],
        notes: "Dịch vụ vận tải công cộng như tàu điện, xe buýt.",
      },
    ],
  },
  {
    id: "topic_general_science_ta4",
    title: "Chủ đề: Khoa học thường thức",
    category: "topic",
    description: "Các học thuyết khoa học cơ bản, thí nghiệm trong phòng nghiên cứu, hiện tượng tự nhiên và phát minh.",
    color: "bg-indigo-700",
    words: [
      {
        id: "sci1",
        term: "Experiment",
        phonetic: "/ɪkˈsperɪmənt/",
        translation: "Thí nghiệm khoa học",
        examples: [
          { en: "The scientists conducted an experiment to test the new drug.", vi: "Các nhà khoa học đã tiến hành một thí nghiệm để thử nghiệm loại thuốc mới." },
          { en: "The chemistry experiment failed because the temperature was too low.", vi: "Thí nghiệm hóa học đã thất bại vì nhiệt độ quá thấp." },
          { en: "We did several fun physics experiments in school.", vi: "Chúng tôi đã làm vài thí nghiệm vật lý vui nhộn ở trường học." },
        ],
        notes: "Nghiên cứu kiểm tra giả thuyết có kiểm soát.",
      },
      {
        id: "sci2",
        term: "Theory",
        phonetic: "/ˈθɪəri/",
        translation: "Thuyết, lý thuyết, học thuyết",
        examples: [
          { en: "Einstein's theory of relativity changed physics forever.", vi: "Thuyết tương đối của Einstein đã thay đổi vật lý học mãi mãi." },
          { en: "His scientific theory was confirmed by recent experiments.", vi: "Thuyết khoa học của ông đã được xác nhận bằng các thí nghiệm gần đây." },
          { en: "In theory, the plan is perfect, but in practice, it is difficult.", vi: "Về lý thuyết, kế hoạch này hoàn hảo, nhưng thực tế thì lại khó khăn." },
        ],
        notes: "Hệ thống giả thuyết lý giải hiện tượng, đã được khoa học kiểm chứng.",
      },
      {
        id: "sci3",
        term: "Discovery",
        phonetic: "/dɪˈskʌvəri/",
        translation: "Sự phát hiện, sự khám phá ra",
        examples: [
          { en: "The discovery of penicillin saved millions of lives.", vi: "Việc phát hiện ra penicillin đã cứu sống hàng triệu sinh mạng." },
          { en: "Scientists made a major discovery on the surface of Mars.", vi: "Các nhà khoa học đã thực hiện một khám phá lớn trên bề mặt sao Hỏa." },
          { en: "The book is about the history of scientific discoveries.", vi: "Cuốn sách viết về lịch sử của những khám phá khoa học." },
        ],
        notes: "Tìm ra thứ vốn đã có trong tự nhiên nhưng chưa ai biết.",
      },
      {
        id: "sci4",
        term: "Evidence",
        phonetic: "/ˈevɪdəns/",
        translation: "Bằng chứng, chứng cứ học thuật",
        examples: [
          { en: "There is strong evidence to support his theory.", vi: "Có bằng chứng thuyết phục để hỗ trợ ủng hộ lý thuyết của ông." },
          { en: "The police found no physical evidence at the scene.", vi: "Cảnh sát không tìm thấy bằng chứng vật lý nào tại hiện trường." },
          { en: "Scientific evidence shows that smoking causes cancer.", vi: "Bằng chứng khoa học chứng minh rằng hút thuốc lá gây ra ung thư." },
        ],
        notes: "Danh từ không đếm được chỉ bằng chứng thuyết phục hỗ trợ luận điểm.",
      },
      {
        id: "sci5",
        term: "Observation",
        phonetic: "/ˌɒbzəˈveɪʃn/",
        translation: "Sự quan sát, ghi nhận thực tế",
        examples: [
          { en: "The scientist kept the animals under close observation.", vi: "Nhà khoa học đã giữ những con động vật dưới sự quan sát chặt chẽ." },
          { en: "He wrote a report based on his field observations.", vi: "Anh ấy đã viết một bản báo cáo dựa trên những quan sát thực tế ngoài thực địa." },
          { en: "Astronomy relies heavily on direct observation of the stars.", vi: "Thiên văn học tin dùng phần lớn vào việc quan sát trực tiếp các ngôi sao." },
        ],
        notes: "Hành động theo dõi kỹ lưỡng để lấy dữ liệu.",
      },
      {
        id: "sci6",
        term: "Hypothesis",
        phonetic: "/haɪˈpɒθəsɪs/",
        translation: "Giả thuyết (khoa học)",
        examples: [
          { en: "The experiment confirmed the scientist's initial hypothesis.", vi: "Thí nghiệm đã xác nhận giả thuyết khoa học ban đầu của nhà khoa học." },
          { en: "They are proposing a new hypothesis to explain the phenomenon.", vi: "Họ đang đề xuất một giả thuyết mới để giải thích hiện tượng này." },
          { en: "Let's test this hypothesis with some simple calculations.", vi: "Hãy cùng kiểm tra giả thuyết này bằng một vài phép tính đơn giản." },
        ],
        notes: "Giả định ban đầu cần được kiểm chứng bằng thực nghiệm. Số nhiều là 'hypotheses'.",
      },
      {
        id: "sci7",
        term: "Laboratory",
        phonetic: "/ləˈbɒrətri/",
        translation: "Phòng thí nghiệm",
        examples: [
          { en: "The university has a state-of-the-art physics laboratory.", vi: "Trường đại học có một phòng thí nghiệm vật lý vô cùng hiện đại." },
          { en: "She works as a researcher in a medical laboratory.", vi: "Cô ấy làm việc với tư cách là một nhà nghiên cứu trong phòng thí nghiệm y tế." },
          { en: "Safety goggles must be worn in the chemistry laboratory.", vi: "Kính bảo hộ an toàn bắt buộc phải được đeo trong phòng thí nghiệm hóa học." },
        ],
        notes: "Có thể viết tắt là 'lab'.",
      },
      {
        id: "sci8",
        term: "Phenomenon",
        phonetic: "/fəˈnɒmɪnən/",
        translation: "Hiện tượng tự nhiên/xã hội",
        examples: [
          { en: "The northern lights are an amazing natural phenomenon.", vi: "Bắc cực quang là một hiện tượng tự nhiên tuyệt vời." },
          { en: "Gravity is a natural phenomenon that exists everywhere.", vi: "Trọng lực là một hiện tượng tự nhiên tồn tại ở khắp mọi nơi." },
          { en: "Scientists are trying to understand this weather phenomenon.", vi: "Các nhà khoa học đang cố gắng thấu hiểu hiện tượng thời tiết này." },
        ],
        notes: "Sự việc có thể quan sát thấy, đặc biệt là những hiện tượng thú vị. Số nhiều là 'phenomena'.",
      },
      {
        id: "sci9",
        term: "Element",
        phonetic: "/ˈelɪmənt/",
        translation: "Nguyên tố hóa học / Yếu tố, thành phần",
        examples: [
          { en: "Oxygen is a chemical element essential for life.", vi: "Oxy là một nguyên tố hóa học thiết yếu cho sự sống." },
          { en: "Trust is a key element of any successful partnership.", vi: "Sự tin tưởng là một yếu tố then chốt của bất kỳ mối quan hệ hợp tác thành công nào." },
          { en: "The periodic table lists all known elements.", vi: "Bảng tuần hoàn liệt kê tất cả các nguyên tố đã được biết đến." },
        ],
        notes: "Thành phần cơ bản cấu thành vật chất hoặc sự việc.",
      },
      {
        id: "sci10",
        term: "Substance",
        phonetic: "/ˈsʌbstəns/",
        translation: "Chất, chất hóa học",
        examples: [
          { en: "Water is a substance that is necessary for all living things.", vi: "Nước là một chất cần thiết cho tất cả mọi sinh vật sống." },
          { en: "The laboratory analyzed the sticky chemical substance.", vi: "Phòng thí nghiệm đã phân tích chất hóa học dính dính." },
          { en: "Avoid touching any toxic substances in the factory.", vi: "Tránh chạm vào bất kỳ chất độc hại nào trong nhà máy." },
        ],
        notes: "Vật chất có các tính chất vật lý và hóa học đặc trưng.",
      },
      {
        id: "sci11",
        term: "Gravity",
        phonetic: "/ˈɡrævəti/",
        translation: "Trọng lực, lực hút Trái Đất",
        examples: [
          { en: "The moon has weaker gravity than the Earth.", vi: "Mặt trăng có trọng lực yếu hơn so với Trái Đất." },
          { en: "Gravity keeps the planets orbiting around the sun.", vi: "Trọng lực giữ các hành tinh quay xung quanh mặt trời." },
          { en: "Without gravity, we would float away into space.", vi: "Nếu không có trọng lực, chúng ta sẽ lơ lửng trôi dạt vào không gian vũ trụ." },
        ],
        notes: "Lực hút vật lý kéo các vật thể lại gần nhau.",
      },
      {
        id: "sci12",
        term: "Evolution",
        phonetic: "/ˌiːvəˈluːʃn/",
        translation: "Sự tiến hóa, sự phát triển dần dần",
        examples: [
          { en: "Darwin's theory explains the evolution of species.", vi: "Thuyết của Darwin lý giải sự tiến hóa của các loài sinh vật." },
          { en: "The evolution of the mobile phone over the past decades is incredible.", vi: "Sự phát triển tiến hóa của điện thoại di động trong suốt nhiều thập kỷ qua thật đáng kinh ngạc." },
          { en: "We can study human evolution by analyzing fossils.", vi: "Chúng ta có thể nghiên cứu sự tiến hóa của loài người bằng cách phân tích các hóa thạch." },
        ],
        notes: "Quá trình biến đổi sinh học hoặc kỹ thuật lâu dài theo thời gian.",
      },
      {
        id: "sci13",
        term: "Gene",
        phonetic: "/dʒiːn/",
        translation: "Gen di truyền",
        examples: [
          { en: "He inherited the gene for blue eyes from his father.", vi: "Cậu ấy đã thừa hưởng gen quy định đôi mắt màu xanh dương từ bố mình." },
          { en: "Scientists can modify plant genes to resist diseases.", vi: "Các nhà khoa học có thể biến đổi gen thực vật để chống lại dịch bệnh." },
          { en: "The study focuses on the link between genes and behavior.", vi: "Nghiên cứu tập trung vào mối liên hệ giữa các gen và hành vi." },
        ],
        notes: "Đơn vị vật chất di truyền cơ bản trong cơ thể sinh vật.",
      },
      {
        id: "sci14",
        term: "Analyze",
        phonetic: "/ˈænəlaɪz/",
        translation: "Phân tích, mổ xẻ dữ liệu",
        examples: [
          { en: "We need to analyze the data before drawing a conclusion.", vi: "Chúng ta cần phân tích dữ liệu trước khi đưa ra kết luận." },
          { en: "The laboratory analyzed the blood sample.", vi: "Phòng thí nghiệm đã phân tích mẫu máu." },
          { en: "The software is used to analyze market trends.", vi: "Phần mềm được sử dụng để phân tích các xu hướng thị trường." },
        ],
        notes: "Động từ, nghiên cứu cặn kẽ để tìm bản chất.",
      },
      {
        id: "sci15",
        term: "Solar system",
        phonetic: "/ˈsəʊlə ˈsɪstəm/",
        translation: "Hệ mặt trời, thái dương hệ",
        examples: [
          { en: "There are eight planets in our solar system.", vi: "Có tám hành tinh trong hệ mặt trời của chúng ta." },
          { en: "The Earth is the third planet from the sun in the solar system.", vi: "Trái Đất là hành tinh thứ ba tính từ mặt trời trong hệ mặt trời." },
          { en: "They built a scale model of the solar system for the class.", vi: "Họ đã dựng một mô hình thu nhỏ của hệ mặt trời cho lớp học." },
        ],
        notes: "Hệ thống các thiên thể quay quanh mặt trời.",
      },
      {
        id: "sci16",
        term: "Atmosphere",
        phonetic: "/ˈætməsfɪə/",
        translation: "Khí quyển / Bầu không khí",
        examples: [
          { en: "The Earth's atmosphere protects us from harmful radiation.", vi: "Bầu khí quyển của Trái Đất bảo vệ chúng ta khỏi bức xạ có hại." },
          { en: "The restaurant has a very friendly and warm atmosphere.", vi: "Nhà hàng có một bầu không khí rất thân thiện và ấm áp." },
          { en: "Pollution is damaging the protective ozone layer in the atmosphere.", vi: "Ô nhiễm đang phá hủy tầng ozone bảo vệ trong bầu khí quyển." },
        ],
        notes: "Lớp khí bao quanh hành tinh hoặc cảm giác không khí tại một địa điểm.",
      },
      {
        id: "sci17",
        term: "Invention",
        phonetic: "/ɪnˈvenʃn/",
        translation: "Sự phát minh, vật phát minh",
        examples: [
          { en: "The invention of the printing press changed history.", vi: "Sự phát minh ra máy in đã thay đổi lịch sử." },
          { en: "The light bulb is a famous invention by Thomas Edison.", vi: "Bóng đèn sợi đốt là một phát minh nổi tiếng của Thomas Edison." },
          { en: "He filed a patent for his new technical invention.", vi: "Anh ấy đã nộp bằng sáng chế cho phát minh kỹ thuật mới của mình." },
        ],
        notes: "Tạo ra một công cụ mới chưa từng có trước đây.",
      },
      {
        id: "sci18",
        term: "Microscope",
        phonetic: "/ˈmaɪkrəskəʊp/",
        translation: "Kính hiển vi",
        examples: [
          { en: "Bacteria are too small to see without a microscope.", vi: "Vi khuẩn quá nhỏ để có thể nhìn thấy nếu không có kính hiển vi." },
          { en: "He examined the plant leaf under the microscope.", vi: "Cậu ấy đã xem xét kỹ chiếc lá cây dưới kính hiển vi." },
          { en: "The biology laboratory is equipped with digital microscopes.", vi: "Phòng thí nghiệm sinh học được trang bị các kính hiển vi kỹ thuật số." },
        ],
        notes: "Thiết bị khoa học phóng đại các vật siêu nhỏ.",
      },
      {
        id: "sci19",
        term: "Data",
        phonetic: "/ˈdeɪtə/",
        translation: "Dữ liệu, số liệu thông tin",
        examples: [
          { en: "The researchers gathered data from over two thousand people.", vi: "Các nhà nghiên cứu đã thu thập dữ liệu từ hơn hai ngàn người." },
          { en: "We must store the customer data securely.", vi: "Chúng ta phải lưu trữ dữ liệu khách hàng một cách an toàn." },
          { en: "The software analyzed the statistical data quickly.", vi: "Phần mềm đã phân tích số liệu thống kê rất nhanh." },
        ],
        notes: "Danh từ số nhiều của 'datum', nhưng trong tiếng Anh hiện đại thường dùng đi kèm với động từ số ít hoặc số nhiều để chỉ chung thông tin.",
      },
      {
        id: "sci20",
        term: "Analyze data",
        phonetic: "/ˈænəlaɪz ˈdeɪtə/",
        translation: "Phân tích dữ liệu",
        examples: [
          { en: "The researcher spent hours trying to analyze data from the experiment.", vi: "Nhà nghiên cứu dành nhiều giờ đồng hồ cố gắng phân tích dữ liệu từ thí nghiệm." },
          { en: "We use statistical software to analyze data.", vi: "Chúng tôi sử dụng phần mềm thống kê để phân tích dữ liệu." },
          { en: "An analyst's main job is to analyze data and find trends.", vi: "Công việc chính của một nhà phân tích là phân tích dữ liệu và tìm ra các xu hướng." },
        ],
        notes: "Cụm động từ cốt lõi trong nghiên cứu và công nghệ thông tin.",
      },
    ],
  },
];
