name: Deploy to Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 47.129.99.208
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Lưu nội dung file .pem vào GitHub Secret
          script: |
            set -e
            cd /home/zentask/backend
            git fetch origin main
            git reset --hard origin/main
            npm install
            pm2 restart --update-env backend
